In [178]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [179]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '59 tGravityAcc-energy()-Z',
 '125 tBodyGyro-std()-Y',
 '128 tBodyGyro-mad()-Y',
 '138 tBodyGyro-energy()-Y',
 '165 tBodyGyroJerk-std()-Y',
 '168 tBodyGyroJerk-mad()-Y',
 '178 tBodyGyroJerk-energy()-Y',
 '181 tBodyGyroJerk-iqr()-Y',
 '425 fBodyGyro-mean()-Y',
 '428 fBodyGyro-std()-Y',
 '431 fBodyGyro-mad()-Y',
 '441 fBodyGyro-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '478 fBodyGyro-bandsEnergy()-25,32',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '204 tBodyAccMag-max()',
 '215 tGravityAccMag-std()',
 '217 tGravityAccMag-max()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '275 fBodyAcc-max()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '506 fBodyAccMag-max()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [180]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            classifier_block(15, 10),
            nn.Linear(10, 9)
        )
    def forward(self, x):
        return self.network(x)

In [181]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def get_act_matrix(batch_size, a_dim):
    indexes = np.random.randint(a_dim, size = batch_size)
    
    one_hot = np.zeros((len(indexes), indexes.max()+1))
    one_hot[np.arange(len(indexes)),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)
    
def get_usr_matrix(batch_size, u_dim):
    indexes = np.random.randint(u_dim, size = batch_size)
    
    one_hot = np.zeros((indexes.size, indexes.max()+1))
    one_hot[np.arange(indexes.size),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../saved_models/{model_name}'))

# Train on Real Test on Real

In [182]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9)
    
    return X_train, np.asarray(y_train)

In [183]:
activities = [1, 3, 4]
users = [1, 3, 5]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

In [184]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [185]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 4.452085971832275, Final Batch Loss: 2.2119810581207275
Epoch 2, Loss: 4.451161623001099, Final Batch Loss: 2.2264087200164795
Epoch 3, Loss: 4.443710803985596, Final Batch Loss: 2.2184813022613525
Epoch 4, Loss: 4.442732334136963, Final Batch Loss: 2.2178618907928467
Epoch 5, Loss: 4.442281723022461, Final Batch Loss: 2.2302377223968506
Epoch 6, Loss: 4.439357280731201, Final Batch Loss: 2.230043411254883
Epoch 7, Loss: 4.420681476593018, Final Batch Loss: 2.195150375366211
Epoch 8, Loss: 4.412769317626953, Final Batch Loss: 2.188819408416748
Epoch 9, Loss: 4.4177327156066895, Final Batch Loss: 2.2168095111846924
Epoch 10, Loss: 4.420544624328613, Final Batch Loss: 2.2267842292785645
Epoch 11, Loss: 4.404106616973877, Final Batch Loss: 2.203859806060791
Epoch 12, Loss: 4.3958775997161865, Final Batch Loss: 2.2021379470825195
Epoch 13, Loss: 4.384618520736694, Final Batch Loss: 2.188055992126465
Epoch 14, Loss: 4.378288745880127, Final Batch Loss: 2.19391131401062
Epoch 

Epoch 125, Loss: 2.0532474517822266, Final Batch Loss: 0.9920840263366699
Epoch 126, Loss: 2.020070195198059, Final Batch Loss: 1.0039656162261963
Epoch 127, Loss: 1.934305489063263, Final Batch Loss: 0.9073588252067566
Epoch 128, Loss: 2.0967047214508057, Final Batch Loss: 1.1043118238449097
Epoch 129, Loss: 2.0154263973236084, Final Batch Loss: 0.9715622663497925
Epoch 130, Loss: 1.8752815127372742, Final Batch Loss: 0.8571147322654724
Epoch 131, Loss: 1.8935051560401917, Final Batch Loss: 0.8968578577041626
Epoch 132, Loss: 1.9150832891464233, Final Batch Loss: 0.969791829586029
Epoch 133, Loss: 1.9160397052764893, Final Batch Loss: 0.983177661895752
Epoch 134, Loss: 1.9315056800842285, Final Batch Loss: 0.9388752579689026
Epoch 135, Loss: 1.907244861125946, Final Batch Loss: 1.0310388803482056
Epoch 136, Loss: 1.9086102843284607, Final Batch Loss: 0.9589402675628662
Epoch 137, Loss: 1.8526723384857178, Final Batch Loss: 0.9814061522483826
Epoch 138, Loss: 1.9305467009544373, Final 

Epoch 244, Loss: 1.12730073928833, Final Batch Loss: 0.5555812120437622
Epoch 245, Loss: 1.0885522961616516, Final Batch Loss: 0.509425699710846
Epoch 246, Loss: 1.0819045305252075, Final Batch Loss: 0.5658247470855713
Epoch 247, Loss: 1.1220088601112366, Final Batch Loss: 0.5802668929100037
Epoch 248, Loss: 1.0327616333961487, Final Batch Loss: 0.5115811228752136
Epoch 249, Loss: 1.1485384106636047, Final Batch Loss: 0.5937907695770264
Epoch 250, Loss: 1.0358011722564697, Final Batch Loss: 0.5186923146247864
Epoch 251, Loss: 1.2267341017723083, Final Batch Loss: 0.543980598449707
Epoch 252, Loss: 1.14228755235672, Final Batch Loss: 0.6066933870315552
Epoch 253, Loss: 1.0621596574783325, Final Batch Loss: 0.5413356423377991
Epoch 254, Loss: 1.1309849619865417, Final Batch Loss: 0.5884868502616882
Epoch 255, Loss: 1.0735015869140625, Final Batch Loss: 0.4852635860443115
Epoch 256, Loss: 1.0189102292060852, Final Batch Loss: 0.5033032894134521
Epoch 257, Loss: 1.1265581846237183, Final B

Epoch 369, Loss: 0.911255270242691, Final Batch Loss: 0.46673843264579773
Epoch 370, Loss: 0.9503285884857178, Final Batch Loss: 0.5461252927780151
Epoch 371, Loss: 0.9270475804805756, Final Batch Loss: 0.4909852147102356
Epoch 372, Loss: 0.9125403761863708, Final Batch Loss: 0.5033171772956848
Epoch 373, Loss: 0.8852497637271881, Final Batch Loss: 0.3642512261867523
Epoch 374, Loss: 0.8929900825023651, Final Batch Loss: 0.4815034866333008
Epoch 375, Loss: 0.9288673102855682, Final Batch Loss: 0.48586538434028625
Epoch 376, Loss: 0.9032082855701447, Final Batch Loss: 0.4820229113101959
Epoch 377, Loss: 0.8832864761352539, Final Batch Loss: 0.39674755930900574
Epoch 378, Loss: 0.8555938899517059, Final Batch Loss: 0.45116081833839417
Epoch 379, Loss: 0.8440591990947723, Final Batch Loss: 0.42449888586997986
Epoch 380, Loss: 0.8295158743858337, Final Batch Loss: 0.33106571435928345
Epoch 381, Loss: 0.9004021286964417, Final Batch Loss: 0.3983585238456726
Epoch 382, Loss: 0.91558825969696

Epoch 486, Loss: 0.8636487424373627, Final Batch Loss: 0.4521697759628296
Epoch 487, Loss: 0.8343479335308075, Final Batch Loss: 0.45585906505584717
Epoch 488, Loss: 0.8109950721263885, Final Batch Loss: 0.39529648423194885
Epoch 489, Loss: 0.8389362692832947, Final Batch Loss: 0.3829059600830078
Epoch 490, Loss: 0.7704326510429382, Final Batch Loss: 0.38216185569763184
Epoch 491, Loss: 0.727622002363205, Final Batch Loss: 0.37106141448020935
Epoch 492, Loss: 0.7441194951534271, Final Batch Loss: 0.35205936431884766
Epoch 493, Loss: 0.8418553173542023, Final Batch Loss: 0.49109789729118347
Epoch 494, Loss: 0.7780665457248688, Final Batch Loss: 0.3630353808403015
Epoch 495, Loss: 0.7771190106868744, Final Batch Loss: 0.3900231719017029
Epoch 496, Loss: 0.776375949382782, Final Batch Loss: 0.44187963008880615
Epoch 497, Loss: 0.8295967876911163, Final Batch Loss: 0.42291295528411865
Epoch 498, Loss: 0.7851683497428894, Final Batch Loss: 0.38400837779045105
Epoch 499, Loss: 0.841899067163

Epoch 612, Loss: 0.7388001084327698, Final Batch Loss: 0.3806711435317993
Epoch 613, Loss: 0.8531128764152527, Final Batch Loss: 0.470645010471344
Epoch 614, Loss: 0.7433187067508698, Final Batch Loss: 0.37526392936706543
Epoch 615, Loss: 0.8045766651630402, Final Batch Loss: 0.44633617997169495
Epoch 616, Loss: 0.7288953363895416, Final Batch Loss: 0.3371173143386841
Epoch 617, Loss: 0.7287055552005768, Final Batch Loss: 0.3714139759540558
Epoch 618, Loss: 0.8248583674430847, Final Batch Loss: 0.43836989998817444
Epoch 619, Loss: 0.6888741850852966, Final Batch Loss: 0.3328301012516022
Epoch 620, Loss: 0.7783516943454742, Final Batch Loss: 0.3894549310207367
Epoch 621, Loss: 0.7239126265048981, Final Batch Loss: 0.41241613030433655
Epoch 622, Loss: 0.6993787288665771, Final Batch Loss: 0.32948169112205505
Epoch 623, Loss: 0.7834537029266357, Final Batch Loss: 0.3298822045326233
Epoch 624, Loss: 0.7381303608417511, Final Batch Loss: 0.4032812714576721
Epoch 625, Loss: 0.721779823303222

Epoch 734, Loss: 0.7402344942092896, Final Batch Loss: 0.35182619094848633
Epoch 735, Loss: 0.7411428391933441, Final Batch Loss: 0.3310668468475342
Epoch 736, Loss: 0.6822068691253662, Final Batch Loss: 0.33305925130844116
Epoch 737, Loss: 0.7373572587966919, Final Batch Loss: 0.4105183184146881
Epoch 738, Loss: 0.7104690372943878, Final Batch Loss: 0.2958134114742279
Epoch 739, Loss: 0.7297219038009644, Final Batch Loss: 0.3405463397502899
Epoch 740, Loss: 0.6882911324501038, Final Batch Loss: 0.3011975586414337
Epoch 741, Loss: 0.6701237261295319, Final Batch Loss: 0.3361404240131378
Epoch 742, Loss: 0.7284726202487946, Final Batch Loss: 0.37170642614364624
Epoch 743, Loss: 0.6748412251472473, Final Batch Loss: 0.31319695711135864
Epoch 744, Loss: 0.7529401481151581, Final Batch Loss: 0.3593892455101013
Epoch 745, Loss: 0.7561075985431671, Final Batch Loss: 0.32261034846305847
Epoch 746, Loss: 0.7381057143211365, Final Batch Loss: 0.4231759309768677
Epoch 747, Loss: 0.69746935367584

Epoch 847, Loss: 0.6555833220481873, Final Batch Loss: 0.2926190197467804
Epoch 848, Loss: 0.7009904384613037, Final Batch Loss: 0.32576942443847656
Epoch 849, Loss: 0.6704086065292358, Final Batch Loss: 0.3185577392578125
Epoch 850, Loss: 0.6337036192417145, Final Batch Loss: 0.3174779713153839
Epoch 851, Loss: 0.6775229871273041, Final Batch Loss: 0.35064423084259033
Epoch 852, Loss: 0.6437520086765289, Final Batch Loss: 0.3001191318035126
Epoch 853, Loss: 0.644602507352829, Final Batch Loss: 0.3094402551651001
Epoch 854, Loss: 0.6793707311153412, Final Batch Loss: 0.3405386507511139
Epoch 855, Loss: 0.710184782743454, Final Batch Loss: 0.3448275327682495
Epoch 856, Loss: 0.7428337037563324, Final Batch Loss: 0.3967684209346771
Epoch 857, Loss: 0.7113038301467896, Final Batch Loss: 0.3354337215423584
Epoch 858, Loss: 0.7394604086875916, Final Batch Loss: 0.37254461646080017
Epoch 859, Loss: 0.602488100528717, Final Batch Loss: 0.32251501083374023
Epoch 860, Loss: 0.6596297919750214, 

Epoch 962, Loss: 0.6042178571224213, Final Batch Loss: 0.29804283380508423
Epoch 963, Loss: 0.582259327173233, Final Batch Loss: 0.29253584146499634
Epoch 964, Loss: 0.5687118470668793, Final Batch Loss: 0.2933015823364258
Epoch 965, Loss: 0.629827618598938, Final Batch Loss: 0.3148079812526703
Epoch 966, Loss: 0.6501573920249939, Final Batch Loss: 0.3187862038612366
Epoch 967, Loss: 0.6492637991905212, Final Batch Loss: 0.35088348388671875
Epoch 968, Loss: 0.589074969291687, Final Batch Loss: 0.3015265166759491
Epoch 969, Loss: 0.6449180245399475, Final Batch Loss: 0.34144869446754456
Epoch 970, Loss: 0.6337379515171051, Final Batch Loss: 0.2971338629722595
Epoch 971, Loss: 0.6205388307571411, Final Batch Loss: 0.2947293221950531
Epoch 972, Loss: 0.6181294322013855, Final Batch Loss: 0.32470592856407166
Epoch 973, Loss: 0.6695027947425842, Final Batch Loss: 0.37417659163475037
Epoch 974, Loss: 0.6282570064067841, Final Batch Loss: 0.2706161439418793
Epoch 975, Loss: 0.5865755081176758

Epoch 1078, Loss: 0.5769913792610168, Final Batch Loss: 0.22896459698677063
Epoch 1079, Loss: 0.4975152909755707, Final Batch Loss: 0.23697435855865479
Epoch 1080, Loss: 0.5115790367126465, Final Batch Loss: 0.23443347215652466
Epoch 1081, Loss: 0.5707210302352905, Final Batch Loss: 0.28639376163482666
Epoch 1082, Loss: 0.5992015302181244, Final Batch Loss: 0.31307414174079895
Epoch 1083, Loss: 0.588234156370163, Final Batch Loss: 0.35549482703208923
Epoch 1084, Loss: 0.5575561076402664, Final Batch Loss: 0.31859222054481506
Epoch 1085, Loss: 0.6079256236553192, Final Batch Loss: 0.3142208755016327
Epoch 1086, Loss: 0.6148209273815155, Final Batch Loss: 0.3330635130405426
Epoch 1087, Loss: 0.542559340596199, Final Batch Loss: 0.2387654036283493
Epoch 1088, Loss: 0.6142610311508179, Final Batch Loss: 0.3399181365966797
Epoch 1089, Loss: 0.5380213856697083, Final Batch Loss: 0.27488040924072266
Epoch 1090, Loss: 0.5479540228843689, Final Batch Loss: 0.2826659679412842
Epoch 1091, Loss: 0

Epoch 1188, Loss: 0.5339965373277664, Final Batch Loss: 0.30955711007118225
Epoch 1189, Loss: 0.48948438465595245, Final Batch Loss: 0.2526382505893707
Epoch 1190, Loss: 0.534508228302002, Final Batch Loss: 0.26676610112190247
Epoch 1191, Loss: 0.5189217627048492, Final Batch Loss: 0.26816508173942566
Epoch 1192, Loss: 0.5101785063743591, Final Batch Loss: 0.25373604893684387
Epoch 1193, Loss: 0.5179580301046371, Final Batch Loss: 0.2310875803232193
Epoch 1194, Loss: 0.5181102007627487, Final Batch Loss: 0.2725951671600342
Epoch 1195, Loss: 0.5767851173877716, Final Batch Loss: 0.3257195055484772
Epoch 1196, Loss: 0.5851108729839325, Final Batch Loss: 0.3035000264644623
Epoch 1197, Loss: 0.5537412166595459, Final Batch Loss: 0.23818707466125488
Epoch 1198, Loss: 0.5311859548091888, Final Batch Loss: 0.24264442920684814
Epoch 1199, Loss: 0.5365204513072968, Final Batch Loss: 0.26537972688674927
Epoch 1200, Loss: 0.5696089565753937, Final Batch Loss: 0.2461167871952057
Epoch 1201, Loss: 

Epoch 1307, Loss: 0.5113189071416855, Final Batch Loss: 0.21687139570713043
Epoch 1308, Loss: 0.4733027517795563, Final Batch Loss: 0.21867325901985168
Epoch 1309, Loss: 0.5141393542289734, Final Batch Loss: 0.26294657588005066
Epoch 1310, Loss: 0.46429844200611115, Final Batch Loss: 0.1832929402589798
Epoch 1311, Loss: 0.47267545759677887, Final Batch Loss: 0.2094113677740097
Epoch 1312, Loss: 0.4677761048078537, Final Batch Loss: 0.2215796262025833
Epoch 1313, Loss: 0.49855050444602966, Final Batch Loss: 0.2535664737224579
Epoch 1314, Loss: 0.4617668092250824, Final Batch Loss: 0.22752141952514648
Epoch 1315, Loss: 0.511786162853241, Final Batch Loss: 0.23565909266471863
Epoch 1316, Loss: 0.5126748383045197, Final Batch Loss: 0.2573918104171753
Epoch 1317, Loss: 0.5346689075231552, Final Batch Loss: 0.29371377825737
Epoch 1318, Loss: 0.48189079761505127, Final Batch Loss: 0.24994856119155884
Epoch 1319, Loss: 0.5300653874874115, Final Batch Loss: 0.2552333176136017
Epoch 1320, Loss: 

Epoch 1426, Loss: 0.491867333650589, Final Batch Loss: 0.27983176708221436
Epoch 1427, Loss: 0.502001166343689, Final Batch Loss: 0.2584643065929413
Epoch 1428, Loss: 0.4569356292486191, Final Batch Loss: 0.20290519297122955
Epoch 1429, Loss: 0.50956991314888, Final Batch Loss: 0.2882494032382965
Epoch 1430, Loss: 0.45840510725975037, Final Batch Loss: 0.21299725770950317
Epoch 1431, Loss: 0.46424221992492676, Final Batch Loss: 0.2207399159669876
Epoch 1432, Loss: 0.5016297250986099, Final Batch Loss: 0.27428218722343445
Epoch 1433, Loss: 0.4627727121114731, Final Batch Loss: 0.21063874661922455
Epoch 1434, Loss: 0.4304669499397278, Final Batch Loss: 0.1848578006029129
Epoch 1435, Loss: 0.47728846967220306, Final Batch Loss: 0.20033518970012665
Epoch 1436, Loss: 0.4939933121204376, Final Batch Loss: 0.2664273679256439
Epoch 1437, Loss: 0.45704659819602966, Final Batch Loss: 0.23670171201229095
Epoch 1438, Loss: 0.5002439171075821, Final Batch Loss: 0.2962871789932251
Epoch 1439, Loss: 

Epoch 1536, Loss: 0.48572951555252075, Final Batch Loss: 0.23525959253311157
Epoch 1537, Loss: 0.43634776771068573, Final Batch Loss: 0.20433862507343292
Epoch 1538, Loss: 0.41733285784721375, Final Batch Loss: 0.19887378811836243
Epoch 1539, Loss: 0.5035942643880844, Final Batch Loss: 0.2576260268688202
Epoch 1540, Loss: 0.49052204191684723, Final Batch Loss: 0.25818783044815063
Epoch 1541, Loss: 0.4808661937713623, Final Batch Loss: 0.206802636384964
Epoch 1542, Loss: 0.5301612913608551, Final Batch Loss: 0.24660176038742065
Epoch 1543, Loss: 0.4071205407381058, Final Batch Loss: 0.19703568518161774
Epoch 1544, Loss: 0.5442819744348526, Final Batch Loss: 0.3232431411743164
Epoch 1545, Loss: 0.477863609790802, Final Batch Loss: 0.261596143245697
Epoch 1546, Loss: 0.43558093905448914, Final Batch Loss: 0.19241784512996674
Epoch 1547, Loss: 0.4289660304784775, Final Batch Loss: 0.1808134913444519
Epoch 1548, Loss: 0.4500104486942291, Final Batch Loss: 0.2705952227115631
Epoch 1549, Loss

Epoch 1654, Loss: 0.43658657371997833, Final Batch Loss: 0.18438036739826202
Epoch 1655, Loss: 0.4312174618244171, Final Batch Loss: 0.17364642024040222
Epoch 1656, Loss: 0.45676475763320923, Final Batch Loss: 0.23987774550914764
Epoch 1657, Loss: 0.46191267669200897, Final Batch Loss: 0.2025643140077591
Epoch 1658, Loss: 0.4493096321821213, Final Batch Loss: 0.1936260610818863
Epoch 1659, Loss: 0.41967883706092834, Final Batch Loss: 0.18781454861164093
Epoch 1660, Loss: 0.4681684374809265, Final Batch Loss: 0.24691037833690643
Epoch 1661, Loss: 0.3790592551231384, Final Batch Loss: 0.16080394387245178
Epoch 1662, Loss: 0.48605599999427795, Final Batch Loss: 0.205750972032547
Epoch 1663, Loss: 0.4695942550897598, Final Batch Loss: 0.2322758585214615
Epoch 1664, Loss: 0.47441744804382324, Final Batch Loss: 0.2297619879245758
Epoch 1665, Loss: 0.43823422491550446, Final Batch Loss: 0.20930832624435425
Epoch 1666, Loss: 0.42805148661136627, Final Batch Loss: 0.22927765548229218
Epoch 1667

Epoch 1777, Loss: 0.4238532930612564, Final Batch Loss: 0.22991281747817993
Epoch 1778, Loss: 0.42143702507019043, Final Batch Loss: 0.2353099137544632
Epoch 1779, Loss: 0.44081243872642517, Final Batch Loss: 0.1522178053855896
Epoch 1780, Loss: 0.42771418392658234, Final Batch Loss: 0.2593457102775574
Epoch 1781, Loss: 0.4346282631158829, Final Batch Loss: 0.17142222821712494
Epoch 1782, Loss: 0.45045986771583557, Final Batch Loss: 0.22663329541683197
Epoch 1783, Loss: 0.42264871299266815, Final Batch Loss: 0.18140897154808044
Epoch 1784, Loss: 0.472665473818779, Final Batch Loss: 0.2126946896314621
Epoch 1785, Loss: 0.45161911845207214, Final Batch Loss: 0.2277553379535675
Epoch 1786, Loss: 0.38838355243206024, Final Batch Loss: 0.1862972378730774
Epoch 1787, Loss: 0.40321142971515656, Final Batch Loss: 0.18635736405849457
Epoch 1788, Loss: 0.42682093381881714, Final Batch Loss: 0.2211254984140396
Epoch 1789, Loss: 0.3672574311494827, Final Batch Loss: 0.1726178377866745
Epoch 1790, 

Epoch 1899, Loss: 0.3912908434867859, Final Batch Loss: 0.19874005019664764
Epoch 1900, Loss: 0.3895137906074524, Final Batch Loss: 0.16005849838256836
Epoch 1901, Loss: 0.3485911935567856, Final Batch Loss: 0.1403319090604782
Epoch 1902, Loss: 0.3496548682451248, Final Batch Loss: 0.14624319970607758
Epoch 1903, Loss: 0.3995978534221649, Final Batch Loss: 0.18578672409057617
Epoch 1904, Loss: 0.4082953929901123, Final Batch Loss: 0.19817300140857697
Epoch 1905, Loss: 0.34795787930488586, Final Batch Loss: 0.14029821753501892
Epoch 1906, Loss: 0.46616126596927643, Final Batch Loss: 0.28871554136276245
Epoch 1907, Loss: 0.4566420912742615, Final Batch Loss: 0.2234673798084259
Epoch 1908, Loss: 0.3353662043809891, Final Batch Loss: 0.1300174444913864
Epoch 1909, Loss: 0.36539046466350555, Final Batch Loss: 0.1821843683719635
Epoch 1910, Loss: 0.3804817348718643, Final Batch Loss: 0.18246892094612122
Epoch 1911, Loss: 0.39459389448165894, Final Batch Loss: 0.20456621050834656
Epoch 1912, 

Epoch 2023, Loss: 0.4278320074081421, Final Batch Loss: 0.19659161567687988
Epoch 2024, Loss: 0.38751986622810364, Final Batch Loss: 0.184788778424263
Epoch 2025, Loss: 0.3546747863292694, Final Batch Loss: 0.16114917397499084
Epoch 2026, Loss: 0.3628826141357422, Final Batch Loss: 0.15185175836086273
Epoch 2027, Loss: 0.3784022778272629, Final Batch Loss: 0.1753782033920288
Epoch 2028, Loss: 0.35952869057655334, Final Batch Loss: 0.18613767623901367
Epoch 2029, Loss: 0.3796234279870987, Final Batch Loss: 0.19313837587833405
Epoch 2030, Loss: 0.40151649713516235, Final Batch Loss: 0.20081281661987305
Epoch 2031, Loss: 0.4161186069250107, Final Batch Loss: 0.21303151547908783
Epoch 2032, Loss: 0.36153358221054077, Final Batch Loss: 0.1502547562122345
Epoch 2033, Loss: 0.42659173905849457, Final Batch Loss: 0.2096138894557953
Epoch 2034, Loss: 0.37236298620700836, Final Batch Loss: 0.1908421814441681
Epoch 2035, Loss: 0.40971411764621735, Final Batch Loss: 0.24179843068122864
Epoch 2036,

Epoch 2135, Loss: 0.3496187776327133, Final Batch Loss: 0.17974433302879333
Epoch 2136, Loss: 0.3664983808994293, Final Batch Loss: 0.1927463710308075
Epoch 2137, Loss: 0.38214200735092163, Final Batch Loss: 0.16124428808689117
Epoch 2138, Loss: 0.3874617964029312, Final Batch Loss: 0.23250626027584076
Epoch 2139, Loss: 0.40660667419433594, Final Batch Loss: 0.2180667221546173
Epoch 2140, Loss: 0.39833344519138336, Final Batch Loss: 0.18094126880168915
Epoch 2141, Loss: 0.3917354792356491, Final Batch Loss: 0.22225724160671234
Epoch 2142, Loss: 0.35741935670375824, Final Batch Loss: 0.17132969200611115
Epoch 2143, Loss: 0.41978752613067627, Final Batch Loss: 0.19721917808055878
Epoch 2144, Loss: 0.35261236131191254, Final Batch Loss: 0.12645624577999115
Epoch 2145, Loss: 0.35531124472618103, Final Batch Loss: 0.19954736530780792
Epoch 2146, Loss: 0.38629262149333954, Final Batch Loss: 0.20311246812343597
Epoch 2147, Loss: 0.39152923226356506, Final Batch Loss: 0.21885806322097778
Epoch

Epoch 2251, Loss: 0.3529282808303833, Final Batch Loss: 0.19367487728595734
Epoch 2252, Loss: 0.40047837793827057, Final Batch Loss: 0.2127552032470703
Epoch 2253, Loss: 0.3824850916862488, Final Batch Loss: 0.22030022740364075
Epoch 2254, Loss: 0.34923167526721954, Final Batch Loss: 0.179356187582016
Epoch 2255, Loss: 0.3304353952407837, Final Batch Loss: 0.13419930636882782
Epoch 2256, Loss: 0.3362976759672165, Final Batch Loss: 0.1392054557800293
Epoch 2257, Loss: 0.2971000075340271, Final Batch Loss: 0.1361503303050995
Epoch 2258, Loss: 0.3905683904886246, Final Batch Loss: 0.14178234338760376
Epoch 2259, Loss: 0.34602969884872437, Final Batch Loss: 0.18399660289287567
Epoch 2260, Loss: 0.39570020139217377, Final Batch Loss: 0.2097165733575821
Epoch 2261, Loss: 0.3653483986854553, Final Batch Loss: 0.22165179252624512
Epoch 2262, Loss: 0.38408589363098145, Final Batch Loss: 0.18945391476154327
Epoch 2263, Loss: 0.3850824385881424, Final Batch Loss: 0.18203915655612946
Epoch 2264, L

Epoch 2371, Loss: 0.3165375366806984, Final Batch Loss: 0.1201961562037468
Epoch 2372, Loss: 0.3675556629896164, Final Batch Loss: 0.1750369668006897
Epoch 2373, Loss: 0.355090469121933, Final Batch Loss: 0.1617841124534607
Epoch 2374, Loss: 0.34422533214092255, Final Batch Loss: 0.16409257054328918
Epoch 2375, Loss: 0.30898450314998627, Final Batch Loss: 0.13731051981449127
Epoch 2376, Loss: 0.354784831404686, Final Batch Loss: 0.19364413619041443
Epoch 2377, Loss: 0.34561698138713837, Final Batch Loss: 0.18570104241371155
Epoch 2378, Loss: 0.33474311232566833, Final Batch Loss: 0.15960942208766937
Epoch 2379, Loss: 0.3886472284793854, Final Batch Loss: 0.15312594175338745
Epoch 2380, Loss: 0.4082813411951065, Final Batch Loss: 0.18637003004550934
Epoch 2381, Loss: 0.3642643541097641, Final Batch Loss: 0.18705244362354279
Epoch 2382, Loss: 0.3502229303121567, Final Batch Loss: 0.1952715814113617
Epoch 2383, Loss: 0.40443915128707886, Final Batch Loss: 0.21637074649333954
Epoch 2384, L

Epoch 2500, Loss: 0.3948451578617096, Final Batch Loss: 0.21255333721637726
Epoch 2501, Loss: 0.36577053368091583, Final Batch Loss: 0.18215353786945343
Epoch 2502, Loss: 0.33100810647010803, Final Batch Loss: 0.14261195063591003
Epoch 2503, Loss: 0.33775436878204346, Final Batch Loss: 0.14945974946022034
Epoch 2504, Loss: 0.3639846593141556, Final Batch Loss: 0.14935974776744843
Epoch 2505, Loss: 0.360133096575737, Final Batch Loss: 0.2006453424692154
Epoch 2506, Loss: 0.36456456780433655, Final Batch Loss: 0.1892651617527008
Epoch 2507, Loss: 0.32723478972911835, Final Batch Loss: 0.1382884532213211
Epoch 2508, Loss: 0.35630784183740616, Final Batch Loss: 0.11969564110040665
Epoch 2509, Loss: 0.37192797660827637, Final Batch Loss: 0.18448221683502197
Epoch 2510, Loss: 0.31715692579746246, Final Batch Loss: 0.14916887879371643
Epoch 2511, Loss: 0.4154272824525833, Final Batch Loss: 0.25426122546195984
Epoch 2512, Loss: 0.3530581146478653, Final Batch Loss: 0.18473467230796814
Epoch 25

Epoch 2616, Loss: 0.3433566391468048, Final Batch Loss: 0.1451490819454193
Epoch 2617, Loss: 0.3180885314941406, Final Batch Loss: 0.1691131293773651
Epoch 2618, Loss: 0.3137129545211792, Final Batch Loss: 0.17394334077835083
Epoch 2619, Loss: 0.3048071563243866, Final Batch Loss: 0.14520706236362457
Epoch 2620, Loss: 0.31583403050899506, Final Batch Loss: 0.15960663557052612
Epoch 2621, Loss: 0.37878261506557465, Final Batch Loss: 0.2066681981086731
Epoch 2622, Loss: 0.30105258524417877, Final Batch Loss: 0.1358489990234375
Epoch 2623, Loss: 0.29021888226270676, Final Batch Loss: 0.11160475760698318
Epoch 2624, Loss: 0.29392896592617035, Final Batch Loss: 0.12509438395500183
Epoch 2625, Loss: 0.3331030458211899, Final Batch Loss: 0.18619339168071747
Epoch 2626, Loss: 0.35130660235881805, Final Batch Loss: 0.18194261193275452
Epoch 2627, Loss: 0.3318338841199875, Final Batch Loss: 0.17901983857154846
Epoch 2628, Loss: 0.33879660069942474, Final Batch Loss: 0.1308882087469101
Epoch 2629

Epoch 2730, Loss: 0.3289557844400406, Final Batch Loss: 0.14845138788223267
Epoch 2731, Loss: 0.2886977791786194, Final Batch Loss: 0.1468982845544815
Epoch 2732, Loss: 0.33120594918727875, Final Batch Loss: 0.16650541126728058
Epoch 2733, Loss: 0.27459628880023956, Final Batch Loss: 0.1424945741891861
Epoch 2734, Loss: 0.2701359689235687, Final Batch Loss: 0.11983904242515564
Epoch 2735, Loss: 0.275224968791008, Final Batch Loss: 0.1400763988494873
Epoch 2736, Loss: 0.3087294101715088, Final Batch Loss: 0.1574392467737198
Epoch 2737, Loss: 0.2923135757446289, Final Batch Loss: 0.1277584433555603
Epoch 2738, Loss: 0.335592657327652, Final Batch Loss: 0.16372956335544586
Epoch 2739, Loss: 0.31981199979782104, Final Batch Loss: 0.16106747090816498
Epoch 2740, Loss: 0.3036591559648514, Final Batch Loss: 0.18921159207820892
Epoch 2741, Loss: 0.3389018177986145, Final Batch Loss: 0.20145735144615173
Epoch 2742, Loss: 0.3126848489046097, Final Batch Loss: 0.20402851700782776
Epoch 2743, Loss

Epoch 2846, Loss: 0.34209710359573364, Final Batch Loss: 0.17330150306224823
Epoch 2847, Loss: 0.29282285273075104, Final Batch Loss: 0.17234571278095245
Epoch 2848, Loss: 0.2616283968091011, Final Batch Loss: 0.11322527378797531
Epoch 2849, Loss: 0.3248720020055771, Final Batch Loss: 0.1746463179588318
Epoch 2850, Loss: 0.24876776337623596, Final Batch Loss: 0.10202336311340332
Epoch 2851, Loss: 0.2919240891933441, Final Batch Loss: 0.12816764414310455
Epoch 2852, Loss: 0.27592049539089203, Final Batch Loss: 0.14386649429798126
Epoch 2853, Loss: 0.2859603017568588, Final Batch Loss: 0.1337004452943802
Epoch 2854, Loss: 0.28498387336730957, Final Batch Loss: 0.12130007147789001
Epoch 2855, Loss: 0.33379003405570984, Final Batch Loss: 0.16002978384494781
Epoch 2856, Loss: 0.31626658141613007, Final Batch Loss: 0.14047712087631226
Epoch 2857, Loss: 0.29476191103458405, Final Batch Loss: 0.11551055312156677
Epoch 2858, Loss: 0.3075520247220993, Final Batch Loss: 0.13031651079654694
Epoch 

Epoch 2959, Loss: 0.3143477290868759, Final Batch Loss: 0.16580289602279663
Epoch 2960, Loss: 0.23163218051195145, Final Batch Loss: 0.10832709819078445
Epoch 2961, Loss: 0.3095101863145828, Final Batch Loss: 0.1691693663597107
Epoch 2962, Loss: 0.2384650632739067, Final Batch Loss: 0.09822555631399155
Epoch 2963, Loss: 0.26096274703741074, Final Batch Loss: 0.1614392250776291
Epoch 2964, Loss: 0.3390984684228897, Final Batch Loss: 0.165390744805336
Epoch 2965, Loss: 0.30870120227336884, Final Batch Loss: 0.13562509417533875
Epoch 2966, Loss: 0.30805082619190216, Final Batch Loss: 0.1774401217699051
Epoch 2967, Loss: 0.23847321420907974, Final Batch Loss: 0.09681185334920883
Epoch 2968, Loss: 0.30268795788288116, Final Batch Loss: 0.17515936493873596
Epoch 2969, Loss: 0.3717540577054024, Final Batch Loss: 0.1238023117184639
Epoch 2970, Loss: 0.31530818343162537, Final Batch Loss: 0.16179272532463074
Epoch 2971, Loss: 0.3282182663679123, Final Batch Loss: 0.17873090505599976
Epoch 2972,

Epoch 3075, Loss: 0.27031461894512177, Final Batch Loss: 0.13426001369953156
Epoch 3076, Loss: 0.2753375545144081, Final Batch Loss: 0.15542416274547577
Epoch 3077, Loss: 0.3019886612892151, Final Batch Loss: 0.14514075219631195
Epoch 3078, Loss: 0.23892714083194733, Final Batch Loss: 0.10723106563091278
Epoch 3079, Loss: 0.35412634909152985, Final Batch Loss: 0.21952560544013977
Epoch 3080, Loss: 0.2627236992120743, Final Batch Loss: 0.14178770780563354
Epoch 3081, Loss: 0.2999202013015747, Final Batch Loss: 0.1296035647392273
Epoch 3082, Loss: 0.2906268388032913, Final Batch Loss: 0.14329257607460022
Epoch 3083, Loss: 0.3309953212738037, Final Batch Loss: 0.14706948399543762
Epoch 3084, Loss: 0.23930057138204575, Final Batch Loss: 0.1124647781252861
Epoch 3085, Loss: 0.33507344126701355, Final Batch Loss: 0.158718079328537
Epoch 3086, Loss: 0.2735278755426407, Final Batch Loss: 0.12697501480579376
Epoch 3087, Loss: 0.3069872111082077, Final Batch Loss: 0.1277942955493927
Epoch 3088, 

Epoch 3193, Loss: 0.34547531604766846, Final Batch Loss: 0.17275112867355347
Epoch 3194, Loss: 0.3470298945903778, Final Batch Loss: 0.12784871459007263
Epoch 3195, Loss: 0.29241184145212173, Final Batch Loss: 0.10585299879312515
Epoch 3196, Loss: 0.2914871275424957, Final Batch Loss: 0.13648399710655212
Epoch 3197, Loss: 0.31149742007255554, Final Batch Loss: 0.15175186097621918
Epoch 3198, Loss: 0.27439816296100616, Final Batch Loss: 0.12460440397262573
Epoch 3199, Loss: 0.3085368201136589, Final Batch Loss: 0.18363375961780548
Epoch 3200, Loss: 0.25979815423488617, Final Batch Loss: 0.1170484721660614
Epoch 3201, Loss: 0.27018001675605774, Final Batch Loss: 0.1550486534833908
Epoch 3202, Loss: 0.28141041845083237, Final Batch Loss: 0.12242414802312851
Epoch 3203, Loss: 0.2878524214029312, Final Batch Loss: 0.12012642621994019
Epoch 3204, Loss: 0.315628245472908, Final Batch Loss: 0.16805222630500793
Epoch 3205, Loss: 0.3261774927377701, Final Batch Loss: 0.18199659883975983
Epoch 32

Epoch 3308, Loss: 0.3409993499517441, Final Batch Loss: 0.16907130181789398
Epoch 3309, Loss: 0.2559213414788246, Final Batch Loss: 0.11795852333307266
Epoch 3310, Loss: 0.2478460669517517, Final Batch Loss: 0.1529289036989212
Epoch 3311, Loss: 0.1848193034529686, Final Batch Loss: 0.07821930944919586
Epoch 3312, Loss: 0.3100525587797165, Final Batch Loss: 0.15574492514133453
Epoch 3313, Loss: 0.2219233736395836, Final Batch Loss: 0.09563872963190079
Epoch 3314, Loss: 0.294413685798645, Final Batch Loss: 0.156650573015213
Epoch 3315, Loss: 0.22989298403263092, Final Batch Loss: 0.09283746778964996
Epoch 3316, Loss: 0.26057717949151993, Final Batch Loss: 0.1457541435956955
Epoch 3317, Loss: 0.26217474043369293, Final Batch Loss: 0.14684200286865234
Epoch 3318, Loss: 0.26261308789253235, Final Batch Loss: 0.12419793009757996
Epoch 3319, Loss: 0.2583785578608513, Final Batch Loss: 0.09561989456415176
Epoch 3320, Loss: 0.20430297404527664, Final Batch Loss: 0.07769737392663956
Epoch 3321, 

Epoch 3424, Loss: 0.2299715057015419, Final Batch Loss: 0.12189464271068573
Epoch 3425, Loss: 0.24558722972869873, Final Batch Loss: 0.11279366910457611
Epoch 3426, Loss: 0.2618393078446388, Final Batch Loss: 0.15927070379257202
Epoch 3427, Loss: 0.24614299833774567, Final Batch Loss: 0.11545373499393463
Epoch 3428, Loss: 0.22653795778751373, Final Batch Loss: 0.0822051614522934
Epoch 3429, Loss: 0.24999625980854034, Final Batch Loss: 0.1212950199842453
Epoch 3430, Loss: 0.2849240303039551, Final Batch Loss: 0.1475151777267456
Epoch 3431, Loss: 0.20263861864805222, Final Batch Loss: 0.12799549102783203
Epoch 3432, Loss: 0.3134623169898987, Final Batch Loss: 0.20127755403518677
Epoch 3433, Loss: 0.26087289303541183, Final Batch Loss: 0.13982349634170532
Epoch 3434, Loss: 0.24208932369947433, Final Batch Loss: 0.09147212654352188
Epoch 3435, Loss: 0.24528927356004715, Final Batch Loss: 0.13372695446014404
Epoch 3436, Loss: 0.2666298598051071, Final Batch Loss: 0.1444343626499176
Epoch 34

Epoch 3548, Loss: 0.22277569770812988, Final Batch Loss: 0.12481416016817093
Epoch 3549, Loss: 0.1840457320213318, Final Batch Loss: 0.07671036571264267
Epoch 3550, Loss: 0.23041150718927383, Final Batch Loss: 0.09438740462064743
Epoch 3551, Loss: 0.25764328241348267, Final Batch Loss: 0.1304919272661209
Epoch 3552, Loss: 0.15868350118398666, Final Batch Loss: 0.07420390844345093
Epoch 3553, Loss: 0.24731702357530594, Final Batch Loss: 0.12441924214363098
Epoch 3554, Loss: 0.32813723385334015, Final Batch Loss: 0.19460831582546234
Epoch 3555, Loss: 0.2520676553249359, Final Batch Loss: 0.1584911346435547
Epoch 3556, Loss: 0.2060507833957672, Final Batch Loss: 0.10890225321054459
Epoch 3557, Loss: 0.2615528702735901, Final Batch Loss: 0.15374711155891418
Epoch 3558, Loss: 0.24017030745744705, Final Batch Loss: 0.12826204299926758
Epoch 3559, Loss: 0.29107168316841125, Final Batch Loss: 0.16939647495746613
Epoch 3560, Loss: 0.22546449303627014, Final Batch Loss: 0.11633159220218658
Epoch

Epoch 3658, Loss: 0.26121992617845535, Final Batch Loss: 0.15068887174129486
Epoch 3659, Loss: 0.266486719250679, Final Batch Loss: 0.1383078694343567
Epoch 3660, Loss: 0.28680409491062164, Final Batch Loss: 0.14053139090538025
Epoch 3661, Loss: 0.2369092032313347, Final Batch Loss: 0.12300463020801544
Epoch 3662, Loss: 0.22111745178699493, Final Batch Loss: 0.09540565311908722
Epoch 3663, Loss: 0.2189928963780403, Final Batch Loss: 0.11187038570642471
Epoch 3664, Loss: 0.1780613660812378, Final Batch Loss: 0.07358759641647339
Epoch 3665, Loss: 0.2751188725233078, Final Batch Loss: 0.11735723912715912
Epoch 3666, Loss: 0.19565751403570175, Final Batch Loss: 0.0899457111954689
Epoch 3667, Loss: 0.277692973613739, Final Batch Loss: 0.12525136768817902
Epoch 3668, Loss: 0.20407484471797943, Final Batch Loss: 0.08265653997659683
Epoch 3669, Loss: 0.2938520908355713, Final Batch Loss: 0.15599125623703003
Epoch 3670, Loss: 0.29358746111392975, Final Batch Loss: 0.12822768092155457
Epoch 3671

Epoch 3771, Loss: 0.24841484427452087, Final Batch Loss: 0.12637247145175934
Epoch 3772, Loss: 0.18328650668263435, Final Batch Loss: 0.04957840219140053
Epoch 3773, Loss: 0.24109061807394028, Final Batch Loss: 0.12544682621955872
Epoch 3774, Loss: 0.2739686295390129, Final Batch Loss: 0.09811874479055405
Epoch 3775, Loss: 0.25273969024419785, Final Batch Loss: 0.1293209344148636
Epoch 3776, Loss: 0.21504800766706467, Final Batch Loss: 0.0946987196803093
Epoch 3777, Loss: 0.223761148750782, Final Batch Loss: 0.09912526607513428
Epoch 3778, Loss: 0.16021154075860977, Final Batch Loss: 0.08067577332258224
Epoch 3779, Loss: 0.435310997068882, Final Batch Loss: 0.31870096921920776
Epoch 3780, Loss: 0.2619955539703369, Final Batch Loss: 0.15934708714485168
Epoch 3781, Loss: 0.3256145566701889, Final Batch Loss: 0.19315986335277557
Epoch 3782, Loss: 0.19487299770116806, Final Batch Loss: 0.09040624648332596
Epoch 3783, Loss: 0.1836465373635292, Final Batch Loss: 0.08555572479963303
Epoch 378

Epoch 3883, Loss: 0.21908030658960342, Final Batch Loss: 0.09642721712589264
Epoch 3884, Loss: 0.19965588301420212, Final Batch Loss: 0.10697294771671295
Epoch 3885, Loss: 0.1878330409526825, Final Batch Loss: 0.10375278443098068
Epoch 3886, Loss: 0.2093547210097313, Final Batch Loss: 0.13511385023593903
Epoch 3887, Loss: 0.2810598686337471, Final Batch Loss: 0.11100590974092484
Epoch 3888, Loss: 0.22343578934669495, Final Batch Loss: 0.0871935784816742
Epoch 3889, Loss: 0.2930036410689354, Final Batch Loss: 0.1174183115363121
Epoch 3890, Loss: 0.2150629758834839, Final Batch Loss: 0.12215742468833923
Epoch 3891, Loss: 0.20550885796546936, Final Batch Loss: 0.08748336881399155
Epoch 3892, Loss: 0.20949596166610718, Final Batch Loss: 0.06341968476772308
Epoch 3893, Loss: 0.1953534260392189, Final Batch Loss: 0.07935196906328201
Epoch 3894, Loss: 0.20918381214141846, Final Batch Loss: 0.11812794208526611
Epoch 3895, Loss: 0.2631828933954239, Final Batch Loss: 0.18585632741451263
Epoch 38

Epoch 3995, Loss: 0.2552417293190956, Final Batch Loss: 0.13456088304519653
Epoch 3996, Loss: 0.22780870646238327, Final Batch Loss: 0.14151136577129364
Epoch 3997, Loss: 0.23527763783931732, Final Batch Loss: 0.10807134211063385
Epoch 3998, Loss: 0.278532013297081, Final Batch Loss: 0.1304597109556198
Epoch 3999, Loss: 0.2522125095129013, Final Batch Loss: 0.13918328285217285
Epoch 4000, Loss: 0.24055420607328415, Final Batch Loss: 0.1027059331536293
Epoch 4001, Loss: 0.2966403365135193, Final Batch Loss: 0.1887427419424057
Epoch 4002, Loss: 0.2276948243379593, Final Batch Loss: 0.1382479965686798
Epoch 4003, Loss: 0.30623912811279297, Final Batch Loss: 0.17536349594593048
Epoch 4004, Loss: 0.21064206212759018, Final Batch Loss: 0.08667753636837006
Epoch 4005, Loss: 0.24652926623821259, Final Batch Loss: 0.15733453631401062
Epoch 4006, Loss: 0.3084639310836792, Final Batch Loss: 0.18930210173130035
Epoch 4007, Loss: 0.26423005759716034, Final Batch Loss: 0.15175913274288177
Epoch 4008

Epoch 4110, Loss: 0.3328167498111725, Final Batch Loss: 0.17254026234149933
Epoch 4111, Loss: 0.19270580261945724, Final Batch Loss: 0.09523864090442657
Epoch 4112, Loss: 0.20784325152635574, Final Batch Loss: 0.10050308704376221
Epoch 4113, Loss: 0.2356022447347641, Final Batch Loss: 0.16349443793296814
Epoch 4114, Loss: 0.22048934549093246, Final Batch Loss: 0.12684223055839539
Epoch 4115, Loss: 0.18945523351430893, Final Batch Loss: 0.05363360792398453
Epoch 4116, Loss: 0.16622334718704224, Final Batch Loss: 0.08380936831235886
Epoch 4117, Loss: 0.20923079550266266, Final Batch Loss: 0.0861673578619957
Epoch 4118, Loss: 0.2175236940383911, Final Batch Loss: 0.1078038290143013
Epoch 4119, Loss: 0.21801266074180603, Final Batch Loss: 0.08768357336521149
Epoch 4120, Loss: 0.151121586561203, Final Batch Loss: 0.06598594784736633
Epoch 4121, Loss: 0.2259514406323433, Final Batch Loss: 0.11178800463676453
Epoch 4122, Loss: 0.244065523147583, Final Batch Loss: 0.14068643748760223
Epoch 412

Epoch 4223, Loss: 0.2249317169189453, Final Batch Loss: 0.1434738039970398
Epoch 4224, Loss: 0.24211354553699493, Final Batch Loss: 0.09701010584831238
Epoch 4225, Loss: 0.24326545000076294, Final Batch Loss: 0.1226256862282753
Epoch 4226, Loss: 0.2732270583510399, Final Batch Loss: 0.11873861402273178
Epoch 4227, Loss: 0.166649729013443, Final Batch Loss: 0.06863430142402649
Epoch 4228, Loss: 0.20206185430288315, Final Batch Loss: 0.09536095708608627
Epoch 4229, Loss: 0.325541116297245, Final Batch Loss: 0.22120246291160583
Epoch 4230, Loss: 0.1762462966144085, Final Batch Loss: 0.06068749353289604
Epoch 4231, Loss: 0.18678981810808182, Final Batch Loss: 0.10554342716932297
Epoch 4232, Loss: 0.2804693952202797, Final Batch Loss: 0.17077192664146423
Epoch 4233, Loss: 0.21793480962514877, Final Batch Loss: 0.1283939629793167
Epoch 4234, Loss: 0.3019024580717087, Final Batch Loss: 0.15494489669799805
Epoch 4235, Loss: 0.257171630859375, Final Batch Loss: 0.14616508781909943
Epoch 4236, L

Epoch 4337, Loss: 0.2075548842549324, Final Batch Loss: 0.08010151237249374
Epoch 4338, Loss: 0.21651417762041092, Final Batch Loss: 0.09554290026426315
Epoch 4339, Loss: 0.311959907412529, Final Batch Loss: 0.1615809053182602
Epoch 4340, Loss: 0.1803993061184883, Final Batch Loss: 0.08713194727897644
Epoch 4341, Loss: 0.21199370920658112, Final Batch Loss: 0.11434230953454971
Epoch 4342, Loss: 0.17499911040067673, Final Batch Loss: 0.09786199033260345
Epoch 4343, Loss: 0.2760689854621887, Final Batch Loss: 0.15352636575698853
Epoch 4344, Loss: 0.29399100691080093, Final Batch Loss: 0.1155344769358635
Epoch 4345, Loss: 0.21849096566438675, Final Batch Loss: 0.1332160383462906
Epoch 4346, Loss: 0.19785889238119125, Final Batch Loss: 0.07774395495653152
Epoch 4347, Loss: 0.24187052994966507, Final Batch Loss: 0.12425863742828369
Epoch 4348, Loss: 0.13028960302472115, Final Batch Loss: 0.07323098182678223
Epoch 4349, Loss: 0.22467408329248428, Final Batch Loss: 0.09790881723165512
Epoch 4

Epoch 4450, Loss: 0.18286597728729248, Final Batch Loss: 0.07551492005586624
Epoch 4451, Loss: 0.27844327688217163, Final Batch Loss: 0.13677754998207092
Epoch 4452, Loss: 0.2211771234869957, Final Batch Loss: 0.11370570957660675
Epoch 4453, Loss: 0.17841382324695587, Final Batch Loss: 0.06839116662740707
Epoch 4454, Loss: 0.2089892029762268, Final Batch Loss: 0.12137484550476074
Epoch 4455, Loss: 0.14507203549146652, Final Batch Loss: 0.0627676472067833
Epoch 4456, Loss: 0.21507905423641205, Final Batch Loss: 0.12862151861190796
Epoch 4457, Loss: 0.1761307492852211, Final Batch Loss: 0.07703227549791336
Epoch 4458, Loss: 0.21796602755784988, Final Batch Loss: 0.07797285169363022
Epoch 4459, Loss: 0.14531387388706207, Final Batch Loss: 0.06835572421550751
Epoch 4460, Loss: 0.17441987991333008, Final Batch Loss: 0.07933668047189713
Epoch 4461, Loss: 0.20844805240631104, Final Batch Loss: 0.09088282287120819
Epoch 4462, Loss: 0.17581962049007416, Final Batch Loss: 0.07527457177639008
Epo

Epoch 4561, Loss: 0.18154702335596085, Final Batch Loss: 0.06359310448169708
Epoch 4562, Loss: 0.20515019446611404, Final Batch Loss: 0.08159332722425461
Epoch 4563, Loss: 0.2317010909318924, Final Batch Loss: 0.12609738111495972
Epoch 4564, Loss: 0.17368608713150024, Final Batch Loss: 0.10055797547101974
Epoch 4565, Loss: 0.16246102005243301, Final Batch Loss: 0.09463146328926086
Epoch 4566, Loss: 0.2129187509417534, Final Batch Loss: 0.12176142632961273
Epoch 4567, Loss: 0.2571898326277733, Final Batch Loss: 0.09424792975187302
Epoch 4568, Loss: 0.1969277337193489, Final Batch Loss: 0.09879229962825775
Epoch 4569, Loss: 0.2000475972890854, Final Batch Loss: 0.09165756404399872
Epoch 4570, Loss: 0.20821496099233627, Final Batch Loss: 0.12447801232337952
Epoch 4571, Loss: 0.21478526294231415, Final Batch Loss: 0.10727684199810028
Epoch 4572, Loss: 0.22511909902095795, Final Batch Loss: 0.12166096270084381
Epoch 4573, Loss: 0.22881296277046204, Final Batch Loss: 0.10945528745651245
Epoc

Epoch 4672, Loss: 0.21754104644060135, Final Batch Loss: 0.1304243505001068
Epoch 4673, Loss: 0.23417479544878006, Final Batch Loss: 0.15166904032230377
Epoch 4674, Loss: 0.23818986117839813, Final Batch Loss: 0.09916380047798157
Epoch 4675, Loss: 0.16400843113660812, Final Batch Loss: 0.091618113219738
Epoch 4676, Loss: 0.20455146580934525, Final Batch Loss: 0.09217371791601181
Epoch 4677, Loss: 0.21625296771526337, Final Batch Loss: 0.14682511985301971
Epoch 4678, Loss: 0.2504638582468033, Final Batch Loss: 0.1373957097530365
Epoch 4679, Loss: 0.22915935516357422, Final Batch Loss: 0.09336104989051819
Epoch 4680, Loss: 0.15808677673339844, Final Batch Loss: 0.07114493101835251
Epoch 4681, Loss: 0.18245181441307068, Final Batch Loss: 0.10363525152206421
Epoch 4682, Loss: 0.24583376944065094, Final Batch Loss: 0.10021248459815979
Epoch 4683, Loss: 0.28540556132793427, Final Batch Loss: 0.14305591583251953
Epoch 4684, Loss: 0.17736519128084183, Final Batch Loss: 0.10539324581623077
Epoc

Epoch 4784, Loss: 0.19919109344482422, Final Batch Loss: 0.07493841648101807
Epoch 4785, Loss: 0.19797784835100174, Final Batch Loss: 0.10192470252513885
Epoch 4786, Loss: 0.20949847996234894, Final Batch Loss: 0.1044020876288414
Epoch 4787, Loss: 0.1867453157901764, Final Batch Loss: 0.09250257909297943
Epoch 4788, Loss: 0.15220796316862106, Final Batch Loss: 0.06684347987174988
Epoch 4789, Loss: 0.21382589638233185, Final Batch Loss: 0.1008482426404953
Epoch 4790, Loss: 0.21625323593616486, Final Batch Loss: 0.0838804543018341
Epoch 4791, Loss: 0.23402804136276245, Final Batch Loss: 0.11028219759464264
Epoch 4792, Loss: 0.14107517898082733, Final Batch Loss: 0.0625104084610939
Epoch 4793, Loss: 0.24429992586374283, Final Batch Loss: 0.09181607514619827
Epoch 4794, Loss: 0.22761959582567215, Final Batch Loss: 0.08858095854520798
Epoch 4795, Loss: 0.21310542523860931, Final Batch Loss: 0.10143326967954636
Epoch 4796, Loss: 0.17421536147594452, Final Batch Loss: 0.09902460873126984
Epoc

Epoch 4897, Loss: 0.16347705572843552, Final Batch Loss: 0.07901841402053833
Epoch 4898, Loss: 0.17880918085575104, Final Batch Loss: 0.08442215621471405
Epoch 4899, Loss: 0.2553791478276253, Final Batch Loss: 0.1805746704339981
Epoch 4900, Loss: 0.16907446458935738, Final Batch Loss: 0.11507628858089447
Epoch 4901, Loss: 0.17990579456090927, Final Batch Loss: 0.0640285462141037
Epoch 4902, Loss: 0.2142663449048996, Final Batch Loss: 0.13544540107250214
Epoch 4903, Loss: 0.21623771637678146, Final Batch Loss: 0.10612701624631882
Epoch 4904, Loss: 0.25547612458467484, Final Batch Loss: 0.15996429324150085
Epoch 4905, Loss: 0.15684397518634796, Final Batch Loss: 0.07867634296417236
Epoch 4906, Loss: 0.17463793605566025, Final Batch Loss: 0.11192311346530914
Epoch 4907, Loss: 0.14774642139673233, Final Batch Loss: 0.05794867128133774
Epoch 4908, Loss: 0.13298435509204865, Final Batch Loss: 0.06449439376592636
Epoch 4909, Loss: 0.22617466747760773, Final Batch Loss: 0.0908125787973404
Epoc

In [186]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[18  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0]
 [ 0  0  0  1 14  0  0  0  0]
 [ 0  0  1  0  0  6  0  0  0]
 [ 0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  1  0  0  7]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        18
           1    1.00000   1.00000   1.00000        11
           2    0.90909   1.00000   0.95238        10
           3    0.90909   1.00000   0.95238        10
           4    1.00000   0.93333   0.96552        15
           5    0.85714   0.85714   0.85714         7
           6    1.00000   1.00000   1.00000        11
           7    1.00000   1.00000   1.00000        10
           8    1.00000   0.87500   0.93333         8

    accuracy                        0.97000       100
   macro avg    0.96392   0.96283   0.96231       100
weighted avg    0.97182   0.97000   0.96997       100



# Train on Fake Test on Real

In [ ]:
# 20,000 epochs DEFAULT PARAMETERS FOR THRESHOLDS

In [187]:
gen = Generator(z_dim = 106)
load_model(gen, "cGAN_UCI_8_19_gen.param")
gen.eval()

Generator(
  (gen): Sequential(
    (0): Sequential(
      (0): Linear(in_features=106, out_features=80, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Linear(in_features=80, out_features=60, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (2): Sequential(
      (0): Linear(in_features=60, out_features=50, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (3): Linear(in_features=50, out_features=46, bias=True)
    (4): Tanh()
  )
)

In [201]:
size = len(X_test)
latent_vectors = get_noise(size, 100)
act_vectors = get_act_matrix(size, 3)
usr_vectors = get_usr_matrix(size, 3)

fake_labels = []

for k in range(size):
    if act_vectors[0][k] == 0 and usr_vectors[0][k] == 0:
        fake_labels.append(0)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 0:
        fake_labels.append(1)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 0:
        fake_labels.append(2)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 1:
        fake_labels.append(3)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 1:
        fake_labels.append(4)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 1:
        fake_labels.append(5)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 2:
        fake_labels.append(6)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 2:
        fake_labels.append(7)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 2:
        fake_labels.append(8)

fake_labels = np.asarray(fake_labels)
to_gen = torch.cat((latent_vectors, act_vectors[1], usr_vectors[1]), 1)
fake_features = gen(to_gen).detach()
#fake_features = gen(to_gen).detach().numpy()

In [202]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[13  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0]
 [ 0  0 14  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0 13  0  0  1]
 [ 0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0 16  0]
 [ 0  0  0  0  0  0  2  0  0]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        13
           1    1.00000   1.00000   1.00000         5
           2    1.00000   1.00000   1.00000        14
           3    1.00000   1.00000   1.00000        15
           4    1.00000   1.00000   1.00000        10
           5    1.00000   0.92857   0.96296        14
           6    0.84615   1.00000   0.91667        11
           7    1.00000   1.00000   1.00000        16
           8    0.00000   0.00000   0.00000         2

    accuracy                        0.97000       100
   macro avg    0.87179   0.88095   0.87551       100
weighted avg    0.96308   0.97000   0.96565       100

