In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '59 tGravityAcc-energy()-Z',
 '125 tBodyGyro-std()-Y',
 '128 tBodyGyro-mad()-Y',
 '138 tBodyGyro-energy()-Y',
 '165 tBodyGyroJerk-std()-Y',
 '168 tBodyGyroJerk-mad()-Y',
 '178 tBodyGyroJerk-energy()-Y',
 '181 tBodyGyroJerk-iqr()-Y',
 '425 fBodyGyro-mean()-Y',
 '428 fBodyGyro-std()-Y',
 '431 fBodyGyro-mad()-Y',
 '441 fBodyGyro-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '478 fBodyGyro-bandsEnergy()-25,32',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '204 tBodyAccMag-max()',
 '215 tGravityAccMag-std()',
 '217 tGravityAccMag-max()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '275 fBodyAcc-max()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '506 fBodyAccMag-max()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            classifier_block(15, 10),
            nn.Linear(10, 9)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../saved_models/{model_name}'))

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']

    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 14) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 14) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 14) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 15) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 15) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 15) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 17) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 17) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 17) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [14, 15, 17]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [7]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 4.440162181854248, Final Batch Loss: 2.2082464694976807
Epoch 2, Loss: 4.431634902954102, Final Batch Loss: 2.1955196857452393
Epoch 3, Loss: 4.43436861038208, Final Batch Loss: 2.2138521671295166
Epoch 4, Loss: 4.429298400878906, Final Batch Loss: 2.202758312225342
Epoch 5, Loss: 4.432542324066162, Final Batch Loss: 2.2178549766540527
Epoch 6, Loss: 4.4314258098602295, Final Batch Loss: 2.2220101356506348
Epoch 7, Loss: 4.422696590423584, Final Batch Loss: 2.209352493286133
Epoch 8, Loss: 4.416726350784302, Final Batch Loss: 2.2054061889648438
Epoch 9, Loss: 4.411235570907593, Final Batch Loss: 2.2046492099761963
Epoch 10, Loss: 4.4143922328948975, Final Batch Loss: 2.2101757526397705
Epoch 11, Loss: 4.403315305709839, Final Batch Loss: 2.195671796798706
Epoch 12, Loss: 4.398383378982544, Final Batch Loss: 2.190040349960327
Epoch 13, Loss: 4.407072067260742, Final Batch Loss: 2.2158682346343994
Epoch 14, Loss: 4.391805171966553, Final Batch Loss: 2.197657823562622
Epoch

Epoch 121, Loss: 2.027718961238861, Final Batch Loss: 0.9879737496376038
Epoch 122, Loss: 2.083704948425293, Final Batch Loss: 1.0287251472473145
Epoch 123, Loss: 1.9738521575927734, Final Batch Loss: 0.9669747352600098
Epoch 124, Loss: 2.032165765762329, Final Batch Loss: 1.0507198572158813
Epoch 125, Loss: 2.105739712715149, Final Batch Loss: 1.0992822647094727
Epoch 126, Loss: 1.9250598549842834, Final Batch Loss: 0.9483267068862915
Epoch 127, Loss: 1.954932153224945, Final Batch Loss: 0.9554834365844727
Epoch 128, Loss: 1.9411250352859497, Final Batch Loss: 0.9258109331130981
Epoch 129, Loss: 2.0324826836586, Final Batch Loss: 1.0531355142593384
Epoch 130, Loss: 1.914914608001709, Final Batch Loss: 0.9776797294616699
Epoch 131, Loss: 1.9749276041984558, Final Batch Loss: 0.9987398982048035
Epoch 132, Loss: 1.9969715476036072, Final Batch Loss: 0.9913132786750793
Epoch 133, Loss: 2.0436244010925293, Final Batch Loss: 1.0102170705795288
Epoch 134, Loss: 1.9552233219146729, Final Batc

Epoch 241, Loss: 1.3535632491111755, Final Batch Loss: 0.7030386924743652
Epoch 242, Loss: 1.3702980279922485, Final Batch Loss: 0.6922874450683594
Epoch 243, Loss: 1.3329049348831177, Final Batch Loss: 0.6790294647216797
Epoch 244, Loss: 1.289788842201233, Final Batch Loss: 0.6131523251533508
Epoch 245, Loss: 1.3759021759033203, Final Batch Loss: 0.6969937086105347
Epoch 246, Loss: 1.358367145061493, Final Batch Loss: 0.6670178174972534
Epoch 247, Loss: 1.385493278503418, Final Batch Loss: 0.770465075969696
Epoch 248, Loss: 1.3358246684074402, Final Batch Loss: 0.6873610019683838
Epoch 249, Loss: 1.2903789281845093, Final Batch Loss: 0.5875228643417358
Epoch 250, Loss: 1.256798267364502, Final Batch Loss: 0.619580090045929
Epoch 251, Loss: 1.3335672616958618, Final Batch Loss: 0.6402621269226074
Epoch 252, Loss: 1.277637243270874, Final Batch Loss: 0.6371472477912903
Epoch 253, Loss: 1.282669186592102, Final Batch Loss: 0.6854606866836548
Epoch 254, Loss: 1.2250239253044128, Final Bat

Epoch 357, Loss: 0.9990724325180054, Final Batch Loss: 0.5215614438056946
Epoch 358, Loss: 1.0800487995147705, Final Batch Loss: 0.5731357932090759
Epoch 359, Loss: 0.9824163317680359, Final Batch Loss: 0.5382736921310425
Epoch 360, Loss: 0.9794229865074158, Final Batch Loss: 0.4740772247314453
Epoch 361, Loss: 0.9346596896648407, Final Batch Loss: 0.4541826546192169
Epoch 362, Loss: 0.9205688834190369, Final Batch Loss: 0.43905705213546753
Epoch 363, Loss: 0.9127344191074371, Final Batch Loss: 0.3824264109134674
Epoch 364, Loss: 1.0033100843429565, Final Batch Loss: 0.4915015697479248
Epoch 365, Loss: 1.0985193252563477, Final Batch Loss: 0.564925491809845
Epoch 366, Loss: 1.0098675191402435, Final Batch Loss: 0.6032668352127075
Epoch 367, Loss: 1.0161621272563934, Final Batch Loss: 0.5790647268295288
Epoch 368, Loss: 1.020173966884613, Final Batch Loss: 0.5213600993156433
Epoch 369, Loss: 0.9244889318943024, Final Batch Loss: 0.4272715151309967
Epoch 370, Loss: 0.9644765555858612, Fi

Epoch 489, Loss: 0.8452869057655334, Final Batch Loss: 0.4414781332015991
Epoch 490, Loss: 0.8302426338195801, Final Batch Loss: 0.4073777496814728
Epoch 491, Loss: 0.8284578621387482, Final Batch Loss: 0.41619402170181274
Epoch 492, Loss: 0.8495442569255829, Final Batch Loss: 0.45137977600097656
Epoch 493, Loss: 0.8466687500476837, Final Batch Loss: 0.42650124430656433
Epoch 494, Loss: 0.8626956045627594, Final Batch Loss: 0.40636932849884033
Epoch 495, Loss: 0.8121715486049652, Final Batch Loss: 0.3614071309566498
Epoch 496, Loss: 0.8299790024757385, Final Batch Loss: 0.3609566390514374
Epoch 497, Loss: 0.8750272691249847, Final Batch Loss: 0.4366535544395447
Epoch 498, Loss: 0.9393079876899719, Final Batch Loss: 0.47879213094711304
Epoch 499, Loss: 0.891334593296051, Final Batch Loss: 0.4050208330154419
Epoch 500, Loss: 0.8612225651741028, Final Batch Loss: 0.46480703353881836
Epoch 501, Loss: 0.8440901041030884, Final Batch Loss: 0.4137289822101593
Epoch 502, Loss: 0.85301029682159

Epoch 617, Loss: 0.7919317483901978, Final Batch Loss: 0.44741883873939514
Epoch 618, Loss: 0.7514171004295349, Final Batch Loss: 0.3329709768295288
Epoch 619, Loss: 0.8035233020782471, Final Batch Loss: 0.3886737823486328
Epoch 620, Loss: 0.8048924207687378, Final Batch Loss: 0.3677983582019806
Epoch 621, Loss: 0.844156414270401, Final Batch Loss: 0.47586789727211
Epoch 622, Loss: 0.8567602038383484, Final Batch Loss: 0.4759347140789032
Epoch 623, Loss: 0.807996392250061, Final Batch Loss: 0.4019576609134674
Epoch 624, Loss: 0.7982386946678162, Final Batch Loss: 0.38517677783966064
Epoch 625, Loss: 0.81346395611763, Final Batch Loss: 0.4017103910446167
Epoch 626, Loss: 0.7584227621555328, Final Batch Loss: 0.3392518162727356
Epoch 627, Loss: 0.8559302389621735, Final Batch Loss: 0.4868301749229431
Epoch 628, Loss: 0.8274253308773041, Final Batch Loss: 0.45438265800476074
Epoch 629, Loss: 0.825180321931839, Final Batch Loss: 0.4425080716609955
Epoch 630, Loss: 0.7823302149772644, Final

Epoch 745, Loss: 0.7609599828720093, Final Batch Loss: 0.35450172424316406
Epoch 746, Loss: 0.769745260477066, Final Batch Loss: 0.4312070310115814
Epoch 747, Loss: 0.7731520533561707, Final Batch Loss: 0.3842511773109436
Epoch 748, Loss: 0.7242460250854492, Final Batch Loss: 0.3515700101852417
Epoch 749, Loss: 0.7528943419456482, Final Batch Loss: 0.36238110065460205
Epoch 750, Loss: 0.7402602136135101, Final Batch Loss: 0.3820503354072571
Epoch 751, Loss: 0.7248794734477997, Final Batch Loss: 0.38495394587516785
Epoch 752, Loss: 0.8115681707859039, Final Batch Loss: 0.42504727840423584
Epoch 753, Loss: 0.762953132390976, Final Batch Loss: 0.3759625256061554
Epoch 754, Loss: 0.7006478309631348, Final Batch Loss: 0.3610050678253174
Epoch 755, Loss: 0.7963029742240906, Final Batch Loss: 0.31627678871154785
Epoch 756, Loss: 0.7429707050323486, Final Batch Loss: 0.3824307918548584
Epoch 757, Loss: 0.7689498960971832, Final Batch Loss: 0.3655736744403839
Epoch 758, Loss: 0.7996677756309509

Epoch 874, Loss: 0.7555351853370667, Final Batch Loss: 0.33875906467437744
Epoch 875, Loss: 0.6858914792537689, Final Batch Loss: 0.32895371317863464
Epoch 876, Loss: 0.704905241727829, Final Batch Loss: 0.3730643689632416
Epoch 877, Loss: 0.7372937798500061, Final Batch Loss: 0.41311487555503845
Epoch 878, Loss: 0.7066936492919922, Final Batch Loss: 0.3642067313194275
Epoch 879, Loss: 0.6694838106632233, Final Batch Loss: 0.31543704867362976
Epoch 880, Loss: 0.7028918564319611, Final Batch Loss: 0.3706105947494507
Epoch 881, Loss: 0.7246206998825073, Final Batch Loss: 0.337998628616333
Epoch 882, Loss: 0.7254526019096375, Final Batch Loss: 0.32693883776664734
Epoch 883, Loss: 0.6992147266864777, Final Batch Loss: 0.3319903314113617
Epoch 884, Loss: 0.720938503742218, Final Batch Loss: 0.3180919587612152
Epoch 885, Loss: 0.6976231336593628, Final Batch Loss: 0.32680782675743103
Epoch 886, Loss: 0.6715425848960876, Final Batch Loss: 0.31126970052719116
Epoch 887, Loss: 0.727930992841720

Epoch 997, Loss: 0.6989153623580933, Final Batch Loss: 0.308536171913147
Epoch 998, Loss: 0.7320312261581421, Final Batch Loss: 0.39330944418907166
Epoch 999, Loss: 0.7139775454998016, Final Batch Loss: 0.3469749987125397
Epoch 1000, Loss: 0.7434061765670776, Final Batch Loss: 0.4451986849308014
Epoch 1001, Loss: 0.6915625035762787, Final Batch Loss: 0.35356804728507996
Epoch 1002, Loss: 0.6892466247081757, Final Batch Loss: 0.3697410821914673
Epoch 1003, Loss: 0.6833967864513397, Final Batch Loss: 0.3640322983264923
Epoch 1004, Loss: 0.6814523339271545, Final Batch Loss: 0.3621789515018463
Epoch 1005, Loss: 0.7477120757102966, Final Batch Loss: 0.37007254362106323
Epoch 1006, Loss: 0.7004427909851074, Final Batch Loss: 0.3102808892726898
Epoch 1007, Loss: 0.7114290297031403, Final Batch Loss: 0.3715290129184723
Epoch 1008, Loss: 0.6367690563201904, Final Batch Loss: 0.3196122646331787
Epoch 1009, Loss: 0.7816676199436188, Final Batch Loss: 0.44092053174972534
Epoch 1010, Loss: 0.66531

Epoch 1121, Loss: 0.6386202275753021, Final Batch Loss: 0.29207050800323486
Epoch 1122, Loss: 0.6547160744667053, Final Batch Loss: 0.3426332175731659
Epoch 1123, Loss: 0.6539117991924286, Final Batch Loss: 0.31534522771835327
Epoch 1124, Loss: 0.6310699582099915, Final Batch Loss: 0.294392466545105
Epoch 1125, Loss: 0.6565142869949341, Final Batch Loss: 0.32249391078948975
Epoch 1126, Loss: 0.6744058430194855, Final Batch Loss: 0.3632356822490692
Epoch 1127, Loss: 0.6651150286197662, Final Batch Loss: 0.3400048613548279
Epoch 1128, Loss: 0.659231036901474, Final Batch Loss: 0.3365570306777954
Epoch 1129, Loss: 0.6700442731380463, Final Batch Loss: 0.34710854291915894
Epoch 1130, Loss: 0.6018147468566895, Final Batch Loss: 0.27949923276901245
Epoch 1131, Loss: 0.6036454737186432, Final Batch Loss: 0.28348278999328613
Epoch 1132, Loss: 0.6068529486656189, Final Batch Loss: 0.3134276270866394
Epoch 1133, Loss: 0.6462826132774353, Final Batch Loss: 0.34274882078170776
Epoch 1134, Loss: 0.

Epoch 1247, Loss: 0.6130620837211609, Final Batch Loss: 0.2440037727355957
Epoch 1248, Loss: 0.639846920967102, Final Batch Loss: 0.34182068705558777
Epoch 1249, Loss: 0.7396516799926758, Final Batch Loss: 0.4024307429790497
Epoch 1250, Loss: 0.5829660594463348, Final Batch Loss: 0.2779996395111084
Epoch 1251, Loss: 0.6870647072792053, Final Batch Loss: 0.3687606155872345
Epoch 1252, Loss: 0.5860988795757294, Final Batch Loss: 0.3054403066635132
Epoch 1253, Loss: 0.6617991328239441, Final Batch Loss: 0.3229638636112213
Epoch 1254, Loss: 0.7157657742500305, Final Batch Loss: 0.36694321036338806
Epoch 1255, Loss: 0.6094053089618683, Final Batch Loss: 0.29462891817092896
Epoch 1256, Loss: 0.6853485703468323, Final Batch Loss: 0.372807115316391
Epoch 1257, Loss: 0.6220984756946564, Final Batch Loss: 0.3403001129627228
Epoch 1258, Loss: 0.6343886256217957, Final Batch Loss: 0.3254227638244629
Epoch 1259, Loss: 0.6659730672836304, Final Batch Loss: 0.3509462773799896
Epoch 1260, Loss: 0.5877

Epoch 1365, Loss: 0.5917130708694458, Final Batch Loss: 0.2950183153152466
Epoch 1366, Loss: 0.6125487983226776, Final Batch Loss: 0.29015693068504333
Epoch 1367, Loss: 0.6267406642436981, Final Batch Loss: 0.3317665755748749
Epoch 1368, Loss: 0.6350703537464142, Final Batch Loss: 0.34474119544029236
Epoch 1369, Loss: 0.6295132339000702, Final Batch Loss: 0.3334846496582031
Epoch 1370, Loss: 0.6361751556396484, Final Batch Loss: 0.3059360086917877
Epoch 1371, Loss: 0.6208906769752502, Final Batch Loss: 0.3026474118232727
Epoch 1372, Loss: 0.5830206573009491, Final Batch Loss: 0.31881776452064514
Epoch 1373, Loss: 0.656565934419632, Final Batch Loss: 0.4026574194431305
Epoch 1374, Loss: 0.6793861389160156, Final Batch Loss: 0.40656179189682007
Epoch 1375, Loss: 0.6225528120994568, Final Batch Loss: 0.3359020948410034
Epoch 1376, Loss: 0.6408877670764923, Final Batch Loss: 0.3511998951435089
Epoch 1377, Loss: 0.662937194108963, Final Batch Loss: 0.31298622488975525
Epoch 1378, Loss: 0.59

Epoch 1487, Loss: 0.6320710182189941, Final Batch Loss: 0.3182299733161926
Epoch 1488, Loss: 0.6239182651042938, Final Batch Loss: 0.3645954132080078
Epoch 1489, Loss: 0.611097127199173, Final Batch Loss: 0.2925628423690796
Epoch 1490, Loss: 0.5946861803531647, Final Batch Loss: 0.2588089406490326
Epoch 1491, Loss: 0.5941075086593628, Final Batch Loss: 0.29043444991111755
Epoch 1492, Loss: 0.5862491726875305, Final Batch Loss: 0.3004751205444336
Epoch 1493, Loss: 0.64591184258461, Final Batch Loss: 0.35206568241119385
Epoch 1494, Loss: 0.5639536529779434, Final Batch Loss: 0.2488846331834793
Epoch 1495, Loss: 0.5954731702804565, Final Batch Loss: 0.2739435136318207
Epoch 1496, Loss: 0.5961821675300598, Final Batch Loss: 0.2500636875629425
Epoch 1497, Loss: 0.5789524018764496, Final Batch Loss: 0.29892948269844055
Epoch 1498, Loss: 0.5961765050888062, Final Batch Loss: 0.311470627784729
Epoch 1499, Loss: 0.6042765378952026, Final Batch Loss: 0.32390570640563965
Epoch 1500, Loss: 0.58920

Epoch 1609, Loss: 0.5729998052120209, Final Batch Loss: 0.3017065227031708
Epoch 1610, Loss: 0.5308035314083099, Final Batch Loss: 0.2189059555530548
Epoch 1611, Loss: 0.6346472799777985, Final Batch Loss: 0.34635424613952637
Epoch 1612, Loss: 0.6293015480041504, Final Batch Loss: 0.28928089141845703
Epoch 1613, Loss: 0.5711809396743774, Final Batch Loss: 0.2646466791629791
Epoch 1614, Loss: 0.5708140730857849, Final Batch Loss: 0.2707836329936981
Epoch 1615, Loss: 0.6153852641582489, Final Batch Loss: 0.3002975583076477
Epoch 1616, Loss: 0.5885220468044281, Final Batch Loss: 0.3131459355354309
Epoch 1617, Loss: 0.5731571018695831, Final Batch Loss: 0.2886207103729248
Epoch 1618, Loss: 0.5697273910045624, Final Batch Loss: 0.26041683554649353
Epoch 1619, Loss: 0.5944064855575562, Final Batch Loss: 0.3471089005470276
Epoch 1620, Loss: 0.59166219830513, Final Batch Loss: 0.2692350745201111
Epoch 1621, Loss: 0.5817244052886963, Final Batch Loss: 0.27217817306518555
Epoch 1622, Loss: 0.567

Epoch 1730, Loss: 0.577917218208313, Final Batch Loss: 0.3071400821208954
Epoch 1731, Loss: 0.6492262482643127, Final Batch Loss: 0.3869382441043854
Epoch 1732, Loss: 0.5683488845825195, Final Batch Loss: 0.2613300085067749
Epoch 1733, Loss: 0.6097801327705383, Final Batch Loss: 0.3333297371864319
Epoch 1734, Loss: 0.5722737610340118, Final Batch Loss: 0.28432950377464294
Epoch 1735, Loss: 0.5596771538257599, Final Batch Loss: 0.2695685923099518
Epoch 1736, Loss: 0.5655449479818344, Final Batch Loss: 0.24591900408267975
Epoch 1737, Loss: 0.6024670898914337, Final Batch Loss: 0.28348731994628906
Epoch 1738, Loss: 0.5739938020706177, Final Batch Loss: 0.2778196334838867
Epoch 1739, Loss: 0.5675080716609955, Final Batch Loss: 0.27501145005226135
Epoch 1740, Loss: 0.5538050830364227, Final Batch Loss: 0.2576783001422882
Epoch 1741, Loss: 0.5803565382957458, Final Batch Loss: 0.29436060786247253
Epoch 1742, Loss: 0.5862798690795898, Final Batch Loss: 0.27137795090675354
Epoch 1743, Loss: 0.

Epoch 1855, Loss: 0.5593834221363068, Final Batch Loss: 0.28195059299468994
Epoch 1856, Loss: 0.5785250067710876, Final Batch Loss: 0.27623993158340454
Epoch 1857, Loss: 0.5938472151756287, Final Batch Loss: 0.3008357584476471
Epoch 1858, Loss: 0.5711258947849274, Final Batch Loss: 0.3099996745586395
Epoch 1859, Loss: 0.5841314196586609, Final Batch Loss: 0.32628583908081055
Epoch 1860, Loss: 0.524741142988205, Final Batch Loss: 0.2525193989276886
Epoch 1861, Loss: 0.5829418003559113, Final Batch Loss: 0.3229890763759613
Epoch 1862, Loss: 0.55030956864357, Final Batch Loss: 0.24480387568473816
Epoch 1863, Loss: 0.5255547165870667, Final Batch Loss: 0.2500917613506317
Epoch 1864, Loss: 0.576495349407196, Final Batch Loss: 0.3186669945716858
Epoch 1865, Loss: 0.5501312017440796, Final Batch Loss: 0.2827024459838867
Epoch 1866, Loss: 0.5449056029319763, Final Batch Loss: 0.290546715259552
Epoch 1867, Loss: 0.5459988713264465, Final Batch Loss: 0.25183287262916565
Epoch 1868, Loss: 0.58796

Epoch 1983, Loss: 0.6223128437995911, Final Batch Loss: 0.31826600432395935
Epoch 1984, Loss: 0.5717242062091827, Final Batch Loss: 0.23556554317474365
Epoch 1985, Loss: 0.5519953072071075, Final Batch Loss: 0.30856451392173767
Epoch 1986, Loss: 0.579115629196167, Final Batch Loss: 0.302033394575119
Epoch 1987, Loss: 0.5599138140678406, Final Batch Loss: 0.2574498951435089
Epoch 1988, Loss: 0.5694517195224762, Final Batch Loss: 0.307646781206131
Epoch 1989, Loss: 0.5533845126628876, Final Batch Loss: 0.25553473830223083
Epoch 1990, Loss: 0.5297215133905411, Final Batch Loss: 0.23672674596309662
Epoch 1991, Loss: 0.5619896948337555, Final Batch Loss: 0.284932941198349
Epoch 1992, Loss: 0.5086250007152557, Final Batch Loss: 0.20379683375358582
Epoch 1993, Loss: 0.5722776353359222, Final Batch Loss: 0.2907322347164154
Epoch 1994, Loss: 0.5573713779449463, Final Batch Loss: 0.27929747104644775
Epoch 1995, Loss: 0.6389966309070587, Final Batch Loss: 0.34591957926750183
Epoch 1996, Loss: 0.5

Epoch 2105, Loss: 0.5549182891845703, Final Batch Loss: 0.27007606625556946
Epoch 2106, Loss: 0.547751784324646, Final Batch Loss: 0.3039959669113159
Epoch 2107, Loss: 0.5423287600278854, Final Batch Loss: 0.24152089655399323
Epoch 2108, Loss: 0.5788542628288269, Final Batch Loss: 0.33348187804222107
Epoch 2109, Loss: 0.5587893426418304, Final Batch Loss: 0.2814916968345642
Epoch 2110, Loss: 0.5204913020133972, Final Batch Loss: 0.24745908379554749
Epoch 2111, Loss: 0.5695949196815491, Final Batch Loss: 0.2990018129348755
Epoch 2112, Loss: 0.5914301574230194, Final Batch Loss: 0.2679036855697632
Epoch 2113, Loss: 0.5476921051740646, Final Batch Loss: 0.3086026906967163
Epoch 2114, Loss: 0.6427418291568756, Final Batch Loss: 0.28691715002059937
Epoch 2115, Loss: 0.548381507396698, Final Batch Loss: 0.2827129364013672
Epoch 2116, Loss: 0.5444745421409607, Final Batch Loss: 0.25781163573265076
Epoch 2117, Loss: 0.5857146680355072, Final Batch Loss: 0.2530786097049713
Epoch 2118, Loss: 0.5

Epoch 2227, Loss: 0.5496582537889481, Final Batch Loss: 0.30587804317474365
Epoch 2228, Loss: 0.5225252360105515, Final Batch Loss: 0.22960178554058075
Epoch 2229, Loss: 0.5492673218250275, Final Batch Loss: 0.2898198366165161
Epoch 2230, Loss: 0.48781082034111023, Final Batch Loss: 0.2096288502216339
Epoch 2231, Loss: 0.5464075207710266, Final Batch Loss: 0.27158206701278687
Epoch 2232, Loss: 0.5562611073255539, Final Batch Loss: 0.23175479471683502
Epoch 2233, Loss: 0.584447592496872, Final Batch Loss: 0.2921495735645294
Epoch 2234, Loss: 0.6008591949939728, Final Batch Loss: 0.33082401752471924
Epoch 2235, Loss: 0.5564267039299011, Final Batch Loss: 0.2949632704257965
Epoch 2236, Loss: 0.5352008640766144, Final Batch Loss: 0.2665865421295166
Epoch 2237, Loss: 0.5583010911941528, Final Batch Loss: 0.28693896532058716
Epoch 2238, Loss: 0.4960643947124481, Final Batch Loss: 0.21809741854667664
Epoch 2239, Loss: 0.5379095673561096, Final Batch Loss: 0.2857295572757721
Epoch 2240, Loss: 

Epoch 2355, Loss: 0.542633980512619, Final Batch Loss: 0.2810805141925812
Epoch 2356, Loss: 0.5291769504547119, Final Batch Loss: 0.24144530296325684
Epoch 2357, Loss: 0.5482105612754822, Final Batch Loss: 0.24532189965248108
Epoch 2358, Loss: 0.5547191500663757, Final Batch Loss: 0.2964995503425598
Epoch 2359, Loss: 0.5302388370037079, Final Batch Loss: 0.269479900598526
Epoch 2360, Loss: 0.6286898553371429, Final Batch Loss: 0.40000778436660767
Epoch 2361, Loss: 0.573045015335083, Final Batch Loss: 0.26030564308166504
Epoch 2362, Loss: 0.5179869532585144, Final Batch Loss: 0.2691055238246918
Epoch 2363, Loss: 0.5087407231330872, Final Batch Loss: 0.21341589093208313
Epoch 2364, Loss: 0.556306779384613, Final Batch Loss: 0.3054441213607788
Epoch 2365, Loss: 0.5216449797153473, Final Batch Loss: 0.24671819806098938
Epoch 2366, Loss: 0.5600070357322693, Final Batch Loss: 0.2895645797252655
Epoch 2367, Loss: 0.5594681948423386, Final Batch Loss: 0.3196122348308563
Epoch 2368, Loss: 0.524

Epoch 2472, Loss: 0.5653980225324631, Final Batch Loss: 0.3505537509918213
Epoch 2473, Loss: 0.5437068045139313, Final Batch Loss: 0.26043519377708435
Epoch 2474, Loss: 0.5513234734535217, Final Batch Loss: 0.30407094955444336
Epoch 2475, Loss: 0.5548265278339386, Final Batch Loss: 0.2899363040924072
Epoch 2476, Loss: 0.5583748817443848, Final Batch Loss: 0.2668590247631073
Epoch 2477, Loss: 0.5304127633571625, Final Batch Loss: 0.2680489122867584
Epoch 2478, Loss: 0.5724478960037231, Final Batch Loss: 0.3191353380680084
Epoch 2479, Loss: 0.6091930568218231, Final Batch Loss: 0.3187822103500366
Epoch 2480, Loss: 0.5281606614589691, Final Batch Loss: 0.26251909136772156
Epoch 2481, Loss: 0.5572423934936523, Final Batch Loss: 0.2931540012359619
Epoch 2482, Loss: 0.543410062789917, Final Batch Loss: 0.27454236149787903
Epoch 2483, Loss: 0.5539261996746063, Final Batch Loss: 0.2590370178222656
Epoch 2484, Loss: 0.543411135673523, Final Batch Loss: 0.2988300621509552
Epoch 2485, Loss: 0.529

Epoch 2594, Loss: 0.551766037940979, Final Batch Loss: 0.2593284249305725
Epoch 2595, Loss: 0.5380735397338867, Final Batch Loss: 0.2739587426185608
Epoch 2596, Loss: 0.49694670736789703, Final Batch Loss: 0.2726362645626068
Epoch 2597, Loss: 0.5221980512142181, Final Batch Loss: 0.25330373644828796
Epoch 2598, Loss: 0.582032710313797, Final Batch Loss: 0.34425994753837585
Epoch 2599, Loss: 0.5377397835254669, Final Batch Loss: 0.264737069606781
Epoch 2600, Loss: 0.5162771046161652, Final Batch Loss: 0.25684717297554016
Epoch 2601, Loss: 0.5693722069263458, Final Batch Loss: 0.32414546608924866
Epoch 2602, Loss: 0.6003498435020447, Final Batch Loss: 0.33685699105262756
Epoch 2603, Loss: 0.5737380385398865, Final Batch Loss: 0.31812262535095215
Epoch 2604, Loss: 0.5663098394870758, Final Batch Loss: 0.3082168400287628
Epoch 2605, Loss: 0.5222759246826172, Final Batch Loss: 0.2545442283153534
Epoch 2606, Loss: 0.5262747406959534, Final Batch Loss: 0.2649245858192444
Epoch 2607, Loss: 0.5

Epoch 2706, Loss: 0.5448936522006989, Final Batch Loss: 0.2143380343914032
Epoch 2707, Loss: 0.5426910817623138, Final Batch Loss: 0.2779368460178375
Epoch 2708, Loss: 0.5281067788600922, Final Batch Loss: 0.2578635811805725
Epoch 2709, Loss: 0.562650054693222, Final Batch Loss: 0.3302938938140869
Epoch 2710, Loss: 0.4820479452610016, Final Batch Loss: 0.23893100023269653
Epoch 2711, Loss: 0.5020334720611572, Final Batch Loss: 0.2643378973007202
Epoch 2712, Loss: 0.49363210797309875, Final Batch Loss: 0.2278718650341034
Epoch 2713, Loss: 0.5479637980461121, Final Batch Loss: 0.3143254518508911
Epoch 2714, Loss: 0.5606943964958191, Final Batch Loss: 0.295817106962204
Epoch 2715, Loss: 0.5798607766628265, Final Batch Loss: 0.3166274130344391
Epoch 2716, Loss: 0.4982350319623947, Final Batch Loss: 0.21315397322177887
Epoch 2717, Loss: 0.5671564042568207, Final Batch Loss: 0.3096086382865906
Epoch 2718, Loss: 0.515727311372757, Final Batch Loss: 0.2432767152786255
Epoch 2719, Loss: 0.56777

Epoch 2822, Loss: 0.5173740386962891, Final Batch Loss: 0.2514370381832123
Epoch 2823, Loss: 0.49238406121730804, Final Batch Loss: 0.2484915554523468
Epoch 2824, Loss: 0.5131877958774567, Final Batch Loss: 0.2526693046092987
Epoch 2825, Loss: 0.49908019602298737, Final Batch Loss: 0.20848165452480316
Epoch 2826, Loss: 0.5521559119224548, Final Batch Loss: 0.3127630054950714
Epoch 2827, Loss: 0.5184736400842667, Final Batch Loss: 0.2480669468641281
Epoch 2828, Loss: 0.5408186912536621, Final Batch Loss: 0.2737289071083069
Epoch 2829, Loss: 0.5041858851909637, Final Batch Loss: 0.27246278524398804
Epoch 2830, Loss: 0.5391403883695602, Final Batch Loss: 0.333312064409256
Epoch 2831, Loss: 0.5368827730417252, Final Batch Loss: 0.28809940814971924
Epoch 2832, Loss: 0.5320113599300385, Final Batch Loss: 0.2569708228111267
Epoch 2833, Loss: 0.5126164555549622, Final Batch Loss: 0.2612832486629486
Epoch 2834, Loss: 0.5153068006038666, Final Batch Loss: 0.2872726023197174
Epoch 2835, Loss: 0.5

Epoch 2947, Loss: 0.5116845816373825, Final Batch Loss: 0.2690621316432953
Epoch 2948, Loss: 0.48537391424179077, Final Batch Loss: 0.22200796008110046
Epoch 2949, Loss: 0.49008049070835114, Final Batch Loss: 0.217363640666008
Epoch 2950, Loss: 0.5413659512996674, Final Batch Loss: 0.28933829069137573
Epoch 2951, Loss: 0.5073462128639221, Final Batch Loss: 0.23638704419136047
Epoch 2952, Loss: 0.490152508020401, Final Batch Loss: 0.2620851993560791
Epoch 2953, Loss: 0.48701027035713196, Final Batch Loss: 0.2635754644870758
Epoch 2954, Loss: 0.504748061299324, Final Batch Loss: 0.24094928801059723
Epoch 2955, Loss: 0.4993771016597748, Final Batch Loss: 0.21512192487716675
Epoch 2956, Loss: 0.5170360803604126, Final Batch Loss: 0.26956906914711
Epoch 2957, Loss: 0.5352354049682617, Final Batch Loss: 0.25178709626197815
Epoch 2958, Loss: 0.5100596100091934, Final Batch Loss: 0.23853491246700287
Epoch 2959, Loss: 0.5532160997390747, Final Batch Loss: 0.28095173835754395
Epoch 2960, Loss: 0

Epoch 3076, Loss: 0.5111462771892548, Final Batch Loss: 0.23959341645240784
Epoch 3077, Loss: 0.5195751935243607, Final Batch Loss: 0.27076220512390137
Epoch 3078, Loss: 0.5346251130104065, Final Batch Loss: 0.26508527994155884
Epoch 3079, Loss: 0.4921409636735916, Final Batch Loss: 0.2746562957763672
Epoch 3080, Loss: 0.46765607595443726, Final Batch Loss: 0.19980087876319885
Epoch 3081, Loss: 0.4817612022161484, Final Batch Loss: 0.2623738944530487
Epoch 3082, Loss: 0.4677038639783859, Final Batch Loss: 0.21982073783874512
Epoch 3083, Loss: 0.48075735569000244, Final Batch Loss: 0.22871094942092896
Epoch 3084, Loss: 0.48060280084609985, Final Batch Loss: 0.24162860214710236
Epoch 3085, Loss: 0.5473520010709763, Final Batch Loss: 0.31623387336730957
Epoch 3086, Loss: 0.46977710723876953, Final Batch Loss: 0.2084023356437683
Epoch 3087, Loss: 0.5043725371360779, Final Batch Loss: 0.23593851923942566
Epoch 3088, Loss: 0.5139530599117279, Final Batch Loss: 0.2731752097606659
Epoch 3089, 

Epoch 3187, Loss: 0.5268070697784424, Final Batch Loss: 0.2666202187538147
Epoch 3188, Loss: 0.46052883565425873, Final Batch Loss: 0.24894221127033234
Epoch 3189, Loss: 0.49111491441726685, Final Batch Loss: 0.2477698177099228
Epoch 3190, Loss: 0.488884761929512, Final Batch Loss: 0.24491219222545624
Epoch 3191, Loss: 0.5405632853507996, Final Batch Loss: 0.3408639132976532
Epoch 3192, Loss: 0.48314929008483887, Final Batch Loss: 0.25844451785087585
Epoch 3193, Loss: 0.4677671045064926, Final Batch Loss: 0.2553272247314453
Epoch 3194, Loss: 0.48255808651447296, Final Batch Loss: 0.20932398736476898
Epoch 3195, Loss: 0.5021511018276215, Final Batch Loss: 0.2838052213191986
Epoch 3196, Loss: 0.4537498652935028, Final Batch Loss: 0.22858862578868866
Epoch 3197, Loss: 0.43770577013492584, Final Batch Loss: 0.2049049735069275
Epoch 3198, Loss: 0.4670752286911011, Final Batch Loss: 0.23722685873508453
Epoch 3199, Loss: 0.4751638174057007, Final Batch Loss: 0.2021382749080658
Epoch 3200, Los

Epoch 3301, Loss: 0.3983009457588196, Final Batch Loss: 0.19742423295974731
Epoch 3302, Loss: 0.41970326006412506, Final Batch Loss: 0.18158474564552307
Epoch 3303, Loss: 0.47926919162273407, Final Batch Loss: 0.2541133463382721
Epoch 3304, Loss: 0.4213765114545822, Final Batch Loss: 0.2039583921432495
Epoch 3305, Loss: 0.4106338322162628, Final Batch Loss: 0.16174007952213287
Epoch 3306, Loss: 0.43238380551338196, Final Batch Loss: 0.21018129587173462
Epoch 3307, Loss: 0.4171200841665268, Final Batch Loss: 0.17127010226249695
Epoch 3308, Loss: 0.4694162756204605, Final Batch Loss: 0.2464452087879181
Epoch 3309, Loss: 0.42866507172584534, Final Batch Loss: 0.23772433400154114
Epoch 3310, Loss: 0.3722241073846817, Final Batch Loss: 0.1786646991968155
Epoch 3311, Loss: 0.449867308139801, Final Batch Loss: 0.23745349049568176
Epoch 3312, Loss: 0.44952113926410675, Final Batch Loss: 0.26866644620895386
Epoch 3313, Loss: 0.44462767243385315, Final Batch Loss: 0.252439022064209
Epoch 3314, L

Epoch 3423, Loss: 0.3852575123310089, Final Batch Loss: 0.18197090923786163
Epoch 3424, Loss: 0.4064635783433914, Final Batch Loss: 0.21466873586177826
Epoch 3425, Loss: 0.3678978830575943, Final Batch Loss: 0.2103307843208313
Epoch 3426, Loss: 0.3802524507045746, Final Batch Loss: 0.18714125454425812
Epoch 3427, Loss: 0.3818894773721695, Final Batch Loss: 0.18808838725090027
Epoch 3428, Loss: 0.45235849916934967, Final Batch Loss: 0.2509556710720062
Epoch 3429, Loss: 0.44480061531066895, Final Batch Loss: 0.22636346518993378
Epoch 3430, Loss: 0.38333937525749207, Final Batch Loss: 0.2146369218826294
Epoch 3431, Loss: 0.43075020611286163, Final Batch Loss: 0.21422062814235687
Epoch 3432, Loss: 0.426318421959877, Final Batch Loss: 0.21058203279972076
Epoch 3433, Loss: 0.36666345596313477, Final Batch Loss: 0.1554660052061081
Epoch 3434, Loss: 0.44406160712242126, Final Batch Loss: 0.2436983734369278
Epoch 3435, Loss: 0.40118078887462616, Final Batch Loss: 0.2273586094379425
Epoch 3436, 

Epoch 3543, Loss: 0.4232787936925888, Final Batch Loss: 0.22388826310634613
Epoch 3544, Loss: 0.3946709930896759, Final Batch Loss: 0.2026059329509735
Epoch 3545, Loss: 0.4107537418603897, Final Batch Loss: 0.22199293971061707
Epoch 3546, Loss: 0.3990206718444824, Final Batch Loss: 0.22301538288593292
Epoch 3547, Loss: 0.4188574552536011, Final Batch Loss: 0.22619085013866425
Epoch 3548, Loss: 0.46596159040927887, Final Batch Loss: 0.27154111862182617
Epoch 3549, Loss: 0.4756678640842438, Final Batch Loss: 0.29407739639282227
Epoch 3550, Loss: 0.4367543160915375, Final Batch Loss: 0.20448586344718933
Epoch 3551, Loss: 0.35876281559467316, Final Batch Loss: 0.13466887176036835
Epoch 3552, Loss: 0.4362339675426483, Final Batch Loss: 0.22509250044822693
Epoch 3553, Loss: 0.3844630569219589, Final Batch Loss: 0.21237453818321228
Epoch 3554, Loss: 0.3384060710668564, Final Batch Loss: 0.18281462788581848
Epoch 3555, Loss: 0.3741077035665512, Final Batch Loss: 0.1877761334180832
Epoch 3556, 

Epoch 3661, Loss: 0.4347022622823715, Final Batch Loss: 0.2487190067768097
Epoch 3662, Loss: 0.3451423645019531, Final Batch Loss: 0.1519845575094223
Epoch 3663, Loss: 0.34711819887161255, Final Batch Loss: 0.17520178854465485
Epoch 3664, Loss: 0.33022768795490265, Final Batch Loss: 0.1512102633714676
Epoch 3665, Loss: 0.3761025220155716, Final Batch Loss: 0.179692804813385
Epoch 3666, Loss: 0.3876389265060425, Final Batch Loss: 0.17333872616291046
Epoch 3667, Loss: 0.31859734654426575, Final Batch Loss: 0.1471511274576187
Epoch 3668, Loss: 0.33547188341617584, Final Batch Loss: 0.1554838865995407
Epoch 3669, Loss: 0.37753449380397797, Final Batch Loss: 0.16687098145484924
Epoch 3670, Loss: 0.3815714716911316, Final Batch Loss: 0.17076578736305237
Epoch 3671, Loss: 0.4036497473716736, Final Batch Loss: 0.2029608190059662
Epoch 3672, Loss: 0.34064243733882904, Final Batch Loss: 0.14262525737285614
Epoch 3673, Loss: 0.36072225868701935, Final Batch Loss: 0.1804637461900711
Epoch 3674, Lo

Epoch 3780, Loss: 0.4272971600294113, Final Batch Loss: 0.20952102541923523
Epoch 3781, Loss: 0.3075626343488693, Final Batch Loss: 0.14058881998062134
Epoch 3782, Loss: 0.4189802557229996, Final Batch Loss: 0.27106645703315735
Epoch 3783, Loss: 0.3804869055747986, Final Batch Loss: 0.19102585315704346
Epoch 3784, Loss: 0.36788786947727203, Final Batch Loss: 0.1973772943019867
Epoch 3785, Loss: 0.3581400513648987, Final Batch Loss: 0.14101511240005493
Epoch 3786, Loss: 0.37291909754276276, Final Batch Loss: 0.16810736060142517
Epoch 3787, Loss: 0.3710966408252716, Final Batch Loss: 0.19749818742275238
Epoch 3788, Loss: 0.3753695487976074, Final Batch Loss: 0.17843623459339142
Epoch 3789, Loss: 0.45739905536174774, Final Batch Loss: 0.27445435523986816
Epoch 3790, Loss: 0.41094622015953064, Final Batch Loss: 0.2244853377342224
Epoch 3791, Loss: 0.3460724502801895, Final Batch Loss: 0.18644604086875916
Epoch 3792, Loss: 0.474569633603096, Final Batch Loss: 0.19177834689617157
Epoch 3793,

Epoch 3894, Loss: 0.34914420545101166, Final Batch Loss: 0.1651422530412674
Epoch 3895, Loss: 0.3335704058408737, Final Batch Loss: 0.15652313828468323
Epoch 3896, Loss: 0.3175508975982666, Final Batch Loss: 0.1642780750989914
Epoch 3897, Loss: 0.4003441333770752, Final Batch Loss: 0.19065171480178833
Epoch 3898, Loss: 0.3495389223098755, Final Batch Loss: 0.15970192849636078
Epoch 3899, Loss: 0.32121793925762177, Final Batch Loss: 0.13498573005199432
Epoch 3900, Loss: 0.34252171218395233, Final Batch Loss: 0.13771094381809235
Epoch 3901, Loss: 0.27753402292728424, Final Batch Loss: 0.10933013260364532
Epoch 3902, Loss: 0.3784521520137787, Final Batch Loss: 0.2041836678981781
Epoch 3903, Loss: 0.3026805967092514, Final Batch Loss: 0.1398794800043106
Epoch 3904, Loss: 0.3468773365020752, Final Batch Loss: 0.1673293262720108
Epoch 3905, Loss: 0.41475580632686615, Final Batch Loss: 0.24174124002456665
Epoch 3906, Loss: 0.3283616155385971, Final Batch Loss: 0.1506107747554779
Epoch 3907, L

Epoch 4015, Loss: 0.33036066591739655, Final Batch Loss: 0.15951292216777802
Epoch 4016, Loss: 0.36372236907482147, Final Batch Loss: 0.20165829360485077
Epoch 4017, Loss: 0.29858266562223434, Final Batch Loss: 0.10130039602518082
Epoch 4018, Loss: 0.369639128446579, Final Batch Loss: 0.19957926869392395
Epoch 4019, Loss: 0.29039278626441956, Final Batch Loss: 0.16130533814430237
Epoch 4020, Loss: 0.3864048272371292, Final Batch Loss: 0.23250463604927063
Epoch 4021, Loss: 0.34913013875484467, Final Batch Loss: 0.138606458902359
Epoch 4022, Loss: 0.33354587852954865, Final Batch Loss: 0.18771933019161224
Epoch 4023, Loss: 0.3230518251657486, Final Batch Loss: 0.16734175384044647
Epoch 4024, Loss: 0.27364741265773773, Final Batch Loss: 0.12769222259521484
Epoch 4025, Loss: 0.3622729927301407, Final Batch Loss: 0.15305060148239136
Epoch 4026, Loss: 0.33331185579299927, Final Batch Loss: 0.1439247876405716
Epoch 4027, Loss: 0.39064665138721466, Final Batch Loss: 0.18880192935466766
Epoch 4

Epoch 4132, Loss: 0.3416213244199753, Final Batch Loss: 0.17689478397369385
Epoch 4133, Loss: 0.3116706311702728, Final Batch Loss: 0.12459591031074524
Epoch 4134, Loss: 0.3270748406648636, Final Batch Loss: 0.16844947636127472
Epoch 4135, Loss: 0.2563403695821762, Final Batch Loss: 0.11863945424556732
Epoch 4136, Loss: 0.2962174490094185, Final Batch Loss: 0.08837974816560745
Epoch 4137, Loss: 0.33885030448436737, Final Batch Loss: 0.17845134437084198
Epoch 4138, Loss: 0.3005746901035309, Final Batch Loss: 0.1433028280735016
Epoch 4139, Loss: 0.32779285311698914, Final Batch Loss: 0.13134820759296417
Epoch 4140, Loss: 0.3464154899120331, Final Batch Loss: 0.20474115014076233
Epoch 4141, Loss: 0.3855605125427246, Final Batch Loss: 0.19973944127559662
Epoch 4142, Loss: 0.3168274462223053, Final Batch Loss: 0.1444244384765625
Epoch 4143, Loss: 0.3118688762187958, Final Batch Loss: 0.13850532472133636
Epoch 4144, Loss: 0.39941973984241486, Final Batch Loss: 0.265970379114151
Epoch 4145, L

Epoch 4253, Loss: 0.32253575325012207, Final Batch Loss: 0.1421298235654831
Epoch 4254, Loss: 0.29707978665828705, Final Batch Loss: 0.13609008491039276
Epoch 4255, Loss: 0.36633481085300446, Final Batch Loss: 0.1543952375650406
Epoch 4256, Loss: 0.3988683968782425, Final Batch Loss: 0.20087987184524536
Epoch 4257, Loss: 0.32171186804771423, Final Batch Loss: 0.196061909198761
Epoch 4258, Loss: 0.412929892539978, Final Batch Loss: 0.18730704486370087
Epoch 4259, Loss: 0.3190901130437851, Final Batch Loss: 0.1626449078321457
Epoch 4260, Loss: 0.33041320741176605, Final Batch Loss: 0.15395143628120422
Epoch 4261, Loss: 0.2754710391163826, Final Batch Loss: 0.11291082948446274
Epoch 4262, Loss: 0.3822057694196701, Final Batch Loss: 0.2293403446674347
Epoch 4263, Loss: 0.3152769133448601, Final Batch Loss: 0.11914006620645523
Epoch 4264, Loss: 0.3274244964122772, Final Batch Loss: 0.15431976318359375
Epoch 4265, Loss: 0.3443792462348938, Final Batch Loss: 0.21593131124973297
Epoch 4266, Lo

Epoch 4381, Loss: 0.2744033485651016, Final Batch Loss: 0.12148435413837433
Epoch 4382, Loss: 0.30152076482772827, Final Batch Loss: 0.15987588465213776
Epoch 4383, Loss: 0.3613458424806595, Final Batch Loss: 0.19838951528072357
Epoch 4384, Loss: 0.33103199303150177, Final Batch Loss: 0.1605791598558426
Epoch 4385, Loss: 0.29959045350551605, Final Batch Loss: 0.1651233434677124
Epoch 4386, Loss: 0.3150322437286377, Final Batch Loss: 0.17057514190673828
Epoch 4387, Loss: 0.32835377752780914, Final Batch Loss: 0.19708716869354248
Epoch 4388, Loss: 0.3703094869852066, Final Batch Loss: 0.14672864973545074
Epoch 4389, Loss: 0.3114754855632782, Final Batch Loss: 0.1553472876548767
Epoch 4390, Loss: 0.29781512916088104, Final Batch Loss: 0.16139577329158783
Epoch 4391, Loss: 0.3997225761413574, Final Batch Loss: 0.2424367070198059
Epoch 4392, Loss: 0.28480857610702515, Final Batch Loss: 0.13943110406398773
Epoch 4393, Loss: 0.3304625302553177, Final Batch Loss: 0.20384544134140015
Epoch 4394

Epoch 4508, Loss: 0.2827308624982834, Final Batch Loss: 0.11968103051185608
Epoch 4509, Loss: 0.32745160162448883, Final Batch Loss: 0.1683339923620224
Epoch 4510, Loss: 0.2851405292749405, Final Batch Loss: 0.15529565513134003
Epoch 4511, Loss: 0.2862449884414673, Final Batch Loss: 0.15253616869449615
Epoch 4512, Loss: 0.3190660774707794, Final Batch Loss: 0.15327848494052887
Epoch 4513, Loss: 0.253009170293808, Final Batch Loss: 0.10902726650238037
Epoch 4514, Loss: 0.25849296152591705, Final Batch Loss: 0.09745422005653381
Epoch 4515, Loss: 0.2778814509510994, Final Batch Loss: 0.11486542969942093
Epoch 4516, Loss: 0.2830222398042679, Final Batch Loss: 0.12991821765899658
Epoch 4517, Loss: 0.31190650165081024, Final Batch Loss: 0.14671632647514343
Epoch 4518, Loss: 0.31375719606876373, Final Batch Loss: 0.161209836602211
Epoch 4519, Loss: 0.2589115649461746, Final Batch Loss: 0.12682530283927917
Epoch 4520, Loss: 0.3650791794061661, Final Batch Loss: 0.23541750013828278
Epoch 4521, 

Epoch 4628, Loss: 0.2794994115829468, Final Batch Loss: 0.13618822395801544
Epoch 4629, Loss: 0.2572117894887924, Final Batch Loss: 0.12174546718597412
Epoch 4630, Loss: 0.27354899048805237, Final Batch Loss: 0.13367369771003723
Epoch 4631, Loss: 0.2942562773823738, Final Batch Loss: 0.09936103969812393
Epoch 4632, Loss: 0.27601318061351776, Final Batch Loss: 0.14363504946231842
Epoch 4633, Loss: 0.269070141017437, Final Batch Loss: 0.14906112849712372
Epoch 4634, Loss: 0.26276180893182755, Final Batch Loss: 0.14243581891059875
Epoch 4635, Loss: 0.3446711525321007, Final Batch Loss: 0.22491636872291565
Epoch 4636, Loss: 0.260465145111084, Final Batch Loss: 0.11023594439029694
Epoch 4637, Loss: 0.25081755220890045, Final Batch Loss: 0.1330433338880539
Epoch 4638, Loss: 0.29255741834640503, Final Batch Loss: 0.16908258199691772
Epoch 4639, Loss: 0.29705360531806946, Final Batch Loss: 0.1680937111377716
Epoch 4640, Loss: 0.237098827958107, Final Batch Loss: 0.1367906928062439
Epoch 4641, 

Epoch 4752, Loss: 0.23391831666231155, Final Batch Loss: 0.10725107043981552
Epoch 4753, Loss: 0.2413797527551651, Final Batch Loss: 0.06834663450717926
Epoch 4754, Loss: 0.24910999834537506, Final Batch Loss: 0.12400482594966888
Epoch 4755, Loss: 0.24998673051595688, Final Batch Loss: 0.13530948758125305
Epoch 4756, Loss: 0.2742750197649002, Final Batch Loss: 0.1396322399377823
Epoch 4757, Loss: 0.2880241423845291, Final Batch Loss: 0.1346760094165802
Epoch 4758, Loss: 0.2760499566793442, Final Batch Loss: 0.1686081886291504
Epoch 4759, Loss: 0.2778678983449936, Final Batch Loss: 0.1319492608308792
Epoch 4760, Loss: 0.2600501477718353, Final Batch Loss: 0.10302591323852539
Epoch 4761, Loss: 0.28955867886543274, Final Batch Loss: 0.16494335234165192
Epoch 4762, Loss: 0.23326408118009567, Final Batch Loss: 0.12123018503189087
Epoch 4763, Loss: 0.23719732463359833, Final Batch Loss: 0.11204126477241516
Epoch 4764, Loss: 0.24299712479114532, Final Batch Loss: 0.13099108636379242
Epoch 476

Epoch 4875, Loss: 0.2379748523235321, Final Batch Loss: 0.08487054705619812
Epoch 4876, Loss: 0.21940472722053528, Final Batch Loss: 0.07686467468738556
Epoch 4877, Loss: 0.2784995883703232, Final Batch Loss: 0.1452629417181015
Epoch 4878, Loss: 0.23596389591693878, Final Batch Loss: 0.12260337918996811
Epoch 4879, Loss: 0.26924092322587967, Final Batch Loss: 0.14860346913337708
Epoch 4880, Loss: 0.28359922021627426, Final Batch Loss: 0.18739593029022217
Epoch 4881, Loss: 0.20189018547534943, Final Batch Loss: 0.09767189621925354
Epoch 4882, Loss: 0.2128836140036583, Final Batch Loss: 0.07322227209806442
Epoch 4883, Loss: 0.23301928490400314, Final Batch Loss: 0.10111527889966965
Epoch 4884, Loss: 0.21720115840435028, Final Batch Loss: 0.08708122372627258
Epoch 4885, Loss: 0.2452443689107895, Final Batch Loss: 0.08419455587863922
Epoch 4886, Loss: 0.1967778503894806, Final Batch Loss: 0.08174130320549011
Epoch 4887, Loss: 0.2409558668732643, Final Batch Loss: 0.12070439755916595
Epoch 

Epoch 4982, Loss: 0.19325220584869385, Final Batch Loss: 0.09454800188541412
Epoch 4983, Loss: 0.17383059859275818, Final Batch Loss: 0.0881182923913002
Epoch 4984, Loss: 0.2427009865641594, Final Batch Loss: 0.10072367638349533
Epoch 4985, Loss: 0.2325357049703598, Final Batch Loss: 0.13621850311756134
Epoch 4986, Loss: 0.2838699221611023, Final Batch Loss: 0.15411975979804993
Epoch 4987, Loss: 0.2473076656460762, Final Batch Loss: 0.12275644391775131
Epoch 4988, Loss: 0.2797350138425827, Final Batch Loss: 0.1437150090932846
Epoch 4989, Loss: 0.20456843823194504, Final Batch Loss: 0.10762491077184677
Epoch 4990, Loss: 0.21720967441797256, Final Batch Loss: 0.07143130153417587
Epoch 4991, Loss: 0.26669611781835556, Final Batch Loss: 0.11088188737630844
Epoch 4992, Loss: 0.25098979473114014, Final Batch Loss: 0.10707665979862213
Epoch 4993, Loss: 0.2279892861843109, Final Batch Loss: 0.14592181146144867
Epoch 4994, Loss: 0.26798000931739807, Final Batch Loss: 0.12589074671268463
Epoch 4

In [8]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[14  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  1]
 [ 0  0  0  7  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0]
 [ 0  0  1  0  0 11  0  0  1]
 [ 0  0  0  0  0  0 12  0  0]
 [ 0  0  0  0  0  0  0  9  0]
 [ 0  0  1  0  0  0  0  0 14]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        14
           1    1.00000   1.00000   1.00000         9
           2    0.84615   0.91667   0.88000        12
           3    1.00000   1.00000   1.00000         7
           4    1.00000   1.00000   1.00000         6
           5    1.00000   0.84615   0.91667        13
           6    1.00000   1.00000   1.00000        12
           7    1.00000   1.00000   1.00000         9
           8    0.87500   0.93333   0.90323        15

    accuracy                        0.95876        97
   macro avg    0.96902   0.96624   0.96665        97
weighted avg    0.96164   0.95876   0.95902        97



In [24]:
n_samples = 20

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A0 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_1 = gen(latent_vectors).detach().numpy()

y_1 = np.zeros(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A1 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_2 = gen(latent_vectors).detach().numpy()

y_2 = np.ones(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A2 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_3 = gen(latent_vectors).detach().numpy()

y_3 = np.ones(n_samples) + 1

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A0 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_4 = gen(latent_vectors).detach().numpy()

y_4 = np.ones(n_samples) + 2

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A1 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_5 = gen(latent_vectors).detach().numpy()

y_5 = np.ones(n_samples) + 3

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A2 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_6 = gen(latent_vectors).detach().numpy()

y_6 = np.ones(n_samples) + 4

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A0 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_7 = gen(latent_vectors).detach().numpy()

y_7 = np.ones(n_samples) + 5

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A1 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_8 = gen(latent_vectors).detach().numpy()

y_8 = np.ones(n_samples) + 6

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A2 Solo GAN Group 3_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_9 = gen(latent_vectors).detach().numpy()

y_9 = np.ones(n_samples) + 7

fake_features = np.concatenate((fake_features_1, fake_features_2, fake_features_3, fake_features_4, fake_features_5, fake_features_6,
                         fake_features_7, fake_features_8, fake_features_9))
fake_labels = np.concatenate((y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9))

fake_features = torch.Tensor(fake_features)

In [25]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[20  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  3  0  0  5]
 [ 0  0  0 19  1  0  0  0  0]
 [ 0  0  0  0 17  0  0  3  0]
 [ 0  0  4  0  0 15  0  0  1]
 [ 0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0 20  0]
 [ 0  0  2  0  0  3  0  0 15]]
              precision    recall  f1-score   support

         0.0    1.00000   1.00000   1.00000        20
         1.0    1.00000   1.00000   1.00000        20
         2.0    0.66667   0.60000   0.63158        20
         3.0    1.00000   0.95000   0.97436        20
         4.0    0.94444   0.85000   0.89474        20
         5.0    0.71429   0.75000   0.73171        20
         6.0    1.00000   1.00000   1.00000        20
         7.0    0.86957   1.00000   0.93023        20
         8.0    0.71429   0.75000   0.73171        20

    accuracy                        0.87778       180
   macro avg    0.87881   0.87778   0.87715       180
weighted avg    0.87881   0.87778   0.87715       180

