In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '58 tGravityAcc-energy()-Y',
 '59 tGravityAcc-energy()-Z',
 '128 tBodyGyro-mad()-Y',
 '141 tBodyGyro-iqr()-Y',
 '428 fBodyGyro-std()-Y',
 '434 fBodyGyro-max()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '203 tBodyAccMag-mad()',
 '215 tGravityAccMag-std()',
 '216 tGravityAccMag-mad()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '382 fBodyAccJerk-bandsEnergy()-1,8',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 30),
            classifier_block(30, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            nn.Linear(15, 15)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../../saved_models/{model_name}'))

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_10 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_11 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_12 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_13 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_14 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_15 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9) + [9] * len(X_10) + [10] * len(X_11) + [11] * len(X_12) + [12] * len(X_13) + [13] * len(X_14) + [14] * len(X_15)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [1, 3, 5, 7, 8]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [7]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 8.177769184112549, Final Batch Loss: 2.7224531173706055
Epoch 2, Loss: 8.167686462402344, Final Batch Loss: 2.7219529151916504
Epoch 3, Loss: 8.15138554573059, Final Batch Loss: 2.705904722213745
Epoch 4, Loss: 8.15267276763916, Final Batch Loss: 2.7183644771575928
Epoch 5, Loss: 8.139990329742432, Final Batch Loss: 2.7069091796875
Epoch 6, Loss: 8.133266687393188, Final Batch Loss: 2.717188835144043
Epoch 7, Loss: 8.126067638397217, Final Batch Loss: 2.7089264392852783
Epoch 8, Loss: 8.109956502914429, Final Batch Loss: 2.709545850753784
Epoch 9, Loss: 8.093474864959717, Final Batch Loss: 2.6938278675079346
Epoch 10, Loss: 8.07895040512085, Final Batch Loss: 2.680131196975708
Epoch 11, Loss: 8.040251016616821, Final Batch Loss: 2.658381700515747
Epoch 12, Loss: 8.016799926757812, Final Batch Loss: 2.659492015838623
Epoch 13, Loss: 8.01409125328064, Final Batch Loss: 2.6736557483673096
Epoch 14, Loss: 7.965330600738525, Final Batch Loss: 2.6631548404693604
Epoch 15, Loss

Epoch 128, Loss: 3.4488022327423096, Final Batch Loss: 1.1662291288375854
Epoch 129, Loss: 3.360398769378662, Final Batch Loss: 1.1469480991363525
Epoch 130, Loss: 3.459819197654724, Final Batch Loss: 1.1565370559692383
Epoch 131, Loss: 3.3738791942596436, Final Batch Loss: 1.1661906242370605
Epoch 132, Loss: 3.3577369451522827, Final Batch Loss: 1.122756004333496
Epoch 133, Loss: 3.361010432243347, Final Batch Loss: 1.1573371887207031
Epoch 134, Loss: 3.214348077774048, Final Batch Loss: 1.0492806434631348
Epoch 135, Loss: 3.366024613380432, Final Batch Loss: 1.089063286781311
Epoch 136, Loss: 3.416367292404175, Final Batch Loss: 1.2142877578735352
Epoch 137, Loss: 3.340568423271179, Final Batch Loss: 1.1397546529769897
Epoch 138, Loss: 3.4205946922302246, Final Batch Loss: 1.1145747900009155
Epoch 139, Loss: 3.3296287059783936, Final Batch Loss: 1.1089563369750977
Epoch 140, Loss: 3.320494294166565, Final Batch Loss: 1.1232314109802246
Epoch 141, Loss: 3.244964122772217, Final Batch 

Epoch 240, Loss: 2.737009108066559, Final Batch Loss: 0.9028817415237427
Epoch 241, Loss: 2.7322688698768616, Final Batch Loss: 0.8967946767807007
Epoch 242, Loss: 2.7549678087234497, Final Batch Loss: 0.9510049223899841
Epoch 243, Loss: 2.6720088720321655, Final Batch Loss: 0.8099027276039124
Epoch 244, Loss: 2.7036232352256775, Final Batch Loss: 0.9524038434028625
Epoch 245, Loss: 2.7093843817710876, Final Batch Loss: 0.9121677279472351
Epoch 246, Loss: 2.8274841904640198, Final Batch Loss: 0.9547707438468933
Epoch 247, Loss: 2.8006219267845154, Final Batch Loss: 0.95805823802948
Epoch 248, Loss: 2.6386460661888123, Final Batch Loss: 0.808814287185669
Epoch 249, Loss: 2.6489736437797546, Final Batch Loss: 0.8418446779251099
Epoch 250, Loss: 2.6481334567070007, Final Batch Loss: 0.8883662819862366
Epoch 251, Loss: 2.7247522473335266, Final Batch Loss: 0.8031099438667297
Epoch 252, Loss: 2.6531792283058167, Final Batch Loss: 0.8879942297935486
Epoch 253, Loss: 2.8381585478782654, Final

Epoch 360, Loss: 2.443763494491577, Final Batch Loss: 0.7702013850212097
Epoch 361, Loss: 2.5993043184280396, Final Batch Loss: 0.8261994123458862
Epoch 362, Loss: 2.397452652454376, Final Batch Loss: 0.6920777559280396
Epoch 363, Loss: 2.4247010350227356, Final Batch Loss: 0.7210518717765808
Epoch 364, Loss: 2.385859787464142, Final Batch Loss: 0.789771318435669
Epoch 365, Loss: 2.4677241444587708, Final Batch Loss: 0.8002732992172241
Epoch 366, Loss: 2.4676854014396667, Final Batch Loss: 0.7766843438148499
Epoch 367, Loss: 2.371144413948059, Final Batch Loss: 0.708256185054779
Epoch 368, Loss: 2.40841007232666, Final Batch Loss: 0.7706584930419922
Epoch 369, Loss: 2.503638803958893, Final Batch Loss: 0.7853737473487854
Epoch 370, Loss: 2.5132779479026794, Final Batch Loss: 0.8663626313209534
Epoch 371, Loss: 2.4252877831459045, Final Batch Loss: 0.8627345561981201
Epoch 372, Loss: 2.5336243510246277, Final Batch Loss: 0.8733600378036499
Epoch 373, Loss: 2.32599538564682, Final Batch 

Epoch 487, Loss: 2.3509780764579773, Final Batch Loss: 0.8077635765075684
Epoch 488, Loss: 2.2793740034103394, Final Batch Loss: 0.8066166639328003
Epoch 489, Loss: 2.28692227602005, Final Batch Loss: 0.6711451411247253
Epoch 490, Loss: 2.338951826095581, Final Batch Loss: 0.6983197927474976
Epoch 491, Loss: 2.3311960101127625, Final Batch Loss: 0.9151055812835693
Epoch 492, Loss: 2.204559624195099, Final Batch Loss: 0.7171642780303955
Epoch 493, Loss: 2.346126616001129, Final Batch Loss: 0.7988313436508179
Epoch 494, Loss: 2.3858678340911865, Final Batch Loss: 0.7599321007728577
Epoch 495, Loss: 2.2736161947250366, Final Batch Loss: 0.7483795881271362
Epoch 496, Loss: 2.324258506298065, Final Batch Loss: 0.8467038869857788
Epoch 497, Loss: 2.269140839576721, Final Batch Loss: 0.7061317563056946
Epoch 498, Loss: 2.2995938062667847, Final Batch Loss: 0.7984402775764465
Epoch 499, Loss: 2.3305631279945374, Final Batch Loss: 0.8118811845779419
Epoch 500, Loss: 2.2971271872520447, Final Ba

Epoch 608, Loss: 2.09894722700119, Final Batch Loss: 0.6841323971748352
Epoch 609, Loss: 2.1867364048957825, Final Batch Loss: 0.7727410197257996
Epoch 610, Loss: 2.10592257976532, Final Batch Loss: 0.751055896282196
Epoch 611, Loss: 2.113816499710083, Final Batch Loss: 0.6476213932037354
Epoch 612, Loss: 2.042837619781494, Final Batch Loss: 0.6395926475524902
Epoch 613, Loss: 2.08310604095459, Final Batch Loss: 0.7190037369728088
Epoch 614, Loss: 2.0335901975631714, Final Batch Loss: 0.5940495729446411
Epoch 615, Loss: 2.0737550258636475, Final Batch Loss: 0.7554017305374146
Epoch 616, Loss: 2.0514251589775085, Final Batch Loss: 0.6244710087776184
Epoch 617, Loss: 2.055826485157013, Final Batch Loss: 0.679707944393158
Epoch 618, Loss: 1.9247302412986755, Final Batch Loss: 0.5371683835983276
Epoch 619, Loss: 2.1273829340934753, Final Batch Loss: 0.6813454627990723
Epoch 620, Loss: 2.0325180292129517, Final Batch Loss: 0.6459403038024902
Epoch 621, Loss: 2.148327946662903, Final Batch L

Epoch 729, Loss: 1.8906007409095764, Final Batch Loss: 0.6136683821678162
Epoch 730, Loss: 1.9112926125526428, Final Batch Loss: 0.6633923053741455
Epoch 731, Loss: 1.9029788374900818, Final Batch Loss: 0.6444600224494934
Epoch 732, Loss: 1.907447338104248, Final Batch Loss: 0.6371365189552307
Epoch 733, Loss: 1.941441833972931, Final Batch Loss: 0.5901906490325928
Epoch 734, Loss: 1.9483891725540161, Final Batch Loss: 0.6563403606414795
Epoch 735, Loss: 1.898208498954773, Final Batch Loss: 0.7513264417648315
Epoch 736, Loss: 1.8975314497947693, Final Batch Loss: 0.6585476398468018
Epoch 737, Loss: 2.0489194989204407, Final Batch Loss: 0.7080023288726807
Epoch 738, Loss: 1.9362836480140686, Final Batch Loss: 0.5786939263343811
Epoch 739, Loss: 1.9292582869529724, Final Batch Loss: 0.6283131241798401
Epoch 740, Loss: 1.888034701347351, Final Batch Loss: 0.6300073862075806
Epoch 741, Loss: 1.9472249150276184, Final Batch Loss: 0.6165199279785156
Epoch 742, Loss: 1.823129415512085, Final 

Epoch 843, Loss: 1.8111939430236816, Final Batch Loss: 0.6002733111381531
Epoch 844, Loss: 1.6991704106330872, Final Batch Loss: 0.5343387722969055
Epoch 845, Loss: 1.8332683444023132, Final Batch Loss: 0.6321994662284851
Epoch 846, Loss: 1.7518041133880615, Final Batch Loss: 0.5385273694992065
Epoch 847, Loss: 1.8006360530853271, Final Batch Loss: 0.627483606338501
Epoch 848, Loss: 1.6818984746932983, Final Batch Loss: 0.5197537541389465
Epoch 849, Loss: 1.70390385389328, Final Batch Loss: 0.5230098962783813
Epoch 850, Loss: 1.7567777633666992, Final Batch Loss: 0.5325821042060852
Epoch 851, Loss: 1.7212566137313843, Final Batch Loss: 0.5658565759658813
Epoch 852, Loss: 1.7224323153495789, Final Batch Loss: 0.562100887298584
Epoch 853, Loss: 1.6580179035663605, Final Batch Loss: 0.48500898480415344
Epoch 854, Loss: 1.8439747095108032, Final Batch Loss: 0.6258485913276672
Epoch 855, Loss: 1.7586988806724548, Final Batch Loss: 0.5644014477729797
Epoch 856, Loss: 1.8089779019355774, Fina

Epoch 965, Loss: 1.8018541932106018, Final Batch Loss: 0.7030110955238342
Epoch 966, Loss: 1.6584298312664032, Final Batch Loss: 0.6172875761985779
Epoch 967, Loss: 1.6182147562503815, Final Batch Loss: 0.5580297112464905
Epoch 968, Loss: 1.52303546667099, Final Batch Loss: 0.4694305658340454
Epoch 969, Loss: 1.64144629240036, Final Batch Loss: 0.590217113494873
Epoch 970, Loss: 1.6208442449569702, Final Batch Loss: 0.5290889143943787
Epoch 971, Loss: 1.7025186419487, Final Batch Loss: 0.6120964884757996
Epoch 972, Loss: 1.4985686242580414, Final Batch Loss: 0.4977165162563324
Epoch 973, Loss: 1.6008245944976807, Final Batch Loss: 0.5856741070747375
Epoch 974, Loss: 1.5651436746120453, Final Batch Loss: 0.5290206074714661
Epoch 975, Loss: 1.6087527871131897, Final Batch Loss: 0.4856107234954834
Epoch 976, Loss: 1.634423553943634, Final Batch Loss: 0.564084529876709
Epoch 977, Loss: 1.4670952558517456, Final Batch Loss: 0.3940187692642212
Epoch 978, Loss: 1.7211852073669434, Final Batch

Epoch 1084, Loss: 1.6101904213428497, Final Batch Loss: 0.5976309776306152
Epoch 1085, Loss: 1.558056503534317, Final Batch Loss: 0.49716857075691223
Epoch 1086, Loss: 1.6336503624916077, Final Batch Loss: 0.5204128623008728
Epoch 1087, Loss: 1.6515169143676758, Final Batch Loss: 0.604250431060791
Epoch 1088, Loss: 1.5053508877754211, Final Batch Loss: 0.484507292509079
Epoch 1089, Loss: 1.5193417072296143, Final Batch Loss: 0.4730941653251648
Epoch 1090, Loss: 1.6488005816936493, Final Batch Loss: 0.6202144622802734
Epoch 1091, Loss: 1.4769883751869202, Final Batch Loss: 0.5138534903526306
Epoch 1092, Loss: 1.5715224146842957, Final Batch Loss: 0.4837416112422943
Epoch 1093, Loss: 1.6247621774673462, Final Batch Loss: 0.5617181062698364
Epoch 1094, Loss: 1.4994149506092072, Final Batch Loss: 0.5034089088439941
Epoch 1095, Loss: 1.4375353753566742, Final Batch Loss: 0.41381171345710754
Epoch 1096, Loss: 1.498489648103714, Final Batch Loss: 0.4637294113636017
Epoch 1097, Loss: 1.5574460

Epoch 1204, Loss: 1.404190719127655, Final Batch Loss: 0.43770939111709595
Epoch 1205, Loss: 1.3854085505008698, Final Batch Loss: 0.3782373368740082
Epoch 1206, Loss: 1.530457764863968, Final Batch Loss: 0.6150949001312256
Epoch 1207, Loss: 1.3155688643455505, Final Batch Loss: 0.4684350788593292
Epoch 1208, Loss: 1.3672045767307281, Final Batch Loss: 0.4302087128162384
Epoch 1209, Loss: 1.2326982915401459, Final Batch Loss: 0.33842402696609497
Epoch 1210, Loss: 1.457368791103363, Final Batch Loss: 0.4860696494579315
Epoch 1211, Loss: 1.3445027470588684, Final Batch Loss: 0.3921920359134674
Epoch 1212, Loss: 1.37932088971138, Final Batch Loss: 0.4992452561855316
Epoch 1213, Loss: 1.5312301814556122, Final Batch Loss: 0.4984508156776428
Epoch 1214, Loss: 1.4342334270477295, Final Batch Loss: 0.4442340135574341
Epoch 1215, Loss: 1.3982194066047668, Final Batch Loss: 0.39306747913360596
Epoch 1216, Loss: 1.514561951160431, Final Batch Loss: 0.5700494050979614
Epoch 1217, Loss: 1.49569350

Epoch 1314, Loss: 1.369333952665329, Final Batch Loss: 0.45176807045936584
Epoch 1315, Loss: 1.3570367693901062, Final Batch Loss: 0.46925264596939087
Epoch 1316, Loss: 1.3796959817409515, Final Batch Loss: 0.4751984179019928
Epoch 1317, Loss: 1.3293504416942596, Final Batch Loss: 0.4219907522201538
Epoch 1318, Loss: 1.3111883103847504, Final Batch Loss: 0.49381178617477417
Epoch 1319, Loss: 1.3282463550567627, Final Batch Loss: 0.4297923445701599
Epoch 1320, Loss: 1.4647769629955292, Final Batch Loss: 0.5523356795310974
Epoch 1321, Loss: 1.328370839357376, Final Batch Loss: 0.42416009306907654
Epoch 1322, Loss: 1.3645786345005035, Final Batch Loss: 0.40412673354148865
Epoch 1323, Loss: 1.376592993736267, Final Batch Loss: 0.47620928287506104
Epoch 1324, Loss: 1.153202772140503, Final Batch Loss: 0.2924962341785431
Epoch 1325, Loss: 1.3674144446849823, Final Batch Loss: 0.42856279015541077
Epoch 1326, Loss: 1.373057633638382, Final Batch Loss: 0.4739731252193451
Epoch 1327, Loss: 1.332

Epoch 1426, Loss: 1.2718932628631592, Final Batch Loss: 0.3943706452846527
Epoch 1427, Loss: 1.2736295461654663, Final Batch Loss: 0.41224753856658936
Epoch 1428, Loss: 1.2991794645786285, Final Batch Loss: 0.482079416513443
Epoch 1429, Loss: 1.3107371926307678, Final Batch Loss: 0.45270678400993347
Epoch 1430, Loss: 1.3431262969970703, Final Batch Loss: 0.4231441617012024
Epoch 1431, Loss: 1.275728702545166, Final Batch Loss: 0.42419877648353577
Epoch 1432, Loss: 1.3679827451705933, Final Batch Loss: 0.4918310046195984
Epoch 1433, Loss: 1.2123321890830994, Final Batch Loss: 0.3834547698497772
Epoch 1434, Loss: 1.2357885539531708, Final Batch Loss: 0.384133517742157
Epoch 1435, Loss: 1.361654669046402, Final Batch Loss: 0.5016881823539734
Epoch 1436, Loss: 1.2434102296829224, Final Batch Loss: 0.42140716314315796
Epoch 1437, Loss: 1.1630459129810333, Final Batch Loss: 0.3478260040283203
Epoch 1438, Loss: 1.242801696062088, Final Batch Loss: 0.41791287064552307
Epoch 1439, Loss: 1.25977

Epoch 1536, Loss: 1.2523778676986694, Final Batch Loss: 0.49323391914367676
Epoch 1537, Loss: 1.1691868603229523, Final Batch Loss: 0.39596855640411377
Epoch 1538, Loss: 1.2382028996944427, Final Batch Loss: 0.46777814626693726
Epoch 1539, Loss: 1.239585816860199, Final Batch Loss: 0.3156667649745941
Epoch 1540, Loss: 1.2472331523895264, Final Batch Loss: 0.39491137862205505
Epoch 1541, Loss: 1.2193306684494019, Final Batch Loss: 0.33640408515930176
Epoch 1542, Loss: 1.2897177338600159, Final Batch Loss: 0.42951810359954834
Epoch 1543, Loss: 1.2317546606063843, Final Batch Loss: 0.387961208820343
Epoch 1544, Loss: 1.3026338517665863, Final Batch Loss: 0.5049825310707092
Epoch 1545, Loss: 1.2473114132881165, Final Batch Loss: 0.455121248960495
Epoch 1546, Loss: 1.1569799482822418, Final Batch Loss: 0.33526402711868286
Epoch 1547, Loss: 1.2096679508686066, Final Batch Loss: 0.4706183671951294
Epoch 1548, Loss: 1.2705738842487335, Final Batch Loss: 0.41227608919143677
Epoch 1549, Loss: 1.

Epoch 1649, Loss: 1.211243897676468, Final Batch Loss: 0.3086616098880768
Epoch 1650, Loss: 1.3681012988090515, Final Batch Loss: 0.5645405054092407
Epoch 1651, Loss: 1.2028734385967255, Final Batch Loss: 0.4494418501853943
Epoch 1652, Loss: 1.1472530663013458, Final Batch Loss: 0.40226924419403076
Epoch 1653, Loss: 1.213865041732788, Final Batch Loss: 0.3400786221027374
Epoch 1654, Loss: 1.2155489027500153, Final Batch Loss: 0.353217750787735
Epoch 1655, Loss: 1.2556076347827911, Final Batch Loss: 0.3564605116844177
Epoch 1656, Loss: 1.1310202181339264, Final Batch Loss: 0.38259512186050415
Epoch 1657, Loss: 1.2997530102729797, Final Batch Loss: 0.4648221433162689
Epoch 1658, Loss: 1.1851339936256409, Final Batch Loss: 0.34317973256111145
Epoch 1659, Loss: 1.1212177872657776, Final Batch Loss: 0.27789953351020813
Epoch 1660, Loss: 1.2219352424144745, Final Batch Loss: 0.4195317327976227
Epoch 1661, Loss: 1.1889544427394867, Final Batch Loss: 0.4380991756916046
Epoch 1662, Loss: 1.1805

Epoch 1767, Loss: 1.1437179744243622, Final Batch Loss: 0.41822192072868347
Epoch 1768, Loss: 1.2624563574790955, Final Batch Loss: 0.4424510896205902
Epoch 1769, Loss: 1.116201013326645, Final Batch Loss: 0.330148845911026
Epoch 1770, Loss: 1.216859519481659, Final Batch Loss: 0.38929614424705505
Epoch 1771, Loss: 1.2657583951950073, Final Batch Loss: 0.44769832491874695
Epoch 1772, Loss: 1.1817426085472107, Final Batch Loss: 0.4769929349422455
Epoch 1773, Loss: 1.098135083913803, Final Batch Loss: 0.3970405161380768
Epoch 1774, Loss: 1.021153211593628, Final Batch Loss: 0.2764480710029602
Epoch 1775, Loss: 1.1856994330883026, Final Batch Loss: 0.3844611346721649
Epoch 1776, Loss: 1.1405691802501678, Final Batch Loss: 0.396671861410141
Epoch 1777, Loss: 1.2697237432003021, Final Batch Loss: 0.39711278676986694
Epoch 1778, Loss: 1.1380980908870697, Final Batch Loss: 0.300888329744339
Epoch 1779, Loss: 1.2414356768131256, Final Batch Loss: 0.45290857553482056
Epoch 1780, Loss: 1.1463198

Epoch 1885, Loss: 1.0592540502548218, Final Batch Loss: 0.28632986545562744
Epoch 1886, Loss: 1.1544395089149475, Final Batch Loss: 0.38756120204925537
Epoch 1887, Loss: 1.2193259596824646, Final Batch Loss: 0.39335909485816956
Epoch 1888, Loss: 1.083598554134369, Final Batch Loss: 0.30344346165657043
Epoch 1889, Loss: 1.1139287948608398, Final Batch Loss: 0.37621697783470154
Epoch 1890, Loss: 1.0231327414512634, Final Batch Loss: 0.35741162300109863
Epoch 1891, Loss: 1.018223911523819, Final Batch Loss: 0.32289382815361023
Epoch 1892, Loss: 1.1086686551570892, Final Batch Loss: 0.4276590347290039
Epoch 1893, Loss: 1.1338678896427155, Final Batch Loss: 0.35366854071617126
Epoch 1894, Loss: 1.175850659608841, Final Batch Loss: 0.39436373114585876
Epoch 1895, Loss: 1.0848303437232971, Final Batch Loss: 0.3254804313182831
Epoch 1896, Loss: 1.090873122215271, Final Batch Loss: 0.30502671003341675
Epoch 1897, Loss: 1.0933472514152527, Final Batch Loss: 0.35276368260383606
Epoch 1898, Loss: 

Epoch 1993, Loss: 1.2777714133262634, Final Batch Loss: 0.49114876985549927
Epoch 1994, Loss: 1.0249994397163391, Final Batch Loss: 0.2671775221824646
Epoch 1995, Loss: 1.1469659805297852, Final Batch Loss: 0.2694762647151947
Epoch 1996, Loss: 1.183758944272995, Final Batch Loss: 0.42349758744239807
Epoch 1997, Loss: 1.1256577670574188, Final Batch Loss: 0.4025353491306305
Epoch 1998, Loss: 1.0905870497226715, Final Batch Loss: 0.40798020362854004
Epoch 1999, Loss: 1.0373539328575134, Final Batch Loss: 0.29292652010917664
Epoch 2000, Loss: 1.1372123658657074, Final Batch Loss: 0.42664095759391785
Epoch 2001, Loss: 1.180950790643692, Final Batch Loss: 0.44450223445892334
Epoch 2002, Loss: 1.0223223865032196, Final Batch Loss: 0.36232802271842957
Epoch 2003, Loss: 1.0781414806842804, Final Batch Loss: 0.3267901539802551
Epoch 2004, Loss: 1.0873871147632599, Final Batch Loss: 0.36965975165367126
Epoch 2005, Loss: 1.1795975863933563, Final Batch Loss: 0.4771937429904938
Epoch 2006, Loss: 1

Epoch 2104, Loss: 1.118221789598465, Final Batch Loss: 0.3294661045074463
Epoch 2105, Loss: 1.0925955176353455, Final Batch Loss: 0.37948352098464966
Epoch 2106, Loss: 1.1193757951259613, Final Batch Loss: 0.3989255726337433
Epoch 2107, Loss: 1.131334513425827, Final Batch Loss: 0.427353173494339
Epoch 2108, Loss: 0.9923329055309296, Final Batch Loss: 0.29125428199768066
Epoch 2109, Loss: 1.0191764831542969, Final Batch Loss: 0.3684195280075073
Epoch 2110, Loss: 1.1134582459926605, Final Batch Loss: 0.3517882823944092
Epoch 2111, Loss: 1.1687287092208862, Final Batch Loss: 0.3948034346103668
Epoch 2112, Loss: 1.0257095694541931, Final Batch Loss: 0.31268513202667236
Epoch 2113, Loss: 0.9325306266546249, Final Batch Loss: 0.23608438670635223
Epoch 2114, Loss: 0.9915181696414948, Final Batch Loss: 0.278964102268219
Epoch 2115, Loss: 1.0286591351032257, Final Batch Loss: 0.3489973247051239
Epoch 2116, Loss: 1.0249308049678802, Final Batch Loss: 0.2810564935207367
Epoch 2117, Loss: 1.20881

Epoch 2225, Loss: 0.9953321516513824, Final Batch Loss: 0.27404868602752686
Epoch 2226, Loss: 1.115134835243225, Final Batch Loss: 0.4636978209018707
Epoch 2227, Loss: 1.059000939130783, Final Batch Loss: 0.37063178420066833
Epoch 2228, Loss: 1.2135541439056396, Final Batch Loss: 0.4805724620819092
Epoch 2229, Loss: 1.041066825389862, Final Batch Loss: 0.36617475748062134
Epoch 2230, Loss: 0.8979964852333069, Final Batch Loss: 0.2083771824836731
Epoch 2231, Loss: 1.0352641642093658, Final Batch Loss: 0.3645251393318176
Epoch 2232, Loss: 1.0646869838237762, Final Batch Loss: 0.3316226899623871
Epoch 2233, Loss: 1.1657082438468933, Final Batch Loss: 0.484282523393631
Epoch 2234, Loss: 1.0089132189750671, Final Batch Loss: 0.2722000777721405
Epoch 2235, Loss: 1.1305813789367676, Final Batch Loss: 0.388041615486145
Epoch 2236, Loss: 1.1390742659568787, Final Batch Loss: 0.3881969451904297
Epoch 2237, Loss: 1.071361631155014, Final Batch Loss: 0.435259073972702
Epoch 2238, Loss: 1.195396751

Epoch 2343, Loss: 1.079247772693634, Final Batch Loss: 0.39762821793556213
Epoch 2344, Loss: 1.0274212062358856, Final Batch Loss: 0.311998188495636
Epoch 2345, Loss: 1.0711674094200134, Final Batch Loss: 0.3430728316307068
Epoch 2346, Loss: 0.981732577085495, Final Batch Loss: 0.2744538486003876
Epoch 2347, Loss: 1.0170675218105316, Final Batch Loss: 0.34060487151145935
Epoch 2348, Loss: 1.1301254034042358, Final Batch Loss: 0.40775054693222046
Epoch 2349, Loss: 1.0881660878658295, Final Batch Loss: 0.36009398102760315
Epoch 2350, Loss: 0.9698319733142853, Final Batch Loss: 0.33533284068107605
Epoch 2351, Loss: 1.0850633382797241, Final Batch Loss: 0.37678268551826477
Epoch 2352, Loss: 1.0434797406196594, Final Batch Loss: 0.28811588883399963
Epoch 2353, Loss: 1.0667095184326172, Final Batch Loss: 0.35328108072280884
Epoch 2354, Loss: 1.005705088376999, Final Batch Loss: 0.3579128384590149
Epoch 2355, Loss: 1.0193938910961151, Final Batch Loss: 0.3618864119052887
Epoch 2356, Loss: 1.0

Epoch 2466, Loss: 0.937421441078186, Final Batch Loss: 0.2677600383758545
Epoch 2467, Loss: 1.0502695143222809, Final Batch Loss: 0.3457491099834442
Epoch 2468, Loss: 1.0426141023635864, Final Batch Loss: 0.32216814160346985
Epoch 2469, Loss: 0.8710406124591827, Final Batch Loss: 0.2707253694534302
Epoch 2470, Loss: 1.1236677467823029, Final Batch Loss: 0.4069474935531616
Epoch 2471, Loss: 0.997194766998291, Final Batch Loss: 0.328836053609848
Epoch 2472, Loss: 1.039482057094574, Final Batch Loss: 0.3541581332683563
Epoch 2473, Loss: 1.0605020225048065, Final Batch Loss: 0.4345291256904602
Epoch 2474, Loss: 1.0644030570983887, Final Batch Loss: 0.3285579979419708
Epoch 2475, Loss: 1.0858387351036072, Final Batch Loss: 0.3526766896247864
Epoch 2476, Loss: 0.9328598380088806, Final Batch Loss: 0.2955775856971741
Epoch 2477, Loss: 0.8975330591201782, Final Batch Loss: 0.2513203024864197
Epoch 2478, Loss: 1.023174524307251, Final Batch Loss: 0.3338284194469452
Epoch 2479, Loss: 1.164314329

Epoch 2587, Loss: 1.038361370563507, Final Batch Loss: 0.3547765612602234
Epoch 2588, Loss: 0.9947422295808792, Final Batch Loss: 0.42771396040916443
Epoch 2589, Loss: 1.0633017718791962, Final Batch Loss: 0.264486700296402
Epoch 2590, Loss: 1.0431574881076813, Final Batch Loss: 0.39621466398239136
Epoch 2591, Loss: 0.9523726105690002, Final Batch Loss: 0.3270082473754883
Epoch 2592, Loss: 0.9430164694786072, Final Batch Loss: 0.303436279296875
Epoch 2593, Loss: 1.0862692892551422, Final Batch Loss: 0.3293645679950714
Epoch 2594, Loss: 0.9821389019489288, Final Batch Loss: 0.29844263195991516
Epoch 2595, Loss: 0.9773320853710175, Final Batch Loss: 0.3211440443992615
Epoch 2596, Loss: 1.097634732723236, Final Batch Loss: 0.31272196769714355
Epoch 2597, Loss: 0.9335982799530029, Final Batch Loss: 0.2854456305503845
Epoch 2598, Loss: 1.003570318222046, Final Batch Loss: 0.34939998388290405
Epoch 2599, Loss: 1.0082283318042755, Final Batch Loss: 0.3542921245098114
Epoch 2600, Loss: 1.12986

Epoch 2705, Loss: 1.0537500977516174, Final Batch Loss: 0.3683496117591858
Epoch 2706, Loss: 1.0012539327144623, Final Batch Loss: 0.3410177528858185
Epoch 2707, Loss: 0.9433229863643646, Final Batch Loss: 0.28943538665771484
Epoch 2708, Loss: 0.9592659771442413, Final Batch Loss: 0.34667420387268066
Epoch 2709, Loss: 0.9311603307723999, Final Batch Loss: 0.3011130392551422
Epoch 2710, Loss: 0.9791388809680939, Final Batch Loss: 0.3236328065395355
Epoch 2711, Loss: 0.9823164641857147, Final Batch Loss: 0.264631986618042
Epoch 2712, Loss: 0.9554345309734344, Final Batch Loss: 0.3687906563282013
Epoch 2713, Loss: 1.0453040599822998, Final Batch Loss: 0.37620389461517334
Epoch 2714, Loss: 1.0328470468521118, Final Batch Loss: 0.33382171392440796
Epoch 2715, Loss: 0.9434504508972168, Final Batch Loss: 0.27167877554893494
Epoch 2716, Loss: 1.0625883042812347, Final Batch Loss: 0.38213881850242615
Epoch 2717, Loss: 1.0436716973781586, Final Batch Loss: 0.4239804744720459
Epoch 2718, Loss: 0.

Epoch 2826, Loss: 0.9551512598991394, Final Batch Loss: 0.3385005593299866
Epoch 2827, Loss: 0.9623027443885803, Final Batch Loss: 0.22143879532814026
Epoch 2828, Loss: 0.8962249755859375, Final Batch Loss: 0.27223360538482666
Epoch 2829, Loss: 0.9573745429515839, Final Batch Loss: 0.3278796970844269
Epoch 2830, Loss: 0.974366307258606, Final Batch Loss: 0.3051273226737976
Epoch 2831, Loss: 0.9555200338363647, Final Batch Loss: 0.34762415289878845
Epoch 2832, Loss: 1.0153533816337585, Final Batch Loss: 0.3281228840351105
Epoch 2833, Loss: 0.8399378806352615, Final Batch Loss: 0.23122094571590424
Epoch 2834, Loss: 1.0385884642601013, Final Batch Loss: 0.32071325182914734
Epoch 2835, Loss: 0.9272826313972473, Final Batch Loss: 0.18892842531204224
Epoch 2836, Loss: 0.8844020068645477, Final Batch Loss: 0.3079591691493988
Epoch 2837, Loss: 1.0384545028209686, Final Batch Loss: 0.4050320088863373
Epoch 2838, Loss: 1.0927722454071045, Final Batch Loss: 0.3985455632209778
Epoch 2839, Loss: 0.

Epoch 2935, Loss: 0.9251402616500854, Final Batch Loss: 0.3466838598251343
Epoch 2936, Loss: 0.9175924956798553, Final Batch Loss: 0.2545575499534607
Epoch 2937, Loss: 0.9543562233448029, Final Batch Loss: 0.29517966508865356
Epoch 2938, Loss: 0.9597639441490173, Final Batch Loss: 0.29543107748031616
Epoch 2939, Loss: 0.9667491316795349, Final Batch Loss: 0.366110235452652
Epoch 2940, Loss: 0.9023755937814713, Final Batch Loss: 0.24482251703739166
Epoch 2941, Loss: 1.0004869401454926, Final Batch Loss: 0.40069833397865295
Epoch 2942, Loss: 1.035016804933548, Final Batch Loss: 0.29967910051345825
Epoch 2943, Loss: 0.9538534283638, Final Batch Loss: 0.25937044620513916
Epoch 2944, Loss: 0.9408433735370636, Final Batch Loss: 0.2599834203720093
Epoch 2945, Loss: 0.9225284159183502, Final Batch Loss: 0.2576553225517273
Epoch 2946, Loss: 0.929583728313446, Final Batch Loss: 0.3194669783115387
Epoch 2947, Loss: 1.0823359489440918, Final Batch Loss: 0.4754677414894104
Epoch 2948, Loss: 0.86406

Epoch 3056, Loss: 0.920884370803833, Final Batch Loss: 0.3384336829185486
Epoch 3057, Loss: 0.8133509308099747, Final Batch Loss: 0.2747343182563782
Epoch 3058, Loss: 0.7761757522821426, Final Batch Loss: 0.22625233232975006
Epoch 3059, Loss: 0.9838606715202332, Final Batch Loss: 0.3557375371456146
Epoch 3060, Loss: 0.9000604450702667, Final Batch Loss: 0.29997384548187256
Epoch 3061, Loss: 0.9217325150966644, Final Batch Loss: 0.36567479372024536
Epoch 3062, Loss: 0.9488590657711029, Final Batch Loss: 0.28243449330329895
Epoch 3063, Loss: 0.8918924927711487, Final Batch Loss: 0.3384377360343933
Epoch 3064, Loss: 0.9597290754318237, Final Batch Loss: 0.37049928307533264
Epoch 3065, Loss: 0.8781103193759918, Final Batch Loss: 0.3068508207798004
Epoch 3066, Loss: 0.8731978535652161, Final Batch Loss: 0.33468541502952576
Epoch 3067, Loss: 0.9174471199512482, Final Batch Loss: 0.29058343172073364
Epoch 3068, Loss: 0.9258885979652405, Final Batch Loss: 0.3618922829627991
Epoch 3069, Loss: 1

Epoch 3176, Loss: 0.8330144286155701, Final Batch Loss: 0.31441766023635864
Epoch 3177, Loss: 0.8437692224979401, Final Batch Loss: 0.2787424325942993
Epoch 3178, Loss: 0.8457551300525665, Final Batch Loss: 0.3018481731414795
Epoch 3179, Loss: 0.9147273898124695, Final Batch Loss: 0.3294716775417328
Epoch 3180, Loss: 1.0140248537063599, Final Batch Loss: 0.37043315172195435
Epoch 3181, Loss: 0.8877156972885132, Final Batch Loss: 0.2014324963092804
Epoch 3182, Loss: 0.7417725622653961, Final Batch Loss: 0.1679830700159073
Epoch 3183, Loss: 0.8316937237977982, Final Batch Loss: 0.23996327817440033
Epoch 3184, Loss: 0.9762759506702423, Final Batch Loss: 0.35834380984306335
Epoch 3185, Loss: 0.9933525323867798, Final Batch Loss: 0.3885597288608551
Epoch 3186, Loss: 0.9460147321224213, Final Batch Loss: 0.38147372007369995
Epoch 3187, Loss: 0.8069976270198822, Final Batch Loss: 0.2618426978588104
Epoch 3188, Loss: 0.7980950176715851, Final Batch Loss: 0.24675865471363068
Epoch 3189, Loss: 0

Epoch 3299, Loss: 0.8930412530899048, Final Batch Loss: 0.26701727509498596
Epoch 3300, Loss: 0.8816770166158676, Final Batch Loss: 0.24069856107234955
Epoch 3301, Loss: 0.8083439916372299, Final Batch Loss: 0.17811338603496552
Epoch 3302, Loss: 0.8729234635829926, Final Batch Loss: 0.2562025785446167
Epoch 3303, Loss: 0.9141955524682999, Final Batch Loss: 0.37708085775375366
Epoch 3304, Loss: 0.8641492128372192, Final Batch Loss: 0.30570098757743835
Epoch 3305, Loss: 0.8937578797340393, Final Batch Loss: 0.300216943025589
Epoch 3306, Loss: 0.892157644033432, Final Batch Loss: 0.25966906547546387
Epoch 3307, Loss: 0.9217612445354462, Final Batch Loss: 0.3300681710243225
Epoch 3308, Loss: 0.9483957290649414, Final Batch Loss: 0.3087640106678009
Epoch 3309, Loss: 0.9718904793262482, Final Batch Loss: 0.44712701439857483
Epoch 3310, Loss: 1.0285375714302063, Final Batch Loss: 0.3762739896774292
Epoch 3311, Loss: 0.9448081254959106, Final Batch Loss: 0.2954355776309967
Epoch 3312, Loss: 0.

Epoch 3419, Loss: 0.9703837037086487, Final Batch Loss: 0.3482001721858978
Epoch 3420, Loss: 0.9637207984924316, Final Batch Loss: 0.2548452615737915
Epoch 3421, Loss: 0.8170361518859863, Final Batch Loss: 0.31503230333328247
Epoch 3422, Loss: 0.9166743457317352, Final Batch Loss: 0.2792794704437256
Epoch 3423, Loss: 0.8916924893856049, Final Batch Loss: 0.3659871816635132
Epoch 3424, Loss: 0.8972448408603668, Final Batch Loss: 0.35136890411376953
Epoch 3425, Loss: 1.0140533149242401, Final Batch Loss: 0.30836454033851624
Epoch 3426, Loss: 0.8057378083467484, Final Batch Loss: 0.23348505795001984
Epoch 3427, Loss: 0.9529694318771362, Final Batch Loss: 0.2783692479133606
Epoch 3428, Loss: 0.9202446341514587, Final Batch Loss: 0.2810925245285034
Epoch 3429, Loss: 0.7586941868066788, Final Batch Loss: 0.23988012969493866
Epoch 3430, Loss: 0.887458860874176, Final Batch Loss: 0.3107374310493469
Epoch 3431, Loss: 0.8672169148921967, Final Batch Loss: 0.2997332513332367
Epoch 3432, Loss: 0.8

Epoch 3529, Loss: 0.8486319482326508, Final Batch Loss: 0.25621646642684937
Epoch 3530, Loss: 0.9380120933055878, Final Batch Loss: 0.30818164348602295
Epoch 3531, Loss: 0.9049587547779083, Final Batch Loss: 0.27139517664909363
Epoch 3532, Loss: 0.9064626395702362, Final Batch Loss: 0.3013085722923279
Epoch 3533, Loss: 0.9748422205448151, Final Batch Loss: 0.3383122384548187
Epoch 3534, Loss: 0.8388961851596832, Final Batch Loss: 0.2833441495895386
Epoch 3535, Loss: 0.8586195856332779, Final Batch Loss: 0.24722321331501007
Epoch 3536, Loss: 0.8967643082141876, Final Batch Loss: 0.3396488428115845
Epoch 3537, Loss: 0.9497587382793427, Final Batch Loss: 0.37172019481658936
Epoch 3538, Loss: 0.9028531759977341, Final Batch Loss: 0.379401832818985
Epoch 3539, Loss: 0.8443537354469299, Final Batch Loss: 0.33058303594589233
Epoch 3540, Loss: 0.7775941044092178, Final Batch Loss: 0.24833910167217255
Epoch 3541, Loss: 0.8646448254585266, Final Batch Loss: 0.28129586577415466
Epoch 3542, Loss: 

Epoch 3646, Loss: 1.0014533400535583, Final Batch Loss: 0.43570733070373535
Epoch 3647, Loss: 0.7128819972276688, Final Batch Loss: 0.20741409063339233
Epoch 3648, Loss: 0.9308306276798248, Final Batch Loss: 0.3918909430503845
Epoch 3649, Loss: 0.82647505402565, Final Batch Loss: 0.2205338180065155
Epoch 3650, Loss: 0.8336286246776581, Final Batch Loss: 0.18396222591400146
Epoch 3651, Loss: 0.8651931881904602, Final Batch Loss: 0.2964889705181122
Epoch 3652, Loss: 0.9059871286153793, Final Batch Loss: 0.39046502113342285
Epoch 3653, Loss: 0.8915677070617676, Final Batch Loss: 0.2772877812385559
Epoch 3654, Loss: 0.8575327694416046, Final Batch Loss: 0.26026543974876404
Epoch 3655, Loss: 0.8019613176584244, Final Batch Loss: 0.2761754095554352
Epoch 3656, Loss: 0.8438115119934082, Final Batch Loss: 0.2953602075576782
Epoch 3657, Loss: 1.028213083744049, Final Batch Loss: 0.4079902470111847
Epoch 3658, Loss: 0.7698413729667664, Final Batch Loss: 0.20941799879074097
Epoch 3659, Loss: 0.84

Epoch 3756, Loss: 0.8085876107215881, Final Batch Loss: 0.22838541865348816
Epoch 3757, Loss: 0.8476223796606064, Final Batch Loss: 0.3461017906665802
Epoch 3758, Loss: 0.7633327841758728, Final Batch Loss: 0.23552371561527252
Epoch 3759, Loss: 0.7866669148206711, Final Batch Loss: 0.29612889885902405
Epoch 3760, Loss: 0.857161670923233, Final Batch Loss: 0.332404226064682
Epoch 3761, Loss: 0.8116893619298935, Final Batch Loss: 0.2980680763721466
Epoch 3762, Loss: 0.7985000461339951, Final Batch Loss: 0.20614184439182281
Epoch 3763, Loss: 0.8148601651191711, Final Batch Loss: 0.2811206579208374
Epoch 3764, Loss: 1.1604787707328796, Final Batch Loss: 0.5993956923484802
Epoch 3765, Loss: 0.818787083029747, Final Batch Loss: 0.24987871944904327
Epoch 3766, Loss: 0.8821729421615601, Final Batch Loss: 0.3389374017715454
Epoch 3767, Loss: 0.894843339920044, Final Batch Loss: 0.3110007643699646
Epoch 3768, Loss: 0.7208631485700607, Final Batch Loss: 0.27753913402557373
Epoch 3769, Loss: 0.912

Epoch 3866, Loss: 0.8850438594818115, Final Batch Loss: 0.2727176547050476
Epoch 3867, Loss: 0.8826012313365936, Final Batch Loss: 0.3333284556865692
Epoch 3868, Loss: 0.7686777859926224, Final Batch Loss: 0.24746160209178925
Epoch 3869, Loss: 0.9140085577964783, Final Batch Loss: 0.3391953706741333
Epoch 3870, Loss: 0.8761367946863174, Final Batch Loss: 0.20923160016536713
Epoch 3871, Loss: 0.8527466654777527, Final Batch Loss: 0.264810174703598
Epoch 3872, Loss: 0.7723560780286789, Final Batch Loss: 0.16090644896030426
Epoch 3873, Loss: 0.8568158894777298, Final Batch Loss: 0.3115328252315521
Epoch 3874, Loss: 1.0287379622459412, Final Batch Loss: 0.35720327496528625
Epoch 3875, Loss: 0.7839528024196625, Final Batch Loss: 0.15578657388687134
Epoch 3876, Loss: 0.7798162400722504, Final Batch Loss: 0.25213688611984253
Epoch 3877, Loss: 0.7934868782758713, Final Batch Loss: 0.22822462022304535
Epoch 3878, Loss: 0.8275477290153503, Final Batch Loss: 0.35046449303627014
Epoch 3879, Loss: 

Epoch 3984, Loss: 0.763766348361969, Final Batch Loss: 0.25275442004203796
Epoch 3985, Loss: 0.7478239685297012, Final Batch Loss: 0.24260413646697998
Epoch 3986, Loss: 0.8190253376960754, Final Batch Loss: 0.3263876140117645
Epoch 3987, Loss: 0.8607748746871948, Final Batch Loss: 0.316748708486557
Epoch 3988, Loss: 0.8401710689067841, Final Batch Loss: 0.3249290883541107
Epoch 3989, Loss: 0.7826264202594757, Final Batch Loss: 0.23893767595291138
Epoch 3990, Loss: 0.7789039313793182, Final Batch Loss: 0.2452661693096161
Epoch 3991, Loss: 1.0094310939311981, Final Batch Loss: 0.3605116307735443
Epoch 3992, Loss: 0.8091132640838623, Final Batch Loss: 0.27774882316589355
Epoch 3993, Loss: 0.8297087401151657, Final Batch Loss: 0.27130770683288574
Epoch 3994, Loss: 0.8153912127017975, Final Batch Loss: 0.2233484387397766
Epoch 3995, Loss: 0.8103476166725159, Final Batch Loss: 0.2500813901424408
Epoch 3996, Loss: 0.8988681733608246, Final Batch Loss: 0.346942275762558
Epoch 3997, Loss: 0.796

Epoch 4097, Loss: 0.774842381477356, Final Batch Loss: 0.20944255590438843
Epoch 4098, Loss: 0.8463459610939026, Final Batch Loss: 0.2521788775920868
Epoch 4099, Loss: 0.8019880801439285, Final Batch Loss: 0.2931618094444275
Epoch 4100, Loss: 0.8307174742221832, Final Batch Loss: 0.26859787106513977
Epoch 4101, Loss: 0.7859157025814056, Final Batch Loss: 0.24357019364833832
Epoch 4102, Loss: 0.7628224939107895, Final Batch Loss: 0.16749240458011627
Epoch 4103, Loss: 0.7639441192150116, Final Batch Loss: 0.2113204002380371
Epoch 4104, Loss: 0.8439533114433289, Final Batch Loss: 0.284554123878479
Epoch 4105, Loss: 0.7792610079050064, Final Batch Loss: 0.23497238755226135
Epoch 4106, Loss: 0.8204860538244247, Final Batch Loss: 0.3248724341392517
Epoch 4107, Loss: 0.7499514520168304, Final Batch Loss: 0.19939586520195007
Epoch 4108, Loss: 0.7700995653867722, Final Batch Loss: 0.20029707252979279
Epoch 4109, Loss: 0.6991387605667114, Final Batch Loss: 0.17957240343093872
Epoch 4110, Loss: 0

Epoch 4218, Loss: 0.8555727005004883, Final Batch Loss: 0.33159056305885315
Epoch 4219, Loss: 0.7465472519397736, Final Batch Loss: 0.19971957802772522
Epoch 4220, Loss: 0.8667712956666946, Final Batch Loss: 0.3269874155521393
Epoch 4221, Loss: 0.8264284133911133, Final Batch Loss: 0.28828248381614685
Epoch 4222, Loss: 0.7629043459892273, Final Batch Loss: 0.25123459100723267
Epoch 4223, Loss: 0.7736337184906006, Final Batch Loss: 0.23506277799606323
Epoch 4224, Loss: 0.7528290450572968, Final Batch Loss: 0.25015291571617126
Epoch 4225, Loss: 0.7988169938325882, Final Batch Loss: 0.2146998792886734
Epoch 4226, Loss: 0.9664068073034286, Final Batch Loss: 0.4458233714103699
Epoch 4227, Loss: 0.8513186573982239, Final Batch Loss: 0.28805848956108093
Epoch 4228, Loss: 0.8168675452470779, Final Batch Loss: 0.2997496724128723
Epoch 4229, Loss: 0.725785493850708, Final Batch Loss: 0.25503966212272644
Epoch 4230, Loss: 0.9072102606296539, Final Batch Loss: 0.20549821853637695
Epoch 4231, Loss:

Epoch 4339, Loss: 0.7021780014038086, Final Batch Loss: 0.2161203920841217
Epoch 4340, Loss: 0.8104497194290161, Final Batch Loss: 0.2560684382915497
Epoch 4341, Loss: 0.721000924706459, Final Batch Loss: 0.24602089822292328
Epoch 4342, Loss: 0.8563206791877747, Final Batch Loss: 0.35589608550071716
Epoch 4343, Loss: 0.858844131231308, Final Batch Loss: 0.2634909749031067
Epoch 4344, Loss: 0.8475137203931808, Final Batch Loss: 0.27497848868370056
Epoch 4345, Loss: 0.7616080343723297, Final Batch Loss: 0.26526668667793274
Epoch 4346, Loss: 0.8269274532794952, Final Batch Loss: 0.2429393082857132
Epoch 4347, Loss: 0.8529868721961975, Final Batch Loss: 0.27109506726264954
Epoch 4348, Loss: 0.7592027336359024, Final Batch Loss: 0.24424563348293304
Epoch 4349, Loss: 0.7754054218530655, Final Batch Loss: 0.2238057553768158
Epoch 4350, Loss: 0.8102191835641861, Final Batch Loss: 0.27913039922714233
Epoch 4351, Loss: 0.7864732146263123, Final Batch Loss: 0.2998332977294922
Epoch 4352, Loss: 0.

Epoch 4461, Loss: 0.7379040718078613, Final Batch Loss: 0.1760009378194809
Epoch 4462, Loss: 0.8325831145048141, Final Batch Loss: 0.3352440595626831
Epoch 4463, Loss: 0.7436998039484024, Final Batch Loss: 0.2553139626979828
Epoch 4464, Loss: 0.8465525209903717, Final Batch Loss: 0.3268398940563202
Epoch 4465, Loss: 0.8161707073450089, Final Batch Loss: 0.2799432575702667
Epoch 4466, Loss: 0.7917259335517883, Final Batch Loss: 0.2616164982318878
Epoch 4467, Loss: 0.7378311008214951, Final Batch Loss: 0.2661806643009186
Epoch 4468, Loss: 0.7832795977592468, Final Batch Loss: 0.2275277078151703
Epoch 4469, Loss: 0.7257529944181442, Final Batch Loss: 0.24828213453292847
Epoch 4470, Loss: 0.8859237730503082, Final Batch Loss: 0.2909923493862152
Epoch 4471, Loss: 0.724128857254982, Final Batch Loss: 0.21791143715381622
Epoch 4472, Loss: 0.8489443957805634, Final Batch Loss: 0.2895049750804901
Epoch 4473, Loss: 0.7855512052774429, Final Batch Loss: 0.247922882437706
Epoch 4474, Loss: 0.74394

Epoch 4572, Loss: 0.7330328077077866, Final Batch Loss: 0.2365954965353012
Epoch 4573, Loss: 0.7809027135372162, Final Batch Loss: 0.2967871129512787
Epoch 4574, Loss: 0.776068925857544, Final Batch Loss: 0.19644354283809662
Epoch 4575, Loss: 0.7861611396074295, Final Batch Loss: 0.2513754069805145
Epoch 4576, Loss: 0.8574210107326508, Final Batch Loss: 0.3522956371307373
Epoch 4577, Loss: 0.7273855954408646, Final Batch Loss: 0.2369120568037033
Epoch 4578, Loss: 0.7382264882326126, Final Batch Loss: 0.23013606667518616
Epoch 4579, Loss: 0.8238526582717896, Final Batch Loss: 0.30826815962791443
Epoch 4580, Loss: 0.8190379589796066, Final Batch Loss: 0.3067404329776764
Epoch 4581, Loss: 0.6988376080989838, Final Batch Loss: 0.176228329539299
Epoch 4582, Loss: 0.7117886543273926, Final Batch Loss: 0.2638768255710602
Epoch 4583, Loss: 0.7188486307859421, Final Batch Loss: 0.2486567199230194
Epoch 4584, Loss: 0.7578462362289429, Final Batch Loss: 0.2626374661922455
Epoch 4585, Loss: 0.6961

Epoch 4691, Loss: 0.8444871306419373, Final Batch Loss: 0.21690627932548523
Epoch 4692, Loss: 0.7656484395265579, Final Batch Loss: 0.29711419343948364
Epoch 4693, Loss: 0.8055001050233841, Final Batch Loss: 0.2700493633747101
Epoch 4694, Loss: 0.735363095998764, Final Batch Loss: 0.22505082190036774
Epoch 4695, Loss: 0.8185482025146484, Final Batch Loss: 0.263126403093338
Epoch 4696, Loss: 0.6819024682044983, Final Batch Loss: 0.2488558143377304
Epoch 4697, Loss: 0.6984629184007645, Final Batch Loss: 0.24421273171901703
Epoch 4698, Loss: 0.8375874310731888, Final Batch Loss: 0.24571995437145233
Epoch 4699, Loss: 0.7607681751251221, Final Batch Loss: 0.2773018479347229
Epoch 4700, Loss: 0.7672654241323471, Final Batch Loss: 0.26309528946876526
Epoch 4701, Loss: 0.7139180302619934, Final Batch Loss: 0.23584917187690735
Epoch 4702, Loss: 0.6609308123588562, Final Batch Loss: 0.23575164377689362
Epoch 4703, Loss: 0.7687216103076935, Final Batch Loss: 0.2158411145210266
Epoch 4704, Loss: 0

Epoch 4812, Loss: 0.7085794806480408, Final Batch Loss: 0.21913111209869385
Epoch 4813, Loss: 0.8365488350391388, Final Batch Loss: 0.35914885997772217
Epoch 4814, Loss: 0.7590373158454895, Final Batch Loss: 0.2718757688999176
Epoch 4815, Loss: 0.7911156862974167, Final Batch Loss: 0.2911188006401062
Epoch 4816, Loss: 0.8550262302160263, Final Batch Loss: 0.23256663978099823
Epoch 4817, Loss: 0.830237939953804, Final Batch Loss: 0.35051438212394714
Epoch 4818, Loss: 0.8184681236743927, Final Batch Loss: 0.24284303188323975
Epoch 4819, Loss: 0.7103334069252014, Final Batch Loss: 0.1658416986465454
Epoch 4820, Loss: 0.8195820599794388, Final Batch Loss: 0.3465299904346466
Epoch 4821, Loss: 0.7308111488819122, Final Batch Loss: 0.2802888751029968
Epoch 4822, Loss: 0.6844441741704941, Final Batch Loss: 0.23080819845199585
Epoch 4823, Loss: 0.7576818615198135, Final Batch Loss: 0.24756354093551636
Epoch 4824, Loss: 0.7255326807498932, Final Batch Loss: 0.24702109396457672
Epoch 4825, Loss: 

Epoch 4921, Loss: 0.7148543149232864, Final Batch Loss: 0.2487582117319107
Epoch 4922, Loss: 0.7267736047506332, Final Batch Loss: 0.22472982108592987
Epoch 4923, Loss: 0.7244439721107483, Final Batch Loss: 0.247938334941864
Epoch 4924, Loss: 0.7598877549171448, Final Batch Loss: 0.30810827016830444
Epoch 4925, Loss: 0.7350207269191742, Final Batch Loss: 0.26926642656326294
Epoch 4926, Loss: 0.7252707034349442, Final Batch Loss: 0.21072803437709808
Epoch 4927, Loss: 0.7860008031129837, Final Batch Loss: 0.24512846767902374
Epoch 4928, Loss: 0.7593415379524231, Final Batch Loss: 0.244456484913826
Epoch 4929, Loss: 0.9252462983131409, Final Batch Loss: 0.33915936946868896
Epoch 4930, Loss: 0.8831250220537186, Final Batch Loss: 0.39524295926094055
Epoch 4931, Loss: 0.6563548296689987, Final Batch Loss: 0.22554779052734375
Epoch 4932, Loss: 0.7673037201166153, Final Batch Loss: 0.27026599645614624
Epoch 4933, Loss: 0.6420511454343796, Final Batch Loss: 0.21909216046333313
Epoch 4934, Loss:

In [8]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 11  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  4  0  0  4  0  0  0  0  0  2]
 [ 0  0  0  0  0  0 11  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  5]
 [ 0  0  0  0  0  1  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  1  0  0  5  0]
 [ 0  0  2  0  0  3  0  0  0  0  0  0  0  0  5]]
              precision    recall  f1-score   support

           0    0.94737   1.00000   0.97297        18
           1    0.90000   0.90000   0.90000        10
           2    0.55556   1.00000   0.71429         5
           3    1.00000   1.00000   1.00000        13
        

In [9]:
n_samples = 20

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_1 = gen(latent_vectors).detach().numpy()

y_1 = np.zeros(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_2 = gen(latent_vectors).detach().numpy()

y_2 = np.ones(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_3 = gen(latent_vectors).detach().numpy()

y_3 = np.ones(n_samples) + 1

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_4 = gen(latent_vectors).detach().numpy()

y_4 = np.ones(n_samples) + 2

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_5 = gen(latent_vectors).detach().numpy()

y_5 = np.ones(n_samples) + 3

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_6 = gen(latent_vectors).detach().numpy()

y_6 = np.ones(n_samples) + 4

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_7 = gen(latent_vectors).detach().numpy()

y_7 = np.ones(n_samples) + 5

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_8 = gen(latent_vectors).detach().numpy()

y_8 = np.ones(n_samples) + 6

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_9 = gen(latent_vectors).detach().numpy()

y_9 = np.ones(n_samples) + 7

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_10 = gen(latent_vectors).detach().numpy()

y_10 = np.ones(n_samples) + 8

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_11 = gen(latent_vectors).detach().numpy()

y_11 = np.ones(n_samples) + 9

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_12 = gen(latent_vectors).detach().numpy()

y_12 = np.ones(n_samples) + 10

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U4A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_13 = gen(latent_vectors).detach().numpy()

y_13 = np.ones(n_samples) + 11

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U4A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_14 = gen(latent_vectors).detach().numpy()

y_14 = np.ones(n_samples) + 12

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U4A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_15 = gen(latent_vectors).detach().numpy()

y_15 = np.ones(n_samples) + 13


fake_features = np.concatenate((fake_features_1, fake_features_2, fake_features_3, fake_features_4, fake_features_5, fake_features_6,
                         fake_features_7, fake_features_8, fake_features_9, fake_features_10, fake_features_11, fake_features_12,
                               fake_features_13, fake_features_14, fake_features_15))
fake_labels = np.concatenate((y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9, y_10, y_11, y_12, y_13, y_14, y_15))

fake_features = torch.Tensor(fake_features)

In [10]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  3  0  0  0  0  0  4  0  0  7]
 [ 0  0  0 19  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  2  0  0 16  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  5  0  0  7  0  0  2  0  0  2  0  0  4]
 [ 0  0  0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 12  0  0  8  0  0  0  0]
 [ 0  0  0  0  0  4  0  0 10  0  0  2  0  0  4]
 [ 0  1  0  0  0  0  0  0  0  9  7  0  1  2  0]
 [ 0  0  0  1  4  0  0  2  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  3  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  4  0  0 15  0]
 [ 0  0  9  0  0  3  0  0  2  0  0  0  0  0  6]]
              precision    recall  f1-score   support

         0.0    1.00000   1.00000   1.00000        20
         1.0    0.86957   1.00000   0.93023        20
         2.0    0.30000   0.30000   0.30000        20
         3.0    0.95000   0.95000   0.95000        20
        