In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '58 tGravityAcc-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '90 tBodyAccJerk-max()-X',
 '202 tBodyAccMag-std()',
 '203 tBodyAccMag-mad()',
 '215 tGravityAccMag-std()',
 '216 tGravityAccMag-mad()',
 '266 fBodyAcc-mean()-X',
 '272 fBodyAcc-mad()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 30),
            classifier_block(30, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            nn.Linear(15, 15)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def get_act_matrix(batch_size, a_dim):
    indexes = np.random.randint(a_dim, size = batch_size)
    
    one_hot = np.zeros((len(indexes), indexes.max()+1))
    one_hot[np.arange(len(indexes)),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)
    
def get_usr_matrix(batch_size, u_dim):
    indexes = np.random.randint(u_dim, size = batch_size)
    
    one_hot = np.zeros((indexes.size, indexes.max()+1))
    one_hot[np.arange(indexes.size),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../../saved_models/{model_name}'))

# Train on Real Test on Real

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_10 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_11 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_12 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_13 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_14 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_15 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9) + [9] * len(X_10) + [10] * len(X_11) + [11] * len(X_12) + [12] * len(X_13) + [13] * len(X_14) + [14] * len(X_15)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [1, 3, 5, 7, 8]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [8]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 8.172544479370117, Final Batch Loss: 2.7316579818725586
Epoch 2, Loss: 8.154963731765747, Final Batch Loss: 2.7064859867095947
Epoch 3, Loss: 8.150194644927979, Final Batch Loss: 2.721109390258789
Epoch 4, Loss: 8.146137237548828, Final Batch Loss: 2.7202839851379395
Epoch 5, Loss: 8.13899564743042, Final Batch Loss: 2.712228536605835
Epoch 6, Loss: 8.130512952804565, Final Batch Loss: 2.7118113040924072
Epoch 7, Loss: 8.131357908248901, Final Batch Loss: 2.725954294204712
Epoch 8, Loss: 8.118293523788452, Final Batch Loss: 2.7083590030670166
Epoch 9, Loss: 8.096697092056274, Final Batch Loss: 2.679025650024414
Epoch 10, Loss: 8.099243640899658, Final Batch Loss: 2.6928298473358154
Epoch 11, Loss: 8.09138536453247, Final Batch Loss: 2.6920089721679688
Epoch 12, Loss: 8.081949949264526, Final Batch Loss: 2.6925458908081055
Epoch 13, Loss: 8.074125528335571, Final Batch Loss: 2.6950323581695557
Epoch 14, Loss: 8.050451517105103, Final Batch Loss: 2.6773452758789062
Epoch 1

Epoch 120, Loss: 3.767132878303528, Final Batch Loss: 1.1788127422332764
Epoch 121, Loss: 3.860102415084839, Final Batch Loss: 1.3423594236373901
Epoch 122, Loss: 3.7901018857955933, Final Batch Loss: 1.198707103729248
Epoch 123, Loss: 3.726729154586792, Final Batch Loss: 1.2427669763565063
Epoch 124, Loss: 3.717448353767395, Final Batch Loss: 1.257447600364685
Epoch 125, Loss: 3.760271430015564, Final Batch Loss: 1.2860336303710938
Epoch 126, Loss: 3.76931369304657, Final Batch Loss: 1.1978704929351807
Epoch 127, Loss: 3.7508513927459717, Final Batch Loss: 1.2299760580062866
Epoch 128, Loss: 3.661033272743225, Final Batch Loss: 1.202179193496704
Epoch 129, Loss: 3.7312577962875366, Final Batch Loss: 1.2545747756958008
Epoch 130, Loss: 3.682947039604187, Final Batch Loss: 1.1804968118667603
Epoch 131, Loss: 3.745893359184265, Final Batch Loss: 1.294352412223816
Epoch 132, Loss: 3.623727560043335, Final Batch Loss: 1.3163801431655884
Epoch 133, Loss: 3.6399019956588745, Final Batch Loss

Epoch 234, Loss: 2.8332161903381348, Final Batch Loss: 0.93327796459198
Epoch 235, Loss: 2.7774727940559387, Final Batch Loss: 0.8563329577445984
Epoch 236, Loss: 2.86604380607605, Final Batch Loss: 0.9028850197792053
Epoch 237, Loss: 2.742743670940399, Final Batch Loss: 0.8988276720046997
Epoch 238, Loss: 2.902869999408722, Final Batch Loss: 1.0384595394134521
Epoch 239, Loss: 2.8143069744110107, Final Batch Loss: 0.9495493769645691
Epoch 240, Loss: 2.8119568824768066, Final Batch Loss: 0.8934794068336487
Epoch 241, Loss: 2.8764721751213074, Final Batch Loss: 1.0197991132736206
Epoch 242, Loss: 2.7660643458366394, Final Batch Loss: 0.891944944858551
Epoch 243, Loss: 2.7524913549423218, Final Batch Loss: 0.8946846723556519
Epoch 244, Loss: 2.790008306503296, Final Batch Loss: 0.977592945098877
Epoch 245, Loss: 2.764802634716034, Final Batch Loss: 0.8512153029441833
Epoch 246, Loss: 2.6365898847579956, Final Batch Loss: 0.835214376449585
Epoch 247, Loss: 2.7810025811195374, Final Batch 

Epoch 356, Loss: 2.4448389410972595, Final Batch Loss: 0.9184064269065857
Epoch 357, Loss: 2.4483324885368347, Final Batch Loss: 0.8516925573348999
Epoch 358, Loss: 2.3489471077919006, Final Batch Loss: 0.7277833819389343
Epoch 359, Loss: 2.2969375252723694, Final Batch Loss: 0.7043113112449646
Epoch 360, Loss: 2.3862507343292236, Final Batch Loss: 0.8550324440002441
Epoch 361, Loss: 2.3815714716911316, Final Batch Loss: 0.7526801228523254
Epoch 362, Loss: 2.280105471611023, Final Batch Loss: 0.7295131683349609
Epoch 363, Loss: 2.2767646312713623, Final Batch Loss: 0.7097166776657104
Epoch 364, Loss: 2.278864026069641, Final Batch Loss: 0.6604459881782532
Epoch 365, Loss: 2.3162500858306885, Final Batch Loss: 0.7495490312576294
Epoch 366, Loss: 2.2945291996002197, Final Batch Loss: 0.815077543258667
Epoch 367, Loss: 2.379838287830353, Final Batch Loss: 0.8473616242408752
Epoch 368, Loss: 2.3146650791168213, Final Batch Loss: 0.688154399394989
Epoch 369, Loss: 2.257830262184143, Final B

Epoch 474, Loss: 1.9142173528671265, Final Batch Loss: 0.5282555818557739
Epoch 475, Loss: 2.1625670194625854, Final Batch Loss: 0.7613092660903931
Epoch 476, Loss: 1.9102672338485718, Final Batch Loss: 0.6157441139221191
Epoch 477, Loss: 2.1284517645835876, Final Batch Loss: 0.7180635929107666
Epoch 478, Loss: 2.2188428044319153, Final Batch Loss: 0.7475114464759827
Epoch 479, Loss: 2.1360787749290466, Final Batch Loss: 0.7964493632316589
Epoch 480, Loss: 2.0402934551239014, Final Batch Loss: 0.6016120910644531
Epoch 481, Loss: 2.1094512343406677, Final Batch Loss: 0.7281701564788818
Epoch 482, Loss: 2.1761869192123413, Final Batch Loss: 0.7564082145690918
Epoch 483, Loss: 2.063679277896881, Final Batch Loss: 0.6582834124565125
Epoch 484, Loss: 2.0744786858558655, Final Batch Loss: 0.600000262260437
Epoch 485, Loss: 2.057546854019165, Final Batch Loss: 0.7688714265823364
Epoch 486, Loss: 2.060306966304779, Final Batch Loss: 0.6763064861297607
Epoch 487, Loss: 2.0538359880447388, Final

Epoch 591, Loss: 2.003218650817871, Final Batch Loss: 0.6273826360702515
Epoch 592, Loss: 1.967721939086914, Final Batch Loss: 0.6463049054145813
Epoch 593, Loss: 1.9505062103271484, Final Batch Loss: 0.6754606366157532
Epoch 594, Loss: 1.9974892139434814, Final Batch Loss: 0.6009758114814758
Epoch 595, Loss: 1.9727471470832825, Final Batch Loss: 0.6658316254615784
Epoch 596, Loss: 1.8704244494438171, Final Batch Loss: 0.5966702699661255
Epoch 597, Loss: 1.9823570847511292, Final Batch Loss: 0.5833512544631958
Epoch 598, Loss: 2.0205695629119873, Final Batch Loss: 0.7651020884513855
Epoch 599, Loss: 1.803687572479248, Final Batch Loss: 0.5665073394775391
Epoch 600, Loss: 1.9058947563171387, Final Batch Loss: 0.5898243188858032
Epoch 601, Loss: 1.898456633090973, Final Batch Loss: 0.5575721263885498
Epoch 602, Loss: 1.8263522386550903, Final Batch Loss: 0.5312960147857666
Epoch 603, Loss: 1.9868908524513245, Final Batch Loss: 0.6887505054473877
Epoch 604, Loss: 1.9629116654396057, Final

Epoch 703, Loss: 1.9140849709510803, Final Batch Loss: 0.6705939173698425
Epoch 704, Loss: 1.9287217259407043, Final Batch Loss: 0.6540219187736511
Epoch 705, Loss: 1.8464373350143433, Final Batch Loss: 0.5625162720680237
Epoch 706, Loss: 1.741518259048462, Final Batch Loss: 0.5357884168624878
Epoch 707, Loss: 1.905007541179657, Final Batch Loss: 0.680324137210846
Epoch 708, Loss: 1.7527890801429749, Final Batch Loss: 0.5167347192764282
Epoch 709, Loss: 1.9516916275024414, Final Batch Loss: 0.7210370302200317
Epoch 710, Loss: 1.8781087398529053, Final Batch Loss: 0.6081765294075012
Epoch 711, Loss: 1.9337509274482727, Final Batch Loss: 0.7022164463996887
Epoch 712, Loss: 1.87209153175354, Final Batch Loss: 0.6407055258750916
Epoch 713, Loss: 1.8055580258369446, Final Batch Loss: 0.5858380198478699
Epoch 714, Loss: 1.7935259342193604, Final Batch Loss: 0.6056904792785645
Epoch 715, Loss: 1.8704957962036133, Final Batch Loss: 0.6068050265312195
Epoch 716, Loss: 1.792637586593628, Final B

Epoch 817, Loss: 1.7838906645774841, Final Batch Loss: 0.5333042144775391
Epoch 818, Loss: 1.863203763961792, Final Batch Loss: 0.6187549829483032
Epoch 819, Loss: 1.688971757888794, Final Batch Loss: 0.5216308832168579
Epoch 820, Loss: 1.810042142868042, Final Batch Loss: 0.6076733469963074
Epoch 821, Loss: 1.629643440246582, Final Batch Loss: 0.5566657185554504
Epoch 822, Loss: 1.7006301879882812, Final Batch Loss: 0.5169587135314941
Epoch 823, Loss: 1.617156058549881, Final Batch Loss: 0.46423789858818054
Epoch 824, Loss: 1.8140574097633362, Final Batch Loss: 0.6623001098632812
Epoch 825, Loss: 1.7356840372085571, Final Batch Loss: 0.6338241100311279
Epoch 826, Loss: 1.7253955602645874, Final Batch Loss: 0.6456999778747559
Epoch 827, Loss: 1.7539731860160828, Final Batch Loss: 0.5552443265914917
Epoch 828, Loss: 1.8701585531234741, Final Batch Loss: 0.6417496800422668
Epoch 829, Loss: 1.6761547923088074, Final Batch Loss: 0.497205913066864
Epoch 830, Loss: 1.697570025920868, Final B

Epoch 935, Loss: 1.7127403616905212, Final Batch Loss: 0.558320164680481
Epoch 936, Loss: 1.7730284929275513, Final Batch Loss: 0.7135956883430481
Epoch 937, Loss: 1.746475338935852, Final Batch Loss: 0.558392345905304
Epoch 938, Loss: 1.7074007391929626, Final Batch Loss: 0.6332675814628601
Epoch 939, Loss: 1.714130938053131, Final Batch Loss: 0.5426071882247925
Epoch 940, Loss: 1.630406677722931, Final Batch Loss: 0.5385478138923645
Epoch 941, Loss: 1.7109392881393433, Final Batch Loss: 0.6685203909873962
Epoch 942, Loss: 1.6466946005821228, Final Batch Loss: 0.5864050388336182
Epoch 943, Loss: 1.651004135608673, Final Batch Loss: 0.5830458402633667
Epoch 944, Loss: 1.6825930774211884, Final Batch Loss: 0.6547259092330933
Epoch 945, Loss: 1.5984808504581451, Final Batch Loss: 0.4905037581920624
Epoch 946, Loss: 1.6926530599594116, Final Batch Loss: 0.5882996320724487
Epoch 947, Loss: 1.656865656375885, Final Batch Loss: 0.49675339460372925
Epoch 948, Loss: 1.6952839493751526, Final B

Epoch 1058, Loss: 1.5632986724376678, Final Batch Loss: 0.46816781163215637
Epoch 1059, Loss: 1.5518963038921356, Final Batch Loss: 0.5410499572753906
Epoch 1060, Loss: 1.5838813483715057, Final Batch Loss: 0.4587641656398773
Epoch 1061, Loss: 1.6771401166915894, Final Batch Loss: 0.5307093858718872
Epoch 1062, Loss: 1.5504142343997955, Final Batch Loss: 0.5586334466934204
Epoch 1063, Loss: 1.567980796098709, Final Batch Loss: 0.5871986150741577
Epoch 1064, Loss: 1.496870905160904, Final Batch Loss: 0.4759104251861572
Epoch 1065, Loss: 1.5512603521347046, Final Batch Loss: 0.4798584580421448
Epoch 1066, Loss: 1.6727537214756012, Final Batch Loss: 0.5708171725273132
Epoch 1067, Loss: 1.5772323310375214, Final Batch Loss: 0.5212849974632263
Epoch 1068, Loss: 1.6599713563919067, Final Batch Loss: 0.5489434599876404
Epoch 1069, Loss: 1.7136269211769104, Final Batch Loss: 0.5734935402870178
Epoch 1070, Loss: 1.6616805791854858, Final Batch Loss: 0.5007427930831909
Epoch 1071, Loss: 1.538299

Epoch 1168, Loss: 1.5413342714309692, Final Batch Loss: 0.5261094570159912
Epoch 1169, Loss: 1.5735223591327667, Final Batch Loss: 0.580756425857544
Epoch 1170, Loss: 1.5201578736305237, Final Batch Loss: 0.528308629989624
Epoch 1171, Loss: 1.4764267206192017, Final Batch Loss: 0.4069138169288635
Epoch 1172, Loss: 1.574380338191986, Final Batch Loss: 0.5815039277076721
Epoch 1173, Loss: 1.5605137348175049, Final Batch Loss: 0.5826126337051392
Epoch 1174, Loss: 1.5897480845451355, Final Batch Loss: 0.5356722474098206
Epoch 1175, Loss: 1.6265904307365417, Final Batch Loss: 0.5117766261100769
Epoch 1176, Loss: 1.471914827823639, Final Batch Loss: 0.4686499834060669
Epoch 1177, Loss: 1.5733113586902618, Final Batch Loss: 0.4749195873737335
Epoch 1178, Loss: 1.5031547546386719, Final Batch Loss: 0.4280564785003662
Epoch 1179, Loss: 1.6439819931983948, Final Batch Loss: 0.5934615731239319
Epoch 1180, Loss: 1.4697628319263458, Final Batch Loss: 0.46104124188423157
Epoch 1181, Loss: 1.53046110

Epoch 1279, Loss: 1.48725026845932, Final Batch Loss: 0.513020932674408
Epoch 1280, Loss: 1.4920774400234222, Final Batch Loss: 0.501801609992981
Epoch 1281, Loss: 1.4249746799468994, Final Batch Loss: 0.47116655111312866
Epoch 1282, Loss: 1.46098393201828, Final Batch Loss: 0.5148897767066956
Epoch 1283, Loss: 1.4894943535327911, Final Batch Loss: 0.5925344228744507
Epoch 1284, Loss: 1.4932770133018494, Final Batch Loss: 0.6046027541160583
Epoch 1285, Loss: 1.4247500896453857, Final Batch Loss: 0.4866585433483124
Epoch 1286, Loss: 1.4712961614131927, Final Batch Loss: 0.5500603914260864
Epoch 1287, Loss: 1.509556919336319, Final Batch Loss: 0.5764959454536438
Epoch 1288, Loss: 1.4708691239356995, Final Batch Loss: 0.561170756816864
Epoch 1289, Loss: 1.5667774677276611, Final Batch Loss: 0.5359274744987488
Epoch 1290, Loss: 1.3458493947982788, Final Batch Loss: 0.4721081256866455
Epoch 1291, Loss: 1.567894607782364, Final Batch Loss: 0.632504940032959
Epoch 1292, Loss: 1.43088057637214

Epoch 1394, Loss: 1.5754462480545044, Final Batch Loss: 0.5745276212692261
Epoch 1395, Loss: 1.4462473392486572, Final Batch Loss: 0.4635414183139801
Epoch 1396, Loss: 1.4529820680618286, Final Batch Loss: 0.5517776608467102
Epoch 1397, Loss: 1.4215809106826782, Final Batch Loss: 0.5399667024612427
Epoch 1398, Loss: 1.4426392316818237, Final Batch Loss: 0.5819438695907593
Epoch 1399, Loss: 1.5327998101711273, Final Batch Loss: 0.4793780744075775
Epoch 1400, Loss: 1.366258978843689, Final Batch Loss: 0.4301433265209198
Epoch 1401, Loss: 1.4659741520881653, Final Batch Loss: 0.4506246745586395
Epoch 1402, Loss: 1.3507967591285706, Final Batch Loss: 0.4293937385082245
Epoch 1403, Loss: 1.2700325548648834, Final Batch Loss: 0.3504020869731903
Epoch 1404, Loss: 1.391806960105896, Final Batch Loss: 0.49779772758483887
Epoch 1405, Loss: 1.3849481046199799, Final Batch Loss: 0.45556336641311646
Epoch 1406, Loss: 1.449956476688385, Final Batch Loss: 0.5195580124855042
Epoch 1407, Loss: 1.491226

Epoch 1510, Loss: 1.3717180788516998, Final Batch Loss: 0.4665420651435852
Epoch 1511, Loss: 1.3357373774051666, Final Batch Loss: 0.40818294882774353
Epoch 1512, Loss: 1.3116466999053955, Final Batch Loss: 0.40049752593040466
Epoch 1513, Loss: 1.2463806569576263, Final Batch Loss: 0.3224014341831207
Epoch 1514, Loss: 1.4589254260063171, Final Batch Loss: 0.5297242403030396
Epoch 1515, Loss: 1.4197054505348206, Final Batch Loss: 0.4914674460887909
Epoch 1516, Loss: 1.3551121652126312, Final Batch Loss: 0.41501450538635254
Epoch 1517, Loss: 1.480592131614685, Final Batch Loss: 0.5662887096405029
Epoch 1518, Loss: 1.28575000166893, Final Batch Loss: 0.3857150673866272
Epoch 1519, Loss: 1.3185069561004639, Final Batch Loss: 0.4047640264034271
Epoch 1520, Loss: 1.3661229610443115, Final Batch Loss: 0.5474115014076233
Epoch 1521, Loss: 1.3359033465385437, Final Batch Loss: 0.37995079159736633
Epoch 1522, Loss: 1.3198961913585663, Final Batch Loss: 0.41555875539779663
Epoch 1523, Loss: 1.535

Epoch 1628, Loss: 1.3669540286064148, Final Batch Loss: 0.4764339327812195
Epoch 1629, Loss: 1.2666305303573608, Final Batch Loss: 0.441142201423645
Epoch 1630, Loss: 1.2990702092647552, Final Batch Loss: 0.4584847688674927
Epoch 1631, Loss: 1.312565803527832, Final Batch Loss: 0.4449924826622009
Epoch 1632, Loss: 1.311709702014923, Final Batch Loss: 0.3769998252391815
Epoch 1633, Loss: 1.291011482477188, Final Batch Loss: 0.5230124592781067
Epoch 1634, Loss: 1.3585399687290192, Final Batch Loss: 0.5586491227149963
Epoch 1635, Loss: 1.3537329137325287, Final Batch Loss: 0.45317140221595764
Epoch 1636, Loss: 1.2644112408161163, Final Batch Loss: 0.5061708688735962
Epoch 1637, Loss: 1.3182513415813446, Final Batch Loss: 0.3829263746738434
Epoch 1638, Loss: 1.2920316755771637, Final Batch Loss: 0.4101579785346985
Epoch 1639, Loss: 1.3321237564086914, Final Batch Loss: 0.4259496033191681
Epoch 1640, Loss: 1.2697851061820984, Final Batch Loss: 0.4658676087856293
Epoch 1641, Loss: 1.22436463

Epoch 1740, Loss: 1.2009511590003967, Final Batch Loss: 0.4464866518974304
Epoch 1741, Loss: 1.2333423793315887, Final Batch Loss: 0.4045960307121277
Epoch 1742, Loss: 1.2759263515472412, Final Batch Loss: 0.38632047176361084
Epoch 1743, Loss: 1.3009451031684875, Final Batch Loss: 0.4850335419178009
Epoch 1744, Loss: 1.3018669188022614, Final Batch Loss: 0.373599112033844
Epoch 1745, Loss: 1.2064041495323181, Final Batch Loss: 0.31277865171432495
Epoch 1746, Loss: 1.277673363685608, Final Batch Loss: 0.3907541334629059
Epoch 1747, Loss: 1.2085735201835632, Final Batch Loss: 0.4255025386810303
Epoch 1748, Loss: 1.132598876953125, Final Batch Loss: 0.385989785194397
Epoch 1749, Loss: 1.2422136068344116, Final Batch Loss: 0.4666508436203003
Epoch 1750, Loss: 1.1855781376361847, Final Batch Loss: 0.3687938153743744
Epoch 1751, Loss: 1.2441189587116241, Final Batch Loss: 0.4069894552230835
Epoch 1752, Loss: 1.243381142616272, Final Batch Loss: 0.36432576179504395
Epoch 1753, Loss: 1.1625067

Epoch 1849, Loss: 1.2256740927696228, Final Batch Loss: 0.4653998911380768
Epoch 1850, Loss: 1.150513470172882, Final Batch Loss: 0.3935542702674866
Epoch 1851, Loss: 1.1241753995418549, Final Batch Loss: 0.44626736640930176
Epoch 1852, Loss: 1.3088566064834595, Final Batch Loss: 0.523725152015686
Epoch 1853, Loss: 1.2253901362419128, Final Batch Loss: 0.4394114315509796
Epoch 1854, Loss: 1.233234018087387, Final Batch Loss: 0.48780253529548645
Epoch 1855, Loss: 1.166176199913025, Final Batch Loss: 0.48390206694602966
Epoch 1856, Loss: 1.1709155440330505, Final Batch Loss: 0.3861350417137146
Epoch 1857, Loss: 1.2725048065185547, Final Batch Loss: 0.47167840600013733
Epoch 1858, Loss: 1.151684433221817, Final Batch Loss: 0.3408488631248474
Epoch 1859, Loss: 1.246095448732376, Final Batch Loss: 0.4291355311870575
Epoch 1860, Loss: 1.2362125217914581, Final Batch Loss: 0.3976920247077942
Epoch 1861, Loss: 1.2029250860214233, Final Batch Loss: 0.4838212728500366
Epoch 1862, Loss: 1.1265140

Epoch 1959, Loss: 1.1281071305274963, Final Batch Loss: 0.36587849259376526
Epoch 1960, Loss: 1.2167852222919464, Final Batch Loss: 0.3844510614871979
Epoch 1961, Loss: 1.1415138244628906, Final Batch Loss: 0.4093644917011261
Epoch 1962, Loss: 1.1702775657176971, Final Batch Loss: 0.3876549303531647
Epoch 1963, Loss: 1.0424213707447052, Final Batch Loss: 0.3196961581707001
Epoch 1964, Loss: 1.2382190227508545, Final Batch Loss: 0.40006840229034424
Epoch 1965, Loss: 1.1515713334083557, Final Batch Loss: 0.3137936294078827
Epoch 1966, Loss: 0.9933348596096039, Final Batch Loss: 0.2860932946205139
Epoch 1967, Loss: 1.150851458311081, Final Batch Loss: 0.4407970905303955
Epoch 1968, Loss: 1.1230846047401428, Final Batch Loss: 0.34641578793525696
Epoch 1969, Loss: 1.1158879399299622, Final Batch Loss: 0.3346404731273651
Epoch 1970, Loss: 1.0523601472377777, Final Batch Loss: 0.3707551956176758
Epoch 1971, Loss: 1.1552431285381317, Final Batch Loss: 0.35146957635879517
Epoch 1972, Loss: 1.19

Epoch 2074, Loss: 1.1244205832481384, Final Batch Loss: 0.4077197313308716
Epoch 2075, Loss: 1.0157796442508698, Final Batch Loss: 0.33572134375572205
Epoch 2076, Loss: 1.1356833577156067, Final Batch Loss: 0.42390522360801697
Epoch 2077, Loss: 1.0817241668701172, Final Batch Loss: 0.39006564021110535
Epoch 2078, Loss: 1.0999740064144135, Final Batch Loss: 0.358688622713089
Epoch 2079, Loss: 1.1415833234786987, Final Batch Loss: 0.41270172595977783
Epoch 2080, Loss: 1.1218194961547852, Final Batch Loss: 0.41086387634277344
Epoch 2081, Loss: 1.0392606556415558, Final Batch Loss: 0.333467036485672
Epoch 2082, Loss: 1.060653269290924, Final Batch Loss: 0.4131786525249481
Epoch 2083, Loss: 1.0947213768959045, Final Batch Loss: 0.3385200798511505
Epoch 2084, Loss: 1.1127856373786926, Final Batch Loss: 0.4120177626609802
Epoch 2085, Loss: 1.1805491745471954, Final Batch Loss: 0.42073142528533936
Epoch 2086, Loss: 1.1686503291130066, Final Batch Loss: 0.44634291529655457
Epoch 2087, Loss: 1.2

Epoch 2186, Loss: 1.0339671075344086, Final Batch Loss: 0.3073977828025818
Epoch 2187, Loss: 1.0802370607852936, Final Batch Loss: 0.3562770187854767
Epoch 2188, Loss: 1.0429154336452484, Final Batch Loss: 0.35405606031417847
Epoch 2189, Loss: 1.0051790177822113, Final Batch Loss: 0.31167927384376526
Epoch 2190, Loss: 1.003860980272293, Final Batch Loss: 0.3686549961566925
Epoch 2191, Loss: 1.14120152592659, Final Batch Loss: 0.45439839363098145
Epoch 2192, Loss: 1.0169870853424072, Final Batch Loss: 0.37560927867889404
Epoch 2193, Loss: 0.9459743499755859, Final Batch Loss: 0.3150688707828522
Epoch 2194, Loss: 1.0540109872817993, Final Batch Loss: 0.4290187358856201
Epoch 2195, Loss: 1.0891427397727966, Final Batch Loss: 0.36881768703460693
Epoch 2196, Loss: 1.0854456424713135, Final Batch Loss: 0.45297977328300476
Epoch 2197, Loss: 1.0096609592437744, Final Batch Loss: 0.32761937379837036
Epoch 2198, Loss: 1.1442208290100098, Final Batch Loss: 0.45533889532089233
Epoch 2199, Loss: 1.

Epoch 2300, Loss: 1.0426084995269775, Final Batch Loss: 0.38361606001853943
Epoch 2301, Loss: 1.2500193119049072, Final Batch Loss: 0.35950931906700134
Epoch 2302, Loss: 1.0820361077785492, Final Batch Loss: 0.37995901703834534
Epoch 2303, Loss: 0.9703304469585419, Final Batch Loss: 0.3524785339832306
Epoch 2304, Loss: 0.8799535036087036, Final Batch Loss: 0.2633892595767975
Epoch 2305, Loss: 0.9774988293647766, Final Batch Loss: 0.2927649915218353
Epoch 2306, Loss: 1.1028645038604736, Final Batch Loss: 0.34478554129600525
Epoch 2307, Loss: 1.0838144421577454, Final Batch Loss: 0.37303927540779114
Epoch 2308, Loss: 1.0666109919548035, Final Batch Loss: 0.32293418049812317
Epoch 2309, Loss: 0.9749431014060974, Final Batch Loss: 0.30169573426246643
Epoch 2310, Loss: 1.0116037130355835, Final Batch Loss: 0.34468090534210205
Epoch 2311, Loss: 1.0658970475196838, Final Batch Loss: 0.40108755230903625
Epoch 2312, Loss: 1.177390456199646, Final Batch Loss: 0.41686397790908813
Epoch 2313, Loss

Epoch 2411, Loss: 1.0597960948944092, Final Batch Loss: 0.38694167137145996
Epoch 2412, Loss: 0.8766005784273148, Final Batch Loss: 0.2195543497800827
Epoch 2413, Loss: 0.9934277832508087, Final Batch Loss: 0.3303182125091553
Epoch 2414, Loss: 0.9493021667003632, Final Batch Loss: 0.3132150173187256
Epoch 2415, Loss: 0.9384255111217499, Final Batch Loss: 0.2900146543979645
Epoch 2416, Loss: 1.0140110850334167, Final Batch Loss: 0.3571215867996216
Epoch 2417, Loss: 0.8806672543287277, Final Batch Loss: 0.2072763293981552
Epoch 2418, Loss: 0.9027466773986816, Final Batch Loss: 0.3160974979400635
Epoch 2419, Loss: 0.9939479827880859, Final Batch Loss: 0.3251100480556488
Epoch 2420, Loss: 1.1683330833911896, Final Batch Loss: 0.462761253118515
Epoch 2421, Loss: 1.0999409556388855, Final Batch Loss: 0.38161733746528625
Epoch 2422, Loss: 0.9949196875095367, Final Batch Loss: 0.3407866656780243
Epoch 2423, Loss: 0.9900109469890594, Final Batch Loss: 0.3188450038433075
Epoch 2424, Loss: 1.0503

Epoch 2531, Loss: 1.021821916103363, Final Batch Loss: 0.33185943961143494
Epoch 2532, Loss: 1.0585534870624542, Final Batch Loss: 0.3468668460845947
Epoch 2533, Loss: 0.9836945235729218, Final Batch Loss: 0.3417907953262329
Epoch 2534, Loss: 1.0761246979236603, Final Batch Loss: 0.3669425845146179
Epoch 2535, Loss: 0.9959000051021576, Final Batch Loss: 0.3380849063396454
Epoch 2536, Loss: 0.9253019392490387, Final Batch Loss: 0.3027551472187042
Epoch 2537, Loss: 0.9561507105827332, Final Batch Loss: 0.38099610805511475
Epoch 2538, Loss: 0.9634036719799042, Final Batch Loss: 0.34204262495040894
Epoch 2539, Loss: 0.8371579349040985, Final Batch Loss: 0.285592645406723
Epoch 2540, Loss: 0.953517735004425, Final Batch Loss: 0.4234723150730133
Epoch 2541, Loss: 1.1513091921806335, Final Batch Loss: 0.5249322056770325
Epoch 2542, Loss: 0.9027948975563049, Final Batch Loss: 0.2572614848613739
Epoch 2543, Loss: 0.9389426112174988, Final Batch Loss: 0.31599754095077515
Epoch 2544, Loss: 0.8976

Epoch 2648, Loss: 0.9490828663110733, Final Batch Loss: 0.3792248070240021
Epoch 2649, Loss: 1.1599248945713043, Final Batch Loss: 0.3685820698738098
Epoch 2650, Loss: 0.9720732569694519, Final Batch Loss: 0.33848458528518677
Epoch 2651, Loss: 1.0839413106441498, Final Batch Loss: 0.491691529750824
Epoch 2652, Loss: 1.0573865175247192, Final Batch Loss: 0.398093581199646
Epoch 2653, Loss: 1.0085206627845764, Final Batch Loss: 0.31036442518234253
Epoch 2654, Loss: 0.9233782589435577, Final Batch Loss: 0.2332029640674591
Epoch 2655, Loss: 0.9651956856250763, Final Batch Loss: 0.35105645656585693
Epoch 2656, Loss: 0.9648058712482452, Final Batch Loss: 0.25022441148757935
Epoch 2657, Loss: 0.8476122319698334, Final Batch Loss: 0.2737540602684021
Epoch 2658, Loss: 0.902390792965889, Final Batch Loss: 0.2430795282125473
Epoch 2659, Loss: 0.9877064824104309, Final Batch Loss: 0.39611777663230896
Epoch 2660, Loss: 0.9859797954559326, Final Batch Loss: 0.297004371881485
Epoch 2661, Loss: 0.9032

Epoch 2761, Loss: 0.8696816563606262, Final Batch Loss: 0.258465439081192
Epoch 2762, Loss: 0.8698613047599792, Final Batch Loss: 0.3061234652996063
Epoch 2763, Loss: 0.9299570620059967, Final Batch Loss: 0.37944111227989197
Epoch 2764, Loss: 0.9293157756328583, Final Batch Loss: 0.3189684748649597
Epoch 2765, Loss: 1.100271224975586, Final Batch Loss: 0.4246002733707428
Epoch 2766, Loss: 0.9304872155189514, Final Batch Loss: 0.2829399108886719
Epoch 2767, Loss: 0.8968491554260254, Final Batch Loss: 0.3112412095069885
Epoch 2768, Loss: 0.8830357789993286, Final Batch Loss: 0.3009069561958313
Epoch 2769, Loss: 0.9436651766300201, Final Batch Loss: 0.3352358341217041
Epoch 2770, Loss: 1.0670010447502136, Final Batch Loss: 0.38303595781326294
Epoch 2771, Loss: 0.9417377412319183, Final Batch Loss: 0.28212568163871765
Epoch 2772, Loss: 0.9635914862155914, Final Batch Loss: 0.29746749997138977
Epoch 2773, Loss: 0.9517773687839508, Final Batch Loss: 0.30552157759666443
Epoch 2774, Loss: 1.00

Epoch 2873, Loss: 0.9690617024898529, Final Batch Loss: 0.3457482159137726
Epoch 2874, Loss: 0.8120615184307098, Final Batch Loss: 0.2589936852455139
Epoch 2875, Loss: 0.8480155169963837, Final Batch Loss: 0.3283713757991791
Epoch 2876, Loss: 0.8979443609714508, Final Batch Loss: 0.27386584877967834
Epoch 2877, Loss: 0.9594076573848724, Final Batch Loss: 0.36420387029647827
Epoch 2878, Loss: 0.9313211292028427, Final Batch Loss: 0.3828592002391815
Epoch 2879, Loss: 0.8813155889511108, Final Batch Loss: 0.2883892357349396
Epoch 2880, Loss: 0.840243473649025, Final Batch Loss: 0.25628000497817993
Epoch 2881, Loss: 0.8871284425258636, Final Batch Loss: 0.281057208776474
Epoch 2882, Loss: 0.9508486092090607, Final Batch Loss: 0.32521629333496094
Epoch 2883, Loss: 0.8405127227306366, Final Batch Loss: 0.257503867149353
Epoch 2884, Loss: 0.8735874891281128, Final Batch Loss: 0.2977553606033325
Epoch 2885, Loss: 0.9723428785800934, Final Batch Loss: 0.34930968284606934
Epoch 2886, Loss: 0.822

Epoch 2990, Loss: 0.8592327833175659, Final Batch Loss: 0.268992155790329
Epoch 2991, Loss: 0.8368620276451111, Final Batch Loss: 0.2587851285934448
Epoch 2992, Loss: 0.8269953429698944, Final Batch Loss: 0.2557230591773987
Epoch 2993, Loss: 0.8817707896232605, Final Batch Loss: 0.3345889449119568
Epoch 2994, Loss: 0.925086110830307, Final Batch Loss: 0.2907469570636749
Epoch 2995, Loss: 0.9453659057617188, Final Batch Loss: 0.30554473400115967
Epoch 2996, Loss: 0.8935354351997375, Final Batch Loss: 0.2580890357494354
Epoch 2997, Loss: 1.0263828039169312, Final Batch Loss: 0.3739165961742401
Epoch 2998, Loss: 0.9105357229709625, Final Batch Loss: 0.29606592655181885
Epoch 2999, Loss: 0.9666467607021332, Final Batch Loss: 0.2861209511756897
Epoch 3000, Loss: 0.978520005941391, Final Batch Loss: 0.4055395722389221
Epoch 3001, Loss: 0.8247286677360535, Final Batch Loss: 0.2635948956012726
Epoch 3002, Loss: 0.9415105283260345, Final Batch Loss: 0.3437488377094269
Epoch 3003, Loss: 0.904323

Epoch 3109, Loss: 0.923026978969574, Final Batch Loss: 0.2899940013885498
Epoch 3110, Loss: 0.9045383334159851, Final Batch Loss: 0.3643083870410919
Epoch 3111, Loss: 0.8476307094097137, Final Batch Loss: 0.2140122652053833
Epoch 3112, Loss: 0.8690114617347717, Final Batch Loss: 0.2780042886734009
Epoch 3113, Loss: 0.9967591464519501, Final Batch Loss: 0.4032793641090393
Epoch 3114, Loss: 0.8776110261678696, Final Batch Loss: 0.3466419279575348
Epoch 3115, Loss: 0.9288569092750549, Final Batch Loss: 0.33304744958877563
Epoch 3116, Loss: 1.0747336149215698, Final Batch Loss: 0.4687406122684479
Epoch 3117, Loss: 0.925796166062355, Final Batch Loss: 0.34245598316192627
Epoch 3118, Loss: 0.8814516365528107, Final Batch Loss: 0.37126624584198
Epoch 3119, Loss: 0.9885579943656921, Final Batch Loss: 0.327049195766449
Epoch 3120, Loss: 0.9971007406711578, Final Batch Loss: 0.3304286599159241
Epoch 3121, Loss: 0.8312959671020508, Final Batch Loss: 0.3302568197250366
Epoch 3122, Loss: 0.94969867

Epoch 3224, Loss: 0.9461399167776108, Final Batch Loss: 0.32322970032691956
Epoch 3225, Loss: 0.8643904626369476, Final Batch Loss: 0.2636682987213135
Epoch 3226, Loss: 0.8839439749717712, Final Batch Loss: 0.291332483291626
Epoch 3227, Loss: 0.8858331143856049, Final Batch Loss: 0.2984342575073242
Epoch 3228, Loss: 0.9851772785186768, Final Batch Loss: 0.35253337025642395
Epoch 3229, Loss: 0.9582695364952087, Final Batch Loss: 0.36176639795303345
Epoch 3230, Loss: 0.9122109115123749, Final Batch Loss: 0.34048521518707275
Epoch 3231, Loss: 0.9831963181495667, Final Batch Loss: 0.4133305847644806
Epoch 3232, Loss: 0.803707018494606, Final Batch Loss: 0.22038891911506653
Epoch 3233, Loss: 0.8595393300056458, Final Batch Loss: 0.24624153971672058
Epoch 3234, Loss: 0.9553286731243134, Final Batch Loss: 0.32234713435173035
Epoch 3235, Loss: 0.8324330747127533, Final Batch Loss: 0.2209276556968689
Epoch 3236, Loss: 0.8347896933555603, Final Batch Loss: 0.272888720035553
Epoch 3237, Loss: 0.7

Epoch 3343, Loss: 0.932746171951294, Final Batch Loss: 0.35316887497901917
Epoch 3344, Loss: 0.8833388984203339, Final Batch Loss: 0.28257882595062256
Epoch 3345, Loss: 0.9071907997131348, Final Batch Loss: 0.28639844059944153
Epoch 3346, Loss: 0.9219700247049332, Final Batch Loss: 0.30191633105278015
Epoch 3347, Loss: 0.8638332635164261, Final Batch Loss: 0.28168195486068726
Epoch 3348, Loss: 0.7997486740350723, Final Batch Loss: 0.22341082990169525
Epoch 3349, Loss: 0.7744764685630798, Final Batch Loss: 0.22175857424736023
Epoch 3350, Loss: 0.874654084444046, Final Batch Loss: 0.32043302059173584
Epoch 3351, Loss: 0.8990723788738251, Final Batch Loss: 0.35350990295410156
Epoch 3352, Loss: 0.8908856213092804, Final Batch Loss: 0.37184369564056396
Epoch 3353, Loss: 1.0374074280261993, Final Batch Loss: 0.39122432470321655
Epoch 3354, Loss: 0.8607726097106934, Final Batch Loss: 0.2721283435821533
Epoch 3355, Loss: 0.9241508841514587, Final Batch Loss: 0.23977714776992798
Epoch 3356, Los

Epoch 3459, Loss: 0.8382146060466766, Final Batch Loss: 0.39525917172431946
Epoch 3460, Loss: 0.9079798758029938, Final Batch Loss: 0.37949490547180176
Epoch 3461, Loss: 0.9139202237129211, Final Batch Loss: 0.3051357865333557
Epoch 3462, Loss: 0.8639865517616272, Final Batch Loss: 0.28046759963035583
Epoch 3463, Loss: 0.7838200628757477, Final Batch Loss: 0.24687573313713074
Epoch 3464, Loss: 0.8312851786613464, Final Batch Loss: 0.26939457654953003
Epoch 3465, Loss: 0.810303658246994, Final Batch Loss: 0.23192442953586578
Epoch 3466, Loss: 0.8303749710321426, Final Batch Loss: 0.1864011138677597
Epoch 3467, Loss: 0.9194088578224182, Final Batch Loss: 0.366706520318985
Epoch 3468, Loss: 0.8082553595304489, Final Batch Loss: 0.25908660888671875
Epoch 3469, Loss: 0.8642816245555878, Final Batch Loss: 0.3071053624153137
Epoch 3470, Loss: 0.8465263843536377, Final Batch Loss: 0.26058825850486755
Epoch 3471, Loss: 0.7784989178180695, Final Batch Loss: 0.19856971502304077
Epoch 3472, Loss: 

Epoch 3571, Loss: 0.8977134823799133, Final Batch Loss: 0.3682501018047333
Epoch 3572, Loss: 0.7578529417514801, Final Batch Loss: 0.21057257056236267
Epoch 3573, Loss: 0.8441394120454788, Final Batch Loss: 0.28186365962028503
Epoch 3574, Loss: 0.8401155769824982, Final Batch Loss: 0.33658143877983093
Epoch 3575, Loss: 0.7951843738555908, Final Batch Loss: 0.26278355717658997
Epoch 3576, Loss: 0.8770633041858673, Final Batch Loss: 0.33445075154304504
Epoch 3577, Loss: 0.8379513621330261, Final Batch Loss: 0.22186526656150818
Epoch 3578, Loss: 0.9390210211277008, Final Batch Loss: 0.36619728803634644
Epoch 3579, Loss: 0.8399327993392944, Final Batch Loss: 0.31345176696777344
Epoch 3580, Loss: 0.8582490086555481, Final Batch Loss: 0.29169487953186035
Epoch 3581, Loss: 0.8727698624134064, Final Batch Loss: 0.30942386388778687
Epoch 3582, Loss: 0.7218895256519318, Final Batch Loss: 0.2252349853515625
Epoch 3583, Loss: 0.7879695296287537, Final Batch Loss: 0.29018881916999817
Epoch 3584, Lo

Epoch 3682, Loss: 0.7498132586479187, Final Batch Loss: 0.270457923412323
Epoch 3683, Loss: 0.7606626749038696, Final Batch Loss: 0.25348562002182007
Epoch 3684, Loss: 0.8019406497478485, Final Batch Loss: 0.2669404447078705
Epoch 3685, Loss: 0.8315259665250778, Final Batch Loss: 0.17364172637462616
Epoch 3686, Loss: 0.7469308823347092, Final Batch Loss: 0.18449003994464874
Epoch 3687, Loss: 0.8029255867004395, Final Batch Loss: 0.2630700170993805
Epoch 3688, Loss: 0.7790097296237946, Final Batch Loss: 0.2821238934993744
Epoch 3689, Loss: 0.7915714979171753, Final Batch Loss: 0.2706342339515686
Epoch 3690, Loss: 0.8634312152862549, Final Batch Loss: 0.2696245610713959
Epoch 3691, Loss: 0.7823450267314911, Final Batch Loss: 0.24496468901634216
Epoch 3692, Loss: 0.7822245955467224, Final Batch Loss: 0.2613890767097473
Epoch 3693, Loss: 0.8787684589624405, Final Batch Loss: 0.3006482720375061
Epoch 3694, Loss: 0.733366921544075, Final Batch Loss: 0.2425633668899536
Epoch 3695, Loss: 0.812

Epoch 3795, Loss: 0.7572328597307205, Final Batch Loss: 0.2089618444442749
Epoch 3796, Loss: 0.8310891091823578, Final Batch Loss: 0.2839032709598541
Epoch 3797, Loss: 0.746191143989563, Final Batch Loss: 0.24339324235916138
Epoch 3798, Loss: 0.852694183588028, Final Batch Loss: 0.3062417805194855
Epoch 3799, Loss: 0.8037118911743164, Final Batch Loss: 0.27422064542770386
Epoch 3800, Loss: 0.7473374456167221, Final Batch Loss: 0.2689862847328186
Epoch 3801, Loss: 0.8591102063655853, Final Batch Loss: 0.2901572585105896
Epoch 3802, Loss: 0.7856085747480392, Final Batch Loss: 0.23515520989894867
Epoch 3803, Loss: 0.7256570607423782, Final Batch Loss: 0.20592059195041656
Epoch 3804, Loss: 0.7683268785476685, Final Batch Loss: 0.29503291845321655
Epoch 3805, Loss: 0.7550264596939087, Final Batch Loss: 0.18048211932182312
Epoch 3806, Loss: 0.8940450251102448, Final Batch Loss: 0.34824368357658386
Epoch 3807, Loss: 0.8548243343830109, Final Batch Loss: 0.3214997947216034
Epoch 3808, Loss: 0.

Epoch 3907, Loss: 0.6933958679437637, Final Batch Loss: 0.1951955109834671
Epoch 3908, Loss: 0.8852911591529846, Final Batch Loss: 0.2240208387374878
Epoch 3909, Loss: 0.8660494089126587, Final Batch Loss: 0.35037317872047424
Epoch 3910, Loss: 0.8504611253738403, Final Batch Loss: 0.34692710638046265
Epoch 3911, Loss: 0.8001286089420319, Final Batch Loss: 0.31179139018058777
Epoch 3912, Loss: 0.8248106092214584, Final Batch Loss: 0.31068336963653564
Epoch 3913, Loss: 0.8116351664066315, Final Batch Loss: 0.31609565019607544
Epoch 3914, Loss: 0.7642088979482651, Final Batch Loss: 0.2394222766160965
Epoch 3915, Loss: 0.8559158146381378, Final Batch Loss: 0.327869176864624
Epoch 3916, Loss: 0.865003764629364, Final Batch Loss: 0.27551430463790894
Epoch 3917, Loss: 0.7817957550287247, Final Batch Loss: 0.29750531911849976
Epoch 3918, Loss: 0.8577985763549805, Final Batch Loss: 0.30658432841300964
Epoch 3919, Loss: 0.7328027188777924, Final Batch Loss: 0.20791849493980408
Epoch 3920, Loss: 

Epoch 4024, Loss: 0.8348540216684341, Final Batch Loss: 0.23990117013454437
Epoch 4025, Loss: 0.7212922871112823, Final Batch Loss: 0.2461344599723816
Epoch 4026, Loss: 0.713983491063118, Final Batch Loss: 0.21837332844734192
Epoch 4027, Loss: 0.7856639474630356, Final Batch Loss: 0.27817052602767944
Epoch 4028, Loss: 0.8556147217750549, Final Batch Loss: 0.332060843706131
Epoch 4029, Loss: 0.9149899780750275, Final Batch Loss: 0.2377091348171234
Epoch 4030, Loss: 0.828292578458786, Final Batch Loss: 0.30496516823768616
Epoch 4031, Loss: 0.8072906881570816, Final Batch Loss: 0.23177416622638702
Epoch 4032, Loss: 0.8075851052999496, Final Batch Loss: 0.24029329419136047
Epoch 4033, Loss: 0.8155259937047958, Final Batch Loss: 0.3214142322540283
Epoch 4034, Loss: 0.7877394706010818, Final Batch Loss: 0.2590465545654297
Epoch 4035, Loss: 0.8447071462869644, Final Batch Loss: 0.22990353405475616
Epoch 4036, Loss: 0.7807764112949371, Final Batch Loss: 0.23515765368938446
Epoch 4037, Loss: 0.

Epoch 4142, Loss: 0.8390304148197174, Final Batch Loss: 0.30455508828163147
Epoch 4143, Loss: 0.6936569511890411, Final Batch Loss: 0.15339668095111847
Epoch 4144, Loss: 0.762272521853447, Final Batch Loss: 0.2521775960922241
Epoch 4145, Loss: 0.8053397387266159, Final Batch Loss: 0.24594835937023163
Epoch 4146, Loss: 0.8826922178268433, Final Batch Loss: 0.3401358723640442
Epoch 4147, Loss: 0.876027524471283, Final Batch Loss: 0.33920854330062866
Epoch 4148, Loss: 0.8413310796022415, Final Batch Loss: 0.3511648178100586
Epoch 4149, Loss: 0.6758224964141846, Final Batch Loss: 0.18639346957206726
Epoch 4150, Loss: 0.8493539392948151, Final Batch Loss: 0.32813161611557007
Epoch 4151, Loss: 0.7142706513404846, Final Batch Loss: 0.22604452073574066
Epoch 4152, Loss: 0.7626034766435623, Final Batch Loss: 0.2550336420536041
Epoch 4153, Loss: 0.7037730813026428, Final Batch Loss: 0.23297187685966492
Epoch 4154, Loss: 0.7892758846282959, Final Batch Loss: 0.23587557673454285
Epoch 4155, Loss: 

Epoch 4258, Loss: 0.7477068454027176, Final Batch Loss: 0.23765932023525238
Epoch 4259, Loss: 0.7731995582580566, Final Batch Loss: 0.23570427298545837
Epoch 4260, Loss: 0.7199828624725342, Final Batch Loss: 0.24941569566726685
Epoch 4261, Loss: 0.8190098404884338, Final Batch Loss: 0.2681276500225067
Epoch 4262, Loss: 0.8687039911746979, Final Batch Loss: 0.2563146650791168
Epoch 4263, Loss: 0.7781480103731155, Final Batch Loss: 0.3214530050754547
Epoch 4264, Loss: 0.7631241530179977, Final Batch Loss: 0.25712206959724426
Epoch 4265, Loss: 0.6717965751886368, Final Batch Loss: 0.2169899344444275
Epoch 4266, Loss: 0.8287010788917542, Final Batch Loss: 0.3103347718715668
Epoch 4267, Loss: 0.7236185818910599, Final Batch Loss: 0.1586330085992813
Epoch 4268, Loss: 0.8131440430879593, Final Batch Loss: 0.2776734530925751
Epoch 4269, Loss: 0.7037977278232574, Final Batch Loss: 0.22650673985481262
Epoch 4270, Loss: 0.7653341442346573, Final Batch Loss: 0.24308054149150848
Epoch 4271, Loss: 0

Epoch 4377, Loss: 0.6954779028892517, Final Batch Loss: 0.2159997820854187
Epoch 4378, Loss: 0.724113404750824, Final Batch Loss: 0.2511133849620819
Epoch 4379, Loss: 0.7849486172199249, Final Batch Loss: 0.2818499803543091
Epoch 4380, Loss: 0.7990346401929855, Final Batch Loss: 0.2722703218460083
Epoch 4381, Loss: 0.7276855409145355, Final Batch Loss: 0.19803106784820557
Epoch 4382, Loss: 0.6756511628627777, Final Batch Loss: 0.19694431126117706
Epoch 4383, Loss: 0.7343343496322632, Final Batch Loss: 0.22703136503696442
Epoch 4384, Loss: 0.7587416917085648, Final Batch Loss: 0.22367914021015167
Epoch 4385, Loss: 0.8901284486055374, Final Batch Loss: 0.3878135085105896
Epoch 4386, Loss: 0.6978987753391266, Final Batch Loss: 0.20051239430904388
Epoch 4387, Loss: 0.7233682870864868, Final Batch Loss: 0.2462167590856552
Epoch 4388, Loss: 0.7255571335554123, Final Batch Loss: 0.3004568815231323
Epoch 4389, Loss: 0.9497349709272385, Final Batch Loss: 0.39720410108566284
Epoch 4390, Loss: 0.

Epoch 4488, Loss: 0.7785325348377228, Final Batch Loss: 0.25793102383613586
Epoch 4489, Loss: 0.7168120592832565, Final Batch Loss: 0.27530989050865173
Epoch 4490, Loss: 0.7096008658409119, Final Batch Loss: 0.17846094071865082
Epoch 4491, Loss: 0.824307307600975, Final Batch Loss: 0.36485156416893005
Epoch 4492, Loss: 0.7981959283351898, Final Batch Loss: 0.26599669456481934
Epoch 4493, Loss: 0.8534530848264694, Final Batch Loss: 0.33836662769317627
Epoch 4494, Loss: 0.7075465768575668, Final Batch Loss: 0.26575836539268494
Epoch 4495, Loss: 0.7902192324399948, Final Batch Loss: 0.3312723636627197
Epoch 4496, Loss: 0.7490160167217255, Final Batch Loss: 0.28913596272468567
Epoch 4497, Loss: 0.724363312125206, Final Batch Loss: 0.30348241329193115
Epoch 4498, Loss: 0.7713930159807205, Final Batch Loss: 0.25084105134010315
Epoch 4499, Loss: 0.8842328637838364, Final Batch Loss: 0.39145320653915405
Epoch 4500, Loss: 0.8319536447525024, Final Batch Loss: 0.2969273626804352
Epoch 4501, Loss

Epoch 4603, Loss: 0.7793871909379959, Final Batch Loss: 0.24719345569610596
Epoch 4604, Loss: 0.7138343155384064, Final Batch Loss: 0.2881453037261963
Epoch 4605, Loss: 0.5806925296783447, Final Batch Loss: 0.18596552312374115
Epoch 4606, Loss: 0.7470577508211136, Final Batch Loss: 0.25367292761802673
Epoch 4607, Loss: 0.8018348217010498, Final Batch Loss: 0.2947711944580078
Epoch 4608, Loss: 0.8330143690109253, Final Batch Loss: 0.2816441059112549
Epoch 4609, Loss: 0.6103885322809219, Final Batch Loss: 0.1696217954158783
Epoch 4610, Loss: 0.7808433473110199, Final Batch Loss: 0.2523907721042633
Epoch 4611, Loss: 0.6392036229372025, Final Batch Loss: 0.164871945977211
Epoch 4612, Loss: 0.6398729830980301, Final Batch Loss: 0.18104201555252075
Epoch 4613, Loss: 0.7834833711385727, Final Batch Loss: 0.3034244179725647
Epoch 4614, Loss: 0.8361353874206543, Final Batch Loss: 0.30908405780792236
Epoch 4615, Loss: 0.7131297141313553, Final Batch Loss: 0.22278675436973572
Epoch 4616, Loss: 0.

Epoch 4714, Loss: 0.7308946996927261, Final Batch Loss: 0.18814577162265778
Epoch 4715, Loss: 0.6463800966739655, Final Batch Loss: 0.23137475550174713
Epoch 4716, Loss: 0.7221604287624359, Final Batch Loss: 0.23130559921264648
Epoch 4717, Loss: 0.8132513463497162, Final Batch Loss: 0.30070972442626953
Epoch 4718, Loss: 0.7444133758544922, Final Batch Loss: 0.24137762188911438
Epoch 4719, Loss: 0.7610114812850952, Final Batch Loss: 0.2518845796585083
Epoch 4720, Loss: 0.8297595530748367, Final Batch Loss: 0.3376579284667969
Epoch 4721, Loss: 0.75572569668293, Final Batch Loss: 0.24043698608875275
Epoch 4722, Loss: 0.81389020383358, Final Batch Loss: 0.3113775849342346
Epoch 4723, Loss: 0.7463622093200684, Final Batch Loss: 0.23644351959228516
Epoch 4724, Loss: 0.7606267333030701, Final Batch Loss: 0.2391050010919571
Epoch 4725, Loss: 0.7234482616186142, Final Batch Loss: 0.2058858722448349
Epoch 4726, Loss: 0.7021554708480835, Final Batch Loss: 0.19174273312091827
Epoch 4727, Loss: 0.8

Epoch 4826, Loss: 0.6537554711103439, Final Batch Loss: 0.14755196869373322
Epoch 4827, Loss: 0.6553096175193787, Final Batch Loss: 0.14792640507221222
Epoch 4828, Loss: 0.7269390970468521, Final Batch Loss: 0.1815422922372818
Epoch 4829, Loss: 0.6711417138576508, Final Batch Loss: 0.1923018991947174
Epoch 4830, Loss: 0.754102349281311, Final Batch Loss: 0.2537227272987366
Epoch 4831, Loss: 0.6906582713127136, Final Batch Loss: 0.1375775933265686
Epoch 4832, Loss: 0.7251473665237427, Final Batch Loss: 0.2782171666622162
Epoch 4833, Loss: 0.6459711790084839, Final Batch Loss: 0.2010246068239212
Epoch 4834, Loss: 0.7085820436477661, Final Batch Loss: 0.26825010776519775
Epoch 4835, Loss: 0.679128959774971, Final Batch Loss: 0.25339028239250183
Epoch 4836, Loss: 0.6646818965673447, Final Batch Loss: 0.14528656005859375
Epoch 4837, Loss: 0.676857978105545, Final Batch Loss: 0.2330850511789322
Epoch 4838, Loss: 0.749723419547081, Final Batch Loss: 0.21671853959560394
Epoch 4839, Loss: 0.669

Epoch 4942, Loss: 0.7496336251497269, Final Batch Loss: 0.26205840706825256
Epoch 4943, Loss: 0.7423306852579117, Final Batch Loss: 0.20664416253566742
Epoch 4944, Loss: 0.7830425947904587, Final Batch Loss: 0.3018244504928589
Epoch 4945, Loss: 0.758674681186676, Final Batch Loss: 0.25853294134140015
Epoch 4946, Loss: 0.8174761235713959, Final Batch Loss: 0.26994240283966064
Epoch 4947, Loss: 0.7215414792299271, Final Batch Loss: 0.19475112855434418
Epoch 4948, Loss: 0.6812148541212082, Final Batch Loss: 0.2039886862039566
Epoch 4949, Loss: 0.6973604559898376, Final Batch Loss: 0.20105914771556854
Epoch 4950, Loss: 0.7070957273244858, Final Batch Loss: 0.22125962376594543
Epoch 4951, Loss: 0.6791283786296844, Final Batch Loss: 0.2526906132698059
Epoch 4952, Loss: 0.7925958633422852, Final Batch Loss: 0.27858489751815796
Epoch 4953, Loss: 0.6533331274986267, Final Batch Loss: 0.2651267945766449
Epoch 4954, Loss: 0.7353804409503937, Final Batch Loss: 0.22510996460914612
Epoch 4955, Loss:

In [9]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  6  0  0  0  0  0  0  0  0  7]
 [ 0  0  0  0  0  0  9  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  5  0  0  0  0  0  1]
 [ 0  1  0  0  0  0  0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  6  0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  3]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        23
           1    0.85714   0.85714   0.85714        14
           2    0.53846   1.00000   0.70000         7
           3    1.00000   0.85714   0.92308         7
        

# Train on Fake Test on Real

In [10]:
# 20,000 epochs DEFAULT PARAMETERS FOR THRESHOLDS

In [11]:
gen = Generator(z_dim = 108)
load_model(gen, "3 Label 5 Subject GAN Ablation_gen.param")
gen.eval()

Generator(
  (gen): Sequential(
    (0): Sequential(
      (0): Linear(in_features=108, out_features=80, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Linear(in_features=80, out_features=60, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (2): Sequential(
      (0): Linear(in_features=60, out_features=50, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (3): Linear(in_features=50, out_features=30, bias=True)
    (4): Tanh()
  )
)

In [25]:
size = len(X_test)
latent_vectors = get_noise(size, 100)
act_vectors = get_act_matrix(size, 3)
usr_vectors = get_usr_matrix(size, 5)

fake_labels = []

for k in range(size):
    if act_vectors[0][k] == 0 and usr_vectors[0][k] == 0:
        fake_labels.append(0)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 0:
        fake_labels.append(1)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 0:
        fake_labels.append(2)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 1:
        fake_labels.append(3)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 1:
        fake_labels.append(4)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 1:
        fake_labels.append(5)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 2:
        fake_labels.append(6)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 2:
        fake_labels.append(7)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 2:
        fake_labels.append(8)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 3:
        fake_labels.append(9)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 3:
        fake_labels.append(10)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 3:
        fake_labels.append(11)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 4:
        fake_labels.append(12)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 4:
        fake_labels.append(13)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 4:
        fake_labels.append(14)
        
fake_labels = np.asarray(fake_labels)
to_gen = torch.cat((latent_vectors, act_vectors[1], usr_vectors[1]), 1)
fake_features = gen(to_gen).detach()
#fake_features = gen(to_gen).detach().numpy()

In [26]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5, zero_division = 0))

[[ 8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0]
 [ 0  7  0  0  1  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 10]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000         8
           1    0.63158   1.00000   0.77419        12
           2    1.00000   1.00000   1.00000        11
           3    1.00000   1.00000   1.00000        13
        