In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '58 tGravityAcc-energy()-Y',
 '59 tGravityAcc-energy()-Z',
 '128 tBodyGyro-mad()-Y',
 '141 tBodyGyro-iqr()-Y',
 '428 fBodyGyro-std()-Y',
 '434 fBodyGyro-max()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '203 tBodyAccMag-mad()',
 '215 tGravityAccMag-std()',
 '216 tGravityAccMag-mad()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '382 fBodyAccJerk-bandsEnergy()-1,8',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 30),
            classifier_block(30, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            nn.Linear(15, 12)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../../saved_models/{model_name}'))

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_10 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_11 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_12 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9) + [9] * len(X_10) + [10] * len(X_11) + [11] * len(X_12)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [1, 3, 5, 7]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [7]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 7.422689199447632, Final Batch Loss: 2.453273057937622
Epoch 2, Loss: 7.370434284210205, Final Batch Loss: 2.406439781188965
Epoch 3, Loss: 7.4301841259002686, Final Batch Loss: 2.477592706680298
Epoch 4, Loss: 7.389699459075928, Final Batch Loss: 2.442140579223633
Epoch 5, Loss: 7.482944965362549, Final Batch Loss: 2.5409023761749268
Epoch 6, Loss: 7.366950750350952, Final Batch Loss: 2.422630786895752
Epoch 7, Loss: 7.390000820159912, Final Batch Loss: 2.4611198902130127
Epoch 8, Loss: 7.3953564167022705, Final Batch Loss: 2.4677884578704834
Epoch 9, Loss: 7.428051710128784, Final Batch Loss: 2.5073204040527344
Epoch 10, Loss: 7.333410739898682, Final Batch Loss: 2.425410509109497
Epoch 11, Loss: 7.342511892318726, Final Batch Loss: 2.442734479904175
Epoch 12, Loss: 7.303533554077148, Final Batch Loss: 2.4173624515533447
Epoch 13, Loss: 7.3596882820129395, Final Batch Loss: 2.481877326965332
Epoch 14, Loss: 7.262422561645508, Final Batch Loss: 2.404369354248047
Epoch 1

Epoch 117, Loss: 3.427583336830139, Final Batch Loss: 1.1823242902755737
Epoch 118, Loss: 3.2597157955169678, Final Batch Loss: 1.063146710395813
Epoch 119, Loss: 3.4876513481140137, Final Batch Loss: 1.3867236375808716
Epoch 120, Loss: 3.2262483835220337, Final Batch Loss: 1.0066908597946167
Epoch 121, Loss: 3.1837856769561768, Final Batch Loss: 1.025815725326538
Epoch 122, Loss: 3.4219497442245483, Final Batch Loss: 1.3123468160629272
Epoch 123, Loss: 3.139937400817871, Final Batch Loss: 0.9784226417541504
Epoch 124, Loss: 3.1385037899017334, Final Batch Loss: 0.9966672658920288
Epoch 125, Loss: 3.267960786819458, Final Batch Loss: 1.139164924621582
Epoch 126, Loss: 3.433777928352356, Final Batch Loss: 1.2146730422973633
Epoch 127, Loss: 3.080708682537079, Final Batch Loss: 0.9566335082054138
Epoch 128, Loss: 3.121229887008667, Final Batch Loss: 1.026881456375122
Epoch 129, Loss: 3.207728147506714, Final Batch Loss: 1.1390676498413086
Epoch 130, Loss: 3.0669084191322327, Final Batch 

Epoch 240, Loss: 2.562880039215088, Final Batch Loss: 0.9492486715316772
Epoch 241, Loss: 2.4186298847198486, Final Batch Loss: 0.7012877464294434
Epoch 242, Loss: 2.501971125602722, Final Batch Loss: 0.9094704985618591
Epoch 243, Loss: 2.660338878631592, Final Batch Loss: 1.071550726890564
Epoch 244, Loss: 2.515383720397949, Final Batch Loss: 0.9008351564407349
Epoch 245, Loss: 2.4574268460273743, Final Batch Loss: 0.7946351170539856
Epoch 246, Loss: 2.9826626777648926, Final Batch Loss: 1.2346558570861816
Epoch 247, Loss: 2.659198820590973, Final Batch Loss: 0.9632810354232788
Epoch 248, Loss: 2.4432127475738525, Final Batch Loss: 0.781440258026123
Epoch 249, Loss: 2.620486855506897, Final Batch Loss: 1.0203454494476318
Epoch 250, Loss: 2.398397982120514, Final Batch Loss: 0.7455203533172607
Epoch 251, Loss: 2.658624231815338, Final Batch Loss: 1.0219988822937012
Epoch 252, Loss: 2.513192296028137, Final Batch Loss: 0.8394344449043274
Epoch 253, Loss: 2.2527737617492676, Final Batch 

Epoch 356, Loss: 2.417973220348358, Final Batch Loss: 1.0592554807662964
Epoch 357, Loss: 2.0828887820243835, Final Batch Loss: 0.7447357177734375
Epoch 358, Loss: 1.9610441327095032, Final Batch Loss: 0.5549768805503845
Epoch 359, Loss: 2.0557820200920105, Final Batch Loss: 0.6312133073806763
Epoch 360, Loss: 2.0889267325401306, Final Batch Loss: 0.6124946475028992
Epoch 361, Loss: 2.090624511241913, Final Batch Loss: 0.688174307346344
Epoch 362, Loss: 2.152690351009369, Final Batch Loss: 0.6995115280151367
Epoch 363, Loss: 1.762330025434494, Final Batch Loss: 0.3550420105457306
Epoch 364, Loss: 2.1940632462501526, Final Batch Loss: 0.8724821209907532
Epoch 365, Loss: 1.9057292342185974, Final Batch Loss: 0.5616421103477478
Epoch 366, Loss: 2.27535480260849, Final Batch Loss: 0.8767470121383667
Epoch 367, Loss: 2.237858235836029, Final Batch Loss: 0.7914186120033264
Epoch 368, Loss: 2.1019963026046753, Final Batch Loss: 0.6712498068809509
Epoch 369, Loss: 1.8404226005077362, Final Bat

Epoch 482, Loss: 2.0395464301109314, Final Batch Loss: 0.7394116520881653
Epoch 483, Loss: 1.8157429099082947, Final Batch Loss: 0.594957172870636
Epoch 484, Loss: 1.8317511081695557, Final Batch Loss: 0.6016479730606079
Epoch 485, Loss: 2.142364203929901, Final Batch Loss: 0.8083497881889343
Epoch 486, Loss: 1.917198657989502, Final Batch Loss: 0.6853881478309631
Epoch 487, Loss: 1.8265911936759949, Final Batch Loss: 0.660183310508728
Epoch 488, Loss: 2.219134509563446, Final Batch Loss: 0.9851030111312866
Epoch 489, Loss: 1.8089088797569275, Final Batch Loss: 0.5741105079650879
Epoch 490, Loss: 1.896019160747528, Final Batch Loss: 0.6555838584899902
Epoch 491, Loss: 2.1121652722358704, Final Batch Loss: 0.9024850726127625
Epoch 492, Loss: 1.6129043996334076, Final Batch Loss: 0.42457345128059387
Epoch 493, Loss: 1.6560169160366058, Final Batch Loss: 0.4028647840023041
Epoch 494, Loss: 2.494306445121765, Final Batch Loss: 1.186206340789795
Epoch 495, Loss: 1.9452713131904602, Final Ba

Epoch 609, Loss: 1.8287878036499023, Final Batch Loss: 0.695806086063385
Epoch 610, Loss: 1.5817356705665588, Final Batch Loss: 0.48889291286468506
Epoch 611, Loss: 1.5323029458522797, Final Batch Loss: 0.3920856714248657
Epoch 612, Loss: 1.9243125915527344, Final Batch Loss: 0.8367767333984375
Epoch 613, Loss: 1.6985580325126648, Final Batch Loss: 0.5478437542915344
Epoch 614, Loss: 1.6969197988510132, Final Batch Loss: 0.6158385872840881
Epoch 615, Loss: 1.7336793839931488, Final Batch Loss: 0.49132201075553894
Epoch 616, Loss: 1.583376407623291, Final Batch Loss: 0.47017186880111694
Epoch 617, Loss: 1.4979506731033325, Final Batch Loss: 0.2823983430862427
Epoch 618, Loss: 1.5014329552650452, Final Batch Loss: 0.43215978145599365
Epoch 619, Loss: 1.5380346179008484, Final Batch Loss: 0.4023205637931824
Epoch 620, Loss: 1.336203157901764, Final Batch Loss: 0.23602449893951416
Epoch 621, Loss: 1.582093894481659, Final Batch Loss: 0.4903782308101654
Epoch 622, Loss: 1.7185442447662354, 

Epoch 730, Loss: 1.694777399301529, Final Batch Loss: 0.6352721452713013
Epoch 731, Loss: 1.555340439081192, Final Batch Loss: 0.5500826239585876
Epoch 732, Loss: 1.6515734791755676, Final Batch Loss: 0.6226084232330322
Epoch 733, Loss: 1.5145678222179413, Final Batch Loss: 0.45839396119117737
Epoch 734, Loss: 1.3041505217552185, Final Batch Loss: 0.3309305012226105
Epoch 735, Loss: 1.6241253018379211, Final Batch Loss: 0.5774451494216919
Epoch 736, Loss: 1.6061492562294006, Final Batch Loss: 0.4497816562652588
Epoch 737, Loss: 1.49633127450943, Final Batch Loss: 0.4707714319229126
Epoch 738, Loss: 1.2911200821399689, Final Batch Loss: 0.33358508348464966
Epoch 739, Loss: 1.8983872532844543, Final Batch Loss: 0.891606867313385
Epoch 740, Loss: 1.493775486946106, Final Batch Loss: 0.45789995789527893
Epoch 741, Loss: 1.6515634059906006, Final Batch Loss: 0.6569679379463196
Epoch 742, Loss: 1.3964650630950928, Final Batch Loss: 0.3763352334499359
Epoch 743, Loss: 1.6358415484428406, Fina

Epoch 858, Loss: 1.3720582723617554, Final Batch Loss: 0.3816010653972626
Epoch 859, Loss: 1.4727087020874023, Final Batch Loss: 0.5346220135688782
Epoch 860, Loss: 1.8544379472732544, Final Batch Loss: 0.9150375723838806
Epoch 861, Loss: 1.61845064163208, Final Batch Loss: 0.6637498736381531
Epoch 862, Loss: 1.4439089000225067, Final Batch Loss: 0.466403603553772
Epoch 863, Loss: 1.5414122641086578, Final Batch Loss: 0.5631377696990967
Epoch 864, Loss: 1.3867526352405548, Final Batch Loss: 0.3687504529953003
Epoch 865, Loss: 1.7593646943569183, Final Batch Loss: 0.7563484311103821
Epoch 866, Loss: 1.4595817923545837, Final Batch Loss: 0.5122589468955994
Epoch 867, Loss: 1.3742220997810364, Final Batch Loss: 0.3739510476589203
Epoch 868, Loss: 1.390528380870819, Final Batch Loss: 0.44268807768821716
Epoch 869, Loss: 1.317745327949524, Final Batch Loss: 0.38086092472076416
Epoch 870, Loss: 1.4070000052452087, Final Batch Loss: 0.47470414638519287
Epoch 871, Loss: 1.328448325395584, Fina

Epoch 973, Loss: 1.392437607049942, Final Batch Loss: 0.5332587957382202
Epoch 974, Loss: 1.3357490599155426, Final Batch Loss: 0.43150606751441956
Epoch 975, Loss: 1.3109604120254517, Final Batch Loss: 0.467013955116272
Epoch 976, Loss: 1.7304259538650513, Final Batch Loss: 0.8549128174781799
Epoch 977, Loss: 1.3499277532100677, Final Batch Loss: 0.4616186320781708
Epoch 978, Loss: 1.2345487177371979, Final Batch Loss: 0.338696151971817
Epoch 979, Loss: 1.4261857867240906, Final Batch Loss: 0.5615670084953308
Epoch 980, Loss: 1.2051132321357727, Final Batch Loss: 0.2888028621673584
Epoch 981, Loss: 1.4877110421657562, Final Batch Loss: 0.5977770090103149
Epoch 982, Loss: 1.527113139629364, Final Batch Loss: 0.5952335596084595
Epoch 983, Loss: 1.3453243970870972, Final Batch Loss: 0.4978675842285156
Epoch 984, Loss: 1.3012065589427948, Final Batch Loss: 0.3713393807411194
Epoch 985, Loss: 1.3842520713806152, Final Batch Loss: 0.451695054769516
Epoch 986, Loss: 1.2956447005271912, Final

Epoch 1093, Loss: 1.3526756763458252, Final Batch Loss: 0.5256412625312805
Epoch 1094, Loss: 1.1642618477344513, Final Batch Loss: 0.382880836725235
Epoch 1095, Loss: 1.2718059420585632, Final Batch Loss: 0.3897516131401062
Epoch 1096, Loss: 1.2866661846637726, Final Batch Loss: 0.42108213901519775
Epoch 1097, Loss: 1.577552080154419, Final Batch Loss: 0.692218005657196
Epoch 1098, Loss: 1.0949735790491104, Final Batch Loss: 0.20314355194568634
Epoch 1099, Loss: 1.2216786444187164, Final Batch Loss: 0.38353976607322693
Epoch 1100, Loss: 1.3228722214698792, Final Batch Loss: 0.47072944045066833
Epoch 1101, Loss: 1.1646257638931274, Final Batch Loss: 0.3199082612991333
Epoch 1102, Loss: 1.3542966842651367, Final Batch Loss: 0.4640105962753296
Epoch 1103, Loss: 1.0792827010154724, Final Batch Loss: 0.23732507228851318
Epoch 1104, Loss: 1.3085879385471344, Final Batch Loss: 0.48297208547592163
Epoch 1105, Loss: 1.340076357126236, Final Batch Loss: 0.4422571659088135
Epoch 1106, Loss: 1.054

Epoch 1216, Loss: 1.0681704878807068, Final Batch Loss: 0.33621180057525635
Epoch 1217, Loss: 1.3925766944885254, Final Batch Loss: 0.5990433692932129
Epoch 1218, Loss: 1.0765989422798157, Final Batch Loss: 0.3019552230834961
Epoch 1219, Loss: 0.987938866019249, Final Batch Loss: 0.20452041923999786
Epoch 1220, Loss: 1.5122277438640594, Final Batch Loss: 0.7350663542747498
Epoch 1221, Loss: 0.9425078630447388, Final Batch Loss: 0.13402163982391357
Epoch 1222, Loss: 0.9957105070352554, Final Batch Loss: 0.21748186647891998
Epoch 1223, Loss: 1.1794600188732147, Final Batch Loss: 0.4242400527000427
Epoch 1224, Loss: 1.047179251909256, Final Batch Loss: 0.22906622290611267
Epoch 1225, Loss: 1.1269286572933197, Final Batch Loss: 0.29632532596588135
Epoch 1226, Loss: 1.0290557742118835, Final Batch Loss: 0.23467448353767395
Epoch 1227, Loss: 1.2117841243743896, Final Batch Loss: 0.3262616991996765
Epoch 1228, Loss: 1.3011020720005035, Final Batch Loss: 0.4512155055999756
Epoch 1229, Loss: 0.

Epoch 1331, Loss: 1.2738195061683655, Final Batch Loss: 0.47872963547706604
Epoch 1332, Loss: 1.0693891942501068, Final Batch Loss: 0.2943528890609741
Epoch 1333, Loss: 1.1963447630405426, Final Batch Loss: 0.3185635507106781
Epoch 1334, Loss: 1.6331431865692139, Final Batch Loss: 0.7615149617195129
Epoch 1335, Loss: 1.2513432800769806, Final Batch Loss: 0.47016850113868713
Epoch 1336, Loss: 1.0798958837985992, Final Batch Loss: 0.3680954575538635
Epoch 1337, Loss: 1.0685139894485474, Final Batch Loss: 0.31274643540382385
Epoch 1338, Loss: 1.0409567952156067, Final Batch Loss: 0.33614248037338257
Epoch 1339, Loss: 1.089699000120163, Final Batch Loss: 0.38196054100990295
Epoch 1340, Loss: 1.1499045193195343, Final Batch Loss: 0.3685295283794403
Epoch 1341, Loss: 1.3167625665664673, Final Batch Loss: 0.530657947063446
Epoch 1342, Loss: 1.1613947749137878, Final Batch Loss: 0.3159635365009308
Epoch 1343, Loss: 1.1287380158901215, Final Batch Loss: 0.3915284276008606
Epoch 1344, Loss: 1.15

Epoch 1445, Loss: 1.2099372744560242, Final Batch Loss: 0.47181758284568787
Epoch 1446, Loss: 1.106144279241562, Final Batch Loss: 0.3937988579273224
Epoch 1447, Loss: 0.9557680189609528, Final Batch Loss: 0.2788529098033905
Epoch 1448, Loss: 1.2117484211921692, Final Batch Loss: 0.46225032210350037
Epoch 1449, Loss: 0.9584963023662567, Final Batch Loss: 0.23817726969718933
Epoch 1450, Loss: 1.0704030096530914, Final Batch Loss: 0.39451390504837036
Epoch 1451, Loss: 1.1887764930725098, Final Batch Loss: 0.5106542110443115
Epoch 1452, Loss: 1.1955238580703735, Final Batch Loss: 0.4292105734348297
Epoch 1453, Loss: 1.3840665817260742, Final Batch Loss: 0.6767339706420898
Epoch 1454, Loss: 1.0888154804706573, Final Batch Loss: 0.37336161732673645
Epoch 1455, Loss: 1.0281042456626892, Final Batch Loss: 0.2862199544906616
Epoch 1456, Loss: 1.1200893819332123, Final Batch Loss: 0.37529635429382324
Epoch 1457, Loss: 0.8854223638772964, Final Batch Loss: 0.13135500252246857
Epoch 1458, Loss: 1

Epoch 1566, Loss: 0.9627597332000732, Final Batch Loss: 0.290617436170578
Epoch 1567, Loss: 0.9286808669567108, Final Batch Loss: 0.22432386875152588
Epoch 1568, Loss: 1.1311730742454529, Final Batch Loss: 0.42229196429252625
Epoch 1569, Loss: 0.9608745276927948, Final Batch Loss: 0.2505853474140167
Epoch 1570, Loss: 1.1316436231136322, Final Batch Loss: 0.42654454708099365
Epoch 1571, Loss: 0.8885337114334106, Final Batch Loss: 0.13815072178840637
Epoch 1572, Loss: 1.082023411989212, Final Batch Loss: 0.352032870054245
Epoch 1573, Loss: 0.9478677809238434, Final Batch Loss: 0.2814532220363617
Epoch 1574, Loss: 1.2804005146026611, Final Batch Loss: 0.6003075242042542
Epoch 1575, Loss: 0.9347040951251984, Final Batch Loss: 0.2615073323249817
Epoch 1576, Loss: 0.9492952674627304, Final Batch Loss: 0.16144908964633942
Epoch 1577, Loss: 1.186224102973938, Final Batch Loss: 0.4264138340950012
Epoch 1578, Loss: 1.1124165654182434, Final Batch Loss: 0.3713228702545166
Epoch 1579, Loss: 1.1654

Epoch 1687, Loss: 0.7732294201850891, Final Batch Loss: 0.10692530870437622
Epoch 1688, Loss: 1.0276593565940857, Final Batch Loss: 0.37743058800697327
Epoch 1689, Loss: 0.850088819861412, Final Batch Loss: 0.18218432366847992
Epoch 1690, Loss: 0.991087019443512, Final Batch Loss: 0.38724520802497864
Epoch 1691, Loss: 0.8439629822969437, Final Batch Loss: 0.2166949361562729
Epoch 1692, Loss: 1.451501339673996, Final Batch Loss: 0.7520284056663513
Epoch 1693, Loss: 1.1613578796386719, Final Batch Loss: 0.5151432752609253
Epoch 1694, Loss: 0.9221366345882416, Final Batch Loss: 0.26660335063934326
Epoch 1695, Loss: 1.1842636466026306, Final Batch Loss: 0.4415683150291443
Epoch 1696, Loss: 0.982129842042923, Final Batch Loss: 0.32333096861839294
Epoch 1697, Loss: 0.923810675740242, Final Batch Loss: 0.23616380989551544
Epoch 1698, Loss: 1.0877989530563354, Final Batch Loss: 0.39963752031326294
Epoch 1699, Loss: 0.90269535779953, Final Batch Loss: 0.2162226140499115
Epoch 1700, Loss: 0.9029

Epoch 1801, Loss: 1.05596524477005, Final Batch Loss: 0.3878587484359741
Epoch 1802, Loss: 0.9640121757984161, Final Batch Loss: 0.3263091742992401
Epoch 1803, Loss: 0.8253568112850189, Final Batch Loss: 0.15159016847610474
Epoch 1804, Loss: 0.8898563534021378, Final Batch Loss: 0.2040795534849167
Epoch 1805, Loss: 0.9433812499046326, Final Batch Loss: 0.3009551763534546
Epoch 1806, Loss: 0.8834883868694305, Final Batch Loss: 0.27261030673980713
Epoch 1807, Loss: 0.8754012733697891, Final Batch Loss: 0.22507022321224213
Epoch 1808, Loss: 1.1540248095989227, Final Batch Loss: 0.5374440550804138
Epoch 1809, Loss: 0.9875480532646179, Final Batch Loss: 0.3298966884613037
Epoch 1810, Loss: 0.9165343940258026, Final Batch Loss: 0.26173630356788635
Epoch 1811, Loss: 0.8819365054368973, Final Batch Loss: 0.216328427195549
Epoch 1812, Loss: 0.8774794787168503, Final Batch Loss: 0.1776166707277298
Epoch 1813, Loss: 0.8074603974819183, Final Batch Loss: 0.15578266978263855
Epoch 1814, Loss: 0.866

Epoch 1917, Loss: 1.2281290292739868, Final Batch Loss: 0.5346934795379639
Epoch 1918, Loss: 0.9459481239318848, Final Batch Loss: 0.28031986951828003
Epoch 1919, Loss: 0.7907997369766235, Final Batch Loss: 0.17806032299995422
Epoch 1920, Loss: 0.9471690058708191, Final Batch Loss: 0.3344317078590393
Epoch 1921, Loss: 0.941701740026474, Final Batch Loss: 0.3063453733921051
Epoch 1922, Loss: 1.2277179062366486, Final Batch Loss: 0.6009487509727478
Epoch 1923, Loss: 0.9642324447631836, Final Batch Loss: 0.3270839750766754
Epoch 1924, Loss: 1.0113311409950256, Final Batch Loss: 0.3862890601158142
Epoch 1925, Loss: 0.9882045090198517, Final Batch Loss: 0.2668260633945465
Epoch 1926, Loss: 0.8426689505577087, Final Batch Loss: 0.25129225850105286
Epoch 1927, Loss: 1.3768118619918823, Final Batch Loss: 0.6781738996505737
Epoch 1928, Loss: 1.1720945239067078, Final Batch Loss: 0.5629417896270752
Epoch 1929, Loss: 0.8641682863235474, Final Batch Loss: 0.26915231347084045
Epoch 1930, Loss: 1.06

Epoch 2032, Loss: 0.7416348531842232, Final Batch Loss: 0.11695531755685806
Epoch 2033, Loss: 0.9067796915769577, Final Batch Loss: 0.24539496004581451
Epoch 2034, Loss: 0.847419798374176, Final Batch Loss: 0.25690945982933044
Epoch 2035, Loss: 0.9602262675762177, Final Batch Loss: 0.3845573365688324
Epoch 2036, Loss: 1.0505026280879974, Final Batch Loss: 0.4036780595779419
Epoch 2037, Loss: 1.0237575471401215, Final Batch Loss: 0.37652453780174255
Epoch 2038, Loss: 1.0609375834465027, Final Batch Loss: 0.5039337277412415
Epoch 2039, Loss: 0.9459520578384399, Final Batch Loss: 0.3483413755893707
Epoch 2040, Loss: 0.7322703450918198, Final Batch Loss: 0.13510529696941376
Epoch 2041, Loss: 0.7054150700569153, Final Batch Loss: 0.11261296272277832
Epoch 2042, Loss: 0.8793597519397736, Final Batch Loss: 0.27489185333251953
Epoch 2043, Loss: 1.0635656118392944, Final Batch Loss: 0.47109824419021606
Epoch 2044, Loss: 0.9637636244297028, Final Batch Loss: 0.3976792097091675
Epoch 2045, Loss: 

Epoch 2145, Loss: 0.9974685609340668, Final Batch Loss: 0.42198923230171204
Epoch 2146, Loss: 0.739850252866745, Final Batch Loss: 0.16012537479400635
Epoch 2147, Loss: 0.944758951663971, Final Batch Loss: 0.35085147619247437
Epoch 2148, Loss: 0.9487298727035522, Final Batch Loss: 0.32078179717063904
Epoch 2149, Loss: 0.8647662252187729, Final Batch Loss: 0.21182690560817719
Epoch 2150, Loss: 0.7595887184143066, Final Batch Loss: 0.19066989421844482
Epoch 2151, Loss: 1.010737955570221, Final Batch Loss: 0.45977166295051575
Epoch 2152, Loss: 0.9052415192127228, Final Batch Loss: 0.3118046522140503
Epoch 2153, Loss: 0.8887728452682495, Final Batch Loss: 0.2959557771682739
Epoch 2154, Loss: 0.7849022299051285, Final Batch Loss: 0.16722674667835236
Epoch 2155, Loss: 0.7757783532142639, Final Batch Loss: 0.15939971804618835
Epoch 2156, Loss: 0.9797258079051971, Final Batch Loss: 0.4063040018081665
Epoch 2157, Loss: 0.952793151140213, Final Batch Loss: 0.3376120328903198
Epoch 2158, Loss: 0.

Epoch 2257, Loss: 1.0319987535476685, Final Batch Loss: 0.4569546580314636
Epoch 2258, Loss: 1.0589493811130524, Final Batch Loss: 0.4721473753452301
Epoch 2259, Loss: 0.8102450370788574, Final Batch Loss: 0.2718690037727356
Epoch 2260, Loss: 0.8628058433532715, Final Batch Loss: 0.26371803879737854
Epoch 2261, Loss: 0.7704997211694717, Final Batch Loss: 0.1695406287908554
Epoch 2262, Loss: 0.9514076113700867, Final Batch Loss: 0.3061883747577667
Epoch 2263, Loss: 0.7470815032720566, Final Batch Loss: 0.18373803794384003
Epoch 2264, Loss: 0.786045253276825, Final Batch Loss: 0.2396688461303711
Epoch 2265, Loss: 0.8500897288322449, Final Batch Loss: 0.269037127494812
Epoch 2266, Loss: 0.8525951951742172, Final Batch Loss: 0.2253766506910324
Epoch 2267, Loss: 0.8780461251735687, Final Batch Loss: 0.26215192675590515
Epoch 2268, Loss: 0.8541928827762604, Final Batch Loss: 0.2760196626186371
Epoch 2269, Loss: 0.9187756478786469, Final Batch Loss: 0.3132021129131317
Epoch 2270, Loss: 0.6936

Epoch 2377, Loss: 0.9601881504058838, Final Batch Loss: 0.3894157409667969
Epoch 2378, Loss: 0.6236057057976723, Final Batch Loss: 0.07852957397699356
Epoch 2379, Loss: 1.0260955393314362, Final Batch Loss: 0.45207875967025757
Epoch 2380, Loss: 0.7502815276384354, Final Batch Loss: 0.1845868080854416
Epoch 2381, Loss: 0.7401277720928192, Final Batch Loss: 0.19586560130119324
Epoch 2382, Loss: 0.7274559140205383, Final Batch Loss: 0.18131577968597412
Epoch 2383, Loss: 0.8478991687297821, Final Batch Loss: 0.3102954924106598
Epoch 2384, Loss: 0.6701523661613464, Final Batch Loss: 0.1270710825920105
Epoch 2385, Loss: 0.7667701989412308, Final Batch Loss: 0.2605864703655243
Epoch 2386, Loss: 0.6734203994274139, Final Batch Loss: 0.15570394694805145
Epoch 2387, Loss: 0.7308508306741714, Final Batch Loss: 0.15969626605510712
Epoch 2388, Loss: 1.223045974969864, Final Batch Loss: 0.6921496987342834
Epoch 2389, Loss: 0.7468398213386536, Final Batch Loss: 0.1810131072998047
Epoch 2390, Loss: 1.

Epoch 2485, Loss: 0.9337812960147858, Final Batch Loss: 0.40475544333457947
Epoch 2486, Loss: 0.6497778296470642, Final Batch Loss: 0.09652534127235413
Epoch 2487, Loss: 0.7570880502462387, Final Batch Loss: 0.22074882686138153
Epoch 2488, Loss: 0.8462866097688675, Final Batch Loss: 0.3139362931251526
Epoch 2489, Loss: 0.9142958372831345, Final Batch Loss: 0.37778958678245544
Epoch 2490, Loss: 1.139790117740631, Final Batch Loss: 0.5804517865180969
Epoch 2491, Loss: 0.7080845832824707, Final Batch Loss: 0.1755635142326355
Epoch 2492, Loss: 0.8430342823266983, Final Batch Loss: 0.24844275414943695
Epoch 2493, Loss: 0.8399590402841568, Final Batch Loss: 0.3159138560295105
Epoch 2494, Loss: 0.9812595844268799, Final Batch Loss: 0.4363543391227722
Epoch 2495, Loss: 0.7392563968896866, Final Batch Loss: 0.15719299018383026
Epoch 2496, Loss: 0.715187780559063, Final Batch Loss: 0.11442448943853378
Epoch 2497, Loss: 0.9120749831199646, Final Batch Loss: 0.4016665816307068
Epoch 2498, Loss: 0.

Epoch 2597, Loss: 0.9298948347568512, Final Batch Loss: 0.2909964323043823
Epoch 2598, Loss: 0.6426554843783379, Final Batch Loss: 0.07798456400632858
Epoch 2599, Loss: 0.9679620862007141, Final Batch Loss: 0.38801252841949463
Epoch 2600, Loss: 0.9126489460468292, Final Batch Loss: 0.3384473919868469
Epoch 2601, Loss: 0.7949886620044708, Final Batch Loss: 0.27570411562919617
Epoch 2602, Loss: 0.8485422134399414, Final Batch Loss: 0.31101545691490173
Epoch 2603, Loss: 0.9422129392623901, Final Batch Loss: 0.39352554082870483
Epoch 2604, Loss: 0.8523370325565338, Final Batch Loss: 0.2761760950088501
Epoch 2605, Loss: 0.9912893772125244, Final Batch Loss: 0.4793933629989624
Epoch 2606, Loss: 0.7043931484222412, Final Batch Loss: 0.13383041322231293
Epoch 2607, Loss: 0.7227675914764404, Final Batch Loss: 0.15976554155349731
Epoch 2608, Loss: 1.0138535797595978, Final Batch Loss: 0.39945805072784424
Epoch 2609, Loss: 0.8437491953372955, Final Batch Loss: 0.26101863384246826
Epoch 2610, Loss

Epoch 2708, Loss: 0.8477887064218521, Final Batch Loss: 0.28388792276382446
Epoch 2709, Loss: 0.6872921288013458, Final Batch Loss: 0.1621076762676239
Epoch 2710, Loss: 0.608237199485302, Final Batch Loss: 0.095326729118824
Epoch 2711, Loss: 0.6845372468233109, Final Batch Loss: 0.15888479351997375
Epoch 2712, Loss: 0.8437630236148834, Final Batch Loss: 0.3838143050670624
Epoch 2713, Loss: 0.7528433501720428, Final Batch Loss: 0.2561448812484741
Epoch 2714, Loss: 0.8860292434692383, Final Batch Loss: 0.34612393379211426
Epoch 2715, Loss: 0.9420123845338821, Final Batch Loss: 0.41443559527397156
Epoch 2716, Loss: 0.7735491096973419, Final Batch Loss: 0.23492205142974854
Epoch 2717, Loss: 0.8738665282726288, Final Batch Loss: 0.2880353629589081
Epoch 2718, Loss: 0.7845214307308197, Final Batch Loss: 0.2179279625415802
Epoch 2719, Loss: 1.0261109471321106, Final Batch Loss: 0.5092740058898926
Epoch 2720, Loss: 0.7533542513847351, Final Batch Loss: 0.28171247243881226
Epoch 2721, Loss: 0.8

Epoch 2833, Loss: 0.9287681877613068, Final Batch Loss: 0.3862733244895935
Epoch 2834, Loss: 0.8507439643144608, Final Batch Loss: 0.3537543714046478
Epoch 2835, Loss: 0.6937018185853958, Final Batch Loss: 0.20076048374176025
Epoch 2836, Loss: 0.7669223845005035, Final Batch Loss: 0.3009271025657654
Epoch 2837, Loss: 0.6583608090877533, Final Batch Loss: 0.13887619972229004
Epoch 2838, Loss: 0.7172626107931137, Final Batch Loss: 0.18707652390003204
Epoch 2839, Loss: 0.7732512503862381, Final Batch Loss: 0.23916567862033844
Epoch 2840, Loss: 0.553801141679287, Final Batch Loss: 0.0815945640206337
Epoch 2841, Loss: 0.76362045109272, Final Batch Loss: 0.2732555866241455
Epoch 2842, Loss: 0.9263963401317596, Final Batch Loss: 0.41328340768814087
Epoch 2843, Loss: 0.749264732003212, Final Batch Loss: 0.23197464644908905
Epoch 2844, Loss: 1.1020135879516602, Final Batch Loss: 0.5554952025413513
Epoch 2845, Loss: 0.7339865416288376, Final Batch Loss: 0.2056828737258911
Epoch 2846, Loss: 0.601

Epoch 2944, Loss: 0.6471660137176514, Final Batch Loss: 0.1899459809064865
Epoch 2945, Loss: 0.5217247381806374, Final Batch Loss: 0.09137629717588425
Epoch 2946, Loss: 0.6053086817264557, Final Batch Loss: 0.18631677329540253
Epoch 2947, Loss: 0.5897066667675972, Final Batch Loss: 0.11591539531946182
Epoch 2948, Loss: 0.6436981856822968, Final Batch Loss: 0.17956972122192383
Epoch 2949, Loss: 0.5861302763223648, Final Batch Loss: 0.12278462946414948
Epoch 2950, Loss: 0.6763617247343063, Final Batch Loss: 0.21795383095741272
Epoch 2951, Loss: 0.7009316235780716, Final Batch Loss: 0.14776483178138733
Epoch 2952, Loss: 0.6953108012676239, Final Batch Loss: 0.21260635554790497
Epoch 2953, Loss: 0.7135293930768967, Final Batch Loss: 0.16724614799022675
Epoch 2954, Loss: 0.5792003497481346, Final Batch Loss: 0.09401381760835648
Epoch 2955, Loss: 0.6675508618354797, Final Batch Loss: 0.14778101444244385
Epoch 2956, Loss: 0.7100517302751541, Final Batch Loss: 0.24431584775447845
Epoch 2957, L

Epoch 3055, Loss: 0.660769060254097, Final Batch Loss: 0.20015698671340942
Epoch 3056, Loss: 0.6135800369083881, Final Batch Loss: 0.04849282279610634
Epoch 3057, Loss: 0.9309100657701492, Final Batch Loss: 0.43636584281921387
Epoch 3058, Loss: 0.524211797863245, Final Batch Loss: 0.043631527572870255
Epoch 3059, Loss: 0.7533138990402222, Final Batch Loss: 0.21818512678146362
Epoch 3060, Loss: 0.8639485836029053, Final Batch Loss: 0.3199869692325592
Epoch 3061, Loss: 0.6099942773580551, Final Batch Loss: 0.145844504237175
Epoch 3062, Loss: 0.7166680246591568, Final Batch Loss: 0.27573370933532715
Epoch 3063, Loss: 0.7529661655426025, Final Batch Loss: 0.30958718061447144
Epoch 3064, Loss: 0.7393391728401184, Final Batch Loss: 0.2875728905200958
Epoch 3065, Loss: 0.8459282219409943, Final Batch Loss: 0.3284030258655548
Epoch 3066, Loss: 0.661082997918129, Final Batch Loss: 0.23449769616127014
Epoch 3067, Loss: 0.6543296724557877, Final Batch Loss: 0.17601358890533447
Epoch 3068, Loss: 0

Epoch 3163, Loss: 0.6230103820562363, Final Batch Loss: 0.14540725946426392
Epoch 3164, Loss: 0.7550758123397827, Final Batch Loss: 0.2765933573246002
Epoch 3165, Loss: 1.071160152554512, Final Batch Loss: 0.6304405331611633
Epoch 3166, Loss: 0.774979829788208, Final Batch Loss: 0.32571008801460266
Epoch 3167, Loss: 0.5406152382493019, Final Batch Loss: 0.1046086773276329
Epoch 3168, Loss: 0.866615504026413, Final Batch Loss: 0.3996071219444275
Epoch 3169, Loss: 0.8211440145969391, Final Batch Loss: 0.38675910234451294
Epoch 3170, Loss: 0.8520037233829498, Final Batch Loss: 0.3206358551979065
Epoch 3171, Loss: 0.7431668490171432, Final Batch Loss: 0.23666521906852722
Epoch 3172, Loss: 0.6912553012371063, Final Batch Loss: 0.16499854624271393
Epoch 3173, Loss: 0.8764523267745972, Final Batch Loss: 0.32214781641960144
Epoch 3174, Loss: 0.7472219318151474, Final Batch Loss: 0.1873370260000229
Epoch 3175, Loss: 0.8050597012042999, Final Batch Loss: 0.32704874873161316
Epoch 3176, Loss: 0.6

Epoch 3271, Loss: 0.6126794219017029, Final Batch Loss: 0.10928486287593842
Epoch 3272, Loss: 0.6743216663599014, Final Batch Loss: 0.1700499802827835
Epoch 3273, Loss: 0.8569033294916153, Final Batch Loss: 0.3245680332183838
Epoch 3274, Loss: 0.7810442745685577, Final Batch Loss: 0.27120253443717957
Epoch 3275, Loss: 0.6677267998456955, Final Batch Loss: 0.21240659058094025
Epoch 3276, Loss: 0.6148251742124557, Final Batch Loss: 0.17413325607776642
Epoch 3277, Loss: 0.831088125705719, Final Batch Loss: 0.38033896684646606
Epoch 3278, Loss: 0.7361233234405518, Final Batch Loss: 0.31482556462287903
Epoch 3279, Loss: 0.6666934192180634, Final Batch Loss: 0.12015527486801147
Epoch 3280, Loss: 0.6559696644544601, Final Batch Loss: 0.17265014350414276
Epoch 3281, Loss: 0.7740879654884338, Final Batch Loss: 0.2799989879131317
Epoch 3282, Loss: 0.7624441981315613, Final Batch Loss: 0.31951460242271423
Epoch 3283, Loss: 0.9228871464729309, Final Batch Loss: 0.42979928851127625
Epoch 3284, Loss

Epoch 3391, Loss: 0.7273141890764236, Final Batch Loss: 0.2776334285736084
Epoch 3392, Loss: 0.5343258380889893, Final Batch Loss: 0.10829775035381317
Epoch 3393, Loss: 0.685840517282486, Final Batch Loss: 0.19728848338127136
Epoch 3394, Loss: 0.6909281760454178, Final Batch Loss: 0.1509065181016922
Epoch 3395, Loss: 0.5276487097144127, Final Batch Loss: 0.10299880057573318
Epoch 3396, Loss: 1.1938514858484268, Final Batch Loss: 0.7374523282051086
Epoch 3397, Loss: 0.5218183770775795, Final Batch Loss: 0.09640791267156601
Epoch 3398, Loss: 0.7270016819238663, Final Batch Loss: 0.28835415840148926
Epoch 3399, Loss: 0.47969263792037964, Final Batch Loss: 0.07184180617332458
Epoch 3400, Loss: 0.7389297932386398, Final Batch Loss: 0.27989280223846436
Epoch 3401, Loss: 0.7216029018163681, Final Batch Loss: 0.2580735683441162
Epoch 3402, Loss: 0.5992400348186493, Final Batch Loss: 0.21314093470573425
Epoch 3403, Loss: 0.9829446524381638, Final Batch Loss: 0.5763228535652161
Epoch 3404, Loss:

Epoch 3515, Loss: 0.6334947347640991, Final Batch Loss: 0.1919092833995819
Epoch 3516, Loss: 0.5801272243261337, Final Batch Loss: 0.12687267363071442
Epoch 3517, Loss: 0.6584372073411942, Final Batch Loss: 0.20680689811706543
Epoch 3518, Loss: 0.56999871134758, Final Batch Loss: 0.1428692638874054
Epoch 3519, Loss: 0.5099009945988655, Final Batch Loss: 0.08815563470125198
Epoch 3520, Loss: 0.636659637093544, Final Batch Loss: 0.23504477739334106
Epoch 3521, Loss: 0.7132102996110916, Final Batch Loss: 0.36421918869018555
Epoch 3522, Loss: 0.7498257160186768, Final Batch Loss: 0.31156912446022034
Epoch 3523, Loss: 0.6076898574829102, Final Batch Loss: 0.17484575510025024
Epoch 3524, Loss: 0.6607834547758102, Final Batch Loss: 0.24310210347175598
Epoch 3525, Loss: 0.556758638471365, Final Batch Loss: 0.04246861860156059
Epoch 3526, Loss: 0.6847429126501083, Final Batch Loss: 0.28089460730552673
Epoch 3527, Loss: 0.42303016409277916, Final Batch Loss: 0.05707274004817009
Epoch 3528, Loss:

Epoch 3638, Loss: 0.6323171705007553, Final Batch Loss: 0.2363683581352234
Epoch 3639, Loss: 0.4947893023490906, Final Batch Loss: 0.06583411991596222
Epoch 3640, Loss: 0.5455367118120193, Final Batch Loss: 0.14285410940647125
Epoch 3641, Loss: 0.7591498643159866, Final Batch Loss: 0.33996716141700745
Epoch 3642, Loss: 0.6024216860532761, Final Batch Loss: 0.18641912937164307
Epoch 3643, Loss: 0.8239225596189499, Final Batch Loss: 0.37876057624816895
Epoch 3644, Loss: 0.5082992389798164, Final Batch Loss: 0.12222295254468918
Epoch 3645, Loss: 0.8237922936677933, Final Batch Loss: 0.38328877091407776
Epoch 3646, Loss: 0.7177295982837677, Final Batch Loss: 0.27759966254234314
Epoch 3647, Loss: 0.5404985323548317, Final Batch Loss: 0.11438383907079697
Epoch 3648, Loss: 0.7393160164356232, Final Batch Loss: 0.25843939185142517
Epoch 3649, Loss: 0.7247281819581985, Final Batch Loss: 0.29294854402542114
Epoch 3650, Loss: 0.9814387857913971, Final Batch Loss: 0.5842571258544922
Epoch 3651, Lo

Epoch 3752, Loss: 0.6923379451036453, Final Batch Loss: 0.20058666169643402
Epoch 3753, Loss: 0.7249422967433929, Final Batch Loss: 0.2598116397857666
Epoch 3754, Loss: 0.625459760427475, Final Batch Loss: 0.23094713687896729
Epoch 3755, Loss: 0.6886528134346008, Final Batch Loss: 0.2102406769990921
Epoch 3756, Loss: 0.4399659959599376, Final Batch Loss: 0.00939312856644392
Epoch 3757, Loss: 0.600243091583252, Final Batch Loss: 0.196633443236351
Epoch 3758, Loss: 0.6513105183839798, Final Batch Loss: 0.27189159393310547
Epoch 3759, Loss: 0.8290119171142578, Final Batch Loss: 0.37486472725868225
Epoch 3760, Loss: 0.7363111972808838, Final Batch Loss: 0.2987806797027588
Epoch 3761, Loss: 0.7186335176229477, Final Batch Loss: 0.32809343934059143
Epoch 3762, Loss: 0.7044022232294083, Final Batch Loss: 0.3076882064342499
Epoch 3763, Loss: 0.7282009273767471, Final Batch Loss: 0.3156180679798126
Epoch 3764, Loss: 0.6181520074605942, Final Batch Loss: 0.2637532949447632
Epoch 3765, Loss: 0.67

Epoch 3872, Loss: 0.6599958539009094, Final Batch Loss: 0.2797502279281616
Epoch 3873, Loss: 0.648091584444046, Final Batch Loss: 0.23762306571006775
Epoch 3874, Loss: 0.49113326519727707, Final Batch Loss: 0.12227324396371841
Epoch 3875, Loss: 0.4795845001935959, Final Batch Loss: 0.08014334738254547
Epoch 3876, Loss: 0.5382847040891647, Final Batch Loss: 0.16012167930603027
Epoch 3877, Loss: 0.6338130086660385, Final Batch Loss: 0.20212037861347198
Epoch 3878, Loss: 0.6727354228496552, Final Batch Loss: 0.26161471009254456
Epoch 3879, Loss: 0.5602077543735504, Final Batch Loss: 0.1358221024274826
Epoch 3880, Loss: 0.6175319105386734, Final Batch Loss: 0.20092922449111938
Epoch 3881, Loss: 0.8479123115539551, Final Batch Loss: 0.3982731103897095
Epoch 3882, Loss: 0.6454980224370956, Final Batch Loss: 0.27149051427841187
Epoch 3883, Loss: 0.5297483280301094, Final Batch Loss: 0.09420482069253922
Epoch 3884, Loss: 0.637817457318306, Final Batch Loss: 0.15622647106647491
Epoch 3885, Loss

Epoch 3996, Loss: 0.4960381090641022, Final Batch Loss: 0.12830011546611786
Epoch 3997, Loss: 0.5832815915346146, Final Batch Loss: 0.2505137324333191
Epoch 3998, Loss: 0.6243915557861328, Final Batch Loss: 0.2522384524345398
Epoch 3999, Loss: 0.513291485607624, Final Batch Loss: 0.07200465351343155
Epoch 4000, Loss: 0.5384101867675781, Final Batch Loss: 0.12751001119613647
Epoch 4001, Loss: 0.4582909196615219, Final Batch Loss: 0.07935914397239685
Epoch 4002, Loss: 0.4971904009580612, Final Batch Loss: 0.09754541516304016
Epoch 4003, Loss: 0.6150272041559219, Final Batch Loss: 0.23070558905601501
Epoch 4004, Loss: 0.5054654777050018, Final Batch Loss: 0.09252206981182098
Epoch 4005, Loss: 0.5831520184874535, Final Batch Loss: 0.21703371405601501
Epoch 4006, Loss: 0.6666288524866104, Final Batch Loss: 0.26399683952331543
Epoch 4007, Loss: 0.7271388918161392, Final Batch Loss: 0.3279735743999481
Epoch 4008, Loss: 0.6151700615882874, Final Batch Loss: 0.19610542058944702
Epoch 4009, Loss

Epoch 4110, Loss: 0.7022421061992645, Final Batch Loss: 0.3260432481765747
Epoch 4111, Loss: 0.4633663520216942, Final Batch Loss: 0.0741979256272316
Epoch 4112, Loss: 0.5263407230377197, Final Batch Loss: 0.11577938497066498
Epoch 4113, Loss: 0.5283020511269569, Final Batch Loss: 0.08753583580255508
Epoch 4114, Loss: 0.9333577901124954, Final Batch Loss: 0.5286405682563782
Epoch 4115, Loss: 0.7684154957532883, Final Batch Loss: 0.30569642782211304
Epoch 4116, Loss: 0.5987507551908493, Final Batch Loss: 0.16315846145153046
Epoch 4117, Loss: 0.5963596105575562, Final Batch Loss: 0.24774140119552612
Epoch 4118, Loss: 0.4937485307455063, Final Batch Loss: 0.1434299796819687
Epoch 4119, Loss: 0.5275449454784393, Final Batch Loss: 0.1676711142063141
Epoch 4120, Loss: 0.4907084032893181, Final Batch Loss: 0.10810714215040207
Epoch 4121, Loss: 0.43482664600014687, Final Batch Loss: 0.04598310962319374
Epoch 4122, Loss: 0.52860127389431, Final Batch Loss: 0.13769280910491943
Epoch 4123, Loss: 

Epoch 4232, Loss: 0.4234200082719326, Final Batch Loss: 0.03603838011622429
Epoch 4233, Loss: 0.6767585873603821, Final Batch Loss: 0.2738448679447174
Epoch 4234, Loss: 0.4211859703063965, Final Batch Loss: 0.07243530452251434
Epoch 4235, Loss: 0.6635653525590897, Final Batch Loss: 0.2453838437795639
Epoch 4236, Loss: 0.5614957064390182, Final Batch Loss: 0.1611149162054062
Epoch 4237, Loss: 0.5331888794898987, Final Batch Loss: 0.16161616146564484
Epoch 4238, Loss: 0.5996268689632416, Final Batch Loss: 0.2094472199678421
Epoch 4239, Loss: 0.3916104771196842, Final Batch Loss: 0.04657130315899849
Epoch 4240, Loss: 0.4568770304322243, Final Batch Loss: 0.06643872708082199
Epoch 4241, Loss: 0.6357370316982269, Final Batch Loss: 0.2716304659843445
Epoch 4242, Loss: 0.6410204917192459, Final Batch Loss: 0.2556261122226715
Epoch 4243, Loss: 0.5999271273612976, Final Batch Loss: 0.2832672894001007
Epoch 4244, Loss: 0.47542403638362885, Final Batch Loss: 0.12244367599487305
Epoch 4245, Loss: 

Epoch 4350, Loss: 0.4920603036880493, Final Batch Loss: 0.11627191305160522
Epoch 4351, Loss: 0.40253283455967903, Final Batch Loss: 0.030809108167886734
Epoch 4352, Loss: 0.49349016696214676, Final Batch Loss: 0.09571710973978043
Epoch 4353, Loss: 0.522857666015625, Final Batch Loss: 0.19436167180538177
Epoch 4354, Loss: 0.41978999227285385, Final Batch Loss: 0.09542617946863174
Epoch 4355, Loss: 0.5501049160957336, Final Batch Loss: 0.1653590053319931
Epoch 4356, Loss: 0.7236985862255096, Final Batch Loss: 0.35623717308044434
Epoch 4357, Loss: 0.48712319880723953, Final Batch Loss: 0.08350171893835068
Epoch 4358, Loss: 0.5297700613737106, Final Batch Loss: 0.11969852447509766
Epoch 4359, Loss: 0.4537564665079117, Final Batch Loss: 0.0815068781375885
Epoch 4360, Loss: 0.6604825258255005, Final Batch Loss: 0.2426750808954239
Epoch 4361, Loss: 0.5677602887153625, Final Batch Loss: 0.21678279340267181
Epoch 4362, Loss: 0.4456496462225914, Final Batch Loss: 0.06474427133798599
Epoch 4363,

Epoch 4468, Loss: 0.41845228895545006, Final Batch Loss: 0.046510692685842514
Epoch 4469, Loss: 0.5482931733131409, Final Batch Loss: 0.1403018832206726
Epoch 4470, Loss: 0.5372059643268585, Final Batch Loss: 0.17591188848018646
Epoch 4471, Loss: 0.42055535316467285, Final Batch Loss: 0.07252363860607147
Epoch 4472, Loss: 0.4643116518855095, Final Batch Loss: 0.046049974858760834
Epoch 4473, Loss: 0.5849869102239609, Final Batch Loss: 0.2092042714357376
Epoch 4474, Loss: 0.49206380173563957, Final Batch Loss: 0.03200076147913933
Epoch 4475, Loss: 0.562303215265274, Final Batch Loss: 0.18300510942935944
Epoch 4476, Loss: 0.5737955719232559, Final Batch Loss: 0.2175697237253189
Epoch 4477, Loss: 0.47572020441293716, Final Batch Loss: 0.11665342003107071
Epoch 4478, Loss: 0.5000303760170937, Final Batch Loss: 0.0731649324297905
Epoch 4479, Loss: 0.45450038462877274, Final Batch Loss: 0.06895139068365097
Epoch 4480, Loss: 0.44563233852386475, Final Batch Loss: 0.1088365912437439
Epoch 4481

Epoch 4591, Loss: 0.4722956568002701, Final Batch Loss: 0.09191827476024628
Epoch 4592, Loss: 0.5601796656847, Final Batch Loss: 0.1453900784254074
Epoch 4593, Loss: 0.43695785105228424, Final Batch Loss: 0.06572481989860535
Epoch 4594, Loss: 0.3598969653248787, Final Batch Loss: 0.048959411680698395
Epoch 4595, Loss: 0.8736111223697662, Final Batch Loss: 0.521377444267273
Epoch 4596, Loss: 0.4448918104171753, Final Batch Loss: 0.1390306055545807
Epoch 4597, Loss: 0.4267287403345108, Final Batch Loss: 0.09687879681587219
Epoch 4598, Loss: 0.6089490205049515, Final Batch Loss: 0.21086464822292328
Epoch 4599, Loss: 0.5652153193950653, Final Batch Loss: 0.14944550395011902
Epoch 4600, Loss: 0.4155363067984581, Final Batch Loss: 0.06861060112714767
Epoch 4601, Loss: 0.6443134546279907, Final Batch Loss: 0.2819133996963501
Epoch 4602, Loss: 0.5695138871669769, Final Batch Loss: 0.2505939304828644
Epoch 4603, Loss: 0.590709775686264, Final Batch Loss: 0.226286381483078
Epoch 4604, Loss: 0.60

Epoch 4705, Loss: 0.802967980504036, Final Batch Loss: 0.4389391839504242
Epoch 4706, Loss: 0.537649855017662, Final Batch Loss: 0.14576134085655212
Epoch 4707, Loss: 0.39133111014962196, Final Batch Loss: 0.04225415363907814
Epoch 4708, Loss: 0.4885893240571022, Final Batch Loss: 0.0969734713435173
Epoch 4709, Loss: 0.4436807781457901, Final Batch Loss: 0.057528287172317505
Epoch 4710, Loss: 0.6094308644533157, Final Batch Loss: 0.2046162486076355
Epoch 4711, Loss: 0.5493947714567184, Final Batch Loss: 0.059905439615249634
Epoch 4712, Loss: 0.7897484302520752, Final Batch Loss: 0.3597220778465271
Epoch 4713, Loss: 0.48472652584314346, Final Batch Loss: 0.06436029821634293
Epoch 4714, Loss: 0.6612119078636169, Final Batch Loss: 0.26062408089637756
Epoch 4715, Loss: 0.5471373349428177, Final Batch Loss: 0.09767836332321167
Epoch 4716, Loss: 0.5774001479148865, Final Batch Loss: 0.19543695449829102
Epoch 4717, Loss: 0.5505374521017075, Final Batch Loss: 0.15709568560123444
Epoch 4718, Lo

Epoch 4824, Loss: 0.4595402777194977, Final Batch Loss: 0.14068925380706787
Epoch 4825, Loss: 0.5080630928277969, Final Batch Loss: 0.1394677758216858
Epoch 4826, Loss: 0.5646183490753174, Final Batch Loss: 0.1541563719511032
Epoch 4827, Loss: 0.6777383238077164, Final Batch Loss: 0.289362370967865
Epoch 4828, Loss: 0.7357814759016037, Final Batch Loss: 0.4109489321708679
Epoch 4829, Loss: 0.4957343861460686, Final Batch Loss: 0.07853015512228012
Epoch 4830, Loss: 0.7675891071557999, Final Batch Loss: 0.4001816213130951
Epoch 4831, Loss: 0.49940426647663116, Final Batch Loss: 0.11924347281455994
Epoch 4832, Loss: 0.4174622744321823, Final Batch Loss: 0.06989549100399017
Epoch 4833, Loss: 0.5525332689285278, Final Batch Loss: 0.16172771155834198
Epoch 4834, Loss: 0.5762249380350113, Final Batch Loss: 0.2138686180114746
Epoch 4835, Loss: 0.42181286960840225, Final Batch Loss: 0.09344453364610672
Epoch 4836, Loss: 0.5289512276649475, Final Batch Loss: 0.1526632457971573
Epoch 4837, Loss: 

Epoch 4938, Loss: 0.4067825600504875, Final Batch Loss: 0.07966230064630508
Epoch 4939, Loss: 0.3703414648771286, Final Batch Loss: 0.03475138545036316
Epoch 4940, Loss: 0.5314431488513947, Final Batch Loss: 0.16947665810585022
Epoch 4941, Loss: 0.5673286020755768, Final Batch Loss: 0.27035948634147644
Epoch 4942, Loss: 0.7594276368618011, Final Batch Loss: 0.4586440622806549
Epoch 4943, Loss: 0.36691969633102417, Final Batch Loss: 0.07721082866191864
Epoch 4944, Loss: 0.38941009156405926, Final Batch Loss: 0.02073451690375805
Epoch 4945, Loss: 0.3872009553015232, Final Batch Loss: 0.05404757335782051
Epoch 4946, Loss: 0.4176507517695427, Final Batch Loss: 0.1159445121884346
Epoch 4947, Loss: 0.5686311274766922, Final Batch Loss: 0.22443921864032745
Epoch 4948, Loss: 0.44788189977407455, Final Batch Loss: 0.04361575096845627
Epoch 4949, Loss: 0.5025646686553955, Final Batch Loss: 0.16353854537010193
Epoch 4950, Loss: 0.49135328084230423, Final Batch Loss: 0.11711966246366501
Epoch 4951

In [8]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[19  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  1  0  0  0]
 [ 0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0  2]
 [ 0  0  0  0  0  0  0  0  0 12  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        19
           1    1.00000   1.00000   1.00000        12
           2    1.00000   1.00000   1.00000        12
           3    1.00000   1.00000   1.00000        12
           4    1.00000   1.00000   1.00000         8
           5    1.00000   0.83333   0.90909         6
           6    1.00000   1.00000   1.00000        11
           7    1.00000   1.00000   1.00000        11
           8    0.85714   0.75000   0.80000 

In [23]:
n_samples = 20

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_1 = gen(latent_vectors).detach().numpy()

y_1 = np.zeros(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_2 = gen(latent_vectors).detach().numpy()

y_2 = np.ones(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_3 = gen(latent_vectors).detach().numpy()

y_3 = np.ones(n_samples) + 1

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_4 = gen(latent_vectors).detach().numpy()

y_4 = np.ones(n_samples) + 2

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_5 = gen(latent_vectors).detach().numpy()

y_5 = np.ones(n_samples) + 3

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_6 = gen(latent_vectors).detach().numpy()

y_6 = np.ones(n_samples) + 4

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_7 = gen(latent_vectors).detach().numpy()

y_7 = np.ones(n_samples) + 5

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_8 = gen(latent_vectors).detach().numpy()

y_8 = np.ones(n_samples) + 6

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_9 = gen(latent_vectors).detach().numpy()

y_9 = np.ones(n_samples) + 7

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A0 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_10 = gen(latent_vectors).detach().numpy()

y_10 = np.ones(n_samples) + 8

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A1 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_11 = gen(latent_vectors).detach().numpy()

y_11 = np.ones(n_samples) + 9

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U3A2 Solo GAN Ablation_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_12 = gen(latent_vectors).detach().numpy()

y_12 = np.ones(n_samples) + 10

fake_features = np.concatenate((fake_features_1, fake_features_2, fake_features_3, fake_features_4, fake_features_5, fake_features_6,
                         fake_features_7, fake_features_8, fake_features_9, fake_features_10, fake_features_11, fake_features_12))
fake_labels = np.concatenate((y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9, y_10, y_11, y_12))

fake_features = torch.Tensor(fake_features)

In [24]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[19  0  0  0  0  0  0  0  0  1  0  0]
 [ 1 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  6  0  0  5  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  2  0  0  0  3  0]
 [ 0  0  3  0  0  8  0  0  8  0  0  1]
 [ 0  0  0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  4  0  0 10  4  0  2]
 [ 0  0  0  0  1  0  7  0  0  8  4  0]
 [ 0  0  0  0  2  0  0  0  0  0 18  0]
 [ 0  0  0  0  0 14  0  0  2  0  0  4]]
              precision    recall  f1-score   support

         0.0    0.95000   0.95000   0.95000        20
         1.0    1.00000   0.95000   0.97436        20
         2.0    0.75000   0.45000   0.56250        20
         3.0    1.00000   1.00000   1.00000        20
         4.0    0.83333   0.75000   0.78947        20
         5.0    0.25000   0.40000   0.30769        20
         6.0    0.68966   1.00000   0.81633        20
         7.0    1.00000   1.00000   1.00000        20
         8.0    0.40000   0.50000   0.44444 