In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '59 tGravityAcc-energy()-Z',
 '125 tBodyGyro-std()-Y',
 '128 tBodyGyro-mad()-Y',
 '138 tBodyGyro-energy()-Y',
 '165 tBodyGyroJerk-std()-Y',
 '168 tBodyGyroJerk-mad()-Y',
 '178 tBodyGyroJerk-energy()-Y',
 '181 tBodyGyroJerk-iqr()-Y',
 '425 fBodyGyro-mean()-Y',
 '428 fBodyGyro-std()-Y',
 '431 fBodyGyro-mad()-Y',
 '441 fBodyGyro-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '478 fBodyGyro-bandsEnergy()-25,32',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '204 tBodyAccMag-max()',
 '215 tGravityAccMag-std()',
 '217 tGravityAccMag-max()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '275 fBodyAcc-max()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '506 fBodyAccMag-max()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            classifier_block(15, 10),
            nn.Linear(10, 9)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def get_act_matrix(batch_size, a_dim):
    indexes = np.random.randint(a_dim, size = batch_size)
    
    one_hot = np.zeros((len(indexes), indexes.max()+1))
    one_hot[np.arange(len(indexes)),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)
    
def get_usr_matrix(batch_size, u_dim):
    indexes = np.random.randint(u_dim, size = batch_size)
    
    one_hot = np.zeros((indexes.size, indexes.max()+1))
    one_hot[np.arange(indexes.size),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../saved_models/{model_name}'))

# Train on Real Test on Real

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [23, 25, 27]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [8]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 4.4347217082977295, Final Batch Loss: 2.2140936851501465
Epoch 2, Loss: 4.434186220169067, Final Batch Loss: 2.2177114486694336
Epoch 3, Loss: 4.431804656982422, Final Batch Loss: 2.2137868404388428
Epoch 4, Loss: 4.428043603897095, Final Batch Loss: 2.2165467739105225
Epoch 5, Loss: 4.425544500350952, Final Batch Loss: 2.204549551010132
Epoch 6, Loss: 4.42397403717041, Final Batch Loss: 2.2126262187957764
Epoch 7, Loss: 4.415851354598999, Final Batch Loss: 2.201073169708252
Epoch 8, Loss: 4.414262294769287, Final Batch Loss: 2.20589280128479
Epoch 9, Loss: 4.414660215377808, Final Batch Loss: 2.205204963684082
Epoch 10, Loss: 4.407128572463989, Final Batch Loss: 2.202409505844116
Epoch 11, Loss: 4.401142597198486, Final Batch Loss: 2.1981611251831055
Epoch 12, Loss: 4.400351285934448, Final Batch Loss: 2.2069504261016846
Epoch 13, Loss: 4.388543367385864, Final Batch Loss: 2.1843740940093994
Epoch 14, Loss: 4.3819968700408936, Final Batch Loss: 2.1880555152893066
Epoch 

Epoch 118, Loss: 1.8835492730140686, Final Batch Loss: 0.9459570646286011
Epoch 119, Loss: 1.8992271423339844, Final Batch Loss: 0.9814133644104004
Epoch 120, Loss: 1.9106677770614624, Final Batch Loss: 0.9000521898269653
Epoch 121, Loss: 1.864456295967102, Final Batch Loss: 0.9402604103088379
Epoch 122, Loss: 1.9069982171058655, Final Batch Loss: 0.9170746803283691
Epoch 123, Loss: 1.8609440922737122, Final Batch Loss: 0.9239597916603088
Epoch 124, Loss: 1.8266807198524475, Final Batch Loss: 0.9040545225143433
Epoch 125, Loss: 1.8396018147468567, Final Batch Loss: 0.9317435026168823
Epoch 126, Loss: 1.798188865184784, Final Batch Loss: 0.8641582727432251
Epoch 127, Loss: 1.8265233635902405, Final Batch Loss: 0.9104364514350891
Epoch 128, Loss: 1.7593640685081482, Final Batch Loss: 0.8292063474655151
Epoch 129, Loss: 1.7262585163116455, Final Batch Loss: 0.8276712894439697
Epoch 130, Loss: 1.7611960768699646, Final Batch Loss: 0.861130952835083
Epoch 131, Loss: 1.8241919875144958, Fina

Epoch 230, Loss: 1.405604064464569, Final Batch Loss: 0.7253932952880859
Epoch 231, Loss: 1.3772156238555908, Final Batch Loss: 0.6603706479072571
Epoch 232, Loss: 1.4119746088981628, Final Batch Loss: 0.7103503346443176
Epoch 233, Loss: 1.3666326999664307, Final Batch Loss: 0.6779454946517944
Epoch 234, Loss: 1.3745115399360657, Final Batch Loss: 0.6249181032180786
Epoch 235, Loss: 1.3957756161689758, Final Batch Loss: 0.7481343746185303
Epoch 236, Loss: 1.4064461588859558, Final Batch Loss: 0.7402979731559753
Epoch 237, Loss: 1.4284409880638123, Final Batch Loss: 0.7040667533874512
Epoch 238, Loss: 1.415938138961792, Final Batch Loss: 0.7446808218955994
Epoch 239, Loss: 1.363386869430542, Final Batch Loss: 0.6713137626647949
Epoch 240, Loss: 1.4204379320144653, Final Batch Loss: 0.6914213299751282
Epoch 241, Loss: 1.416352927684784, Final Batch Loss: 0.7498769760131836
Epoch 242, Loss: 1.4178376197814941, Final Batch Loss: 0.7733689546585083
Epoch 243, Loss: 1.3667928576469421, Final

Epoch 343, Loss: 1.1426265835762024, Final Batch Loss: 0.5714884400367737
Epoch 344, Loss: 1.132542073726654, Final Batch Loss: 0.5799058675765991
Epoch 345, Loss: 1.1451201438903809, Final Batch Loss: 0.6200394630432129
Epoch 346, Loss: 1.1506258249282837, Final Batch Loss: 0.5716219544410706
Epoch 347, Loss: 1.1486912965774536, Final Batch Loss: 0.5651829242706299
Epoch 348, Loss: 1.2254668474197388, Final Batch Loss: 0.6368802785873413
Epoch 349, Loss: 1.185440182685852, Final Batch Loss: 0.540125846862793
Epoch 350, Loss: 1.1319569945335388, Final Batch Loss: 0.5789538025856018
Epoch 351, Loss: 1.166386365890503, Final Batch Loss: 0.6014363765716553
Epoch 352, Loss: 1.1302145719528198, Final Batch Loss: 0.5474064946174622
Epoch 353, Loss: 1.1184534430503845, Final Batch Loss: 0.4858499765396118
Epoch 354, Loss: 1.0803090333938599, Final Batch Loss: 0.5391020774841309
Epoch 355, Loss: 1.157444179058075, Final Batch Loss: 0.5571220517158508
Epoch 356, Loss: 1.1863152980804443, Final 

Epoch 459, Loss: 1.0346530973911285, Final Batch Loss: 0.4808882176876068
Epoch 460, Loss: 1.1069361567497253, Final Batch Loss: 0.5701172351837158
Epoch 461, Loss: 1.021798551082611, Final Batch Loss: 0.5048655271530151
Epoch 462, Loss: 1.0283113718032837, Final Batch Loss: 0.5346570014953613
Epoch 463, Loss: 1.1227824687957764, Final Batch Loss: 0.5576217770576477
Epoch 464, Loss: 1.0181264579296112, Final Batch Loss: 0.46232661604881287
Epoch 465, Loss: 0.9888880252838135, Final Batch Loss: 0.44032835960388184
Epoch 466, Loss: 1.065086841583252, Final Batch Loss: 0.548753023147583
Epoch 467, Loss: 1.0036338865756989, Final Batch Loss: 0.48790374398231506
Epoch 468, Loss: 1.0241032242774963, Final Batch Loss: 0.4475485682487488
Epoch 469, Loss: 1.05765038728714, Final Batch Loss: 0.5312442183494568
Epoch 470, Loss: 1.0422505140304565, Final Batch Loss: 0.563431978225708
Epoch 471, Loss: 1.0117138028144836, Final Batch Loss: 0.5194341540336609
Epoch 472, Loss: 1.0044430792331696, Fina

Epoch 578, Loss: 0.9650138914585114, Final Batch Loss: 0.45631179213523865
Epoch 579, Loss: 0.9650839269161224, Final Batch Loss: 0.5197252035140991
Epoch 580, Loss: 0.9999946653842926, Final Batch Loss: 0.5064185261726379
Epoch 581, Loss: 0.956196516752243, Final Batch Loss: 0.4646238386631012
Epoch 582, Loss: 0.9251269698143005, Final Batch Loss: 0.43854549527168274
Epoch 583, Loss: 0.9819791913032532, Final Batch Loss: 0.5095769762992859
Epoch 584, Loss: 1.048805981874466, Final Batch Loss: 0.572364091873169
Epoch 585, Loss: 0.9845568835735321, Final Batch Loss: 0.5186105370521545
Epoch 586, Loss: 1.0501866340637207, Final Batch Loss: 0.5449257493019104
Epoch 587, Loss: 0.9368450045585632, Final Batch Loss: 0.4661185145378113
Epoch 588, Loss: 0.9505071341991425, Final Batch Loss: 0.45205047726631165
Epoch 589, Loss: 0.9957376718521118, Final Batch Loss: 0.5134995579719543
Epoch 590, Loss: 0.9587345719337463, Final Batch Loss: 0.49012595415115356
Epoch 591, Loss: 0.9941258728504181, 

Epoch 700, Loss: 0.951145201921463, Final Batch Loss: 0.5283325910568237
Epoch 701, Loss: 0.9443357884883881, Final Batch Loss: 0.4941025674343109
Epoch 702, Loss: 0.9445434212684631, Final Batch Loss: 0.48556607961654663
Epoch 703, Loss: 0.8788318037986755, Final Batch Loss: 0.3862670361995697
Epoch 704, Loss: 0.9679847657680511, Final Batch Loss: 0.4864865243434906
Epoch 705, Loss: 0.9391191303730011, Final Batch Loss: 0.4757363796234131
Epoch 706, Loss: 0.9361394941806793, Final Batch Loss: 0.44278019666671753
Epoch 707, Loss: 0.8944839239120483, Final Batch Loss: 0.43849489092826843
Epoch 708, Loss: 0.963970422744751, Final Batch Loss: 0.47492775321006775
Epoch 709, Loss: 0.8970241844654083, Final Batch Loss: 0.4691097140312195
Epoch 710, Loss: 0.8975041210651398, Final Batch Loss: 0.4436049163341522
Epoch 711, Loss: 0.93348628282547, Final Batch Loss: 0.48155835270881653
Epoch 712, Loss: 0.9165236353874207, Final Batch Loss: 0.4664384424686432
Epoch 713, Loss: 0.9672332108020782, 

Epoch 831, Loss: 0.9368621706962585, Final Batch Loss: 0.5173978209495544
Epoch 832, Loss: 0.8868185579776764, Final Batch Loss: 0.47392600774765015
Epoch 833, Loss: 0.8848235607147217, Final Batch Loss: 0.4105037450790405
Epoch 834, Loss: 0.867054283618927, Final Batch Loss: 0.42798489332199097
Epoch 835, Loss: 0.91917285323143, Final Batch Loss: 0.479828804731369
Epoch 836, Loss: 0.9554231762886047, Final Batch Loss: 0.5108548998832703
Epoch 837, Loss: 0.8961870968341827, Final Batch Loss: 0.42457762360572815
Epoch 838, Loss: 0.9200645983219147, Final Batch Loss: 0.4932178258895874
Epoch 839, Loss: 0.9191626608371735, Final Batch Loss: 0.4799892008304596
Epoch 840, Loss: 0.8955626487731934, Final Batch Loss: 0.43445321917533875
Epoch 841, Loss: 0.9256335198879242, Final Batch Loss: 0.4701683521270752
Epoch 842, Loss: 0.885389894247055, Final Batch Loss: 0.4496075212955475
Epoch 843, Loss: 0.939372181892395, Final Batch Loss: 0.5257600545883179
Epoch 844, Loss: 0.9656926095485687, Fin

Epoch 946, Loss: 0.846623569726944, Final Batch Loss: 0.46125906705856323
Epoch 947, Loss: 0.8505944311618805, Final Batch Loss: 0.4464559257030487
Epoch 948, Loss: 0.9331512451171875, Final Batch Loss: 0.4851239323616028
Epoch 949, Loss: 0.8931310474872589, Final Batch Loss: 0.4470585286617279
Epoch 950, Loss: 0.8747761249542236, Final Batch Loss: 0.47166144847869873
Epoch 951, Loss: 0.8040561974048615, Final Batch Loss: 0.39753609895706177
Epoch 952, Loss: 0.876770406961441, Final Batch Loss: 0.41840001940727234
Epoch 953, Loss: 0.8635372817516327, Final Batch Loss: 0.43474888801574707
Epoch 954, Loss: 0.8225297629833221, Final Batch Loss: 0.39754223823547363
Epoch 955, Loss: 0.8740580379962921, Final Batch Loss: 0.4720953404903412
Epoch 956, Loss: 0.8719193637371063, Final Batch Loss: 0.43423891067504883
Epoch 957, Loss: 0.8782240450382233, Final Batch Loss: 0.4829672873020172
Epoch 958, Loss: 0.8892644941806793, Final Batch Loss: 0.4452162981033325
Epoch 959, Loss: 0.88862749934196

Epoch 1058, Loss: 0.7999459505081177, Final Batch Loss: 0.37998121976852417
Epoch 1059, Loss: 0.8521669507026672, Final Batch Loss: 0.45395344495773315
Epoch 1060, Loss: 0.8596025109291077, Final Batch Loss: 0.4137673079967499
Epoch 1061, Loss: 0.8110800087451935, Final Batch Loss: 0.39699986577033997
Epoch 1062, Loss: 0.8515969812870026, Final Batch Loss: 0.43865182995796204
Epoch 1063, Loss: 0.8531939089298248, Final Batch Loss: 0.40260472893714905
Epoch 1064, Loss: 0.8227992355823517, Final Batch Loss: 0.4112482964992523
Epoch 1065, Loss: 0.8644045293331146, Final Batch Loss: 0.473330557346344
Epoch 1066, Loss: 0.8241322338581085, Final Batch Loss: 0.4614160656929016
Epoch 1067, Loss: 0.7909850478172302, Final Batch Loss: 0.3640984892845154
Epoch 1068, Loss: 0.8094419538974762, Final Batch Loss: 0.3840811848640442
Epoch 1069, Loss: 0.853210985660553, Final Batch Loss: 0.4000411629676819
Epoch 1070, Loss: 0.8522390127182007, Final Batch Loss: 0.40570002794265747
Epoch 1071, Loss: 0.8

Epoch 1185, Loss: 0.8195270597934723, Final Batch Loss: 0.45329031348228455
Epoch 1186, Loss: 0.7858833968639374, Final Batch Loss: 0.39022135734558105
Epoch 1187, Loss: 0.7988756895065308, Final Batch Loss: 0.3693808615207672
Epoch 1188, Loss: 0.7557695209980011, Final Batch Loss: 0.39509323239326477
Epoch 1189, Loss: 0.7377635538578033, Final Batch Loss: 0.35750114917755127
Epoch 1190, Loss: 0.7937860488891602, Final Batch Loss: 0.4287346601486206
Epoch 1191, Loss: 0.7849185764789581, Final Batch Loss: 0.39136505126953125
Epoch 1192, Loss: 0.7439090609550476, Final Batch Loss: 0.35598036646842957
Epoch 1193, Loss: 0.7786115109920502, Final Batch Loss: 0.4045124650001526
Epoch 1194, Loss: 0.7793894708156586, Final Batch Loss: 0.36873698234558105
Epoch 1195, Loss: 0.8156425356864929, Final Batch Loss: 0.4051853120326996
Epoch 1196, Loss: 0.7689138948917389, Final Batch Loss: 0.3940616548061371
Epoch 1197, Loss: 0.8276629149913788, Final Batch Loss: 0.41168710589408875
Epoch 1198, Loss:

Epoch 1305, Loss: 0.6990532279014587, Final Batch Loss: 0.3519827127456665
Epoch 1306, Loss: 0.7171840369701385, Final Batch Loss: 0.37032458186149597
Epoch 1307, Loss: 0.6788603067398071, Final Batch Loss: 0.3072018623352051
Epoch 1308, Loss: 0.6615522503852844, Final Batch Loss: 0.37977534532546997
Epoch 1309, Loss: 0.7525725066661835, Final Batch Loss: 0.4004192352294922
Epoch 1310, Loss: 0.6713333129882812, Final Batch Loss: 0.34299060702323914
Epoch 1311, Loss: 0.7110249698162079, Final Batch Loss: 0.42690151929855347
Epoch 1312, Loss: 0.694010853767395, Final Batch Loss: 0.34537526965141296
Epoch 1313, Loss: 0.7336895763874054, Final Batch Loss: 0.3841935694217682
Epoch 1314, Loss: 0.6744944453239441, Final Batch Loss: 0.3029901087284088
Epoch 1315, Loss: 0.643651694059372, Final Batch Loss: 0.2554340064525604
Epoch 1316, Loss: 0.7194489538669586, Final Batch Loss: 0.3832975924015045
Epoch 1317, Loss: 0.7571033835411072, Final Batch Loss: 0.4365217685699463
Epoch 1318, Loss: 0.73

Epoch 1413, Loss: 0.6460095047950745, Final Batch Loss: 0.3357464075088501
Epoch 1414, Loss: 0.646404892206192, Final Batch Loss: 0.3063051104545593
Epoch 1415, Loss: 0.6426662802696228, Final Batch Loss: 0.3594186007976532
Epoch 1416, Loss: 0.6393798291683197, Final Batch Loss: 0.32427147030830383
Epoch 1417, Loss: 0.6104864180088043, Final Batch Loss: 0.34287387132644653
Epoch 1418, Loss: 0.6564003527164459, Final Batch Loss: 0.35124778747558594
Epoch 1419, Loss: 0.6469003558158875, Final Batch Loss: 0.2972210943698883
Epoch 1420, Loss: 0.5859563052654266, Final Batch Loss: 0.30709803104400635
Epoch 1421, Loss: 0.5765958726406097, Final Batch Loss: 0.23258551955223083
Epoch 1422, Loss: 0.6179653108119965, Final Batch Loss: 0.29201042652130127
Epoch 1423, Loss: 0.6178170442581177, Final Batch Loss: 0.30705633759498596
Epoch 1424, Loss: 0.62253737449646, Final Batch Loss: 0.30036142468452454
Epoch 1425, Loss: 0.7356891632080078, Final Batch Loss: 0.43014630675315857
Epoch 1426, Loss: 0

Epoch 1540, Loss: 0.5903926491737366, Final Batch Loss: 0.33672305941581726
Epoch 1541, Loss: 0.5126388818025589, Final Batch Loss: 0.26361772418022156
Epoch 1542, Loss: 0.5485425144433975, Final Batch Loss: 0.3037891983985901
Epoch 1543, Loss: 0.5574195086956024, Final Batch Loss: 0.26282474398612976
Epoch 1544, Loss: 0.48063863813877106, Final Batch Loss: 0.22793345153331757
Epoch 1545, Loss: 0.4899429529905319, Final Batch Loss: 0.23794938623905182
Epoch 1546, Loss: 0.5554207265377045, Final Batch Loss: 0.2983272075653076
Epoch 1547, Loss: 0.5871217250823975, Final Batch Loss: 0.31169575452804565
Epoch 1548, Loss: 0.5244801044464111, Final Batch Loss: 0.26761531829833984
Epoch 1549, Loss: 0.5698402523994446, Final Batch Loss: 0.26019155979156494
Epoch 1550, Loss: 0.49310095608234406, Final Batch Loss: 0.2578199803829193
Epoch 1551, Loss: 0.5533915758132935, Final Batch Loss: 0.2713926136493683
Epoch 1552, Loss: 0.5208463817834854, Final Batch Loss: 0.24280114471912384
Epoch 1553, Lo

Epoch 1649, Loss: 0.5049407184123993, Final Batch Loss: 0.2694763243198395
Epoch 1650, Loss: 0.5003756731748581, Final Batch Loss: 0.2900152802467346
Epoch 1651, Loss: 0.5050694644451141, Final Batch Loss: 0.24867117404937744
Epoch 1652, Loss: 0.43264441192150116, Final Batch Loss: 0.19025872647762299
Epoch 1653, Loss: 0.48315446078777313, Final Batch Loss: 0.2344372719526291
Epoch 1654, Loss: 0.5303737074136734, Final Batch Loss: 0.3206881880760193
Epoch 1655, Loss: 0.5216801166534424, Final Batch Loss: 0.25083428621292114
Epoch 1656, Loss: 0.4772535264492035, Final Batch Loss: 0.24702009558677673
Epoch 1657, Loss: 0.48235437273979187, Final Batch Loss: 0.2075178325176239
Epoch 1658, Loss: 0.49474598467350006, Final Batch Loss: 0.23672975599765778
Epoch 1659, Loss: 0.47523723542690277, Final Batch Loss: 0.22026194632053375
Epoch 1660, Loss: 0.44228340685367584, Final Batch Loss: 0.25710850954055786
Epoch 1661, Loss: 0.45962245762348175, Final Batch Loss: 0.24061745405197144
Epoch 1662

Epoch 1758, Loss: 0.40645238757133484, Final Batch Loss: 0.20250365138053894
Epoch 1759, Loss: 0.42980286478996277, Final Batch Loss: 0.23459728062152863
Epoch 1760, Loss: 0.4146769791841507, Final Batch Loss: 0.19496384263038635
Epoch 1761, Loss: 0.4451049864292145, Final Batch Loss: 0.2051524668931961
Epoch 1762, Loss: 0.4632774293422699, Final Batch Loss: 0.2543140649795532
Epoch 1763, Loss: 0.4642820507287979, Final Batch Loss: 0.23178893327713013
Epoch 1764, Loss: 0.457131564617157, Final Batch Loss: 0.21146371960639954
Epoch 1765, Loss: 0.3691595643758774, Final Batch Loss: 0.16819708049297333
Epoch 1766, Loss: 0.4709843099117279, Final Batch Loss: 0.26160627603530884
Epoch 1767, Loss: 0.4826182574033737, Final Batch Loss: 0.26275959610939026
Epoch 1768, Loss: 0.5064598768949509, Final Batch Loss: 0.2704145014286041
Epoch 1769, Loss: 0.46642808616161346, Final Batch Loss: 0.23360928893089294
Epoch 1770, Loss: 0.4570803642272949, Final Batch Loss: 0.2094111293554306
Epoch 1771, Lo

Epoch 1873, Loss: 0.39068350195884705, Final Batch Loss: 0.17281705141067505
Epoch 1874, Loss: 0.38341978192329407, Final Batch Loss: 0.18114544451236725
Epoch 1875, Loss: 0.3666466176509857, Final Batch Loss: 0.20363503694534302
Epoch 1876, Loss: 0.3914007395505905, Final Batch Loss: 0.19687426090240479
Epoch 1877, Loss: 0.4404821842908859, Final Batch Loss: 0.19334891438484192
Epoch 1878, Loss: 0.39115476608276367, Final Batch Loss: 0.18240942060947418
Epoch 1879, Loss: 0.36731159687042236, Final Batch Loss: 0.2006596177816391
Epoch 1880, Loss: 0.31648923456668854, Final Batch Loss: 0.14139175415039062
Epoch 1881, Loss: 0.38745054602622986, Final Batch Loss: 0.15664508938789368
Epoch 1882, Loss: 0.4156138002872467, Final Batch Loss: 0.20454302430152893
Epoch 1883, Loss: 0.40171973407268524, Final Batch Loss: 0.19051599502563477
Epoch 1884, Loss: 0.3692709505558014, Final Batch Loss: 0.19068795442581177
Epoch 1885, Loss: 0.3920047879219055, Final Batch Loss: 0.19078290462493896
Epoch 

Epoch 1998, Loss: 0.35554489493370056, Final Batch Loss: 0.15957964956760406
Epoch 1999, Loss: 0.36628489196300507, Final Batch Loss: 0.17046670615673065
Epoch 2000, Loss: 0.32498013973236084, Final Batch Loss: 0.16363948583602905
Epoch 2001, Loss: 0.4020327627658844, Final Batch Loss: 0.21869108080863953
Epoch 2002, Loss: 0.3728075325489044, Final Batch Loss: 0.22929559648036957
Epoch 2003, Loss: 0.3953516334295273, Final Batch Loss: 0.16059088706970215
Epoch 2004, Loss: 0.381160169839859, Final Batch Loss: 0.17120930552482605
Epoch 2005, Loss: 0.4549185335636139, Final Batch Loss: 0.20121610164642334
Epoch 2006, Loss: 0.447173073887825, Final Batch Loss: 0.23950181901454926
Epoch 2007, Loss: 0.31133581697940826, Final Batch Loss: 0.14737410843372345
Epoch 2008, Loss: 0.3995978385210037, Final Batch Loss: 0.19522212445735931
Epoch 2009, Loss: 0.3611751198768616, Final Batch Loss: 0.16325901448726654
Epoch 2010, Loss: 0.34992317855358124, Final Batch Loss: 0.2100743055343628
Epoch 2011

Epoch 2115, Loss: 0.38124674558639526, Final Batch Loss: 0.2189292460680008
Epoch 2116, Loss: 0.48139356076717377, Final Batch Loss: 0.1754416972398758
Epoch 2117, Loss: 0.30998755991458893, Final Batch Loss: 0.17128963768482208
Epoch 2118, Loss: 0.33444245159626007, Final Batch Loss: 0.17718318104743958
Epoch 2119, Loss: 0.31027428805828094, Final Batch Loss: 0.13500796258449554
Epoch 2120, Loss: 0.3546968400478363, Final Batch Loss: 0.126021608710289
Epoch 2121, Loss: 0.349385529756546, Final Batch Loss: 0.21798084676265717
Epoch 2122, Loss: 0.3649463653564453, Final Batch Loss: 0.17422911524772644
Epoch 2123, Loss: 0.30433689057826996, Final Batch Loss: 0.17135199904441833
Epoch 2124, Loss: 0.3403942734003067, Final Batch Loss: 0.1938803493976593
Epoch 2125, Loss: 0.31455086171627045, Final Batch Loss: 0.15838377177715302
Epoch 2126, Loss: 0.4378015995025635, Final Batch Loss: 0.2515045702457428
Epoch 2127, Loss: 0.37282004952430725, Final Batch Loss: 0.15864251554012299
Epoch 2128,

Epoch 2230, Loss: 0.3591791242361069, Final Batch Loss: 0.18068334460258484
Epoch 2231, Loss: 0.40184386074543, Final Batch Loss: 0.16694194078445435
Epoch 2232, Loss: 0.3460044860839844, Final Batch Loss: 0.18020948767662048
Epoch 2233, Loss: 0.31628313660621643, Final Batch Loss: 0.13573963940143585
Epoch 2234, Loss: 0.39409828186035156, Final Batch Loss: 0.18898509442806244
Epoch 2235, Loss: 0.28986550867557526, Final Batch Loss: 0.12784597277641296
Epoch 2236, Loss: 0.2933871001005173, Final Batch Loss: 0.15364861488342285
Epoch 2237, Loss: 0.2666090354323387, Final Batch Loss: 0.10704945772886276
Epoch 2238, Loss: 0.32370026409626007, Final Batch Loss: 0.19872824847698212
Epoch 2239, Loss: 0.30847059190273285, Final Batch Loss: 0.16575594246387482
Epoch 2240, Loss: 0.35049211978912354, Final Batch Loss: 0.16368158161640167
Epoch 2241, Loss: 0.25823886692523956, Final Batch Loss: 0.1128586083650589
Epoch 2242, Loss: 0.2848290354013443, Final Batch Loss: 0.13072386384010315
Epoch 22

Epoch 2344, Loss: 0.3137648403644562, Final Batch Loss: 0.1556965410709381
Epoch 2345, Loss: 0.32961931824684143, Final Batch Loss: 0.16213688254356384
Epoch 2346, Loss: 0.2551518529653549, Final Batch Loss: 0.11805212497711182
Epoch 2347, Loss: 0.3154066652059555, Final Batch Loss: 0.16858215630054474
Epoch 2348, Loss: 0.3143683224916458, Final Batch Loss: 0.1454908847808838
Epoch 2349, Loss: 0.25947149097919464, Final Batch Loss: 0.12013532221317291
Epoch 2350, Loss: 0.277680441737175, Final Batch Loss: 0.17348740994930267
Epoch 2351, Loss: 0.3515040874481201, Final Batch Loss: 0.16321508586406708
Epoch 2352, Loss: 0.34751854836940765, Final Batch Loss: 0.1525532454252243
Epoch 2353, Loss: 0.25786853581666946, Final Batch Loss: 0.1193251833319664
Epoch 2354, Loss: 0.30370333790779114, Final Batch Loss: 0.15430030226707458
Epoch 2355, Loss: 0.25364288687705994, Final Batch Loss: 0.13055367767810822
Epoch 2356, Loss: 0.2986489534378052, Final Batch Loss: 0.15150706470012665
Epoch 2357,

Epoch 2455, Loss: 0.24922535568475723, Final Batch Loss: 0.12882764637470245
Epoch 2456, Loss: 0.3508489429950714, Final Batch Loss: 0.2156427949666977
Epoch 2457, Loss: 0.24882785230875015, Final Batch Loss: 0.12533794343471527
Epoch 2458, Loss: 0.34534840285778046, Final Batch Loss: 0.21271279454231262
Epoch 2459, Loss: 0.22790684551000595, Final Batch Loss: 0.11353923380374908
Epoch 2460, Loss: 0.2659911811351776, Final Batch Loss: 0.10252301394939423
Epoch 2461, Loss: 0.33985635638237, Final Batch Loss: 0.15207898616790771
Epoch 2462, Loss: 0.2719385474920273, Final Batch Loss: 0.16152533888816833
Epoch 2463, Loss: 0.2832953706383705, Final Batch Loss: 0.19224925339221954
Epoch 2464, Loss: 0.2482798621058464, Final Batch Loss: 0.13236141204833984
Epoch 2465, Loss: 0.31646572053432465, Final Batch Loss: 0.16632327437400818
Epoch 2466, Loss: 0.37459075450897217, Final Batch Loss: 0.12585508823394775
Epoch 2467, Loss: 0.2860066592693329, Final Batch Loss: 0.14594011008739471
Epoch 246

Epoch 2576, Loss: 0.2852214276790619, Final Batch Loss: 0.1472363919019699
Epoch 2577, Loss: 0.22488413751125336, Final Batch Loss: 0.11024400591850281
Epoch 2578, Loss: 0.32884007692337036, Final Batch Loss: 0.19231227040290833
Epoch 2579, Loss: 0.23160229623317719, Final Batch Loss: 0.12208515405654907
Epoch 2580, Loss: 0.300278440117836, Final Batch Loss: 0.1483682245016098
Epoch 2581, Loss: 0.35130636394023895, Final Batch Loss: 0.14285661280155182
Epoch 2582, Loss: 0.29613617062568665, Final Batch Loss: 0.13832226395606995
Epoch 2583, Loss: 0.25353845953941345, Final Batch Loss: 0.11117474734783173
Epoch 2584, Loss: 0.24922733753919601, Final Batch Loss: 0.13123144209384918
Epoch 2585, Loss: 0.2550303786993027, Final Batch Loss: 0.12689833343029022
Epoch 2586, Loss: 0.31138868629932404, Final Batch Loss: 0.1552589237689972
Epoch 2587, Loss: 0.2638462707400322, Final Batch Loss: 0.12332993000745773
Epoch 2588, Loss: 0.2630380615592003, Final Batch Loss: 0.14667202532291412
Epoch 25

Epoch 2688, Loss: 0.2899929881095886, Final Batch Loss: 0.13722863793373108
Epoch 2689, Loss: 0.27388864755630493, Final Batch Loss: 0.13200122117996216
Epoch 2690, Loss: 0.41089534759521484, Final Batch Loss: 0.23150531947612762
Epoch 2691, Loss: 0.2538324296474457, Final Batch Loss: 0.10128358006477356
Epoch 2692, Loss: 0.22430196404457092, Final Batch Loss: 0.11032316088676453
Epoch 2693, Loss: 0.33116209506988525, Final Batch Loss: 0.15977789461612701
Epoch 2694, Loss: 0.2699233666062355, Final Batch Loss: 0.11964190751314163
Epoch 2695, Loss: 0.3321460038423538, Final Batch Loss: 0.19643591344356537
Epoch 2696, Loss: 0.2652489021420479, Final Batch Loss: 0.14163804054260254
Epoch 2697, Loss: 0.2685747891664505, Final Batch Loss: 0.10212621092796326
Epoch 2698, Loss: 0.24051887542009354, Final Batch Loss: 0.11547672003507614
Epoch 2699, Loss: 0.2254823073744774, Final Batch Loss: 0.11491533368825912
Epoch 2700, Loss: 0.2879718244075775, Final Batch Loss: 0.1542058289051056
Epoch 27

Epoch 2799, Loss: 0.27218349277973175, Final Batch Loss: 0.15477699041366577
Epoch 2800, Loss: 0.25159019231796265, Final Batch Loss: 0.12409549951553345
Epoch 2801, Loss: 0.22027871012687683, Final Batch Loss: 0.0798395574092865
Epoch 2802, Loss: 0.24414902180433273, Final Batch Loss: 0.15042290091514587
Epoch 2803, Loss: 0.2278411164879799, Final Batch Loss: 0.10339109599590302
Epoch 2804, Loss: 0.24356873333454132, Final Batch Loss: 0.11378626525402069
Epoch 2805, Loss: 0.2436143085360527, Final Batch Loss: 0.13319110870361328
Epoch 2806, Loss: 0.2237779051065445, Final Batch Loss: 0.11940672248601913
Epoch 2807, Loss: 0.2587878480553627, Final Batch Loss: 0.11160881072282791
Epoch 2808, Loss: 0.22631032764911652, Final Batch Loss: 0.09198327362537384
Epoch 2809, Loss: 0.2180468663573265, Final Batch Loss: 0.07958569377660751
Epoch 2810, Loss: 0.270100362598896, Final Batch Loss: 0.10273555666208267
Epoch 2811, Loss: 0.26664792746305466, Final Batch Loss: 0.11702042073011398
Epoch 2

Epoch 2915, Loss: 0.22127970308065414, Final Batch Loss: 0.10204876214265823
Epoch 2916, Loss: 0.2179369404911995, Final Batch Loss: 0.10087397694587708
Epoch 2917, Loss: 0.2637737989425659, Final Batch Loss: 0.10655046999454498
Epoch 2918, Loss: 0.2630844861268997, Final Batch Loss: 0.13290543854236603
Epoch 2919, Loss: 0.3176860064268112, Final Batch Loss: 0.15852724015712738
Epoch 2920, Loss: 0.27918073534965515, Final Batch Loss: 0.1441691517829895
Epoch 2921, Loss: 0.27569419145584106, Final Batch Loss: 0.12515190243721008
Epoch 2922, Loss: 0.23905934393405914, Final Batch Loss: 0.13635756075382233
Epoch 2923, Loss: 0.22440333664417267, Final Batch Loss: 0.11608131974935532
Epoch 2924, Loss: 0.23216886073350906, Final Batch Loss: 0.10724730044603348
Epoch 2925, Loss: 0.25912078469991684, Final Batch Loss: 0.13734984397888184
Epoch 2926, Loss: 0.3036545664072037, Final Batch Loss: 0.1444447636604309
Epoch 2927, Loss: 0.20143283158540726, Final Batch Loss: 0.09656176716089249
Epoch 

Epoch 3029, Loss: 0.2105524241924286, Final Batch Loss: 0.10556483268737793
Epoch 3030, Loss: 0.22648869454860687, Final Batch Loss: 0.10251808166503906
Epoch 3031, Loss: 0.28478003293275833, Final Batch Loss: 0.16808290779590607
Epoch 3032, Loss: 0.21981295198202133, Final Batch Loss: 0.10890394449234009
Epoch 3033, Loss: 0.24079860001802444, Final Batch Loss: 0.12256354838609695
Epoch 3034, Loss: 0.21883874386548996, Final Batch Loss: 0.11945636570453644
Epoch 3035, Loss: 0.2599254697561264, Final Batch Loss: 0.13207602500915527
Epoch 3036, Loss: 0.26208260655403137, Final Batch Loss: 0.1416587382555008
Epoch 3037, Loss: 0.23679452389478683, Final Batch Loss: 0.1163991391658783
Epoch 3038, Loss: 0.28000298887491226, Final Batch Loss: 0.09915951639413834
Epoch 3039, Loss: 0.27213384956121445, Final Batch Loss: 0.14824818074703217
Epoch 3040, Loss: 0.4012550562620163, Final Batch Loss: 0.18587027490139008
Epoch 3041, Loss: 0.25698254257440567, Final Batch Loss: 0.1489938348531723
Epoch

Epoch 3138, Loss: 0.2714981883764267, Final Batch Loss: 0.1430426836013794
Epoch 3139, Loss: 0.2349041923880577, Final Batch Loss: 0.11948197335004807
Epoch 3140, Loss: 0.2390609160065651, Final Batch Loss: 0.09130669385194778
Epoch 3141, Loss: 0.22786714881658554, Final Batch Loss: 0.10900534689426422
Epoch 3142, Loss: 0.2273126021027565, Final Batch Loss: 0.09965609759092331
Epoch 3143, Loss: 0.23661485314369202, Final Batch Loss: 0.13947878777980804
Epoch 3144, Loss: 0.26333199441432953, Final Batch Loss: 0.13466747105121613
Epoch 3145, Loss: 0.2106342911720276, Final Batch Loss: 0.1008063405752182
Epoch 3146, Loss: 0.18573486804962158, Final Batch Loss: 0.0776372104883194
Epoch 3147, Loss: 0.2579740360379219, Final Batch Loss: 0.11697874218225479
Epoch 3148, Loss: 0.3026135712862015, Final Batch Loss: 0.17315611243247986
Epoch 3149, Loss: 0.23582520335912704, Final Batch Loss: 0.11438228189945221
Epoch 3150, Loss: 0.215752474963665, Final Batch Loss: 0.11783147603273392
Epoch 3151,

Epoch 3250, Loss: 0.20236290991306305, Final Batch Loss: 0.10052436590194702
Epoch 3251, Loss: 0.18508126586675644, Final Batch Loss: 0.09053251147270203
Epoch 3252, Loss: 0.2424556016921997, Final Batch Loss: 0.10744135081768036
Epoch 3253, Loss: 0.23383646458387375, Final Batch Loss: 0.06699300557374954
Epoch 3254, Loss: 0.22137143462896347, Final Batch Loss: 0.09179873019456863
Epoch 3255, Loss: 0.22791509330272675, Final Batch Loss: 0.11630207300186157
Epoch 3256, Loss: 0.23354802280664444, Final Batch Loss: 0.10000339895486832
Epoch 3257, Loss: 0.2775302082300186, Final Batch Loss: 0.09841981530189514
Epoch 3258, Loss: 0.22235605120658875, Final Batch Loss: 0.12480638176202774
Epoch 3259, Loss: 0.21337151527404785, Final Batch Loss: 0.11698401719331741
Epoch 3260, Loss: 0.21403437107801437, Final Batch Loss: 0.11320208758115768
Epoch 3261, Loss: 0.2443612515926361, Final Batch Loss: 0.09725040197372437
Epoch 3262, Loss: 0.2674379199743271, Final Batch Loss: 0.15160097181797028
Epo

Epoch 3363, Loss: 0.20526525378227234, Final Batch Loss: 0.08744468539953232
Epoch 3364, Loss: 0.2975437119603157, Final Batch Loss: 0.19236916303634644
Epoch 3365, Loss: 0.2798569053411484, Final Batch Loss: 0.11027009785175323
Epoch 3366, Loss: 0.22525806725025177, Final Batch Loss: 0.12296514958143234
Epoch 3367, Loss: 0.24065414816141129, Final Batch Loss: 0.13166053593158722
Epoch 3368, Loss: 0.2162443995475769, Final Batch Loss: 0.11194241046905518
Epoch 3369, Loss: 0.24679017812013626, Final Batch Loss: 0.1271936446428299
Epoch 3370, Loss: 0.24417119473218918, Final Batch Loss: 0.1383381485939026
Epoch 3371, Loss: 0.264143630862236, Final Batch Loss: 0.14385396242141724
Epoch 3372, Loss: 0.287056639790535, Final Batch Loss: 0.12443973124027252
Epoch 3373, Loss: 0.26306329667568207, Final Batch Loss: 0.14549648761749268
Epoch 3374, Loss: 0.2090723216533661, Final Batch Loss: 0.1018805205821991
Epoch 3375, Loss: 0.26320379972457886, Final Batch Loss: 0.12030045688152313
Epoch 3376

Epoch 3476, Loss: 0.215321883559227, Final Batch Loss: 0.1210714653134346
Epoch 3477, Loss: 0.2564636543393135, Final Batch Loss: 0.14498312771320343
Epoch 3478, Loss: 0.22634176909923553, Final Batch Loss: 0.09826509654521942
Epoch 3479, Loss: 0.2627779245376587, Final Batch Loss: 0.11581757664680481
Epoch 3480, Loss: 0.2566814497113228, Final Batch Loss: 0.12077780812978745
Epoch 3481, Loss: 0.27078964561223984, Final Batch Loss: 0.1644687056541443
Epoch 3482, Loss: 0.18961891531944275, Final Batch Loss: 0.09616480767726898
Epoch 3483, Loss: 0.2172459214925766, Final Batch Loss: 0.0719815194606781
Epoch 3484, Loss: 0.23943208158016205, Final Batch Loss: 0.11054527759552002
Epoch 3485, Loss: 0.2201155200600624, Final Batch Loss: 0.12244484573602676
Epoch 3486, Loss: 0.2076953500509262, Final Batch Loss: 0.08746041357517242
Epoch 3487, Loss: 0.25947244465351105, Final Batch Loss: 0.1441468894481659
Epoch 3488, Loss: 0.21604245901107788, Final Batch Loss: 0.08997085690498352
Epoch 3489,

Epoch 3592, Loss: 0.29694129526615143, Final Batch Loss: 0.16195295751094818
Epoch 3593, Loss: 0.21316228061914444, Final Batch Loss: 0.09563028067350388
Epoch 3594, Loss: 0.21453631669282913, Final Batch Loss: 0.12083178013563156
Epoch 3595, Loss: 0.2187388464808464, Final Batch Loss: 0.10962849855422974
Epoch 3596, Loss: 0.19431065768003464, Final Batch Loss: 0.09050393849611282
Epoch 3597, Loss: 0.2132871001958847, Final Batch Loss: 0.08900380879640579
Epoch 3598, Loss: 0.16801823675632477, Final Batch Loss: 0.06616024672985077
Epoch 3599, Loss: 0.2879345268011093, Final Batch Loss: 0.12595823407173157
Epoch 3600, Loss: 0.22750310599803925, Final Batch Loss: 0.10313680768013
Epoch 3601, Loss: 0.2709273062646389, Final Batch Loss: 0.21302413940429688
Epoch 3602, Loss: 0.19984447583556175, Final Batch Loss: 0.060775768011808395
Epoch 3603, Loss: 0.2220560535788536, Final Batch Loss: 0.1263604313135147
Epoch 3604, Loss: 0.1865561679005623, Final Batch Loss: 0.07996935397386551
Epoch 36

Epoch 3703, Loss: 0.21398115158081055, Final Batch Loss: 0.10963359475135803
Epoch 3704, Loss: 0.20962174981832504, Final Batch Loss: 0.11910473555326462
Epoch 3705, Loss: 0.2123376429080963, Final Batch Loss: 0.08072984218597412
Epoch 3706, Loss: 0.16990721225738525, Final Batch Loss: 0.09262620657682419
Epoch 3707, Loss: 0.1820158064365387, Final Batch Loss: 0.07511475682258606
Epoch 3708, Loss: 0.19137389212846756, Final Batch Loss: 0.10522691160440445
Epoch 3709, Loss: 0.19603734463453293, Final Batch Loss: 0.11275309324264526
Epoch 3710, Loss: 0.21267540752887726, Final Batch Loss: 0.10929439961910248
Epoch 3711, Loss: 0.2265162616968155, Final Batch Loss: 0.10812250524759293
Epoch 3712, Loss: 0.21641825139522552, Final Batch Loss: 0.12213499844074249
Epoch 3713, Loss: 0.3059885501861572, Final Batch Loss: 0.1822478324174881
Epoch 3714, Loss: 0.21583443880081177, Final Batch Loss: 0.1083621084690094
Epoch 3715, Loss: 0.2315906658768654, Final Batch Loss: 0.0890347883105278
Epoch 3

Epoch 3830, Loss: 0.2837041765451431, Final Batch Loss: 0.15073162317276
Epoch 3831, Loss: 0.20267264544963837, Final Batch Loss: 0.14086106419563293
Epoch 3832, Loss: 0.18061362206935883, Final Batch Loss: 0.09632886946201324
Epoch 3833, Loss: 0.26652873307466507, Final Batch Loss: 0.17396663129329681
Epoch 3834, Loss: 0.2345290258526802, Final Batch Loss: 0.10042452067136765
Epoch 3835, Loss: 0.21630462259054184, Final Batch Loss: 0.09685155749320984
Epoch 3836, Loss: 0.23485197871923447, Final Batch Loss: 0.09112515300512314
Epoch 3837, Loss: 0.23576293885707855, Final Batch Loss: 0.1300175040960312
Epoch 3838, Loss: 0.22019027173519135, Final Batch Loss: 0.10791532695293427
Epoch 3839, Loss: 0.2640102803707123, Final Batch Loss: 0.1455094963312149
Epoch 3840, Loss: 0.17792188376188278, Final Batch Loss: 0.06164361536502838
Epoch 3841, Loss: 0.23686788976192474, Final Batch Loss: 0.09610363841056824
Epoch 3842, Loss: 0.1985326111316681, Final Batch Loss: 0.10557525604963303
Epoch 38

Epoch 3938, Loss: 0.18611066043376923, Final Batch Loss: 0.08621921390295029
Epoch 3939, Loss: 0.16932176053524017, Final Batch Loss: 0.08211973309516907
Epoch 3940, Loss: 0.15699893981218338, Final Batch Loss: 0.0910646840929985
Epoch 3941, Loss: 0.23553314059972763, Final Batch Loss: 0.07877988368272781
Epoch 3942, Loss: 0.20998472720384598, Final Batch Loss: 0.10634835809469223
Epoch 3943, Loss: 0.1420009881258011, Final Batch Loss: 0.07759107649326324
Epoch 3944, Loss: 0.2124883085489273, Final Batch Loss: 0.10061952471733093
Epoch 3945, Loss: 0.2771241217851639, Final Batch Loss: 0.14515724778175354
Epoch 3946, Loss: 0.2383321225643158, Final Batch Loss: 0.09552685916423798
Epoch 3947, Loss: 0.18522564321756363, Final Batch Loss: 0.07894061505794525
Epoch 3948, Loss: 0.21687740087509155, Final Batch Loss: 0.09744006395339966
Epoch 3949, Loss: 0.19229572266340256, Final Batch Loss: 0.09637434035539627
Epoch 3950, Loss: 0.22999095916748047, Final Batch Loss: 0.09629261493682861
Epoc

Epoch 4059, Loss: 0.2695607915520668, Final Batch Loss: 0.17719420790672302
Epoch 4060, Loss: 0.2686605006456375, Final Batch Loss: 0.15724815428256989
Epoch 4061, Loss: 0.2287389636039734, Final Batch Loss: 0.1481473296880722
Epoch 4062, Loss: 0.17802376300096512, Final Batch Loss: 0.09066269546747208
Epoch 4063, Loss: 0.20113815367221832, Final Batch Loss: 0.10961273312568665
Epoch 4064, Loss: 0.18393423408269882, Final Batch Loss: 0.07369038462638855
Epoch 4065, Loss: 0.23120646178722382, Final Batch Loss: 0.10716444998979568
Epoch 4066, Loss: 0.24738386273384094, Final Batch Loss: 0.13927064836025238
Epoch 4067, Loss: 0.2331554815173149, Final Batch Loss: 0.09651792794466019
Epoch 4068, Loss: 0.19352492690086365, Final Batch Loss: 0.10599546134471893
Epoch 4069, Loss: 0.22993237525224686, Final Batch Loss: 0.13149435818195343
Epoch 4070, Loss: 0.1956857442855835, Final Batch Loss: 0.10666351020336151
Epoch 4071, Loss: 0.24116861075162888, Final Batch Loss: 0.12660491466522217
Epoch

Epoch 4174, Loss: 0.1601208820939064, Final Batch Loss: 0.08479275554418564
Epoch 4175, Loss: 0.1752643957734108, Final Batch Loss: 0.07767137140035629
Epoch 4176, Loss: 0.2727896720170975, Final Batch Loss: 0.14381225407123566
Epoch 4177, Loss: 0.2428603544831276, Final Batch Loss: 0.08818113058805466
Epoch 4178, Loss: 0.18952252715826035, Final Batch Loss: 0.10394711047410965
Epoch 4179, Loss: 0.20984070003032684, Final Batch Loss: 0.08500539511442184
Epoch 4180, Loss: 0.23521418869495392, Final Batch Loss: 0.10250137746334076
Epoch 4181, Loss: 0.2500186413526535, Final Batch Loss: 0.1003512293100357
Epoch 4182, Loss: 0.191641204059124, Final Batch Loss: 0.08798442780971527
Epoch 4183, Loss: 0.15086696296930313, Final Batch Loss: 0.07019005715847015
Epoch 4184, Loss: 0.22051449120044708, Final Batch Loss: 0.1128244623541832
Epoch 4185, Loss: 0.24119746685028076, Final Batch Loss: 0.13216009736061096
Epoch 4186, Loss: 0.23921848088502884, Final Batch Loss: 0.10873889178037643
Epoch 41

Epoch 4291, Loss: 0.18921218067407608, Final Batch Loss: 0.08995375037193298
Epoch 4292, Loss: 0.2741275578737259, Final Batch Loss: 0.13523197174072266
Epoch 4293, Loss: 0.2255922257900238, Final Batch Loss: 0.12094948440790176
Epoch 4294, Loss: 0.20385073125362396, Final Batch Loss: 0.09876798093318939
Epoch 4295, Loss: 0.168556809425354, Final Batch Loss: 0.06298995763063431
Epoch 4296, Loss: 0.1868097335100174, Final Batch Loss: 0.07261110097169876
Epoch 4297, Loss: 0.2101231887936592, Final Batch Loss: 0.09629864990711212
Epoch 4298, Loss: 0.19019784033298492, Final Batch Loss: 0.09074543416500092
Epoch 4299, Loss: 0.2026345133781433, Final Batch Loss: 0.12210948765277863
Epoch 4300, Loss: 0.19204805046319962, Final Batch Loss: 0.08751161396503448
Epoch 4301, Loss: 0.19696424156427383, Final Batch Loss: 0.06950251013040543
Epoch 4302, Loss: 0.2054816037416458, Final Batch Loss: 0.11923743784427643
Epoch 4303, Loss: 0.20923857390880585, Final Batch Loss: 0.114964559674263
Epoch 430

Epoch 4406, Loss: 0.2139115110039711, Final Batch Loss: 0.12842020392417908
Epoch 4407, Loss: 0.20871637761592865, Final Batch Loss: 0.08181199431419373
Epoch 4408, Loss: 0.20539335906505585, Final Batch Loss: 0.09237633645534515
Epoch 4409, Loss: 0.22394836694002151, Final Batch Loss: 0.10509897023439407
Epoch 4410, Loss: 0.15431901812553406, Final Batch Loss: 0.06785985827445984
Epoch 4411, Loss: 0.1882471777498722, Final Batch Loss: 0.057287994772195816
Epoch 4412, Loss: 0.2417389452457428, Final Batch Loss: 0.09803387522697449
Epoch 4413, Loss: 0.2197195142507553, Final Batch Loss: 0.11218562722206116
Epoch 4414, Loss: 0.21553116291761398, Final Batch Loss: 0.09660731256008148
Epoch 4415, Loss: 0.20945563167333603, Final Batch Loss: 0.09657447785139084
Epoch 4416, Loss: 0.20624800026416779, Final Batch Loss: 0.1251566857099533
Epoch 4417, Loss: 0.2597530260682106, Final Batch Loss: 0.16237476468086243
Epoch 4418, Loss: 0.17576471716165543, Final Batch Loss: 0.07011570781469345
Epoc

Epoch 4518, Loss: 0.1668444164097309, Final Batch Loss: 0.1100020632147789
Epoch 4519, Loss: 0.2059701830148697, Final Batch Loss: 0.08603398501873016
Epoch 4520, Loss: 0.23608415573835373, Final Batch Loss: 0.09993945807218552
Epoch 4521, Loss: 0.23288236558437347, Final Batch Loss: 0.09875084459781647
Epoch 4522, Loss: 0.17573243379592896, Final Batch Loss: 0.09130340814590454
Epoch 4523, Loss: 0.18571529537439346, Final Batch Loss: 0.08968599140644073
Epoch 4524, Loss: 0.19986506551504135, Final Batch Loss: 0.0968710407614708
Epoch 4525, Loss: 0.20462344586849213, Final Batch Loss: 0.10711982101202011
Epoch 4526, Loss: 0.2676045298576355, Final Batch Loss: 0.13236522674560547
Epoch 4527, Loss: 0.17843003571033478, Final Batch Loss: 0.07257962971925735
Epoch 4528, Loss: 0.20055659860372543, Final Batch Loss: 0.10855059325695038
Epoch 4529, Loss: 0.20439647883176804, Final Batch Loss: 0.11513368785381317
Epoch 4530, Loss: 0.20000071078538895, Final Batch Loss: 0.08150676637887955
Epoc

Epoch 4636, Loss: 0.15238391235470772, Final Batch Loss: 0.09009139984846115
Epoch 4637, Loss: 0.20141932368278503, Final Batch Loss: 0.10314254462718964
Epoch 4638, Loss: 0.18422629684209824, Final Batch Loss: 0.09022717922925949
Epoch 4639, Loss: 0.20870241522789001, Final Batch Loss: 0.08962642401456833
Epoch 4640, Loss: 0.19989404827356339, Final Batch Loss: 0.09231524914503098
Epoch 4641, Loss: 0.19651976227760315, Final Batch Loss: 0.112610824406147
Epoch 4642, Loss: 0.18813510239124298, Final Batch Loss: 0.10565947741270065
Epoch 4643, Loss: 0.20834166556596756, Final Batch Loss: 0.0881551131606102
Epoch 4644, Loss: 0.17047658562660217, Final Batch Loss: 0.09241954982280731
Epoch 4645, Loss: 0.2607981264591217, Final Batch Loss: 0.1185552328824997
Epoch 4646, Loss: 0.2322218418121338, Final Batch Loss: 0.11372315138578415
Epoch 4647, Loss: 0.16266833990812302, Final Batch Loss: 0.07645126432180405
Epoch 4648, Loss: 0.15770956873893738, Final Batch Loss: 0.08314591646194458
Epoch

Epoch 4749, Loss: 0.28399017453193665, Final Batch Loss: 0.15336918830871582
Epoch 4750, Loss: 0.23474711179733276, Final Batch Loss: 0.13463762402534485
Epoch 4751, Loss: 0.2307855263352394, Final Batch Loss: 0.1300041228532791
Epoch 4752, Loss: 0.26670345664024353, Final Batch Loss: 0.17347675561904907
Epoch 4753, Loss: 0.26941056549549103, Final Batch Loss: 0.12826482951641083
Epoch 4754, Loss: 0.22752974927425385, Final Batch Loss: 0.12028849869966507
Epoch 4755, Loss: 0.20894590020179749, Final Batch Loss: 0.09654133766889572
Epoch 4756, Loss: 0.20990563929080963, Final Batch Loss: 0.09953456372022629
Epoch 4757, Loss: 0.19756988435983658, Final Batch Loss: 0.09372326731681824
Epoch 4758, Loss: 0.1957097202539444, Final Batch Loss: 0.11456121504306793
Epoch 4759, Loss: 0.20837201923131943, Final Batch Loss: 0.11520858108997345
Epoch 4760, Loss: 0.19560855627059937, Final Batch Loss: 0.11533891409635544
Epoch 4761, Loss: 0.15203744918107986, Final Batch Loss: 0.07326235622167587
Ep

Epoch 4859, Loss: 0.26455050706863403, Final Batch Loss: 0.1138475239276886
Epoch 4860, Loss: 0.2599454000592232, Final Batch Loss: 0.12197015434503555
Epoch 4861, Loss: 0.19420651346445084, Final Batch Loss: 0.08276506513357162
Epoch 4862, Loss: 0.15331781655550003, Final Batch Loss: 0.06389104574918747
Epoch 4863, Loss: 0.177162803709507, Final Batch Loss: 0.08785537630319595
Epoch 4864, Loss: 0.22552762925624847, Final Batch Loss: 0.13588951528072357
Epoch 4865, Loss: 0.1968330442905426, Final Batch Loss: 0.08307918906211853
Epoch 4866, Loss: 0.19885173439979553, Final Batch Loss: 0.0743386521935463
Epoch 4867, Loss: 0.33716531842947006, Final Batch Loss: 0.12305449694395065
Epoch 4868, Loss: 0.23019421845674515, Final Batch Loss: 0.12749667465686798
Epoch 4869, Loss: 0.2020956501364708, Final Batch Loss: 0.11966279149055481
Epoch 4870, Loss: 0.17093275487422943, Final Batch Loss: 0.08728935569524765
Epoch 4871, Loss: 0.20697277784347534, Final Batch Loss: 0.11963632702827454
Epoch 

Epoch 4980, Loss: 0.2877914607524872, Final Batch Loss: 0.10279883444309235
Epoch 4981, Loss: 0.20472519099712372, Final Batch Loss: 0.10892688482999802
Epoch 4982, Loss: 0.1781422197818756, Final Batch Loss: 0.1073606088757515
Epoch 4983, Loss: 0.21320762485265732, Final Batch Loss: 0.11308258026838303
Epoch 4984, Loss: 0.23650283366441727, Final Batch Loss: 0.12185713648796082
Epoch 4985, Loss: 0.1839320883154869, Final Batch Loss: 0.09868413954973221
Epoch 4986, Loss: 0.15097910165786743, Final Batch Loss: 0.07208126038312912
Epoch 4987, Loss: 0.25510965287685394, Final Batch Loss: 0.12887461483478546
Epoch 4988, Loss: 0.2018863782286644, Final Batch Loss: 0.10436046123504639
Epoch 4989, Loss: 0.18235743790864944, Final Batch Loss: 0.10025032609701157
Epoch 4990, Loss: 0.21616791188716888, Final Batch Loss: 0.10076625645160675
Epoch 4991, Loss: 0.1842346414923668, Final Batch Loss: 0.07780791819095612
Epoch 4992, Loss: 0.17827627062797546, Final Batch Loss: 0.07654419541358948
Epoch

In [9]:
softmax = nn.Softmax(dim = 1)
model.train()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[15  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0]
 [ 0  0  0  0 16  0  0  0  0]
 [ 0  0  3  0  0  8  0  0  1]
 [ 0  0  0  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  0 11  0]
 [ 0  0  1  0  0  1  0  0 15]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        15
           1    1.00000   1.00000   1.00000         6
           2    0.71429   1.00000   0.83333        10
           3    1.00000   1.00000   1.00000        16
           4    1.00000   1.00000   1.00000        16
           5    0.88889   0.66667   0.76190        12
           6    1.00000   1.00000   1.00000         7
           7    1.00000   1.00000   1.00000        11
           8    0.93750   0.88235   0.90909        17

    accuracy                        0.94545       110
   macro avg    0.94896   0.94989   0.94493       110
weighted avg    0.95225   0.94545   0.94482       110



# Train on Fake Test on Real

In [10]:
# 20,000 epochs DEFAULT PARAMETERS FOR THRESHOLDS

In [11]:
gen = Generator(z_dim = 106)
load_model(gen, "cGAN_UCI_Group_5_gen.param")
gen.eval()

Generator(
  (gen): Sequential(
    (0): Sequential(
      (0): Linear(in_features=106, out_features=80, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Linear(in_features=80, out_features=60, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (2): Sequential(
      (0): Linear(in_features=60, out_features=50, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (3): Linear(in_features=50, out_features=46, bias=True)
    (4): Tanh()
  )
)

In [12]:
size = len(X_test)
latent_vectors = get_noise(size, 100)
act_vectors = get_act_matrix(size, 3)
usr_vectors = get_usr_matrix(size, 3)

fake_labels = []

for k in range(size):
    if act_vectors[0][k] == 0 and usr_vectors[0][k] == 0:
        fake_labels.append(0)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 0:
        fake_labels.append(1)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 0:
        fake_labels.append(2)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 1:
        fake_labels.append(3)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 1:
        fake_labels.append(4)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 1:
        fake_labels.append(5)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 2:
        fake_labels.append(6)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 2:
        fake_labels.append(7)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 2:
        fake_labels.append(8)

fake_labels = np.asarray(fake_labels)
to_gen = torch.cat((latent_vectors, act_vectors[1], usr_vectors[1]), 1)
fake_features = gen(to_gen).detach()
#fake_features = gen(to_gen).detach().numpy()

In [13]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5, zero_division = 0))

[[13  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0]
 [ 0  0  0 15  1  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  2]
 [ 0  0  0  0  1  0 11  0  0]
 [ 0  0  0  0  0  0  0 13  0]
 [ 0  0  0  0  0  0  0  0 10]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        13
           1    1.00000   1.00000   1.00000        19
           2    1.00000   1.00000   1.00000         8
           3    1.00000   0.93750   0.96774        16
           4    0.77778   1.00000   0.87500         7
           5    1.00000   0.83333   0.90909        12
           6    1.00000   0.91667   0.95652        12
           7    1.00000   1.00000   1.00000        13
           8    0.83333   1.00000   0.90909        10

    accuracy                        0.96364       110
   macro avg    0.95679   0.96528   0.95749       110
weighted avg    0.97071   0.96364   0.96443       110

