In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '59 tGravityAcc-energy()-Z',
 '125 tBodyGyro-std()-Y',
 '128 tBodyGyro-mad()-Y',
 '138 tBodyGyro-energy()-Y',
 '165 tBodyGyroJerk-std()-Y',
 '168 tBodyGyroJerk-mad()-Y',
 '178 tBodyGyroJerk-energy()-Y',
 '181 tBodyGyroJerk-iqr()-Y',
 '425 fBodyGyro-mean()-Y',
 '428 fBodyGyro-std()-Y',
 '431 fBodyGyro-mad()-Y',
 '441 fBodyGyro-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '478 fBodyGyro-bandsEnergy()-25,32',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '204 tBodyAccMag-max()',
 '215 tGravityAccMag-std()',
 '217 tGravityAccMag-max()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '275 fBodyAcc-max()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '506 fBodyAccMag-max()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            classifier_block(15, 10),
            nn.Linear(10, 9)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../saved_models/{model_name}'))

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']

    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 23) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 25) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 27) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [23, 25, 27]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [7]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 4.417480230331421, Final Batch Loss: 2.203195095062256
Epoch 2, Loss: 4.4155333042144775, Final Batch Loss: 2.214625835418701
Epoch 3, Loss: 4.410343408584595, Final Batch Loss: 2.1888551712036133
Epoch 4, Loss: 4.402981758117676, Final Batch Loss: 2.189234972000122
Epoch 5, Loss: 4.395047903060913, Final Batch Loss: 2.2000443935394287
Epoch 6, Loss: 4.392462730407715, Final Batch Loss: 2.189796209335327
Epoch 7, Loss: 4.3924713134765625, Final Batch Loss: 2.191723108291626
Epoch 8, Loss: 4.386497497558594, Final Batch Loss: 2.1944785118103027
Epoch 9, Loss: 4.378002882003784, Final Batch Loss: 2.1860768795013428
Epoch 10, Loss: 4.372597932815552, Final Batch Loss: 2.187197685241699
Epoch 11, Loss: 4.366967439651489, Final Batch Loss: 2.158565044403076
Epoch 12, Loss: 4.362393617630005, Final Batch Loss: 2.18190598487854
Epoch 13, Loss: 4.357719898223877, Final Batch Loss: 2.1699423789978027
Epoch 14, Loss: 4.340387582778931, Final Batch Loss: 2.166548728942871
Epoch 15,

Epoch 127, Loss: 2.0656813383102417, Final Batch Loss: 0.9936341047286987
Epoch 128, Loss: 2.101752281188965, Final Batch Loss: 1.0237901210784912
Epoch 129, Loss: 2.0289372205734253, Final Batch Loss: 1.007084608078003
Epoch 130, Loss: 2.110980272293091, Final Batch Loss: 1.0902070999145508
Epoch 131, Loss: 2.1069328784942627, Final Batch Loss: 1.0688987970352173
Epoch 132, Loss: 2.0414472818374634, Final Batch Loss: 1.0075476169586182
Epoch 133, Loss: 2.0814130306243896, Final Batch Loss: 1.066582441329956
Epoch 134, Loss: 2.093071937561035, Final Batch Loss: 1.050696611404419
Epoch 135, Loss: 2.0031570196151733, Final Batch Loss: 0.9957283735275269
Epoch 136, Loss: 2.065882444381714, Final Batch Loss: 1.0061935186386108
Epoch 137, Loss: 2.0617074966430664, Final Batch Loss: 1.0420551300048828
Epoch 138, Loss: 2.0017667412757874, Final Batch Loss: 0.9853231310844421
Epoch 139, Loss: 2.0015493631362915, Final Batch Loss: 1.0143135786056519
Epoch 140, Loss: 2.1015809774398804, Final Ba

Epoch 239, Loss: 1.3689220547676086, Final Batch Loss: 0.6552038788795471
Epoch 240, Loss: 1.3317305445671082, Final Batch Loss: 0.6627016067504883
Epoch 241, Loss: 1.339768409729004, Final Batch Loss: 0.626476526260376
Epoch 242, Loss: 1.379750669002533, Final Batch Loss: 0.6745806336402893
Epoch 243, Loss: 1.4434533715248108, Final Batch Loss: 0.7930467128753662
Epoch 244, Loss: 1.3598390817642212, Final Batch Loss: 0.711434006690979
Epoch 245, Loss: 1.4444997906684875, Final Batch Loss: 0.6954709887504578
Epoch 246, Loss: 1.3558059334754944, Final Batch Loss: 0.6632834076881409
Epoch 247, Loss: 1.2709822058677673, Final Batch Loss: 0.6138315796852112
Epoch 248, Loss: 1.3396541476249695, Final Batch Loss: 0.6736400723457336
Epoch 249, Loss: 1.3123886585235596, Final Batch Loss: 0.6411944627761841
Epoch 250, Loss: 1.3880318999290466, Final Batch Loss: 0.6797888875007629
Epoch 251, Loss: 1.3222402930259705, Final Batch Loss: 0.6054357886314392
Epoch 252, Loss: 1.2667637467384338, Final

Epoch 350, Loss: 1.045074701309204, Final Batch Loss: 0.5305483937263489
Epoch 351, Loss: 1.0662768483161926, Final Batch Loss: 0.5579493045806885
Epoch 352, Loss: 1.097410798072815, Final Batch Loss: 0.5760346055030823
Epoch 353, Loss: 1.087701678276062, Final Batch Loss: 0.5352252721786499
Epoch 354, Loss: 1.021436870098114, Final Batch Loss: 0.50831139087677
Epoch 355, Loss: 1.1161799430847168, Final Batch Loss: 0.5912328362464905
Epoch 356, Loss: 1.1757263541221619, Final Batch Loss: 0.5586245656013489
Epoch 357, Loss: 1.1771308779716492, Final Batch Loss: 0.6009085774421692
Epoch 358, Loss: 1.1748434901237488, Final Batch Loss: 0.6184618473052979
Epoch 359, Loss: 1.0931630730628967, Final Batch Loss: 0.5713986754417419
Epoch 360, Loss: 1.0408830642700195, Final Batch Loss: 0.4773048162460327
Epoch 361, Loss: 1.1155487298965454, Final Batch Loss: 0.5545969009399414
Epoch 362, Loss: 1.11543208360672, Final Batch Loss: 0.5703341960906982
Epoch 363, Loss: 1.1309600472450256, Final Bat

Epoch 475, Loss: 0.9678649008274078, Final Batch Loss: 0.46565255522727966
Epoch 476, Loss: 0.9565528631210327, Final Batch Loss: 0.4426443576812744
Epoch 477, Loss: 1.0456750690937042, Final Batch Loss: 0.48799750208854675
Epoch 478, Loss: 1.0082806646823883, Final Batch Loss: 0.5316212773323059
Epoch 479, Loss: 1.006066918373108, Final Batch Loss: 0.5073798298835754
Epoch 480, Loss: 0.9936303198337555, Final Batch Loss: 0.524957537651062
Epoch 481, Loss: 0.976846843957901, Final Batch Loss: 0.48921477794647217
Epoch 482, Loss: 1.0118446350097656, Final Batch Loss: 0.5194612741470337
Epoch 483, Loss: 1.0436438918113708, Final Batch Loss: 0.5208855271339417
Epoch 484, Loss: 1.0604056417942047, Final Batch Loss: 0.5613831281661987
Epoch 485, Loss: 0.9543739855289459, Final Batch Loss: 0.49662744998931885
Epoch 486, Loss: 0.9880968332290649, Final Batch Loss: 0.5320672988891602
Epoch 487, Loss: 1.0062196254730225, Final Batch Loss: 0.534880518913269
Epoch 488, Loss: 1.0334275364875793, F

Epoch 592, Loss: 0.9964599609375, Final Batch Loss: 0.5054903626441956
Epoch 593, Loss: 0.9208477437496185, Final Batch Loss: 0.48669227957725525
Epoch 594, Loss: 0.9415829479694366, Final Batch Loss: 0.49263638257980347
Epoch 595, Loss: 0.8646248579025269, Final Batch Loss: 0.4146944582462311
Epoch 596, Loss: 0.9470462501049042, Final Batch Loss: 0.5313454866409302
Epoch 597, Loss: 0.944146066904068, Final Batch Loss: 0.45504269003868103
Epoch 598, Loss: 0.9335022568702698, Final Batch Loss: 0.41171789169311523
Epoch 599, Loss: 0.9511077105998993, Final Batch Loss: 0.5145350098609924
Epoch 600, Loss: 0.9237573146820068, Final Batch Loss: 0.48407962918281555
Epoch 601, Loss: 0.956861287355423, Final Batch Loss: 0.4631538689136505
Epoch 602, Loss: 0.9213549494743347, Final Batch Loss: 0.4094812273979187
Epoch 603, Loss: 0.8641766011714935, Final Batch Loss: 0.4139324426651001
Epoch 604, Loss: 0.8805693686008453, Final Batch Loss: 0.42063117027282715
Epoch 605, Loss: 0.9274593889713287, 

Epoch 702, Loss: 0.8683772385120392, Final Batch Loss: 0.4397163987159729
Epoch 703, Loss: 0.8957070708274841, Final Batch Loss: 0.44667476415634155
Epoch 704, Loss: 0.9033637046813965, Final Batch Loss: 0.39502793550491333
Epoch 705, Loss: 0.9270159006118774, Final Batch Loss: 0.4574538469314575
Epoch 706, Loss: 0.9098430573940277, Final Batch Loss: 0.43897485733032227
Epoch 707, Loss: 0.8951475024223328, Final Batch Loss: 0.43122023344039917
Epoch 708, Loss: 0.8793597519397736, Final Batch Loss: 0.42478546500205994
Epoch 709, Loss: 0.8486822545528412, Final Batch Loss: 0.42374199628829956
Epoch 710, Loss: 0.9119121432304382, Final Batch Loss: 0.43450015783309937
Epoch 711, Loss: 0.8840434551239014, Final Batch Loss: 0.4601157307624817
Epoch 712, Loss: 0.9418776333332062, Final Batch Loss: 0.46260741353034973
Epoch 713, Loss: 0.9324363768100739, Final Batch Loss: 0.4943886697292328
Epoch 714, Loss: 0.8460571765899658, Final Batch Loss: 0.4281569719314575
Epoch 715, Loss: 0.89866492152

Epoch 833, Loss: 0.8914288878440857, Final Batch Loss: 0.43980395793914795
Epoch 834, Loss: 0.8634907007217407, Final Batch Loss: 0.45396924018859863
Epoch 835, Loss: 0.9424755275249481, Final Batch Loss: 0.5004832148551941
Epoch 836, Loss: 0.854905515909195, Final Batch Loss: 0.4331631064414978
Epoch 837, Loss: 0.8857055306434631, Final Batch Loss: 0.4825432598590851
Epoch 838, Loss: 0.7998948395252228, Final Batch Loss: 0.37640324234962463
Epoch 839, Loss: 0.8852412104606628, Final Batch Loss: 0.40659791231155396
Epoch 840, Loss: 0.9106811583042145, Final Batch Loss: 0.4465855658054352
Epoch 841, Loss: 0.8348996937274933, Final Batch Loss: 0.4098266065120697
Epoch 842, Loss: 0.8383592963218689, Final Batch Loss: 0.38448649644851685
Epoch 843, Loss: 0.89548259973526, Final Batch Loss: 0.483213871717453
Epoch 844, Loss: 0.8906817436218262, Final Batch Loss: 0.42323774099349976
Epoch 845, Loss: 0.808971494436264, Final Batch Loss: 0.43154072761535645
Epoch 846, Loss: 0.8220786452293396,

Epoch 947, Loss: 0.8511689007282257, Final Batch Loss: 0.43692752718925476
Epoch 948, Loss: 0.9012284874916077, Final Batch Loss: 0.45106109976768494
Epoch 949, Loss: 0.7926271259784698, Final Batch Loss: 0.3997502028942108
Epoch 950, Loss: 0.7854094505310059, Final Batch Loss: 0.37706154584884644
Epoch 951, Loss: 0.8242017924785614, Final Batch Loss: 0.41606706380844116
Epoch 952, Loss: 0.7830191552639008, Final Batch Loss: 0.3961077928543091
Epoch 953, Loss: 0.8034426271915436, Final Batch Loss: 0.39187783002853394
Epoch 954, Loss: 0.8605064153671265, Final Batch Loss: 0.4704357385635376
Epoch 955, Loss: 0.786747395992279, Final Batch Loss: 0.39382174611091614
Epoch 956, Loss: 0.8270225524902344, Final Batch Loss: 0.36690545082092285
Epoch 957, Loss: 0.8089015185832977, Final Batch Loss: 0.3928777575492859
Epoch 958, Loss: 0.7867761850357056, Final Batch Loss: 0.3605116903781891
Epoch 959, Loss: 0.8140745162963867, Final Batch Loss: 0.4058776795864105
Epoch 960, Loss: 0.8053479790687

Epoch 1071, Loss: 0.7875319123268127, Final Batch Loss: 0.4061829149723053
Epoch 1072, Loss: 0.8306678235530853, Final Batch Loss: 0.4313695728778839
Epoch 1073, Loss: 0.8093723654747009, Final Batch Loss: 0.43518295884132385
Epoch 1074, Loss: 0.8346525430679321, Final Batch Loss: 0.4545522928237915
Epoch 1075, Loss: 0.7445974946022034, Final Batch Loss: 0.32428163290023804
Epoch 1076, Loss: 0.7875992953777313, Final Batch Loss: 0.38178107142448425
Epoch 1077, Loss: 0.7625885009765625, Final Batch Loss: 0.37745675444602966
Epoch 1078, Loss: 0.8488878607749939, Final Batch Loss: 0.4296974241733551
Epoch 1079, Loss: 0.818575382232666, Final Batch Loss: 0.4258412718772888
Epoch 1080, Loss: 0.8068414926528931, Final Batch Loss: 0.43360230326652527
Epoch 1081, Loss: 0.8470478057861328, Final Batch Loss: 0.44962653517723083
Epoch 1082, Loss: 0.8255018591880798, Final Batch Loss: 0.4798811972141266
Epoch 1083, Loss: 0.799907773733139, Final Batch Loss: 0.4346306324005127
Epoch 1084, Loss: 0.8

Epoch 1183, Loss: 0.7533906400203705, Final Batch Loss: 0.29742586612701416
Epoch 1184, Loss: 0.786393791437149, Final Batch Loss: 0.4091012477874756
Epoch 1185, Loss: 0.7843860685825348, Final Batch Loss: 0.37837764620780945
Epoch 1186, Loss: 0.7785367071628571, Final Batch Loss: 0.39612171053886414
Epoch 1187, Loss: 0.7852270901203156, Final Batch Loss: 0.3966948986053467
Epoch 1188, Loss: 0.7788385450839996, Final Batch Loss: 0.408953994512558
Epoch 1189, Loss: 0.7867602705955505, Final Batch Loss: 0.409271776676178
Epoch 1190, Loss: 0.7537384927272797, Final Batch Loss: 0.3801635801792145
Epoch 1191, Loss: 0.7303411066532135, Final Batch Loss: 0.29248595237731934
Epoch 1192, Loss: 0.7277356386184692, Final Batch Loss: 0.3342595398426056
Epoch 1193, Loss: 0.8242290914058685, Final Batch Loss: 0.38055843114852905
Epoch 1194, Loss: 0.778380960226059, Final Batch Loss: 0.37695232033729553
Epoch 1195, Loss: 0.7659035623073578, Final Batch Loss: 0.3902861475944519
Epoch 1196, Loss: 0.755

Epoch 1292, Loss: 0.7561070919036865, Final Batch Loss: 0.3586002290248871
Epoch 1293, Loss: 0.7921251058578491, Final Batch Loss: 0.4596693217754364
Epoch 1294, Loss: 0.8422756195068359, Final Batch Loss: 0.49193984270095825
Epoch 1295, Loss: 0.7580999732017517, Final Batch Loss: 0.34557661414146423
Epoch 1296, Loss: 0.760858565568924, Final Batch Loss: 0.37037479877471924
Epoch 1297, Loss: 0.7398614883422852, Final Batch Loss: 0.3641327917575836
Epoch 1298, Loss: 0.7924895584583282, Final Batch Loss: 0.41174182295799255
Epoch 1299, Loss: 0.708983838558197, Final Batch Loss: 0.36481672525405884
Epoch 1300, Loss: 0.7495105564594269, Final Batch Loss: 0.33906418085098267
Epoch 1301, Loss: 0.7802510857582092, Final Batch Loss: 0.38325628638267517
Epoch 1302, Loss: 0.7358950078487396, Final Batch Loss: 0.41022980213165283
Epoch 1303, Loss: 0.8081143200397491, Final Batch Loss: 0.41556185483932495
Epoch 1304, Loss: 0.7688681781291962, Final Batch Loss: 0.39269402623176575
Epoch 1305, Loss:

Epoch 1416, Loss: 0.759179949760437, Final Batch Loss: 0.4045148193836212
Epoch 1417, Loss: 0.7513059377670288, Final Batch Loss: 0.38177406787872314
Epoch 1418, Loss: 0.7091723680496216, Final Batch Loss: 0.3562444746494293
Epoch 1419, Loss: 0.7681780755519867, Final Batch Loss: 0.38585761189460754
Epoch 1420, Loss: 0.7346093058586121, Final Batch Loss: 0.4071681797504425
Epoch 1421, Loss: 0.7296797037124634, Final Batch Loss: 0.36566823720932007
Epoch 1422, Loss: 0.7306902408599854, Final Batch Loss: 0.3916981518268585
Epoch 1423, Loss: 0.7834492623806, Final Batch Loss: 0.46971917152404785
Epoch 1424, Loss: 0.6968826353549957, Final Batch Loss: 0.298239529132843
Epoch 1425, Loss: 0.7025770545005798, Final Batch Loss: 0.32035118341445923
Epoch 1426, Loss: 0.7334963381290436, Final Batch Loss: 0.35253846645355225
Epoch 1427, Loss: 0.7733479142189026, Final Batch Loss: 0.4015810191631317
Epoch 1428, Loss: 0.7142795920372009, Final Batch Loss: 0.36961686611175537
Epoch 1429, Loss: 0.722

Epoch 1543, Loss: 0.6965512335300446, Final Batch Loss: 0.3316822350025177
Epoch 1544, Loss: 0.6859894096851349, Final Batch Loss: 0.3792097568511963
Epoch 1545, Loss: 0.6531157195568085, Final Batch Loss: 0.3291102945804596
Epoch 1546, Loss: 0.7392226159572601, Final Batch Loss: 0.38973531126976013
Epoch 1547, Loss: 0.6695745587348938, Final Batch Loss: 0.3238912522792816
Epoch 1548, Loss: 0.667339950799942, Final Batch Loss: 0.357989639043808
Epoch 1549, Loss: 0.6876653730869293, Final Batch Loss: 0.33934247493743896
Epoch 1550, Loss: 0.6761853992938995, Final Batch Loss: 0.31527215242385864
Epoch 1551, Loss: 0.6528392136096954, Final Batch Loss: 0.30773141980171204
Epoch 1552, Loss: 0.6699754297733307, Final Batch Loss: 0.3224957287311554
Epoch 1553, Loss: 0.7341691553592682, Final Batch Loss: 0.4235040843486786
Epoch 1554, Loss: 0.6608387231826782, Final Batch Loss: 0.36421889066696167
Epoch 1555, Loss: 0.6470719277858734, Final Batch Loss: 0.3130102753639221
Epoch 1556, Loss: 0.62

Epoch 1665, Loss: 0.6610592603683472, Final Batch Loss: 0.33306336402893066
Epoch 1666, Loss: 0.6005101799964905, Final Batch Loss: 0.27492469549179077
Epoch 1667, Loss: 0.6074405312538147, Final Batch Loss: 0.288720965385437
Epoch 1668, Loss: 0.5738751888275146, Final Batch Loss: 0.2627490758895874
Epoch 1669, Loss: 0.6323758959770203, Final Batch Loss: 0.3085244596004486
Epoch 1670, Loss: 0.6544090211391449, Final Batch Loss: 0.36149707436561584
Epoch 1671, Loss: 0.6507938802242279, Final Batch Loss: 0.3504161834716797
Epoch 1672, Loss: 0.6149555742740631, Final Batch Loss: 0.3269836902618408
Epoch 1673, Loss: 0.6389859020709991, Final Batch Loss: 0.35572510957717896
Epoch 1674, Loss: 0.6047567427158356, Final Batch Loss: 0.3196813464164734
Epoch 1675, Loss: 0.6170796751976013, Final Batch Loss: 0.3169427216053009
Epoch 1676, Loss: 0.5641895532608032, Final Batch Loss: 0.2679881453514099
Epoch 1677, Loss: 0.5930326879024506, Final Batch Loss: 0.29154130816459656
Epoch 1678, Loss: 0.6

Epoch 1795, Loss: 0.5534245371818542, Final Batch Loss: 0.2668911814689636
Epoch 1796, Loss: 0.6001852452754974, Final Batch Loss: 0.31253543496131897
Epoch 1797, Loss: 0.5377655327320099, Final Batch Loss: 0.27593371272087097
Epoch 1798, Loss: 0.5858421921730042, Final Batch Loss: 0.25289374589920044
Epoch 1799, Loss: 0.5872189402580261, Final Batch Loss: 0.329233855009079
Epoch 1800, Loss: 0.5844343304634094, Final Batch Loss: 0.25597143173217773
Epoch 1801, Loss: 0.5446053445339203, Final Batch Loss: 0.2696358859539032
Epoch 1802, Loss: 0.5967082530260086, Final Batch Loss: 0.24212850630283356
Epoch 1803, Loss: 0.5879172682762146, Final Batch Loss: 0.3070129156112671
Epoch 1804, Loss: 0.5926941633224487, Final Batch Loss: 0.2943403422832489
Epoch 1805, Loss: 0.5256939679384232, Final Batch Loss: 0.21778301894664764
Epoch 1806, Loss: 0.5917845666408539, Final Batch Loss: 0.3089536726474762
Epoch 1807, Loss: 0.570397138595581, Final Batch Loss: 0.2821124196052551
Epoch 1808, Loss: 0.5

Epoch 1918, Loss: 0.6329462826251984, Final Batch Loss: 0.34046047925949097
Epoch 1919, Loss: 0.5615999698638916, Final Batch Loss: 0.2661501467227936
Epoch 1920, Loss: 0.5406284928321838, Final Batch Loss: 0.26506152749061584
Epoch 1921, Loss: 0.5073528438806534, Final Batch Loss: 0.21249403059482574
Epoch 1922, Loss: 0.544223964214325, Final Batch Loss: 0.2793329358100891
Epoch 1923, Loss: 0.5648421347141266, Final Batch Loss: 0.2596193850040436
Epoch 1924, Loss: 0.5593540668487549, Final Batch Loss: 0.2926405966281891
Epoch 1925, Loss: 0.49357233941555023, Final Batch Loss: 0.23772300779819489
Epoch 1926, Loss: 0.5301487445831299, Final Batch Loss: 0.227277934551239
Epoch 1927, Loss: 0.4858066439628601, Final Batch Loss: 0.2294507920742035
Epoch 1928, Loss: 0.6031230092048645, Final Batch Loss: 0.32532286643981934
Epoch 1929, Loss: 0.5219604074954987, Final Batch Loss: 0.21832537651062012
Epoch 1930, Loss: 0.52635657787323, Final Batch Loss: 0.27329006791114807
Epoch 1931, Loss: 0.4

Epoch 2027, Loss: 0.5281335711479187, Final Batch Loss: 0.2438783347606659
Epoch 2028, Loss: 0.5910314321517944, Final Batch Loss: 0.29716062545776367
Epoch 2029, Loss: 0.5215987414121628, Final Batch Loss: 0.2489054650068283
Epoch 2030, Loss: 0.4786332845687866, Final Batch Loss: 0.26501792669296265
Epoch 2031, Loss: 0.5569951832294464, Final Batch Loss: 0.27309441566467285
Epoch 2032, Loss: 0.4834195673465729, Final Batch Loss: 0.23137512803077698
Epoch 2033, Loss: 0.47035469114780426, Final Batch Loss: 0.19477327167987823
Epoch 2034, Loss: 0.4378074109554291, Final Batch Loss: 0.14902114868164062
Epoch 2035, Loss: 0.4965488165616989, Final Batch Loss: 0.21520863473415375
Epoch 2036, Loss: 0.5111709237098694, Final Batch Loss: 0.2117222547531128
Epoch 2037, Loss: 0.4679861217737198, Final Batch Loss: 0.2298397719860077
Epoch 2038, Loss: 0.5462064445018768, Final Batch Loss: 0.257707417011261
Epoch 2039, Loss: 0.5151943117380142, Final Batch Loss: 0.2404586523771286
Epoch 2040, Loss: 

Epoch 2139, Loss: 0.4609755426645279, Final Batch Loss: 0.19796188175678253
Epoch 2140, Loss: 0.472157821059227, Final Batch Loss: 0.24916371703147888
Epoch 2141, Loss: 0.5577340722084045, Final Batch Loss: 0.2381160855293274
Epoch 2142, Loss: 0.5507075786590576, Final Batch Loss: 0.22765129804611206
Epoch 2143, Loss: 0.4513859748840332, Final Batch Loss: 0.2214438021183014
Epoch 2144, Loss: 0.4475932866334915, Final Batch Loss: 0.22165049612522125
Epoch 2145, Loss: 0.4448683261871338, Final Batch Loss: 0.1705230176448822
Epoch 2146, Loss: 0.4750248044729233, Final Batch Loss: 0.2283218801021576
Epoch 2147, Loss: 0.4682650715112686, Final Batch Loss: 0.21823416650295258
Epoch 2148, Loss: 0.47001464664936066, Final Batch Loss: 0.25065556168556213
Epoch 2149, Loss: 0.4804232120513916, Final Batch Loss: 0.2462829053401947
Epoch 2150, Loss: 0.451062873005867, Final Batch Loss: 0.24961040914058685
Epoch 2151, Loss: 0.46442684531211853, Final Batch Loss: 0.24517196416854858
Epoch 2152, Loss:

Epoch 2252, Loss: 0.45317719876766205, Final Batch Loss: 0.18675987422466278
Epoch 2253, Loss: 0.4569626748561859, Final Batch Loss: 0.22568506002426147
Epoch 2254, Loss: 0.49610206484794617, Final Batch Loss: 0.22844281792640686
Epoch 2255, Loss: 0.4312593340873718, Final Batch Loss: 0.20301344990730286
Epoch 2256, Loss: 0.49744051694869995, Final Batch Loss: 0.2185516357421875
Epoch 2257, Loss: 0.5371948480606079, Final Batch Loss: 0.2830008268356323
Epoch 2258, Loss: 0.5042024850845337, Final Batch Loss: 0.28719353675842285
Epoch 2259, Loss: 0.4175056219100952, Final Batch Loss: 0.19010107219219208
Epoch 2260, Loss: 0.43499739468097687, Final Batch Loss: 0.20731818675994873
Epoch 2261, Loss: 0.494815468788147, Final Batch Loss: 0.23986020684242249
Epoch 2262, Loss: 0.5004490464925766, Final Batch Loss: 0.2215500921010971
Epoch 2263, Loss: 0.4011430889368057, Final Batch Loss: 0.17440184950828552
Epoch 2264, Loss: 0.4232802540063858, Final Batch Loss: 0.23299811780452728
Epoch 2265, 

Epoch 2363, Loss: 0.4334170073270798, Final Batch Loss: 0.1824631243944168
Epoch 2364, Loss: 0.40726085007190704, Final Batch Loss: 0.1723867803812027
Epoch 2365, Loss: 0.5310187637805939, Final Batch Loss: 0.2538418173789978
Epoch 2366, Loss: 0.4207251965999603, Final Batch Loss: 0.23260977864265442
Epoch 2367, Loss: 0.4521259665489197, Final Batch Loss: 0.23213604092597961
Epoch 2368, Loss: 0.5090796053409576, Final Batch Loss: 0.2793722450733185
Epoch 2369, Loss: 0.4844909608364105, Final Batch Loss: 0.2769140601158142
Epoch 2370, Loss: 0.4044284522533417, Final Batch Loss: 0.19016161561012268
Epoch 2371, Loss: 0.4288988709449768, Final Batch Loss: 0.22964903712272644
Epoch 2372, Loss: 0.48155778646469116, Final Batch Loss: 0.21061450242996216
Epoch 2373, Loss: 0.4893234521150589, Final Batch Loss: 0.2370394915342331
Epoch 2374, Loss: 0.4343017488718033, Final Batch Loss: 0.24110621213912964
Epoch 2375, Loss: 0.3921734392642975, Final Batch Loss: 0.1783570647239685
Epoch 2376, Loss:

Epoch 2481, Loss: 0.4202609360218048, Final Batch Loss: 0.2271510511636734
Epoch 2482, Loss: 0.40200673043727875, Final Batch Loss: 0.19617655873298645
Epoch 2483, Loss: 0.4061192274093628, Final Batch Loss: 0.17276565730571747
Epoch 2484, Loss: 0.3993462771177292, Final Batch Loss: 0.1906738132238388
Epoch 2485, Loss: 0.4465017169713974, Final Batch Loss: 0.22105172276496887
Epoch 2486, Loss: 0.4388455003499985, Final Batch Loss: 0.23085738718509674
Epoch 2487, Loss: 0.442910373210907, Final Batch Loss: 0.22953000664710999
Epoch 2488, Loss: 0.4200623631477356, Final Batch Loss: 0.19470734894275665
Epoch 2489, Loss: 0.40672767162323, Final Batch Loss: 0.1988677978515625
Epoch 2490, Loss: 0.4735855758190155, Final Batch Loss: 0.23844163119792938
Epoch 2491, Loss: 0.4261390119791031, Final Batch Loss: 0.24905554950237274
Epoch 2492, Loss: 0.4589342772960663, Final Batch Loss: 0.24648895859718323
Epoch 2493, Loss: 0.43222853541374207, Final Batch Loss: 0.2177797108888626
Epoch 2494, Loss:

Epoch 2602, Loss: 0.3875046819448471, Final Batch Loss: 0.18286262452602386
Epoch 2603, Loss: 0.38916830718517303, Final Batch Loss: 0.17437982559204102
Epoch 2604, Loss: 0.36014023423194885, Final Batch Loss: 0.14251010119915009
Epoch 2605, Loss: 0.4060968905687332, Final Batch Loss: 0.21058878302574158
Epoch 2606, Loss: 0.4141727238893509, Final Batch Loss: 0.24091880023479462
Epoch 2607, Loss: 0.47323866188526154, Final Batch Loss: 0.3078843057155609
Epoch 2608, Loss: 0.3913873881101608, Final Batch Loss: 0.16197288036346436
Epoch 2609, Loss: 0.34411394596099854, Final Batch Loss: 0.15888303518295288
Epoch 2610, Loss: 0.36951276659965515, Final Batch Loss: 0.18189193308353424
Epoch 2611, Loss: 0.3984931707382202, Final Batch Loss: 0.2084895372390747
Epoch 2612, Loss: 0.478681743144989, Final Batch Loss: 0.24917522072792053
Epoch 2613, Loss: 0.3673122376203537, Final Batch Loss: 0.17781950533390045
Epoch 2614, Loss: 0.40842053294181824, Final Batch Loss: 0.22397039830684662
Epoch 261

Epoch 2728, Loss: 0.5000201761722565, Final Batch Loss: 0.26216596364974976
Epoch 2729, Loss: 0.42085306346416473, Final Batch Loss: 0.26010438799858093
Epoch 2730, Loss: 0.3929736614227295, Final Batch Loss: 0.19274194538593292
Epoch 2731, Loss: 0.41355548799037933, Final Batch Loss: 0.15180687606334686
Epoch 2732, Loss: 0.3506082445383072, Final Batch Loss: 0.19029894471168518
Epoch 2733, Loss: 0.4724418967962265, Final Batch Loss: 0.27394336462020874
Epoch 2734, Loss: 0.4041444659233093, Final Batch Loss: 0.20906323194503784
Epoch 2735, Loss: 0.40153002738952637, Final Batch Loss: 0.24470873177051544
Epoch 2736, Loss: 0.3477336913347244, Final Batch Loss: 0.1760299652814865
Epoch 2737, Loss: 0.402291402220726, Final Batch Loss: 0.22124958038330078
Epoch 2738, Loss: 0.4558728486299515, Final Batch Loss: 0.19095878303050995
Epoch 2739, Loss: 0.4458897262811661, Final Batch Loss: 0.21723408997058868
Epoch 2740, Loss: 0.41807883977890015, Final Batch Loss: 0.23683443665504456
Epoch 2741

Epoch 2850, Loss: 0.3677048087120056, Final Batch Loss: 0.15536990761756897
Epoch 2851, Loss: 0.3546796143054962, Final Batch Loss: 0.14139078557491302
Epoch 2852, Loss: 0.33580242097377777, Final Batch Loss: 0.16083049774169922
Epoch 2853, Loss: 0.37409698963165283, Final Batch Loss: 0.1835060864686966
Epoch 2854, Loss: 0.3463785648345947, Final Batch Loss: 0.16569830477237701
Epoch 2855, Loss: 0.34394845366477966, Final Batch Loss: 0.15238720178604126
Epoch 2856, Loss: 0.38727298378944397, Final Batch Loss: 0.22578948736190796
Epoch 2857, Loss: 0.37098297476768494, Final Batch Loss: 0.14778901636600494
Epoch 2858, Loss: 0.31308604776859283, Final Batch Loss: 0.15719468891620636
Epoch 2859, Loss: 0.34581053256988525, Final Batch Loss: 0.15520764887332916
Epoch 2860, Loss: 0.40368877351284027, Final Batch Loss: 0.20338860154151917
Epoch 2861, Loss: 0.41132836043834686, Final Batch Loss: 0.2035851925611496
Epoch 2862, Loss: 0.4149703234434128, Final Batch Loss: 0.2094898372888565
Epoch 

Epoch 2980, Loss: 0.342079758644104, Final Batch Loss: 0.16947337985038757
Epoch 2981, Loss: 0.40617720782756805, Final Batch Loss: 0.21506652235984802
Epoch 2982, Loss: 0.3818426877260208, Final Batch Loss: 0.19186469912528992
Epoch 2983, Loss: 0.32651621103286743, Final Batch Loss: 0.18261560797691345
Epoch 2984, Loss: 0.3103102594614029, Final Batch Loss: 0.12922824919223785
Epoch 2985, Loss: 0.38587281107902527, Final Batch Loss: 0.19813857972621918
Epoch 2986, Loss: 0.3815692514181137, Final Batch Loss: 0.21455861628055573
Epoch 2987, Loss: 0.40832658112049103, Final Batch Loss: 0.21903014183044434
Epoch 2988, Loss: 0.3056415840983391, Final Batch Loss: 0.1210162565112114
Epoch 2989, Loss: 0.38242121040821075, Final Batch Loss: 0.19541727006435394
Epoch 2990, Loss: 0.3846690207719803, Final Batch Loss: 0.18585152924060822
Epoch 2991, Loss: 0.3877671808004379, Final Batch Loss: 0.17730176448822021
Epoch 2992, Loss: 0.39864201843738556, Final Batch Loss: 0.19737233221530914
Epoch 29

Epoch 3088, Loss: 0.4220515340566635, Final Batch Loss: 0.19096972048282623
Epoch 3089, Loss: 0.37151049077510834, Final Batch Loss: 0.1588984876871109
Epoch 3090, Loss: 0.3468841463327408, Final Batch Loss: 0.1497279703617096
Epoch 3091, Loss: 0.3689580708742142, Final Batch Loss: 0.19499605894088745
Epoch 3092, Loss: 0.42715977132320404, Final Batch Loss: 0.17483653128147125
Epoch 3093, Loss: 0.3475668728351593, Final Batch Loss: 0.17920608818531036
Epoch 3094, Loss: 0.3550696074962616, Final Batch Loss: 0.19992321729660034
Epoch 3095, Loss: 0.37946708500385284, Final Batch Loss: 0.1910441368818283
Epoch 3096, Loss: 0.3738597333431244, Final Batch Loss: 0.1826067566871643
Epoch 3097, Loss: 0.3814311623573303, Final Batch Loss: 0.20770671963691711
Epoch 3098, Loss: 0.3777753859758377, Final Batch Loss: 0.16739147901535034
Epoch 3099, Loss: 0.4063786268234253, Final Batch Loss: 0.21514447033405304
Epoch 3100, Loss: 0.3417397141456604, Final Batch Loss: 0.1719626933336258
Epoch 3101, Lo

Epoch 3198, Loss: 0.3880292475223541, Final Batch Loss: 0.20506572723388672
Epoch 3199, Loss: 0.3211994469165802, Final Batch Loss: 0.17796626687049866
Epoch 3200, Loss: 0.41898418962955475, Final Batch Loss: 0.24634318053722382
Epoch 3201, Loss: 0.3500342518091202, Final Batch Loss: 0.18109585344791412
Epoch 3202, Loss: 0.3398909270763397, Final Batch Loss: 0.1606331616640091
Epoch 3203, Loss: 0.37623216211795807, Final Batch Loss: 0.15654537081718445
Epoch 3204, Loss: 0.3167679160833359, Final Batch Loss: 0.15208037197589874
Epoch 3205, Loss: 0.3018214553594589, Final Batch Loss: 0.17851321399211884
Epoch 3206, Loss: 0.3500656187534332, Final Batch Loss: 0.1375807821750641
Epoch 3207, Loss: 0.34865976870059967, Final Batch Loss: 0.1912136822938919
Epoch 3208, Loss: 0.3278631493449211, Final Batch Loss: 0.12063372880220413
Epoch 3209, Loss: 0.30652035772800446, Final Batch Loss: 0.13380230963230133
Epoch 3210, Loss: 0.33487001061439514, Final Batch Loss: 0.15269380807876587
Epoch 3211

Epoch 3305, Loss: 0.29430772364139557, Final Batch Loss: 0.15264669060707092
Epoch 3306, Loss: 0.3496188372373581, Final Batch Loss: 0.17834483087062836
Epoch 3307, Loss: 0.3517194986343384, Final Batch Loss: 0.19779400527477264
Epoch 3308, Loss: 0.37556782364845276, Final Batch Loss: 0.22231356799602509
Epoch 3309, Loss: 0.39094221591949463, Final Batch Loss: 0.21630661189556122
Epoch 3310, Loss: 0.39572393894195557, Final Batch Loss: 0.24079261720180511
Epoch 3311, Loss: 0.3327966630458832, Final Batch Loss: 0.14933648705482483
Epoch 3312, Loss: 0.33435045182704926, Final Batch Loss: 0.1743633896112442
Epoch 3313, Loss: 0.3352974206209183, Final Batch Loss: 0.1694129854440689
Epoch 3314, Loss: 0.29868996888399124, Final Batch Loss: 0.1085786297917366
Epoch 3315, Loss: 0.4183674603700638, Final Batch Loss: 0.1417710930109024
Epoch 3316, Loss: 0.33679112792015076, Final Batch Loss: 0.16640214622020721
Epoch 3317, Loss: 0.3631228506565094, Final Batch Loss: 0.15634740889072418
Epoch 331

Epoch 3433, Loss: 0.3201547712087631, Final Batch Loss: 0.1265667974948883
Epoch 3434, Loss: 0.3526402860879898, Final Batch Loss: 0.17469367384910583
Epoch 3435, Loss: 0.35643045604228973, Final Batch Loss: 0.165312260389328
Epoch 3436, Loss: 0.3064040094614029, Final Batch Loss: 0.14439284801483154
Epoch 3437, Loss: 0.4029373973608017, Final Batch Loss: 0.23125891387462616
Epoch 3438, Loss: 0.2934548705816269, Final Batch Loss: 0.14731311798095703
Epoch 3439, Loss: 0.3358560800552368, Final Batch Loss: 0.19338294863700867
Epoch 3440, Loss: 0.3179769814014435, Final Batch Loss: 0.16365207731723785
Epoch 3441, Loss: 0.32891225814819336, Final Batch Loss: 0.17110128700733185
Epoch 3442, Loss: 0.2901060879230499, Final Batch Loss: 0.15359847247600555
Epoch 3443, Loss: 0.38177672028541565, Final Batch Loss: 0.17964594066143036
Epoch 3444, Loss: 0.3326404094696045, Final Batch Loss: 0.13507448136806488
Epoch 3445, Loss: 0.3919513523578644, Final Batch Loss: 0.22576040029525757
Epoch 3446, 

Epoch 3543, Loss: 0.30995118618011475, Final Batch Loss: 0.17164111137390137
Epoch 3544, Loss: 0.30319055914878845, Final Batch Loss: 0.1567772924900055
Epoch 3545, Loss: 0.3537270128726959, Final Batch Loss: 0.19380679726600647
Epoch 3546, Loss: 0.30533871054649353, Final Batch Loss: 0.15089178085327148
Epoch 3547, Loss: 0.31916068494319916, Final Batch Loss: 0.13555602729320526
Epoch 3548, Loss: 0.3010792136192322, Final Batch Loss: 0.1701352596282959
Epoch 3549, Loss: 0.34005266427993774, Final Batch Loss: 0.2066781371831894
Epoch 3550, Loss: 0.2869138941168785, Final Batch Loss: 0.16497543454170227
Epoch 3551, Loss: 0.24901223927736282, Final Batch Loss: 0.1053270623087883
Epoch 3552, Loss: 0.35258930921554565, Final Batch Loss: 0.23392091691493988
Epoch 3553, Loss: 0.26362593472003937, Final Batch Loss: 0.1135173887014389
Epoch 3554, Loss: 0.36165234446525574, Final Batch Loss: 0.22649134695529938
Epoch 3555, Loss: 0.3478178083896637, Final Batch Loss: 0.1641106754541397
Epoch 355

Epoch 3651, Loss: 0.3449907451868057, Final Batch Loss: 0.16137176752090454
Epoch 3652, Loss: 0.31215720623731613, Final Batch Loss: 0.1906139999628067
Epoch 3653, Loss: 0.29454492032527924, Final Batch Loss: 0.15521705150604248
Epoch 3654, Loss: 0.3355490267276764, Final Batch Loss: 0.16604924201965332
Epoch 3655, Loss: 0.3156236708164215, Final Batch Loss: 0.17005835473537445
Epoch 3656, Loss: 0.28640158474445343, Final Batch Loss: 0.1252765655517578
Epoch 3657, Loss: 0.29266172647476196, Final Batch Loss: 0.16271530091762543
Epoch 3658, Loss: 0.261931337416172, Final Batch Loss: 0.11431895941495895
Epoch 3659, Loss: 0.29243896901607513, Final Batch Loss: 0.14556358754634857
Epoch 3660, Loss: 0.31824490427970886, Final Batch Loss: 0.17386159300804138
Epoch 3661, Loss: 0.30908316373825073, Final Batch Loss: 0.16189385950565338
Epoch 3662, Loss: 0.3768727034330368, Final Batch Loss: 0.19904759526252747
Epoch 3663, Loss: 0.30446256697177887, Final Batch Loss: 0.15853309631347656
Epoch 3

Epoch 3760, Loss: 0.3635687977075577, Final Batch Loss: 0.15843404829502106
Epoch 3761, Loss: 0.3637356013059616, Final Batch Loss: 0.2138291597366333
Epoch 3762, Loss: 0.296703964471817, Final Batch Loss: 0.14357306063175201
Epoch 3763, Loss: 0.28192080557346344, Final Batch Loss: 0.12392528355121613
Epoch 3764, Loss: 0.2785687893629074, Final Batch Loss: 0.15677368640899658
Epoch 3765, Loss: 0.3018973767757416, Final Batch Loss: 0.14482887089252472
Epoch 3766, Loss: 0.3172854781150818, Final Batch Loss: 0.1752670556306839
Epoch 3767, Loss: 0.28334084153175354, Final Batch Loss: 0.15419231355190277
Epoch 3768, Loss: 0.36124663054943085, Final Batch Loss: 0.21572504937648773
Epoch 3769, Loss: 0.28358177840709686, Final Batch Loss: 0.13300721347332
Epoch 3770, Loss: 0.26809513568878174, Final Batch Loss: 0.12814323604106903
Epoch 3771, Loss: 0.2816650718450546, Final Batch Loss: 0.11720892786979675
Epoch 3772, Loss: 0.28798484802246094, Final Batch Loss: 0.17073450982570648
Epoch 3773, 

Epoch 3871, Loss: 0.2574436739087105, Final Batch Loss: 0.12145043164491653
Epoch 3872, Loss: 0.28666746616363525, Final Batch Loss: 0.14284826815128326
Epoch 3873, Loss: 0.32508543133735657, Final Batch Loss: 0.18598629534244537
Epoch 3874, Loss: 0.27683351933956146, Final Batch Loss: 0.13818992674350739
Epoch 3875, Loss: 0.23667779564857483, Final Batch Loss: 0.12402623146772385
Epoch 3876, Loss: 0.27083656191825867, Final Batch Loss: 0.15164825320243835
Epoch 3877, Loss: 0.2698434889316559, Final Batch Loss: 0.13208165764808655
Epoch 3878, Loss: 0.27561408281326294, Final Batch Loss: 0.1154647022485733
Epoch 3879, Loss: 0.2916637137532234, Final Batch Loss: 0.11802484840154648
Epoch 3880, Loss: 0.2884367108345032, Final Batch Loss: 0.1581030786037445
Epoch 3881, Loss: 0.27898193895816803, Final Batch Loss: 0.1256169229745865
Epoch 3882, Loss: 0.2671836316585541, Final Batch Loss: 0.13008816540241241
Epoch 3883, Loss: 0.2766730561852455, Final Batch Loss: 0.15558560192584991
Epoch 38

Epoch 3997, Loss: 0.3032265305519104, Final Batch Loss: 0.15915006399154663
Epoch 3998, Loss: 0.23785730451345444, Final Batch Loss: 0.12476140260696411
Epoch 3999, Loss: 0.2706385850906372, Final Batch Loss: 0.1332503855228424
Epoch 4000, Loss: 0.2729640528559685, Final Batch Loss: 0.12205732613801956
Epoch 4001, Loss: 0.2720266133546829, Final Batch Loss: 0.14444488286972046
Epoch 4002, Loss: 0.2948639392852783, Final Batch Loss: 0.16339685022830963
Epoch 4003, Loss: 0.2925166189670563, Final Batch Loss: 0.13583140075206757
Epoch 4004, Loss: 0.2233157828450203, Final Batch Loss: 0.09992460906505585
Epoch 4005, Loss: 0.26283782720565796, Final Batch Loss: 0.11553366482257843
Epoch 4006, Loss: 0.25716373324394226, Final Batch Loss: 0.12813487648963928
Epoch 4007, Loss: 0.34427572786808014, Final Batch Loss: 0.19505934417247772
Epoch 4008, Loss: 0.2991483211517334, Final Batch Loss: 0.11585946381092072
Epoch 4009, Loss: 0.29337121546268463, Final Batch Loss: 0.17296339571475983
Epoch 40

Epoch 4108, Loss: 0.2816849797964096, Final Batch Loss: 0.13620856404304504
Epoch 4109, Loss: 0.29208536446094513, Final Batch Loss: 0.14214850962162018
Epoch 4110, Loss: 0.31052085757255554, Final Batch Loss: 0.1401212513446808
Epoch 4111, Loss: 0.24005171656608582, Final Batch Loss: 0.10690338909626007
Epoch 4112, Loss: 0.2456885203719139, Final Batch Loss: 0.12001652270555496
Epoch 4113, Loss: 0.24438778311014175, Final Batch Loss: 0.1447858214378357
Epoch 4114, Loss: 0.2725715935230255, Final Batch Loss: 0.09855884313583374
Epoch 4115, Loss: 0.25299401581287384, Final Batch Loss: 0.14559273421764374
Epoch 4116, Loss: 0.2637050598859787, Final Batch Loss: 0.11924909055233002
Epoch 4117, Loss: 0.23839577287435532, Final Batch Loss: 0.11060499399900436
Epoch 4118, Loss: 0.27761927247047424, Final Batch Loss: 0.13753780722618103
Epoch 4119, Loss: 0.3087266832590103, Final Batch Loss: 0.14522744715213776
Epoch 4120, Loss: 0.26088665425777435, Final Batch Loss: 0.15195070207118988
Epoch 

Epoch 4234, Loss: 0.2493324801325798, Final Batch Loss: 0.14871786534786224
Epoch 4235, Loss: 0.3236313909292221, Final Batch Loss: 0.1679326295852661
Epoch 4236, Loss: 0.267110675573349, Final Batch Loss: 0.13950324058532715
Epoch 4237, Loss: 0.24184782058000565, Final Batch Loss: 0.09427999705076218
Epoch 4238, Loss: 0.3103204518556595, Final Batch Loss: 0.13674435019493103
Epoch 4239, Loss: 0.24827199429273605, Final Batch Loss: 0.13926206529140472
Epoch 4240, Loss: 0.26623284816741943, Final Batch Loss: 0.1344798505306244
Epoch 4241, Loss: 0.21867340803146362, Final Batch Loss: 0.11615785211324692
Epoch 4242, Loss: 0.2614290565252304, Final Batch Loss: 0.14438040554523468
Epoch 4243, Loss: 0.2638642489910126, Final Batch Loss: 0.12780612707138062
Epoch 4244, Loss: 0.23648589104413986, Final Batch Loss: 0.09146467596292496
Epoch 4245, Loss: 0.261210098862648, Final Batch Loss: 0.1414923220872879
Epoch 4246, Loss: 0.25885073840618134, Final Batch Loss: 0.10850086808204651
Epoch 4247,

Epoch 4363, Loss: 0.2644004449248314, Final Batch Loss: 0.14078685641288757
Epoch 4364, Loss: 0.2568585276603699, Final Batch Loss: 0.10940596461296082
Epoch 4365, Loss: 0.23999356478452682, Final Batch Loss: 0.130018949508667
Epoch 4366, Loss: 0.2766202390193939, Final Batch Loss: 0.15139339864253998
Epoch 4367, Loss: 0.22391971945762634, Final Batch Loss: 0.10574936121702194
Epoch 4368, Loss: 0.294962540268898, Final Batch Loss: 0.10854077339172363
Epoch 4369, Loss: 0.2694990485906601, Final Batch Loss: 0.1335059106349945
Epoch 4370, Loss: 0.2584048956632614, Final Batch Loss: 0.07501140236854553
Epoch 4371, Loss: 0.27124307304620743, Final Batch Loss: 0.11490433663129807
Epoch 4372, Loss: 0.365776002407074, Final Batch Loss: 0.18527933955192566
Epoch 4373, Loss: 0.2833031862974167, Final Batch Loss: 0.11941741406917572
Epoch 4374, Loss: 0.25634876638650894, Final Batch Loss: 0.11048123985528946
Epoch 4375, Loss: 0.24197863787412643, Final Batch Loss: 0.09353914111852646
Epoch 4376, 

Epoch 4492, Loss: 0.26691487431526184, Final Batch Loss: 0.1579217165708542
Epoch 4493, Loss: 0.25695835798978806, Final Batch Loss: 0.10259883850812912
Epoch 4494, Loss: 0.2525462731719017, Final Batch Loss: 0.14780956506729126
Epoch 4495, Loss: 0.24839933961629868, Final Batch Loss: 0.13707910478115082
Epoch 4496, Loss: 0.270177960395813, Final Batch Loss: 0.10742707550525665
Epoch 4497, Loss: 0.24816831201314926, Final Batch Loss: 0.14438849687576294
Epoch 4498, Loss: 0.20302674919366837, Final Batch Loss: 0.11275661736726761
Epoch 4499, Loss: 0.2334495633840561, Final Batch Loss: 0.12861327826976776
Epoch 4500, Loss: 0.2551723048090935, Final Batch Loss: 0.1312924474477768
Epoch 4501, Loss: 0.2627154216170311, Final Batch Loss: 0.1484857052564621
Epoch 4502, Loss: 0.26359523087739944, Final Batch Loss: 0.11172489076852798
Epoch 4503, Loss: 0.23417264223098755, Final Batch Loss: 0.12858310341835022
Epoch 4504, Loss: 0.22400157898664474, Final Batch Loss: 0.10580305010080338
Epoch 45

Epoch 4620, Loss: 0.26130450516939163, Final Batch Loss: 0.14325366914272308
Epoch 4621, Loss: 0.26717659085989, Final Batch Loss: 0.11905733495950699
Epoch 4622, Loss: 0.2677677720785141, Final Batch Loss: 0.13607630133628845
Epoch 4623, Loss: 0.27481282502412796, Final Batch Loss: 0.15628190338611603
Epoch 4624, Loss: 0.22912582755088806, Final Batch Loss: 0.14277979731559753
Epoch 4625, Loss: 0.23068930953741074, Final Batch Loss: 0.1096893772482872
Epoch 4626, Loss: 0.27216773480176926, Final Batch Loss: 0.17172546684741974
Epoch 4627, Loss: 0.18607056140899658, Final Batch Loss: 0.08690241724252701
Epoch 4628, Loss: 0.2641955614089966, Final Batch Loss: 0.16254067420959473
Epoch 4629, Loss: 0.2660805732011795, Final Batch Loss: 0.09813196957111359
Epoch 4630, Loss: 0.21956531703472137, Final Batch Loss: 0.11818527430295944
Epoch 4631, Loss: 0.27598198503255844, Final Batch Loss: 0.1233542338013649
Epoch 4632, Loss: 0.26472635567188263, Final Batch Loss: 0.1281430721282959
Epoch 46

Epoch 4745, Loss: 0.29780347645282745, Final Batch Loss: 0.1721975952386856
Epoch 4746, Loss: 0.28279344737529755, Final Batch Loss: 0.1440158486366272
Epoch 4747, Loss: 0.23226813226938248, Final Batch Loss: 0.09748228639364243
Epoch 4748, Loss: 0.2142656370997429, Final Batch Loss: 0.09301290661096573
Epoch 4749, Loss: 0.20414021611213684, Final Batch Loss: 0.11511198431253433
Epoch 4750, Loss: 0.31166674196720123, Final Batch Loss: 0.16019044816493988
Epoch 4751, Loss: 0.2231101542711258, Final Batch Loss: 0.10999378561973572
Epoch 4752, Loss: 0.23045466095209122, Final Batch Loss: 0.14454886317253113
Epoch 4753, Loss: 0.24986495077610016, Final Batch Loss: 0.14386174082756042
Epoch 4754, Loss: 0.23263638466596603, Final Batch Loss: 0.13943159580230713
Epoch 4755, Loss: 0.22811077535152435, Final Batch Loss: 0.11035322397947311
Epoch 4756, Loss: 0.20254459977149963, Final Batch Loss: 0.09834203869104385
Epoch 4757, Loss: 0.2524235099554062, Final Batch Loss: 0.10390472412109375
Epoc

Epoch 4871, Loss: 0.28348373621702194, Final Batch Loss: 0.17529547214508057
Epoch 4872, Loss: 0.2103041484951973, Final Batch Loss: 0.10014725476503372
Epoch 4873, Loss: 0.24602264910936356, Final Batch Loss: 0.1293765902519226
Epoch 4874, Loss: 0.21447765827178955, Final Batch Loss: 0.09731850028038025
Epoch 4875, Loss: 0.1875864341855049, Final Batch Loss: 0.06942155957221985
Epoch 4876, Loss: 0.22279765456914902, Final Batch Loss: 0.13438118994235992
Epoch 4877, Loss: 0.24967603385448456, Final Batch Loss: 0.11691330373287201
Epoch 4878, Loss: 0.2489570528268814, Final Batch Loss: 0.165549635887146
Epoch 4879, Loss: 0.17011752724647522, Final Batch Loss: 0.08679133653640747
Epoch 4880, Loss: 0.27698399126529694, Final Batch Loss: 0.1440456062555313
Epoch 4881, Loss: 0.24322015047073364, Final Batch Loss: 0.11607219278812408
Epoch 4882, Loss: 0.24388515204191208, Final Batch Loss: 0.156395822763443
Epoch 4883, Loss: 0.22779599577188492, Final Batch Loss: 0.12780757248401642
Epoch 48

Epoch 4995, Loss: 0.21826045215129852, Final Batch Loss: 0.10295503586530685
Epoch 4996, Loss: 0.29214294254779816, Final Batch Loss: 0.17903666198253632
Epoch 4997, Loss: 0.23645202070474625, Final Batch Loss: 0.09775232523679733
Epoch 4998, Loss: 0.22122252732515335, Final Batch Loss: 0.11259970813989639
Epoch 4999, Loss: 0.2610060125589371, Final Batch Loss: 0.158168762922287
Epoch 5000, Loss: 0.2605656087398529, Final Batch Loss: 0.13585281372070312


In [8]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[12  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  1  0  0  0]
 [ 0  0  0 13  0  0  0  0  0]
 [ 0  0  0  0 13  0  0  0  0]
 [ 0  0  5  0  0 12  0  0  0]
 [ 0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  1  0  0 13]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000        12
           1    1.00000   1.00000   1.00000        11
           2    0.70588   0.92308   0.80000        13
           3    1.00000   1.00000   1.00000        13
           4    1.00000   1.00000   1.00000        13
           5    0.85714   0.70588   0.77419        17
           6    1.00000   1.00000   1.00000        11
           7    1.00000   1.00000   1.00000         6
           8    1.00000   0.92857   0.96296        14

    accuracy                        0.93636       110
   macro avg    0.95145   0.95084   0.94857       110
weighted avg    0.94316   0.93636   0.93675       110



In [37]:
n_samples = 30

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A0 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_1 = gen(latent_vectors).detach().numpy()

y_1 = np.zeros(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A1 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_2 = gen(latent_vectors).detach().numpy()

y_2 = np.ones(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A2 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_3 = gen(latent_vectors).detach().numpy()

y_3 = np.ones(n_samples) + 1

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A0 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_4 = gen(latent_vectors).detach().numpy()

y_4 = np.ones(n_samples) + 2

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A1 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_5 = gen(latent_vectors).detach().numpy()

y_5 = np.ones(n_samples) + 3

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A2 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_6 = gen(latent_vectors).detach().numpy()

y_6 = np.ones(n_samples) + 4

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A0 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_7 = gen(latent_vectors).detach().numpy()

y_7 = np.ones(n_samples) + 5

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A1 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_8 = gen(latent_vectors).detach().numpy()

y_8 = np.ones(n_samples) + 6

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A2 Solo GAN Group 5_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_9 = gen(latent_vectors).detach().numpy()

y_9 = np.ones(n_samples) + 7

fake_features = np.concatenate((fake_features_1, fake_features_2, fake_features_3, fake_features_4, fake_features_5, fake_features_6,
                         fake_features_7, fake_features_8, fake_features_9))
fake_labels = np.concatenate((y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9))

fake_features = torch.Tensor(fake_features)

In [38]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[26  0  0  2  0  0  2  0  0]
 [ 0 30  0  0  0  0  0  0  0]
 [ 0  0 29  0  0  1  0  0  0]
 [ 0  0  0 29  1  0  0  0  0]
 [ 0  0  0  0 23  0  0  7  0]
 [ 0  0  6  0  0 19  0  0  5]
 [ 3  1  0  0  0  0 26  0  0]
 [ 0  0  0  0  0  0  0 30  0]
 [ 0  0 11  0  0  1  0  0 18]]
              precision    recall  f1-score   support

         0.0    0.89655   0.86667   0.88136        30
         1.0    0.96774   1.00000   0.98361        30
         2.0    0.63043   0.96667   0.76316        30
         3.0    0.93548   0.96667   0.95082        30
         4.0    0.95833   0.76667   0.85185        30
         5.0    0.90476   0.63333   0.74510        30
         6.0    0.92857   0.86667   0.89655        30
         7.0    0.81081   1.00000   0.89552        30
         8.0    0.78261   0.60000   0.67925        30

    accuracy                        0.85185       270
   macro avg    0.86837   0.85185   0.84969       270
weighted avg    0.86837   0.85185   0.84969       270

