In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '58 tGravityAcc-energy()-Y',
 '59 tGravityAcc-energy()-Z',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '90 tBodyAccJerk-max()-X',
 '202 tBodyAccMag-std()',
 '203 tBodyAccMag-mad()',
 '215 tGravityAccMag-std()',
 '216 tGravityAccMag-mad()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '382 fBodyAccJerk-bandsEnergy()-1,8',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 40),
            classifier_block(40, 30),
            classifier_block(30, 25),
            classifier_block(25, 20),
            nn.Linear(20, 18)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def get_act_matrix(batch_size, a_dim):
    indexes = np.random.randint(a_dim, size = batch_size)
    
    one_hot = np.zeros((len(indexes), indexes.max()+1))
    one_hot[np.arange(len(indexes)),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)
    
def get_usr_matrix(batch_size, u_dim):
    indexes = np.random.randint(u_dim, size = batch_size)
    
    one_hot = np.zeros((indexes.size, indexes.max()+1))
    one_hot[np.arange(indexes.size),indexes] = 1
    return torch.Tensor(indexes).long(), torch.Tensor(one_hot)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../../saved_models/{model_name}'))

# Train on Real Test on Real

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']
    
    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 1) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 3) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 5) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_10 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_11 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_12 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_13 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_14 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_15 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_16 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_17 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_18 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9, X_10, X_11, X_12, X_13, X_14, X_15, X_16, X_17, X_18))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9) + [9] * len(X_10) + [10] * len(X_11) + [11] * len(X_12) + [12] * len(X_13) + [13] * len(X_14) + [14] * len(X_15) + [15] * len(X_16) + [16] * len(X_17) + [17] * len(X_18)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [1, 3, 5, 7, 8, 11]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [8]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 11.486918687820435, Final Batch Loss: 2.798377275466919
Epoch 2, Loss: 11.599191904067993, Final Batch Loss: 2.9199044704437256
Epoch 3, Loss: 11.635527610778809, Final Batch Loss: 2.9617674350738525
Epoch 4, Loss: 11.411921262741089, Final Batch Loss: 2.746338367462158
Epoch 5, Loss: 11.50093126296997, Final Batch Loss: 2.846264123916626
Epoch 6, Loss: 11.637593984603882, Final Batch Loss: 2.9973459243774414
Epoch 7, Loss: 11.63011884689331, Final Batch Loss: 2.990257978439331
Epoch 8, Loss: 11.442826747894287, Final Batch Loss: 2.8147552013397217
Epoch 9, Loss: 11.402079343795776, Final Batch Loss: 2.780205726623535
Epoch 10, Loss: 11.511808395385742, Final Batch Loss: 2.905625820159912
Epoch 11, Loss: 11.507941961288452, Final Batch Loss: 2.9171841144561768
Epoch 12, Loss: 11.445812940597534, Final Batch Loss: 2.87876558303833
Epoch 13, Loss: 11.36445689201355, Final Batch Loss: 2.822486162185669
Epoch 14, Loss: 11.456492185592651, Final Batch Loss: 2.942516326904297


Epoch 115, Loss: 7.2396416664123535, Final Batch Loss: 1.5786840915679932
Epoch 116, Loss: 7.486827492713928, Final Batch Loss: 1.866039514541626
Epoch 117, Loss: 7.19476854801178, Final Batch Loss: 1.5948172807693481
Epoch 118, Loss: 7.391346216201782, Final Batch Loss: 1.7725478410720825
Epoch 119, Loss: 7.1940836906433105, Final Batch Loss: 1.5019824504852295
Epoch 120, Loss: 6.965549349784851, Final Batch Loss: 1.3292608261108398
Epoch 121, Loss: 6.796924591064453, Final Batch Loss: 1.1219438314437866
Epoch 122, Loss: 6.946574926376343, Final Batch Loss: 1.2762773036956787
Epoch 123, Loss: 7.292706847190857, Final Batch Loss: 1.6512038707733154
Epoch 124, Loss: 6.354308903217316, Final Batch Loss: 0.8046358227729797
Epoch 125, Loss: 7.070627331733704, Final Batch Loss: 1.4095733165740967
Epoch 126, Loss: 7.710625648498535, Final Batch Loss: 1.9397917985916138
Epoch 127, Loss: 6.353235900402069, Final Batch Loss: 0.5350474715232849
Epoch 128, Loss: 7.784826755523682, Final Batch Los

Epoch 235, Loss: 6.68075966835022, Final Batch Loss: 1.5962300300598145
Epoch 236, Loss: 5.947876513004303, Final Batch Loss: 0.9293424487113953
Epoch 237, Loss: 5.620170474052429, Final Batch Loss: 0.614837646484375
Epoch 238, Loss: 6.640827775001526, Final Batch Loss: 1.595555305480957
Epoch 239, Loss: 7.081352472305298, Final Batch Loss: 2.1042845249176025
Epoch 240, Loss: 6.387154936790466, Final Batch Loss: 1.4415926933288574
Epoch 241, Loss: 6.3840168714523315, Final Batch Loss: 1.4844155311584473
Epoch 242, Loss: 5.189683020114899, Final Batch Loss: 0.20042544603347778
Epoch 243, Loss: 5.713385164737701, Final Batch Loss: 0.8102836012840271
Epoch 244, Loss: 5.828915894031525, Final Batch Loss: 0.8962194323539734
Epoch 245, Loss: 6.15729546546936, Final Batch Loss: 1.1651731729507446
Epoch 246, Loss: 7.124658107757568, Final Batch Loss: 2.1449666023254395
Epoch 247, Loss: 6.077902436256409, Final Batch Loss: 1.1694879531860352
Epoch 248, Loss: 7.078617334365845, Final Batch Loss:

Epoch 355, Loss: 5.793393015861511, Final Batch Loss: 1.3220722675323486
Epoch 356, Loss: 5.916965126991272, Final Batch Loss: 1.1316766738891602
Epoch 357, Loss: 7.581018328666687, Final Batch Loss: 2.9031522274017334
Epoch 358, Loss: 6.0466402769088745, Final Batch Loss: 1.5415936708450317
Epoch 359, Loss: 7.022238731384277, Final Batch Loss: 2.4649133682250977
Epoch 360, Loss: 5.676608204841614, Final Batch Loss: 1.2806627750396729
Epoch 361, Loss: 6.655315279960632, Final Batch Loss: 2.109907865524292
Epoch 362, Loss: 6.463378548622131, Final Batch Loss: 1.8324031829833984
Epoch 363, Loss: 5.8807350397109985, Final Batch Loss: 1.302881121635437
Epoch 364, Loss: 5.474005103111267, Final Batch Loss: 0.867477297782898
Epoch 365, Loss: 5.896258473396301, Final Batch Loss: 1.4634393453598022
Epoch 366, Loss: 5.898759365081787, Final Batch Loss: 1.5066261291503906
Epoch 367, Loss: 6.1246994733810425, Final Batch Loss: 1.7544528245925903
Epoch 368, Loss: 4.394489474594593, Final Batch Los

Epoch 469, Loss: 5.099093377590179, Final Batch Loss: 0.9346840977668762
Epoch 470, Loss: 5.967965364456177, Final Batch Loss: 1.8493486642837524
Epoch 471, Loss: 4.9720951318740845, Final Batch Loss: 0.8654394149780273
Epoch 472, Loss: 5.587938189506531, Final Batch Loss: 1.554125189781189
Epoch 473, Loss: 6.188748598098755, Final Batch Loss: 2.068449020385742
Epoch 474, Loss: 5.363922595977783, Final Batch Loss: 1.3762527704238892
Epoch 475, Loss: 5.0501062870025635, Final Batch Loss: 1.010066270828247
Epoch 476, Loss: 5.45414924621582, Final Batch Loss: 1.4579862356185913
Epoch 477, Loss: 5.578767657279968, Final Batch Loss: 1.5176451206207275
Epoch 478, Loss: 5.458387017250061, Final Batch Loss: 1.4896526336669922
Epoch 479, Loss: 5.634007930755615, Final Batch Loss: 1.5802116394042969
Epoch 480, Loss: 6.42603075504303, Final Batch Loss: 2.43857741355896
Epoch 481, Loss: 4.139693811535835, Final Batch Loss: 0.07877428829669952
Epoch 482, Loss: 4.314639985561371, Final Batch Loss: 0

Epoch 592, Loss: 4.605070114135742, Final Batch Loss: 0.9485471248626709
Epoch 593, Loss: 4.766549587249756, Final Batch Loss: 1.0873262882232666
Epoch 594, Loss: 4.4308802485466, Final Batch Loss: 0.7713876366615295
Epoch 595, Loss: 3.834444597363472, Final Batch Loss: 0.21936042606830597
Epoch 596, Loss: 4.6573121547698975, Final Batch Loss: 0.9017683267593384
Epoch 597, Loss: 4.6136462688446045, Final Batch Loss: 0.9347959756851196
Epoch 598, Loss: 4.718655109405518, Final Batch Loss: 0.8732662200927734
Epoch 599, Loss: 5.0026938915252686, Final Batch Loss: 1.1771502494812012
Epoch 600, Loss: 4.568662345409393, Final Batch Loss: 0.8942102789878845
Epoch 601, Loss: 3.735297417268157, Final Batch Loss: 0.01918814145028591
Epoch 602, Loss: 4.418348848819733, Final Batch Loss: 0.7085759043693542
Epoch 603, Loss: 5.081886887550354, Final Batch Loss: 1.420588731765747
Epoch 604, Loss: 4.682586431503296, Final Batch Loss: 0.9845906496047974
Epoch 605, Loss: 4.8867104053497314, Final Batch 

Epoch 705, Loss: 3.531790904700756, Final Batch Loss: 0.0809822604060173
Epoch 706, Loss: 5.628765344619751, Final Batch Loss: 2.139904499053955
Epoch 707, Loss: 3.8921831399202347, Final Batch Loss: 0.1774166375398636
Epoch 708, Loss: 4.862535834312439, Final Batch Loss: 1.1841185092926025
Epoch 709, Loss: 4.048898607492447, Final Batch Loss: 0.49970999360084534
Epoch 710, Loss: 4.583760499954224, Final Batch Loss: 1.149860143661499
Epoch 711, Loss: 5.389185428619385, Final Batch Loss: 1.9626456499099731
Epoch 712, Loss: 5.101428866386414, Final Batch Loss: 1.6830456256866455
Epoch 713, Loss: 3.4675175324082375, Final Batch Loss: 0.051747240126132965
Epoch 714, Loss: 3.5226705372333527, Final Batch Loss: 0.20268800854682922
Epoch 715, Loss: 4.80199933052063, Final Batch Loss: 1.423640251159668
Epoch 716, Loss: 3.5981819480657578, Final Batch Loss: 0.20975099503993988
Epoch 717, Loss: 4.100739896297455, Final Batch Loss: 0.7373926043510437
Epoch 718, Loss: 5.174638271331787, Final Batc

Epoch 819, Loss: 4.028589248657227, Final Batch Loss: 0.8412944078445435
Epoch 820, Loss: 3.9713065028190613, Final Batch Loss: 0.6964666247367859
Epoch 821, Loss: 4.962869048118591, Final Batch Loss: 1.4978004693984985
Epoch 822, Loss: 4.85985791683197, Final Batch Loss: 1.2996412515640259
Epoch 823, Loss: 4.42228502035141, Final Batch Loss: 0.9936287999153137
Epoch 824, Loss: 3.728360742330551, Final Batch Loss: 0.3841594159603119
Epoch 825, Loss: 4.32788610458374, Final Batch Loss: 1.0253108739852905
Epoch 826, Loss: 5.239862561225891, Final Batch Loss: 2.0407638549804688
Epoch 827, Loss: 4.523605585098267, Final Batch Loss: 1.3689894676208496
Epoch 828, Loss: 3.851924777030945, Final Batch Loss: 0.6393204927444458
Epoch 829, Loss: 3.1495662331581116, Final Batch Loss: 0.0330008864402771
Epoch 830, Loss: 3.1900810971856117, Final Batch Loss: 0.06361345201730728
Epoch 831, Loss: 3.609019935131073, Final Batch Loss: 0.3517248034477234
Epoch 832, Loss: 4.684763431549072, Final Batch Lo

Epoch 936, Loss: 4.700728893280029, Final Batch Loss: 1.224351167678833
Epoch 937, Loss: 4.337537527084351, Final Batch Loss: 0.9131799936294556
Epoch 938, Loss: 3.585965022444725, Final Batch Loss: 0.14768050611019135
Epoch 939, Loss: 4.114428520202637, Final Batch Loss: 0.7921100854873657
Epoch 940, Loss: 5.408758282661438, Final Batch Loss: 2.09023380279541
Epoch 941, Loss: 4.849722743034363, Final Batch Loss: 1.670259952545166
Epoch 942, Loss: 5.044605076313019, Final Batch Loss: 1.8570994138717651
Epoch 943, Loss: 3.836009979248047, Final Batch Loss: 0.7380503416061401
Epoch 944, Loss: 4.439187169075012, Final Batch Loss: 1.4311542510986328
Epoch 945, Loss: 4.956303238868713, Final Batch Loss: 1.8288129568099976
Epoch 946, Loss: 3.132132178172469, Final Batch Loss: 0.022093242034316063
Epoch 947, Loss: 5.500027358531952, Final Batch Loss: 2.4214043617248535
Epoch 948, Loss: 3.0509522184729576, Final Batch Loss: 0.024180613458156586
Epoch 949, Loss: 3.7843517661094666, Final Batch 

Epoch 1047, Loss: 3.4335097670555115, Final Batch Loss: 0.5133493542671204
Epoch 1048, Loss: 3.0539172366261482, Final Batch Loss: 0.06705767661333084
Epoch 1049, Loss: 3.2417324632406235, Final Batch Loss: 0.2499864548444748
Epoch 1050, Loss: 3.0607917457818985, Final Batch Loss: 0.19279827177524567
Epoch 1051, Loss: 3.0699948593974113, Final Batch Loss: 0.10367535799741745
Epoch 1052, Loss: 4.406101942062378, Final Batch Loss: 1.4445263147354126
Epoch 1053, Loss: 4.839358925819397, Final Batch Loss: 1.9913467168807983
Epoch 1054, Loss: 4.944628477096558, Final Batch Loss: 2.0516462326049805
Epoch 1055, Loss: 2.866934268735349, Final Batch Loss: 0.005641846917569637
Epoch 1056, Loss: 3.266625851392746, Final Batch Loss: 0.2871260941028595
Epoch 1057, Loss: 4.711804509162903, Final Batch Loss: 1.6603952646255493
Epoch 1058, Loss: 3.7118071913719177, Final Batch Loss: 0.7167040109634399
Epoch 1059, Loss: 3.047094441950321, Final Batch Loss: 0.04851726442575455
Epoch 1060, Loss: 2.903254

Epoch 1167, Loss: 3.0447245836257935, Final Batch Loss: 0.3212946653366089
Epoch 1168, Loss: 3.607291579246521, Final Batch Loss: 0.8156346082687378
Epoch 1169, Loss: 4.1790977120399475, Final Batch Loss: 1.3851511478424072
Epoch 1170, Loss: 5.534947514533997, Final Batch Loss: 2.8076529502868652
Epoch 1171, Loss: 4.354271233081818, Final Batch Loss: 1.5385841131210327
Epoch 1172, Loss: 3.542443037033081, Final Batch Loss: 0.5655801892280579
Epoch 1173, Loss: 3.965438485145569, Final Batch Loss: 0.6046551465988159
Epoch 1174, Loss: 4.8699493408203125, Final Batch Loss: 1.5282678604125977
Epoch 1175, Loss: 6.191198348999023, Final Batch Loss: 3.0540099143981934
Epoch 1176, Loss: 3.5192448496818542, Final Batch Loss: 0.5276610851287842
Epoch 1177, Loss: 3.672798454761505, Final Batch Loss: 0.5991034507751465
Epoch 1178, Loss: 3.492814302444458, Final Batch Loss: 0.5244600176811218
Epoch 1179, Loss: 3.1907745599746704, Final Batch Loss: 0.1621648669242859
Epoch 1180, Loss: 5.4650825262069

Epoch 1283, Loss: 2.9088902783114463, Final Batch Loss: 0.002222926588729024
Epoch 1284, Loss: 4.4868916273117065, Final Batch Loss: 1.6214197874069214
Epoch 1285, Loss: 3.5550652146339417, Final Batch Loss: 0.7129113674163818
Epoch 1286, Loss: 5.253804862499237, Final Batch Loss: 2.448883056640625
Epoch 1287, Loss: 4.41400671005249, Final Batch Loss: 1.5070863962173462
Epoch 1288, Loss: 5.087161183357239, Final Batch Loss: 2.18269681930542
Epoch 1289, Loss: 2.8676480278372765, Final Batch Loss: 0.11225267499685287
Epoch 1290, Loss: 3.8520655035972595, Final Batch Loss: 1.036410927772522
Epoch 1291, Loss: 3.0948246717453003, Final Batch Loss: 0.14448976516723633
Epoch 1292, Loss: 2.8534410186111927, Final Batch Loss: 0.01905002072453499
Epoch 1293, Loss: 4.328755021095276, Final Batch Loss: 1.5945453643798828
Epoch 1294, Loss: 3.345667004585266, Final Batch Loss: 0.5445407629013062
Epoch 1295, Loss: 3.9584280252456665, Final Batch Loss: 1.214902639389038
Epoch 1296, Loss: 2.85578241012

Epoch 1402, Loss: 2.681035164743662, Final Batch Loss: 0.04632717743515968
Epoch 1403, Loss: 4.889346361160278, Final Batch Loss: 2.188337802886963
Epoch 1404, Loss: 3.352510929107666, Final Batch Loss: 0.7489961981773376
Epoch 1405, Loss: 2.7941877990961075, Final Batch Loss: 0.2168930321931839
Epoch 1406, Loss: 2.6138235442340374, Final Batch Loss: 0.035667549818754196
Epoch 1407, Loss: 4.29113644361496, Final Batch Loss: 1.7236878871917725
Epoch 1408, Loss: 3.529057204723358, Final Batch Loss: 0.9812568426132202
Epoch 1409, Loss: 3.378867506980896, Final Batch Loss: 0.7621346712112427
Epoch 1410, Loss: 3.9888749718666077, Final Batch Loss: 1.3999443054199219
Epoch 1411, Loss: 4.786737263202667, Final Batch Loss: 1.9536340236663818
Epoch 1412, Loss: 3.523381769657135, Final Batch Loss: 0.8063194155693054
Epoch 1413, Loss: 3.6373296976089478, Final Batch Loss: 0.8493200540542603
Epoch 1414, Loss: 3.8284061551094055, Final Batch Loss: 1.116832971572876
Epoch 1415, Loss: 2.7498881202191

Epoch 1512, Loss: 2.6091169915744103, Final Batch Loss: 0.0007454953738488257
Epoch 1513, Loss: 2.8959470987319946, Final Batch Loss: 0.3945579528808594
Epoch 1514, Loss: 2.6652657240629196, Final Batch Loss: 0.0326530784368515
Epoch 1515, Loss: 4.312399387359619, Final Batch Loss: 1.8062984943389893
Epoch 1516, Loss: 3.180372655391693, Final Batch Loss: 0.6104301810264587
Epoch 1517, Loss: 2.714957535266876, Final Batch Loss: 0.21777284145355225
Epoch 1518, Loss: 2.5121701206080616, Final Batch Loss: 0.007398113142699003
Epoch 1519, Loss: 2.7821247577667236, Final Batch Loss: 0.21407824754714966
Epoch 1520, Loss: 2.6736435666680336, Final Batch Loss: 0.09142271429300308
Epoch 1521, Loss: 2.6878811717033386, Final Batch Loss: 0.060842037200927734
Epoch 1522, Loss: 2.8414660692214966, Final Batch Loss: 0.28169548511505127
Epoch 1523, Loss: 3.8696495294570923, Final Batch Loss: 1.3072763681411743
Epoch 1524, Loss: 2.566773723985534, Final Batch Loss: 0.0009008163469843566
Epoch 1525, Los

Epoch 1629, Loss: 3.9509111642837524, Final Batch Loss: 1.349220633506775
Epoch 1630, Loss: 2.7199182957410812, Final Batch Loss: 0.20904777944087982
Epoch 1631, Loss: 2.8225926510058343, Final Batch Loss: 0.0005364171229302883
Epoch 1632, Loss: 2.9241107180714607, Final Batch Loss: 0.0847354605793953
Epoch 1633, Loss: 4.190211713314056, Final Batch Loss: 1.538634181022644
Epoch 1634, Loss: 2.611277110874653, Final Batch Loss: 0.08542872220277786
Epoch 1635, Loss: 2.656666560098529, Final Batch Loss: 0.0172490905970335
Epoch 1636, Loss: 2.7741126269102097, Final Batch Loss: 0.24104700982570648
Epoch 1637, Loss: 2.6633377969264984, Final Batch Loss: 0.17871567606925964
Epoch 1638, Loss: 2.8960582315921783, Final Batch Loss: 0.4037483036518097
Epoch 1639, Loss: 3.396412670612335, Final Batch Loss: 0.976334273815155
Epoch 1640, Loss: 3.587950646877289, Final Batch Loss: 1.0501888990402222
Epoch 1641, Loss: 2.65231447853148, Final Batch Loss: 0.0010967198759317398
Epoch 1642, Loss: 4.59438

Epoch 1748, Loss: 2.4845414170995355, Final Batch Loss: 0.014474392868578434
Epoch 1749, Loss: 2.5309558040462434, Final Batch Loss: 0.007378233131021261
Epoch 1750, Loss: 2.6921309321187437, Final Batch Loss: 0.005912789609283209
Epoch 1751, Loss: 5.1012715101242065, Final Batch Loss: 2.4417033195495605
Epoch 1752, Loss: 2.732489843852818, Final Batch Loss: 0.007898171432316303
Epoch 1753, Loss: 2.785509530454874, Final Batch Loss: 0.017326537519693375
Epoch 1754, Loss: 2.76960451900959, Final Batch Loss: 0.09938998520374298
Epoch 1755, Loss: 3.7982651591300964, Final Batch Loss: 1.1622467041015625
Epoch 1756, Loss: 4.361031711101532, Final Batch Loss: 1.8715460300445557
Epoch 1757, Loss: 4.352236568927765, Final Batch Loss: 1.8497833013534546
Epoch 1758, Loss: 4.6777671575546265, Final Batch Loss: 2.270306348800659
Epoch 1759, Loss: 2.6140687091392465, Final Batch Loss: 0.0007426364463753998
Epoch 1760, Loss: 5.224648892879486, Final Batch Loss: 2.4170968532562256
Epoch 1761, Loss: 3

Epoch 1863, Loss: 3.030349612236023, Final Batch Loss: 0.7135185599327087
Epoch 1864, Loss: 3.536745011806488, Final Batch Loss: 1.1795728206634521
Epoch 1865, Loss: 3.0877551436424255, Final Batch Loss: 0.6805907487869263
Epoch 1866, Loss: 3.1277427673339844, Final Batch Loss: 0.8065305352210999
Epoch 1867, Loss: 2.3709951043128967, Final Batch Loss: 0.002315223217010498
Epoch 1868, Loss: 3.0191453099250793, Final Batch Loss: 0.6678485870361328
Epoch 1869, Loss: 2.460731402039528, Final Batch Loss: 0.09939517080783844
Epoch 1870, Loss: 3.458085060119629, Final Batch Loss: 1.1542500257492065
Epoch 1871, Loss: 2.5911042243242264, Final Batch Loss: 0.22689540684223175
Epoch 1872, Loss: 3.8790045976638794, Final Batch Loss: 1.4998639822006226
Epoch 1873, Loss: 2.420949086546898, Final Batch Loss: 0.1255011409521103
Epoch 1874, Loss: 2.3744088374078274, Final Batch Loss: 0.030652817338705063
Epoch 1875, Loss: 3.6183246970176697, Final Batch Loss: 1.2408978939056396
Epoch 1876, Loss: 2.3400

Epoch 1982, Loss: 2.3253594636917114, Final Batch Loss: 0.028347313404083252
Epoch 1983, Loss: 2.393308088183403, Final Batch Loss: 0.03424243628978729
Epoch 1984, Loss: 2.9188942909240723, Final Batch Loss: 0.6070055365562439
Epoch 1985, Loss: 3.5970606207847595, Final Batch Loss: 1.3230081796646118
Epoch 1986, Loss: 2.6580488979816437, Final Batch Loss: 0.397471159696579
Epoch 1987, Loss: 2.273606405593455, Final Batch Loss: 0.014926181174814701
Epoch 1988, Loss: 3.3272184133529663, Final Batch Loss: 1.0774903297424316
Epoch 1989, Loss: 2.409635230898857, Final Batch Loss: 0.2350311130285263
Epoch 1990, Loss: 2.654497981071472, Final Batch Loss: 0.34808820486068726
Epoch 1991, Loss: 2.3783805146813393, Final Batch Loss: 0.11024770885705948
Epoch 1992, Loss: 2.795117199420929, Final Batch Loss: 0.5328627824783325
Epoch 1993, Loss: 2.2880808487534523, Final Batch Loss: 0.05631539970636368
Epoch 1994, Loss: 3.9642120599746704, Final Batch Loss: 1.6325490474700928
Epoch 1995, Loss: 3.555

Epoch 2094, Loss: 4.5669339299201965, Final Batch Loss: 2.168717622756958
Epoch 2095, Loss: 3.5041102170944214, Final Batch Loss: 1.107290506362915
Epoch 2096, Loss: 3.6158676743507385, Final Batch Loss: 1.359357476234436
Epoch 2097, Loss: 2.899862766265869, Final Batch Loss: 0.5464723706245422
Epoch 2098, Loss: 2.3748178482055664, Final Batch Loss: 0.1260644793510437
Epoch 2099, Loss: 2.5817794501781464, Final Batch Loss: 0.3191203773021698
Epoch 2100, Loss: 2.4960208535194397, Final Batch Loss: 0.30905747413635254
Epoch 2101, Loss: 2.2572501227259636, Final Batch Loss: 0.04729991406202316
Epoch 2102, Loss: 2.994190037250519, Final Batch Loss: 0.7991217970848083
Epoch 2103, Loss: 3.2389906644821167, Final Batch Loss: 1.0895620584487915
Epoch 2104, Loss: 2.296174630522728, Final Batch Loss: 0.1286228746175766
Epoch 2105, Loss: 2.2909488156437874, Final Batch Loss: 0.11364401131868362
Epoch 2106, Loss: 3.849146842956543, Final Batch Loss: 1.6513493061065674
Epoch 2107, Loss: 3.675152659

Epoch 2214, Loss: 4.457669198513031, Final Batch Loss: 2.0045533180236816
Epoch 2215, Loss: 5.679331362247467, Final Batch Loss: 3.216050148010254
Epoch 2216, Loss: 4.2536672949790955, Final Batch Loss: 2.0156679153442383
Epoch 2217, Loss: 3.3739163875579834, Final Batch Loss: 0.9885082244873047
Epoch 2218, Loss: 2.356651857495308, Final Batch Loss: 0.04953189194202423
Epoch 2219, Loss: 2.3969360180199146, Final Batch Loss: 0.021486598998308182
Epoch 2220, Loss: 2.3200070746243, Final Batch Loss: 0.013779748231172562
Epoch 2221, Loss: 2.2163067553192377, Final Batch Loss: 0.017549822106957436
Epoch 2222, Loss: 3.9484909176826477, Final Batch Loss: 1.6302682161331177
Epoch 2223, Loss: 2.407448247075081, Final Batch Loss: 0.19769896566867828
Epoch 2224, Loss: 3.377333641052246, Final Batch Loss: 1.1419273614883423
Epoch 2225, Loss: 2.78069144487381, Final Batch Loss: 0.5717321634292603
Epoch 2226, Loss: 2.431008219718933, Final Batch Loss: 0.2792326807975769
Epoch 2227, Loss: 2.745242476

Epoch 2329, Loss: 2.3984211683273315, Final Batch Loss: 0.15582263469696045
Epoch 2330, Loss: 3.1453729271888733, Final Batch Loss: 0.9027717113494873
Epoch 2331, Loss: 2.691178560256958, Final Batch Loss: 0.4730347990989685
Epoch 2332, Loss: 7.804591953754425, Final Batch Loss: 5.633232593536377
Epoch 2333, Loss: 2.948416531085968, Final Batch Loss: 0.7593958973884583
Epoch 2334, Loss: 3.764184355735779, Final Batch Loss: 1.4930846691131592
Epoch 2335, Loss: 3.4485026597976685, Final Batch Loss: 1.0228283405303955
Epoch 2336, Loss: 4.718811631202698, Final Batch Loss: 2.1274378299713135
Epoch 2337, Loss: 2.4873381853103638, Final Batch Loss: 0.07500612735748291
Epoch 2338, Loss: 3.7180830240249634, Final Batch Loss: 1.3901135921478271
Epoch 2339, Loss: 5.671358585357666, Final Batch Loss: 3.328782081604004
Epoch 2340, Loss: 2.7761465907096863, Final Batch Loss: 0.46050792932510376
Epoch 2341, Loss: 2.5939647257328033, Final Batch Loss: 0.17753013968467712
Epoch 2342, Loss: 2.357860680

Epoch 2452, Loss: 4.302641868591309, Final Batch Loss: 2.2116453647613525
Epoch 2453, Loss: 2.8339990973472595, Final Batch Loss: 0.7800464630126953
Epoch 2454, Loss: 4.0254634618759155, Final Batch Loss: 1.9451454877853394
Epoch 2455, Loss: 2.31181663274765, Final Batch Loss: 0.10307550430297852
Epoch 2456, Loss: 2.2631172575056553, Final Batch Loss: 0.05284035578370094
Epoch 2457, Loss: 3.721957206726074, Final Batch Loss: 1.4920270442962646
Epoch 2458, Loss: 2.30211338493973, Final Batch Loss: 0.008271248079836369
Epoch 2459, Loss: 2.2473373115062714, Final Batch Loss: 0.0061747729778289795
Epoch 2460, Loss: 2.2624152936041355, Final Batch Loss: 0.04726523533463478
Epoch 2461, Loss: 3.7789754271507263, Final Batch Loss: 1.7067766189575195
Epoch 2462, Loss: 2.59679314494133, Final Batch Loss: 0.4660079777240753
Epoch 2463, Loss: 2.8424845337867737, Final Batch Loss: 0.7585723996162415
Epoch 2464, Loss: 2.577921986579895, Final Batch Loss: 0.3522570729255676
Epoch 2465, Loss: 5.253681

Epoch 2565, Loss: 3.988676428794861, Final Batch Loss: 2.0132923126220703
Epoch 2566, Loss: 4.483457684516907, Final Batch Loss: 2.499556303024292
Epoch 2567, Loss: 2.0561901554465294, Final Batch Loss: 0.08181127160787582
Epoch 2568, Loss: 2.131717859796481, Final Batch Loss: 4.2437604861333966e-05
Epoch 2569, Loss: 2.2084747552871704, Final Batch Loss: 0.049678683280944824
Epoch 2570, Loss: 2.1200141159351915, Final Batch Loss: 0.0016999093350023031
Epoch 2571, Loss: 2.1819693171419203, Final Batch Loss: 0.006250950042158365
Epoch 2572, Loss: 2.1336638531647623, Final Batch Loss: 0.0027100048027932644
Epoch 2573, Loss: 2.1269916277378798, Final Batch Loss: 0.011966465041041374
Epoch 2574, Loss: 2.343811810016632, Final Batch Loss: 0.29501795768737793
Epoch 2575, Loss: 3.825956344604492, Final Batch Loss: 1.8478286266326904
Epoch 2576, Loss: 3.2507766485214233, Final Batch Loss: 1.1792203187942505
Epoch 2577, Loss: 3.665291428565979, Final Batch Loss: 1.518007755279541
Epoch 2578, Los

Epoch 2679, Loss: 2.437934458255768, Final Batch Loss: 0.41820818185806274
Epoch 2680, Loss: 4.034741282463074, Final Batch Loss: 1.9339988231658936
Epoch 2681, Loss: 2.1715711504220963, Final Batch Loss: 0.08114714920520782
Epoch 2682, Loss: 2.60491144657135, Final Batch Loss: 0.5570305585861206
Epoch 2683, Loss: 2.0527215860784054, Final Batch Loss: 0.04675706848502159
Epoch 2684, Loss: 3.5150500535964966, Final Batch Loss: 1.5659971237182617
Epoch 2685, Loss: 2.697478771209717, Final Batch Loss: 0.6362580060958862
Epoch 2686, Loss: 2.4040322601795197, Final Batch Loss: 0.4520517885684967
Epoch 2687, Loss: 2.102758504450321, Final Batch Loss: 0.12037620693445206
Epoch 2688, Loss: 3.2390644550323486, Final Batch Loss: 1.277305006980896
Epoch 2689, Loss: 2.626687169075012, Final Batch Loss: 0.5656383037567139
Epoch 2690, Loss: 2.406361073255539, Final Batch Loss: 0.3742363750934601
Epoch 2691, Loss: 2.6916747093200684, Final Batch Loss: 0.638843297958374
Epoch 2692, Loss: 3.50491052865

Epoch 2795, Loss: 2.0024011480272748, Final Batch Loss: 0.00041154498467221856
Epoch 2796, Loss: 3.705736994743347, Final Batch Loss: 1.7831286191940308
Epoch 2797, Loss: 1.9065061882138252, Final Batch Loss: 0.004036732017993927
Epoch 2798, Loss: 2.227403908967972, Final Batch Loss: 0.40714582800865173
Epoch 2799, Loss: 2.5751689672470093, Final Batch Loss: 0.753910481929779
Epoch 2800, Loss: 1.8186194298323244, Final Batch Loss: 0.0029283759649842978
Epoch 2801, Loss: 1.9269073526374996, Final Batch Loss: 0.0026085893623530865
Epoch 2802, Loss: 1.9267435716465116, Final Batch Loss: 0.010566596873104572
Epoch 2803, Loss: 1.9067689096555114, Final Batch Loss: 0.010002843104302883
Epoch 2804, Loss: 1.860141990298871, Final Batch Loss: 6.735097849741578e-05
Epoch 2805, Loss: 2.799724817276001, Final Batch Loss: 0.9727885127067566
Epoch 2806, Loss: 1.9014673568308353, Final Batch Loss: 0.00592866912484169
Epoch 2807, Loss: 1.9608066261280328, Final Batch Loss: 0.0038220465648919344
Epoch 

Epoch 2911, Loss: 2.6305575370788574, Final Batch Loss: 0.47892123460769653
Epoch 2912, Loss: 2.3114946335554123, Final Batch Loss: 0.11895452439785004
Epoch 2913, Loss: 2.211544451653026, Final Batch Loss: 0.001692411839030683
Epoch 2914, Loss: 2.6710253953933716, Final Batch Loss: 0.5873504877090454
Epoch 2915, Loss: 3.452233374118805, Final Batch Loss: 1.510035514831543
Epoch 2916, Loss: 2.812812387943268, Final Batch Loss: 0.8674766421318054
Epoch 2917, Loss: 2.7820687890052795, Final Batch Loss: 0.872810959815979
Epoch 2918, Loss: 2.7646071910858154, Final Batch Loss: 0.8530040979385376
Epoch 2919, Loss: 1.9102362412959337, Final Batch Loss: 0.005698980763554573
Epoch 2920, Loss: 2.662462055683136, Final Batch Loss: 0.7396764755249023
Epoch 2921, Loss: 2.8147798776626587, Final Batch Loss: 0.9371193051338196
Epoch 2922, Loss: 2.7103204131126404, Final Batch Loss: 0.7856108546257019
Epoch 2923, Loss: 2.0494853407144547, Final Batch Loss: 0.10739792883396149
Epoch 2924, Loss: 1.9891

Epoch 3022, Loss: 2.5902615785598755, Final Batch Loss: 0.6684213280677795
Epoch 3023, Loss: 2.024781122803688, Final Batch Loss: 0.2170829325914383
Epoch 3024, Loss: 2.0954605489969254, Final Batch Loss: 0.21254028379917145
Epoch 3025, Loss: 2.415709614753723, Final Batch Loss: 0.580798327922821
Epoch 3026, Loss: 2.0764726102352142, Final Batch Loss: 0.3303077518939972
Epoch 3027, Loss: 1.845852161408402, Final Batch Loss: 0.001447463990189135
Epoch 3028, Loss: 3.6594133377075195, Final Batch Loss: 1.872869849205017
Epoch 3029, Loss: 2.2592972218990326, Final Batch Loss: 0.47356387972831726
Epoch 3030, Loss: 1.8791894223541021, Final Batch Loss: 0.009327879175543785
Epoch 3031, Loss: 1.8148550223559141, Final Batch Loss: 0.030343396589159966
Epoch 3032, Loss: 1.8270509835583653, Final Batch Loss: 2.634490556374658e-05
Epoch 3033, Loss: 1.8982337545603514, Final Batch Loss: 0.012414796277880669
Epoch 3034, Loss: 1.8153412910178304, Final Batch Loss: 0.00835388619452715
Epoch 3035, Loss

Epoch 3137, Loss: 2.4530386924743652, Final Batch Loss: 0.5842464566230774
Epoch 3138, Loss: 3.633536636829376, Final Batch Loss: 1.8165833950042725
Epoch 3139, Loss: 4.5960166454315186, Final Batch Loss: 2.857374668121338
Epoch 3140, Loss: 1.8862691819667816, Final Batch Loss: 0.21067765355110168
Epoch 3141, Loss: 2.146262675523758, Final Batch Loss: 0.3764001429080963
Epoch 3142, Loss: 1.778269751026528, Final Batch Loss: 0.0001829695247579366
Epoch 3143, Loss: 1.7904445137828588, Final Batch Loss: 0.024741550907492638
Epoch 3144, Loss: 4.111640393733978, Final Batch Loss: 2.426347017288208
Epoch 3145, Loss: 1.8493115734308958, Final Batch Loss: 0.017782075330615044
Epoch 3146, Loss: 3.197209417819977, Final Batch Loss: 1.416832447052002
Epoch 3147, Loss: 1.8878149641677737, Final Batch Loss: 0.009698416106402874
Epoch 3148, Loss: 1.8865280747413635, Final Batch Loss: 0.03518855571746826
Epoch 3149, Loss: 1.821719104424119, Final Batch Loss: 0.019103938713669777
Epoch 3150, Loss: 4.0

Epoch 3250, Loss: 1.9028167566284537, Final Batch Loss: 0.009309454821050167
Epoch 3251, Loss: 3.5088196396827698, Final Batch Loss: 1.642472267150879
Epoch 3252, Loss: 1.850280499085784, Final Batch Loss: 0.02361074648797512
Epoch 3253, Loss: 1.9936644732952118, Final Batch Loss: 0.20691213011741638
Epoch 3254, Loss: 2.795480728149414, Final Batch Loss: 1.013504981994629
Epoch 3255, Loss: 3.2916876673698425, Final Batch Loss: 1.4567084312438965
Epoch 3256, Loss: 1.7926391926594079, Final Batch Loss: 0.003087636549025774
Epoch 3257, Loss: 2.055725984275341, Final Batch Loss: 0.04462742060422897
Epoch 3258, Loss: 4.280160486698151, Final Batch Loss: 2.11215877532959
Epoch 3259, Loss: 2.0414260388351977, Final Batch Loss: 0.006076788995414972
Epoch 3260, Loss: 1.974554356187582, Final Batch Loss: 0.04102861508727074
Epoch 3261, Loss: 2.86380273103714, Final Batch Loss: 1.0004494190216064
Epoch 3262, Loss: 2.935574531555176, Final Batch Loss: 1.0227794647216797
Epoch 3263, Loss: 1.9247164

Epoch 3360, Loss: 1.7242787778377533, Final Batch Loss: 0.06198588013648987
Epoch 3361, Loss: 3.957942843437195, Final Batch Loss: 2.265273094177246
Epoch 3362, Loss: 1.714010066818446, Final Batch Loss: 0.0061880419962108135
Epoch 3363, Loss: 2.1719022691249847, Final Batch Loss: 0.46237173676490784
Epoch 3364, Loss: 2.2252860069274902, Final Batch Loss: 0.5015957951545715
Epoch 3365, Loss: 1.9424748718738556, Final Batch Loss: 0.12923935055732727
Epoch 3366, Loss: 1.8393348827958107, Final Batch Loss: 0.10039237886667252
Epoch 3367, Loss: 3.785330057144165, Final Batch Loss: 2.0694572925567627
Epoch 3368, Loss: 1.6544868173077703, Final Batch Loss: 0.010127467103302479
Epoch 3369, Loss: 2.126274824142456, Final Batch Loss: 0.5048342347145081
Epoch 3370, Loss: 3.2617819905281067, Final Batch Loss: 1.487061619758606
Epoch 3371, Loss: 1.732861030381173, Final Batch Loss: 0.0042143347673118114
Epoch 3372, Loss: 1.96195288002491, Final Batch Loss: 0.24788333475589752
Epoch 3373, Loss: 3.2

Epoch 3473, Loss: 2.541895031929016, Final Batch Loss: 0.8340693116188049
Epoch 3474, Loss: 2.352040946483612, Final Batch Loss: 0.6484656929969788
Epoch 3475, Loss: 1.8154789199325023, Final Batch Loss: 4.482168878894299e-05
Epoch 3476, Loss: 2.573688268661499, Final Batch Loss: 0.6658971309661865
Epoch 3477, Loss: 2.2074114382267, Final Batch Loss: 0.2250392735004425
Epoch 3478, Loss: 4.099733054637909, Final Batch Loss: 1.9783047437667847
Epoch 3479, Loss: 3.644010543823242, Final Batch Loss: 1.6088851690292358
Epoch 3480, Loss: 2.0882932357490063, Final Batch Loss: 0.04416946694254875
Epoch 3481, Loss: 2.116941422224045, Final Batch Loss: 0.21244803071022034
Epoch 3482, Loss: 2.105558916926384, Final Batch Loss: 0.24133436381816864
Epoch 3483, Loss: 4.07240092754364, Final Batch Loss: 2.267120599746704
Epoch 3484, Loss: 2.0793441236019135, Final Batch Loss: 0.24353811144828796
Epoch 3485, Loss: 1.8958920985460281, Final Batch Loss: 0.01720269024372101
Epoch 3486, Loss: 5.3483673334

Epoch 3585, Loss: 1.7018013742635958, Final Batch Loss: 0.0003000047872774303
Epoch 3586, Loss: 1.7971371673047543, Final Batch Loss: 0.025100376456975937
Epoch 3587, Loss: 1.7365290634334087, Final Batch Loss: 0.028120052069425583
Epoch 3588, Loss: 3.2253578901290894, Final Batch Loss: 1.6217718124389648
Epoch 3589, Loss: 1.596939907874912, Final Batch Loss: 0.0015135272406041622
Epoch 3590, Loss: 1.6372288769343868, Final Batch Loss: 0.0015624469378963113
Epoch 3591, Loss: 1.5990034923888743, Final Batch Loss: 0.007726071868091822
Epoch 3592, Loss: 1.7597323218360543, Final Batch Loss: 0.012431279756128788
Epoch 3593, Loss: 2.829918473958969, Final Batch Loss: 1.1852211952209473
Epoch 3594, Loss: 1.6432297523133457, Final Batch Loss: 0.005818098317831755
Epoch 3595, Loss: 1.8929796814918518, Final Batch Loss: 0.24006247520446777
Epoch 3596, Loss: 1.6973266320419498, Final Batch Loss: 0.0008781867218203843
Epoch 3597, Loss: 1.6291043013334274, Final Batch Loss: 0.053259775042533875
Ep

Epoch 3695, Loss: 2.102522134780884, Final Batch Loss: 0.3026108741760254
Epoch 3696, Loss: 2.4513842463493347, Final Batch Loss: 0.7256090641021729
Epoch 3697, Loss: 1.8108791643753648, Final Batch Loss: 0.005679541267454624
Epoch 3698, Loss: 1.7728001546347514, Final Batch Loss: 0.0018867325270548463
Epoch 3699, Loss: 2.538477301597595, Final Batch Loss: 0.7825033068656921
Epoch 3700, Loss: 2.310203731060028, Final Batch Loss: 0.44177645444869995
Epoch 3701, Loss: 1.8332434110343456, Final Batch Loss: 0.04710159823298454
Epoch 3702, Loss: 2.277040958404541, Final Batch Loss: 0.35428839921951294
Epoch 3703, Loss: 2.3242098689079285, Final Batch Loss: 0.40333980321884155
Epoch 3704, Loss: 1.8760524205863476, Final Batch Loss: 0.043096285313367844
Epoch 3705, Loss: 2.11481474339962, Final Batch Loss: 0.2240254133939743
Epoch 3706, Loss: 2.759653925895691, Final Batch Loss: 0.9449667930603027
Epoch 3707, Loss: 3.2774872183799744, Final Batch Loss: 1.5318506956100464
Epoch 3708, Loss: 1.7

Epoch 3810, Loss: 1.667299821972847, Final Batch Loss: 0.035893335938453674
Epoch 3811, Loss: 1.6478509828448296, Final Batch Loss: 0.043076418340206146
Epoch 3812, Loss: 1.919768288731575, Final Batch Loss: 0.21025104820728302
Epoch 3813, Loss: 2.3012470602989197, Final Batch Loss: 0.5635896325111389
Epoch 3814, Loss: 1.7527275010943413, Final Batch Loss: 0.12142547219991684
Epoch 3815, Loss: 2.737372398376465, Final Batch Loss: 1.063612461090088
Epoch 3816, Loss: 3.0690011382102966, Final Batch Loss: 1.3906666040420532
Epoch 3817, Loss: 2.6782422363758087, Final Batch Loss: 0.9501352310180664
Epoch 3818, Loss: 1.7660971275654447, Final Batch Loss: 4.0649541915627196e-05
Epoch 3819, Loss: 3.844092845916748, Final Batch Loss: 2.189462900161743
Epoch 3820, Loss: 4.777537226676941, Final Batch Loss: 3.0461068153381348
Epoch 3821, Loss: 2.1702041625976562, Final Batch Loss: 0.43100792169570923
Epoch 3822, Loss: 2.6900240778923035, Final Batch Loss: 1.0165220499038696
Epoch 3823, Loss: 2.3

Epoch 3924, Loss: 3.1129640340805054, Final Batch Loss: 1.3945393562316895
Epoch 3925, Loss: 1.6907110214233398, Final Batch Loss: 0.0
Epoch 3926, Loss: 1.5778259169310331, Final Batch Loss: 0.017536116763949394
Epoch 3927, Loss: 1.6821434833109379, Final Batch Loss: 0.04197714105248451
Epoch 3928, Loss: 1.704603774473071, Final Batch Loss: 0.006177498027682304
Epoch 3929, Loss: 2.2019715309143066, Final Batch Loss: 0.46985840797424316
Epoch 3930, Loss: 3.7596924006938934, Final Batch Loss: 2.1598949432373047
Epoch 3931, Loss: 2.0066868364810944, Final Batch Loss: 0.31707099080085754
Epoch 3932, Loss: 1.6523173980094725, Final Batch Loss: 0.0001161031104857102
Epoch 3933, Loss: 1.6213484648615122, Final Batch Loss: 0.016153061762452126
Epoch 3934, Loss: 3.349399656057358, Final Batch Loss: 1.7973823547363281
Epoch 3935, Loss: 1.718825250864029, Final Batch Loss: 0.1055162250995636
Epoch 3936, Loss: 2.4813424944877625, Final Batch Loss: 0.7388009428977966
Epoch 3937, Loss: 1.61909457482

Epoch 4040, Loss: 1.713664773851633, Final Batch Loss: 0.05815953388810158
Epoch 4041, Loss: 1.7572960834950209, Final Batch Loss: 0.0250051598995924
Epoch 4042, Loss: 3.243346869945526, Final Batch Loss: 1.6337846517562866
Epoch 4043, Loss: 1.8082530051469803, Final Batch Loss: 0.17686553299427032
Epoch 4044, Loss: 1.593317672610283, Final Batch Loss: 0.05819271504878998
Epoch 4045, Loss: 1.6376605164259672, Final Batch Loss: 0.006605101749300957
Epoch 4046, Loss: 1.570410366402939, Final Batch Loss: 0.0021296695340424776
Epoch 4047, Loss: 1.6859922260046005, Final Batch Loss: 0.06015317142009735
Epoch 4048, Loss: 3.487010955810547, Final Batch Loss: 1.8883651494979858
Epoch 4049, Loss: 3.2848053872585297, Final Batch Loss: 1.7252020835876465
Epoch 4050, Loss: 2.3665086030960083, Final Batch Loss: 0.8573351502418518
Epoch 4051, Loss: 1.6549685820937157, Final Batch Loss: 0.10473691672086716
Epoch 4052, Loss: 1.677379958331585, Final Batch Loss: 0.02488144487142563
Epoch 4053, Loss: 1.

Epoch 4153, Loss: 1.5586273040244123, Final Batch Loss: 8.237022848334163e-05
Epoch 4154, Loss: 2.0687163174152374, Final Batch Loss: 0.46700355410575867
Epoch 4155, Loss: 1.888271152973175, Final Batch Loss: 0.31411099433898926
Epoch 4156, Loss: 1.5074263233691454, Final Batch Loss: 0.010922761633992195
Epoch 4157, Loss: 1.620272476808168, Final Batch Loss: 0.0017146660247817636
Epoch 4158, Loss: 1.6647614315152168, Final Batch Loss: 0.08801022917032242
Epoch 4159, Loss: 1.56326262652874, Final Batch Loss: 0.005911722779273987
Epoch 4160, Loss: 1.52478945254893, Final Batch Loss: 2.7418097943154862e-06
Epoch 4161, Loss: 1.5552693617064506, Final Batch Loss: 0.0006887924391776323
Epoch 4162, Loss: 1.5459076464144346, Final Batch Loss: 2.50339189733495e-06
Epoch 4163, Loss: 1.6175904124975204, Final Batch Loss: 0.10386191308498383
Epoch 4164, Loss: 1.8384406566619873, Final Batch Loss: 0.35744330286979675
Epoch 4165, Loss: 1.565329065779224, Final Batch Loss: 0.0019264726433902979
Epoch

Epoch 4262, Loss: 3.8438135981559753, Final Batch Loss: 1.923844814300537
Epoch 4263, Loss: 1.9898983351886272, Final Batch Loss: 0.016834806650877
Epoch 4264, Loss: 3.2982866764068604, Final Batch Loss: 1.426220417022705
Epoch 4265, Loss: 1.7365907244384289, Final Batch Loss: 0.02693156525492668
Epoch 4266, Loss: 3.209807336330414, Final Batch Loss: 1.44087553024292
Epoch 4267, Loss: 2.744883179664612, Final Batch Loss: 0.8982177972793579
Epoch 4268, Loss: 3.55411559343338, Final Batch Loss: 1.8302884101867676
Epoch 4269, Loss: 1.6633935449644923, Final Batch Loss: 0.002161073498427868
Epoch 4270, Loss: 1.9495368599891663, Final Batch Loss: 0.3026590347290039
Epoch 4271, Loss: 2.5062862634658813, Final Batch Loss: 0.7438316345214844
Epoch 4272, Loss: 1.5927094454309554, Final Batch Loss: 0.00011383838864276186
Epoch 4273, Loss: 1.7137693911790848, Final Batch Loss: 0.12399806082248688
Epoch 4274, Loss: 2.3413186967372894, Final Batch Loss: 0.7391524314880371
Epoch 4275, Loss: 1.775281

Epoch 4376, Loss: 1.4998887777327923, Final Batch Loss: 3.576278118089249e-07
Epoch 4377, Loss: 3.201707184314728, Final Batch Loss: 1.6271088123321533
Epoch 4378, Loss: 1.688354223035276, Final Batch Loss: 0.007343797944486141
Epoch 4379, Loss: 1.7533550709486008, Final Batch Loss: 0.14294616878032684
Epoch 4380, Loss: 2.3888075053691864, Final Batch Loss: 0.7914301753044128
Epoch 4381, Loss: 1.5805845798749942, Final Batch Loss: 0.00026675479602999985
Epoch 4382, Loss: 1.5144586572423577, Final Batch Loss: 0.002353043295443058
Epoch 4383, Loss: 1.9599295556545258, Final Batch Loss: 0.34910228848457336
Epoch 4384, Loss: 1.5642882049723994, Final Batch Loss: 0.00032729512895457447
Epoch 4385, Loss: 1.9094629883766174, Final Batch Loss: 0.38914918899536133
Epoch 4386, Loss: 1.527536709792912, Final Batch Loss: 0.002796669490635395
Epoch 4387, Loss: 3.2966608107089996, Final Batch Loss: 1.803781270980835
Epoch 4388, Loss: 1.543598664458841, Final Batch Loss: 0.002646160777658224
Epoch 43

Epoch 4491, Loss: 3.192118465900421, Final Batch Loss: 1.7135509252548218
Epoch 4492, Loss: 2.8179002702236176, Final Batch Loss: 1.3376483917236328
Epoch 4493, Loss: 3.2016141414642334, Final Batch Loss: 1.5594792366027832
Epoch 4494, Loss: 6.616860628128052, Final Batch Loss: 4.885774612426758
Epoch 4495, Loss: 1.6904127324232832, Final Batch Loss: 0.0005414212355390191
Epoch 4496, Loss: 2.437986671924591, Final Batch Loss: 0.8003668189048767
Epoch 4497, Loss: 5.527565598487854, Final Batch Loss: 3.798023223876953
Epoch 4498, Loss: 1.6961387479677796, Final Batch Loss: 0.006947644986212254
Epoch 4499, Loss: 1.6681605763733387, Final Batch Loss: 0.0008927173912525177
Epoch 4500, Loss: 1.6807885766029358, Final Batch Loss: 0.07806900143623352
Epoch 4501, Loss: 2.885831117630005, Final Batch Loss: 1.1926515102386475
Epoch 4502, Loss: 1.8236435241997242, Final Batch Loss: 0.05068828538060188
Epoch 4503, Loss: 2.0407804548740387, Final Batch Loss: 0.38013938069343567
Epoch 4504, Loss: 1.8

Epoch 4607, Loss: 1.577736258506775, Final Batch Loss: 0.04944407939910889
Epoch 4608, Loss: 2.5305623412132263, Final Batch Loss: 1.0359145402908325
Epoch 4609, Loss: 1.4783464600332081, Final Batch Loss: 0.002816759515553713
Epoch 4610, Loss: 1.910438358783722, Final Batch Loss: 0.3666794002056122
Epoch 4611, Loss: 1.4952558623626828, Final Batch Loss: 0.010122393257915974
Epoch 4612, Loss: 1.5762798264622688, Final Batch Loss: 0.12119264155626297
Epoch 4613, Loss: 1.5477404571138322, Final Batch Loss: 0.0038890219293534756
Epoch 4614, Loss: 1.8319577872753143, Final Batch Loss: 0.26949170231819153
Epoch 4615, Loss: 1.5745856016874313, Final Batch Loss: 0.1103726178407669
Epoch 4616, Loss: 1.4710652868961915, Final Batch Loss: 0.0008407871937379241
Epoch 4617, Loss: 1.5371640287339687, Final Batch Loss: 0.023129668086767197
Epoch 4618, Loss: 2.1025468707084656, Final Batch Loss: 0.6343157887458801
Epoch 4619, Loss: 1.8827941119670868, Final Batch Loss: 0.38258296251296997
Epoch 4620,

Epoch 4722, Loss: 2.291076123714447, Final Batch Loss: 0.8346859216690063
Epoch 4723, Loss: 1.6142405718564987, Final Batch Loss: 0.1275591105222702
Epoch 4724, Loss: 2.0922585129737854, Final Batch Loss: 0.6077709197998047
Epoch 4725, Loss: 1.520387778058648, Final Batch Loss: 0.010613778606057167
Epoch 4726, Loss: 1.6883578896522522, Final Batch Loss: 0.15205705165863037
Epoch 4727, Loss: 3.375294119119644, Final Batch Loss: 1.875974416732788
Epoch 4728, Loss: 1.460058628454135, Final Batch Loss: 4.60137271147687e-05
Epoch 4729, Loss: 1.5572859607636929, Final Batch Loss: 0.014582600444555283
Epoch 4730, Loss: 1.443637311457337, Final Batch Loss: 1.5497195136049413e-06
Epoch 4731, Loss: 1.467833032249473, Final Batch Loss: 0.0018799504032358527
Epoch 4732, Loss: 1.777338445186615, Final Batch Loss: 0.26549863815307617
Epoch 4733, Loss: 1.4532524733513128, Final Batch Loss: 0.0004698126285802573
Epoch 4734, Loss: 1.6852223873138428, Final Batch Loss: 0.29233962297439575
Epoch 4735, Lo

Epoch 4830, Loss: 3.4072801172733307, Final Batch Loss: 1.8561813831329346
Epoch 4831, Loss: 3.3889695405960083, Final Batch Loss: 1.7825924158096313
Epoch 4832, Loss: 3.371537208557129, Final Batch Loss: 1.8015174865722656
Epoch 4833, Loss: 3.0101715326309204, Final Batch Loss: 1.5109624862670898
Epoch 4834, Loss: 1.6869443580508232, Final Batch Loss: 0.0653320774435997
Epoch 4835, Loss: 1.620162027888, Final Batch Loss: 0.011286932043731213
Epoch 4836, Loss: 2.5057454705238342, Final Batch Loss: 0.9250546097755432
Epoch 4837, Loss: 1.5484149150215671, Final Batch Loss: 3.9457496313843876e-05
Epoch 4838, Loss: 1.719757780432701, Final Batch Loss: 0.1959162801504135
Epoch 4839, Loss: 1.5932591408491135, Final Batch Loss: 0.0667712539434433
Epoch 4840, Loss: 3.62074613571167, Final Batch Loss: 2.1628530025482178
Epoch 4841, Loss: 1.509004186897073, Final Batch Loss: 0.0008322112844325602
Epoch 4842, Loss: 2.0483208894729614, Final Batch Loss: 0.5309142470359802
Epoch 4843, Loss: 1.68318

Epoch 4949, Loss: 1.4214582731947303, Final Batch Loss: 0.00042500998824834824
Epoch 4950, Loss: 1.4079046892002225, Final Batch Loss: 0.01009890902787447
Epoch 4951, Loss: 1.7672795057296753, Final Batch Loss: 0.3139195740222931
Epoch 4952, Loss: 1.8681931793689728, Final Batch Loss: 0.448967307806015
Epoch 4953, Loss: 2.8853592574596405, Final Batch Loss: 1.4647200107574463
Epoch 4954, Loss: 1.4399963913547253, Final Batch Loss: 1.8954096958623268e-05
Epoch 4955, Loss: 1.5250357426702976, Final Batch Loss: 0.03468722477555275
Epoch 4956, Loss: 1.434776388690807, Final Batch Loss: 0.0018941095331683755
Epoch 4957, Loss: 1.408200915902853, Final Batch Loss: 0.02883654460310936
Epoch 4958, Loss: 2.4705729484558105, Final Batch Loss: 0.9617026448249817
Epoch 4959, Loss: 2.144141048192978, Final Batch Loss: 0.7060433030128479
Epoch 4960, Loss: 3.233532190322876, Final Batch Loss: 1.8377058506011963
Epoch 4961, Loss: 1.6053512143553235, Final Batch Loss: 0.0003313469351269305
Epoch 4962, L

In [9]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[27  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  4  0  0  0  0  0  3  0  0  1  0  0  2]
 [ 0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  4  0  0  2  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  1  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  3  0  0  1  0  0  2  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0]
 [ 0  0  3  0  0  0  0  0  0  0

# Train on Fake Test on Real

In [10]:
# 20,000 epochs DEFAULT PARAMETERS FOR THRESHOLDS

In [11]:
gen = Generator(z_dim = 109)
load_model(gen, "3 Label 6 Subject GAN Ablation_gen.param")
gen.eval()

Generator(
  (gen): Sequential(
    (0): Sequential(
      (0): Linear(in_features=109, out_features=80, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (1): Sequential(
      (0): Linear(in_features=80, out_features=60, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (2): Sequential(
      (0): Linear(in_features=60, out_features=50, bias=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): ReLU(inplace=True)
    )
    (3): Linear(in_features=50, out_features=33, bias=True)
    (4): Tanh()
  )
)

In [37]:
size = len(X_test)
latent_vectors = get_noise(size, 100)
act_vectors = get_act_matrix(size, 3)
usr_vectors = get_usr_matrix(size, 6)

fake_labels = []

for k in range(size):
    if act_vectors[0][k] == 0 and usr_vectors[0][k] == 0:
        fake_labels.append(0)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 0:
        fake_labels.append(1)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 0:
        fake_labels.append(2)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 1:
        fake_labels.append(3)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 1:
        fake_labels.append(4)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 1:
        fake_labels.append(5)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 2:
        fake_labels.append(6)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 2:
        fake_labels.append(7)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 2:
        fake_labels.append(8)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 3:
        fake_labels.append(9)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 3:
        fake_labels.append(10)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 3:
        fake_labels.append(11)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 4:
        fake_labels.append(12)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 4:
        fake_labels.append(13)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 4:
        fake_labels.append(14)
    elif act_vectors[0][k] == 0 and usr_vectors[0][k] == 5:
        fake_labels.append(15)
    elif act_vectors[0][k] == 1 and usr_vectors[0][k] == 5:
        fake_labels.append(16)
    elif act_vectors[0][k] == 2 and usr_vectors[0][k] == 5:
        fake_labels.append(17)
        
fake_labels = np.asarray(fake_labels)
to_gen = torch.cat((latent_vectors, act_vectors[1], usr_vectors[1]), 1)
fake_features = gen(to_gen).detach()
#fake_features = gen(to_gen).detach().numpy()

In [38]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5, zero_division = 0))

[[11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0