In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn import metrics
import torch.optim as optim

In [2]:
sub_features = ['42 tGravityAcc-mean()-Y',
 '43 tGravityAcc-mean()-Z',
 '51 tGravityAcc-max()-Y',
 '52 tGravityAcc-max()-Z',
 '54 tGravityAcc-min()-Y',
 '55 tGravityAcc-min()-Z',
 '56 tGravityAcc-sma()',
 '59 tGravityAcc-energy()-Z',
 '125 tBodyGyro-std()-Y',
 '128 tBodyGyro-mad()-Y',
 '138 tBodyGyro-energy()-Y',
 '165 tBodyGyroJerk-std()-Y',
 '168 tBodyGyroJerk-mad()-Y',
 '178 tBodyGyroJerk-energy()-Y',
 '181 tBodyGyroJerk-iqr()-Y',
 '425 fBodyGyro-mean()-Y',
 '428 fBodyGyro-std()-Y',
 '431 fBodyGyro-mad()-Y',
 '441 fBodyGyro-energy()-Y',
 '475 fBodyGyro-bandsEnergy()-1,8',
 '478 fBodyGyro-bandsEnergy()-25,32',
 '483 fBodyGyro-bandsEnergy()-1,16',
 '487 fBodyGyro-bandsEnergy()-1,24',
 '559 angle(X,gravityMean)',
 '560 angle(Y,gravityMean)',
 '561 angle(Z,gravityMean)']

act_features = ['4 tBodyAcc-std()-X',
 '7 tBodyAcc-mad()-X',
 '10 tBodyAcc-max()-X',
 '17 tBodyAcc-energy()-X',
 '202 tBodyAccMag-std()',
 '204 tBodyAccMag-max()',
 '215 tGravityAccMag-std()',
 '217 tGravityAccMag-max()',
 '266 fBodyAcc-mean()-X',
 '269 fBodyAcc-std()-X',
 '272 fBodyAcc-mad()-X',
 '275 fBodyAcc-max()-X',
 '282 fBodyAcc-energy()-X',
 '303 fBodyAcc-bandsEnergy()-1,8',
 '311 fBodyAcc-bandsEnergy()-1,16',
 '315 fBodyAcc-bandsEnergy()-1,24',
 '504 fBodyAccMag-std()',
 '505 fBodyAccMag-mad()',
 '506 fBodyAccMag-max()',
 '509 fBodyAccMag-energy()']

input_shape = len(sub_features) + len(act_features)

In [3]:
def classifier_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.LeakyReLU(0.05)
    )

class Classifier(nn.Module):
    def __init__(self, feature_dim = input_shape):
        super(Classifier, self).__init__()
        self.network = nn.Sequential(
            classifier_block(feature_dim, 25),
            classifier_block(25, 20),
            classifier_block(20, 15),
            classifier_block(15, 10),
            nn.Linear(10, 9)
        )
    def forward(self, x):
        return self.network(x)

In [4]:
#defines each generator layer
#input and output dimensions needed
def generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.Dropout(0.1),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace = True)
    )

#returns n_samples of z_dim (number of dimensions of latent space) noise
def get_noise(n_samples, z_dim):
    return torch.randn(n_samples, z_dim)

#defines generator class
class Generator(nn.Module):
    def __init__(self, z_dim = 10, feature_dim = input_shape, hidden_dim = 128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            generator_block(z_dim, 80),
            generator_block(80, 60),
            generator_block(60, 50),
            nn.Linear(50, feature_dim),
            nn.Tanh()
        )
    def forward(self, noise):
        return self.gen(noise)

def load_model(model, model_name):
    model.load_state_dict(torch.load(f'../../saved_models/{model_name}'))

In [5]:
#label is a list of integers specifying which labels to filter by
#users is a list of integers specifying which users to filter by
#y_label is a string, either "Activity" or "Subject" depending on what y output needs to be returned
def start_data(label, users, y_label, sub_features, act_features):
    #get the dataframe column names
    name_dataframe = pd.read_csv('../../data/features.txt', delimiter = '\n', header = None)
    names = name_dataframe.values.tolist()
    names = [k for row in names for k in row] #List of column names

    data = pd.read_csv('../../data/X_train.txt', delim_whitespace = True, header = None) #Read in dataframe
    data.columns = names #Setting column names
    
    X_train_1 = data[sub_features]
    X_train_2 = data[act_features]
    X_train = pd.concat([X_train_1, X_train_2], axis = 1)
    
    y_train_activity = pd.read_csv('../../data/y_train.txt', header = None)
    y_train_activity.columns = ['Activity']
    
    y_train_subject = pd.read_csv('../../data/subject_train.txt', header = None)
    y_train_subject.columns = ['Subject']

    GAN_data = pd.concat([X_train, y_train_activity, y_train_subject], axis = 1)
    GAN_data = GAN_data[GAN_data['Activity'].isin(label)]
    GAN_data = GAN_data[GAN_data['Subject'].isin(users)]
    
    X_1 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_2 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_3 = GAN_data[(GAN_data['Subject'] == 7) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_4 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_5 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_6 = GAN_data[(GAN_data['Subject'] == 8) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    X_7 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 1)].iloc[:,:-2].values
    X_8 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 3)].iloc[:,:-2].values
    X_9 = GAN_data[(GAN_data['Subject'] == 11) & (GAN_data['Activity'] == 4)].iloc[:,:-2].values
    
    X_train = np.concatenate((X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9))
    y_train = [0] * len(X_1) + [1] * len(X_2) + [2] * len(X_3) + [3] * len(X_4) + [4] * len(X_5) + [5] * len(X_6) + [6] * len(X_7) + [7] * len(X_8) + [8] * len(X_9)
    
    return X_train, np.asarray(y_train)

In [6]:
activities = [1, 3, 4]
users = [7, 8, 11]

X, y = start_data(activities, users, "Activity", sub_features, act_features)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True)

model = Classifier()
lr = 0.001
n_epochs = 5000
batch_size = 250

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = lr)

train_features = torch.tensor(X_train)
train_labels = torch.tensor(y_train)
test_features = torch.tensor(X_test)
test_labels = torch.tensor(y_test)

train_data = torch.utils.data.TensorDataset(train_features, train_labels)
test_data = torch.utils.data.TensorDataset(test_features, test_labels)

train_loader = torch.utils.data.DataLoader(train_data, batch_size = batch_size, shuffle = True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size = len(test_labels), shuffle = True)

In [7]:
for epoch in range(n_epochs):
    total_loss = 0
    for batch in train_loader:
        features, labels = batch
        
        optimizer.zero_grad()
        preds = model(features.float())
        
        loss = criterion(preds, labels.long()) 
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
    print(f'Epoch {epoch + 1}, Loss: {total_loss}, Final Batch Loss: {loss.item()}')

Epoch 1, Loss: 4.453675746917725, Final Batch Loss: 2.2290611267089844
Epoch 2, Loss: 4.44475793838501, Final Batch Loss: 2.231189250946045
Epoch 3, Loss: 4.4294633865356445, Final Batch Loss: 2.2035324573516846
Epoch 4, Loss: 4.413354158401489, Final Batch Loss: 2.192084550857544
Epoch 5, Loss: 4.423693656921387, Final Batch Loss: 2.220151662826538
Epoch 6, Loss: 4.409757852554321, Final Batch Loss: 2.1953811645507812
Epoch 7, Loss: 4.4122772216796875, Final Batch Loss: 2.2103021144866943
Epoch 8, Loss: 4.400604486465454, Final Batch Loss: 2.196280002593994
Epoch 9, Loss: 4.400053262710571, Final Batch Loss: 2.204777240753174
Epoch 10, Loss: 4.400651216506958, Final Batch Loss: 2.209001302719116
Epoch 11, Loss: 4.387958526611328, Final Batch Loss: 2.188906192779541
Epoch 12, Loss: 4.364265441894531, Final Batch Loss: 2.167839527130127
Epoch 13, Loss: 4.363017559051514, Final Batch Loss: 2.17270827293396
Epoch 14, Loss: 4.373602390289307, Final Batch Loss: 2.196155071258545
Epoch 15, L

Epoch 128, Loss: 2.1222002506256104, Final Batch Loss: 1.0191209316253662
Epoch 129, Loss: 2.060320496559143, Final Batch Loss: 1.0155359506607056
Epoch 130, Loss: 2.2010324001312256, Final Batch Loss: 1.0974479913711548
Epoch 131, Loss: 2.0849387645721436, Final Batch Loss: 1.0813450813293457
Epoch 132, Loss: 2.0368192195892334, Final Batch Loss: 0.9917807579040527
Epoch 133, Loss: 2.044560432434082, Final Batch Loss: 1.0195772647857666
Epoch 134, Loss: 2.1002601385116577, Final Batch Loss: 1.1065977811813354
Epoch 135, Loss: 2.068902552127838, Final Batch Loss: 1.1425652503967285
Epoch 136, Loss: 2.067120313644409, Final Batch Loss: 1.0306068658828735
Epoch 137, Loss: 2.071666419506073, Final Batch Loss: 1.0812193155288696
Epoch 138, Loss: 1.9863812923431396, Final Batch Loss: 1.0020908117294312
Epoch 139, Loss: 2.081805109977722, Final Batch Loss: 1.0539032220840454
Epoch 140, Loss: 1.8822236061096191, Final Batch Loss: 0.9355401396751404
Epoch 141, Loss: 1.9166374206542969, Final B

Epoch 255, Loss: 1.2742061614990234, Final Batch Loss: 0.6134803295135498
Epoch 256, Loss: 1.2300794124603271, Final Batch Loss: 0.6623453497886658
Epoch 257, Loss: 1.1163482069969177, Final Batch Loss: 0.49763351678848267
Epoch 258, Loss: 1.2009881734848022, Final Batch Loss: 0.6269548535346985
Epoch 259, Loss: 1.1169044375419617, Final Batch Loss: 0.5743025541305542
Epoch 260, Loss: 1.202799677848816, Final Batch Loss: 0.5888945460319519
Epoch 261, Loss: 1.047234058380127, Final Batch Loss: 0.5517752766609192
Epoch 262, Loss: 1.232102632522583, Final Batch Loss: 0.7039804458618164
Epoch 263, Loss: 1.2471774816513062, Final Batch Loss: 0.6308202147483826
Epoch 264, Loss: 1.163964033126831, Final Batch Loss: 0.5617830157279968
Epoch 265, Loss: 1.1246622204780579, Final Batch Loss: 0.5506120920181274
Epoch 266, Loss: 1.1127955913543701, Final Batch Loss: 0.5591451525688171
Epoch 267, Loss: 1.1168991923332214, Final Batch Loss: 0.5327377915382385
Epoch 268, Loss: 1.16733717918396, Final 

Epoch 373, Loss: 0.8672861158847809, Final Batch Loss: 0.4369940757751465
Epoch 374, Loss: 0.867527037858963, Final Batch Loss: 0.44675007462501526
Epoch 375, Loss: 0.9040864408016205, Final Batch Loss: 0.4705889821052551
Epoch 376, Loss: 0.8403051495552063, Final Batch Loss: 0.40746381878852844
Epoch 377, Loss: 0.8913387954235077, Final Batch Loss: 0.41260939836502075
Epoch 378, Loss: 0.811932384967804, Final Batch Loss: 0.45001277327537537
Epoch 379, Loss: 0.7794253528118134, Final Batch Loss: 0.35423967242240906
Epoch 380, Loss: 0.991836667060852, Final Batch Loss: 0.5301458239555359
Epoch 381, Loss: 0.7944869697093964, Final Batch Loss: 0.37589308619499207
Epoch 382, Loss: 0.8062061071395874, Final Batch Loss: 0.40479564666748047
Epoch 383, Loss: 0.8711641728878021, Final Batch Loss: 0.4382861256599426
Epoch 384, Loss: 0.9456667900085449, Final Batch Loss: 0.53939288854599
Epoch 385, Loss: 0.7964400053024292, Final Batch Loss: 0.3627665638923645
Epoch 386, Loss: 0.8713759779930115,

Epoch 485, Loss: 0.6512385606765747, Final Batch Loss: 0.2848978638648987
Epoch 486, Loss: 0.7787931263446808, Final Batch Loss: 0.39783909916877747
Epoch 487, Loss: 0.6444219946861267, Final Batch Loss: 0.30178308486938477
Epoch 488, Loss: 0.7199484407901764, Final Batch Loss: 0.3222852945327759
Epoch 489, Loss: 0.7481369078159332, Final Batch Loss: 0.3423008322715759
Epoch 490, Loss: 0.7403354942798615, Final Batch Loss: 0.39439961314201355
Epoch 491, Loss: 0.7590352892875671, Final Batch Loss: 0.38454434275627136
Epoch 492, Loss: 0.7711102962493896, Final Batch Loss: 0.39386245608329773
Epoch 493, Loss: 0.8066699802875519, Final Batch Loss: 0.47095805406570435
Epoch 494, Loss: 0.8014414012432098, Final Batch Loss: 0.44441935420036316
Epoch 495, Loss: 0.6557479202747345, Final Batch Loss: 0.32426509261131287
Epoch 496, Loss: 0.7333805859088898, Final Batch Loss: 0.3305043578147888
Epoch 497, Loss: 0.780603438615799, Final Batch Loss: 0.4651423692703247
Epoch 498, Loss: 0.769289135932

Epoch 604, Loss: 0.5943471789360046, Final Batch Loss: 0.2991049587726593
Epoch 605, Loss: 0.5437720566987991, Final Batch Loss: 0.22421224415302277
Epoch 606, Loss: 0.6757191121578217, Final Batch Loss: 0.31095531582832336
Epoch 607, Loss: 0.6273822784423828, Final Batch Loss: 0.32210513949394226
Epoch 608, Loss: 0.5649348199367523, Final Batch Loss: 0.27022257447242737
Epoch 609, Loss: 0.6083544790744781, Final Batch Loss: 0.2560519278049469
Epoch 610, Loss: 0.6735953986644745, Final Batch Loss: 0.3779153823852539
Epoch 611, Loss: 0.661878913640976, Final Batch Loss: 0.34255680441856384
Epoch 612, Loss: 0.5914434492588043, Final Batch Loss: 0.29299747943878174
Epoch 613, Loss: 0.5879680812358856, Final Batch Loss: 0.29053691029548645
Epoch 614, Loss: 0.5553170442581177, Final Batch Loss: 0.24579963088035583
Epoch 615, Loss: 0.6644776165485382, Final Batch Loss: 0.33136337995529175
Epoch 616, Loss: 0.7457129657268524, Final Batch Loss: 0.37345483899116516
Epoch 617, Loss: 0.5061892569

Epoch 714, Loss: 0.5888742804527283, Final Batch Loss: 0.28316259384155273
Epoch 715, Loss: 0.5639466047286987, Final Batch Loss: 0.2614525854587555
Epoch 716, Loss: 0.6393292546272278, Final Batch Loss: 0.31474658846855164
Epoch 717, Loss: 0.554702490568161, Final Batch Loss: 0.26321941614151
Epoch 718, Loss: 0.5817418396472931, Final Batch Loss: 0.26945728063583374
Epoch 719, Loss: 0.6022796034812927, Final Batch Loss: 0.30293479561805725
Epoch 720, Loss: 0.6362597346305847, Final Batch Loss: 0.33634352684020996
Epoch 721, Loss: 0.768082320690155, Final Batch Loss: 0.4357568621635437
Epoch 722, Loss: 0.623773068189621, Final Batch Loss: 0.33010759949684143
Epoch 723, Loss: 0.5950808525085449, Final Batch Loss: 0.32282140851020813
Epoch 724, Loss: 0.5769132673740387, Final Batch Loss: 0.31155142188072205
Epoch 725, Loss: 0.5418146699666977, Final Batch Loss: 0.2378646284341812
Epoch 726, Loss: 0.710781455039978, Final Batch Loss: 0.40449872612953186
Epoch 727, Loss: 0.5930525362491608

Epoch 828, Loss: 0.5849997401237488, Final Batch Loss: 0.31016403436660767
Epoch 829, Loss: 0.49414971470832825, Final Batch Loss: 0.2068166434764862
Epoch 830, Loss: 0.5178445279598236, Final Batch Loss: 0.2591498792171478
Epoch 831, Loss: 0.6959904730319977, Final Batch Loss: 0.3888823390007019
Epoch 832, Loss: 0.5879152715206146, Final Batch Loss: 0.26436465978622437
Epoch 833, Loss: 0.5312356501817703, Final Batch Loss: 0.2275775820016861
Epoch 834, Loss: 0.47615158557891846, Final Batch Loss: 0.20979171991348267
Epoch 835, Loss: 0.5587773025035858, Final Batch Loss: 0.2832806706428528
Epoch 836, Loss: 0.44044503569602966, Final Batch Loss: 0.17510849237442017
Epoch 837, Loss: 0.5763687789440155, Final Batch Loss: 0.3156074583530426
Epoch 838, Loss: 0.5724801272153854, Final Batch Loss: 0.3386695683002472
Epoch 839, Loss: 0.5113346874713898, Final Batch Loss: 0.24742212891578674
Epoch 840, Loss: 0.5850889682769775, Final Batch Loss: 0.25588613748550415
Epoch 841, Loss: 0.5131374597

Epoch 954, Loss: 0.5714327991008759, Final Batch Loss: 0.27184543013572693
Epoch 955, Loss: 0.60128553211689, Final Batch Loss: 0.3669237196445465
Epoch 956, Loss: 0.49811574816703796, Final Batch Loss: 0.2120400071144104
Epoch 957, Loss: 0.5868604481220245, Final Batch Loss: 0.27500584721565247
Epoch 958, Loss: 0.4554288238286972, Final Batch Loss: 0.19584356248378754
Epoch 959, Loss: 0.5257653445005417, Final Batch Loss: 0.22733734548091888
Epoch 960, Loss: 0.5037436932325363, Final Batch Loss: 0.23789988458156586
Epoch 961, Loss: 0.596660852432251, Final Batch Loss: 0.321437269449234
Epoch 962, Loss: 0.4918093830347061, Final Batch Loss: 0.2203260213136673
Epoch 963, Loss: 0.4959968328475952, Final Batch Loss: 0.24334844946861267
Epoch 964, Loss: 0.4576764553785324, Final Batch Loss: 0.2576466202735901
Epoch 965, Loss: 0.5191502422094345, Final Batch Loss: 0.23159600794315338
Epoch 966, Loss: 0.617277204990387, Final Batch Loss: 0.31540799140930176
Epoch 967, Loss: 0.620120823383331

Epoch 1080, Loss: 0.5154258161783218, Final Batch Loss: 0.285234272480011
Epoch 1081, Loss: 0.4833514839410782, Final Batch Loss: 0.26786139607429504
Epoch 1082, Loss: 0.5391601771116257, Final Batch Loss: 0.3053712844848633
Epoch 1083, Loss: 0.4733768701553345, Final Batch Loss: 0.20058545470237732
Epoch 1084, Loss: 0.5120308548212051, Final Batch Loss: 0.21180526912212372
Epoch 1085, Loss: 0.5422457605600357, Final Batch Loss: 0.3395829498767853
Epoch 1086, Loss: 0.5338976383209229, Final Batch Loss: 0.2529808282852173
Epoch 1087, Loss: 0.48425740003585815, Final Batch Loss: 0.23445092141628265
Epoch 1088, Loss: 0.5599775463342667, Final Batch Loss: 0.31323519349098206
Epoch 1089, Loss: 0.498673677444458, Final Batch Loss: 0.27445071935653687
Epoch 1090, Loss: 0.4920775592327118, Final Batch Loss: 0.21508145332336426
Epoch 1091, Loss: 0.46792924404144287, Final Batch Loss: 0.19833692908287048
Epoch 1092, Loss: 0.5031462013721466, Final Batch Loss: 0.257783442735672
Epoch 1093, Loss: 

Epoch 1204, Loss: 0.5453414618968964, Final Batch Loss: 0.3475673198699951
Epoch 1205, Loss: 0.4118146300315857, Final Batch Loss: 0.19466806948184967
Epoch 1206, Loss: 0.4334085136651993, Final Batch Loss: 0.18449769914150238
Epoch 1207, Loss: 0.42334267497062683, Final Batch Loss: 0.1995791494846344
Epoch 1208, Loss: 0.5722685009241104, Final Batch Loss: 0.33545300364494324
Epoch 1209, Loss: 0.5385974943637848, Final Batch Loss: 0.27523475885391235
Epoch 1210, Loss: 0.49488843977451324, Final Batch Loss: 0.2579730451107025
Epoch 1211, Loss: 0.5244956314563751, Final Batch Loss: 0.24433153867721558
Epoch 1212, Loss: 0.5099748969078064, Final Batch Loss: 0.28345006704330444
Epoch 1213, Loss: 0.47825323045253754, Final Batch Loss: 0.22796379029750824
Epoch 1214, Loss: 0.4524335116147995, Final Batch Loss: 0.19492383301258087
Epoch 1215, Loss: 0.4926694929599762, Final Batch Loss: 0.2592044472694397
Epoch 1216, Loss: 0.48167242109775543, Final Batch Loss: 0.18922187387943268
Epoch 1217, 

Epoch 1318, Loss: 0.4198768734931946, Final Batch Loss: 0.2153932899236679
Epoch 1319, Loss: 0.40734873712062836, Final Batch Loss: 0.20624695718288422
Epoch 1320, Loss: 0.49881120026111603, Final Batch Loss: 0.25080856680870056
Epoch 1321, Loss: 0.49196550250053406, Final Batch Loss: 0.20029106736183167
Epoch 1322, Loss: 0.4686856120824814, Final Batch Loss: 0.23437286913394928
Epoch 1323, Loss: 0.4619804620742798, Final Batch Loss: 0.2601943016052246
Epoch 1324, Loss: 0.39740778505802155, Final Batch Loss: 0.18948353826999664
Epoch 1325, Loss: 0.4451800286769867, Final Batch Loss: 0.26169919967651367
Epoch 1326, Loss: 0.4973333179950714, Final Batch Loss: 0.2766333818435669
Epoch 1327, Loss: 0.5168737918138504, Final Batch Loss: 0.29559656977653503
Epoch 1328, Loss: 0.4370548725128174, Final Batch Loss: 0.19316846132278442
Epoch 1329, Loss: 0.44449353218078613, Final Batch Loss: 0.22214891016483307
Epoch 1330, Loss: 0.4002896547317505, Final Batch Loss: 0.17468012869358063
Epoch 1331

Epoch 1429, Loss: 0.3963880240917206, Final Batch Loss: 0.17416688799858093
Epoch 1430, Loss: 0.43401025235652924, Final Batch Loss: 0.22883634269237518
Epoch 1431, Loss: 0.43013519048690796, Final Batch Loss: 0.2351420372724533
Epoch 1432, Loss: 0.38228537142276764, Final Batch Loss: 0.16171583533287048
Epoch 1433, Loss: 0.45100197196006775, Final Batch Loss: 0.2566121220588684
Epoch 1434, Loss: 0.44171565771102905, Final Batch Loss: 0.2088664174079895
Epoch 1435, Loss: 0.42871329188346863, Final Batch Loss: 0.19699127972126007
Epoch 1436, Loss: 0.44241903722286224, Final Batch Loss: 0.2524878978729248
Epoch 1437, Loss: 0.5152338743209839, Final Batch Loss: 0.2500355541706085
Epoch 1438, Loss: 0.3770151734352112, Final Batch Loss: 0.19620458781719208
Epoch 1439, Loss: 0.39629969000816345, Final Batch Loss: 0.200076162815094
Epoch 1440, Loss: 0.494319811463356, Final Batch Loss: 0.28145113587379456
Epoch 1441, Loss: 0.46578918397426605, Final Batch Loss: 0.26276254653930664
Epoch 1442,

Epoch 1542, Loss: 0.4715178906917572, Final Batch Loss: 0.2791464626789093
Epoch 1543, Loss: 0.36591118574142456, Final Batch Loss: 0.15338805317878723
Epoch 1544, Loss: 0.4495592415332794, Final Batch Loss: 0.1913718581199646
Epoch 1545, Loss: 0.44571787118911743, Final Batch Loss: 0.2316124141216278
Epoch 1546, Loss: 0.5003170222043991, Final Batch Loss: 0.3044961392879486
Epoch 1547, Loss: 0.46236173808574677, Final Batch Loss: 0.2631588578224182
Epoch 1548, Loss: 0.37342554330825806, Final Batch Loss: 0.15060578286647797
Epoch 1549, Loss: 0.4287153482437134, Final Batch Loss: 0.2298027127981186
Epoch 1550, Loss: 0.37842172384262085, Final Batch Loss: 0.16596084833145142
Epoch 1551, Loss: 0.4137255996465683, Final Batch Loss: 0.2034812867641449
Epoch 1552, Loss: 0.38124775886535645, Final Batch Loss: 0.17226290702819824
Epoch 1553, Loss: 0.44391465187072754, Final Batch Loss: 0.21433259546756744
Epoch 1554, Loss: 0.44522158801555634, Final Batch Loss: 0.2401772439479828
Epoch 1555, 

Epoch 1653, Loss: 0.42772263288497925, Final Batch Loss: 0.17712587118148804
Epoch 1654, Loss: 0.3747766464948654, Final Batch Loss: 0.1798435002565384
Epoch 1655, Loss: 0.45327867567539215, Final Batch Loss: 0.2715173661708832
Epoch 1656, Loss: 0.4612688720226288, Final Batch Loss: 0.24805152416229248
Epoch 1657, Loss: 0.3968425691127777, Final Batch Loss: 0.1839446872472763
Epoch 1658, Loss: 0.4583321213722229, Final Batch Loss: 0.2363535463809967
Epoch 1659, Loss: 0.49334658682346344, Final Batch Loss: 0.29196467995643616
Epoch 1660, Loss: 0.34899963438510895, Final Batch Loss: 0.18515874445438385
Epoch 1661, Loss: 0.4558435380458832, Final Batch Loss: 0.260369211435318
Epoch 1662, Loss: 0.4097157418727875, Final Batch Loss: 0.24880801141262054
Epoch 1663, Loss: 0.4068557173013687, Final Batch Loss: 0.18118026852607727
Epoch 1664, Loss: 0.4145810306072235, Final Batch Loss: 0.19637301564216614
Epoch 1665, Loss: 0.4287222921848297, Final Batch Loss: 0.20024271309375763
Epoch 1666, Lo

Epoch 1769, Loss: 0.3941895514726639, Final Batch Loss: 0.194500133395195
Epoch 1770, Loss: 0.41094034910202026, Final Batch Loss: 0.2229313850402832
Epoch 1771, Loss: 0.37250688672065735, Final Batch Loss: 0.14320699870586395
Epoch 1772, Loss: 0.41010600328445435, Final Batch Loss: 0.1914169192314148
Epoch 1773, Loss: 0.42128323018550873, Final Batch Loss: 0.2602170407772064
Epoch 1774, Loss: 0.4722674489021301, Final Batch Loss: 0.25772470235824585
Epoch 1775, Loss: 0.35421109199523926, Final Batch Loss: 0.15664924681186676
Epoch 1776, Loss: 0.44261452555656433, Final Batch Loss: 0.22244791686534882
Epoch 1777, Loss: 0.42218002676963806, Final Batch Loss: 0.2154126912355423
Epoch 1778, Loss: 0.4142683148384094, Final Batch Loss: 0.2231702357530594
Epoch 1779, Loss: 0.4099961370229721, Final Batch Loss: 0.22303372621536255
Epoch 1780, Loss: 0.37518566846847534, Final Batch Loss: 0.1561640053987503
Epoch 1781, Loss: 0.37803125381469727, Final Batch Loss: 0.21155354380607605
Epoch 1782,

Epoch 1879, Loss: 0.36170724034309387, Final Batch Loss: 0.17042851448059082
Epoch 1880, Loss: 0.4628332406282425, Final Batch Loss: 0.2599051594734192
Epoch 1881, Loss: 0.4123842567205429, Final Batch Loss: 0.23236066102981567
Epoch 1882, Loss: 0.36262059211730957, Final Batch Loss: 0.16168281435966492
Epoch 1883, Loss: 0.3870280832052231, Final Batch Loss: 0.165652796626091
Epoch 1884, Loss: 0.4523593932390213, Final Batch Loss: 0.24871475994586945
Epoch 1885, Loss: 0.36484141647815704, Final Batch Loss: 0.17659986019134521
Epoch 1886, Loss: 0.3883449137210846, Final Batch Loss: 0.19881831109523773
Epoch 1887, Loss: 0.39490413665771484, Final Batch Loss: 0.1667787730693817
Epoch 1888, Loss: 0.4005099833011627, Final Batch Loss: 0.16444265842437744
Epoch 1889, Loss: 0.4083987921476364, Final Batch Loss: 0.2484574168920517
Epoch 1890, Loss: 0.3182462453842163, Final Batch Loss: 0.12826181948184967
Epoch 1891, Loss: 0.4229744076728821, Final Batch Loss: 0.23723044991493225
Epoch 1892, L

Epoch 1993, Loss: 0.3753764033317566, Final Batch Loss: 0.17823591828346252
Epoch 1994, Loss: 0.3542744517326355, Final Batch Loss: 0.16864466667175293
Epoch 1995, Loss: 0.32741018384695053, Final Batch Loss: 0.11310557276010513
Epoch 1996, Loss: 0.4229334741830826, Final Batch Loss: 0.24785088002681732
Epoch 1997, Loss: 0.3722245693206787, Final Batch Loss: 0.18537193536758423
Epoch 1998, Loss: 0.4338116943836212, Final Batch Loss: 0.23498396575450897
Epoch 1999, Loss: 0.40657763183116913, Final Batch Loss: 0.2399573028087616
Epoch 2000, Loss: 0.3454745262861252, Final Batch Loss: 0.12716364860534668
Epoch 2001, Loss: 0.35515494644641876, Final Batch Loss: 0.1778952032327652
Epoch 2002, Loss: 0.3758518546819687, Final Batch Loss: 0.14470414817333221
Epoch 2003, Loss: 0.4311057776212692, Final Batch Loss: 0.2778017222881317
Epoch 2004, Loss: 0.3730213791131973, Final Batch Loss: 0.13895195722579956
Epoch 2005, Loss: 0.328996941447258, Final Batch Loss: 0.14027650654315948
Epoch 2006, L

Epoch 2103, Loss: 0.36284807324409485, Final Batch Loss: 0.16329962015151978
Epoch 2104, Loss: 0.38781705498695374, Final Batch Loss: 0.22631387412548065
Epoch 2105, Loss: 0.35811538994312286, Final Batch Loss: 0.19010764360427856
Epoch 2106, Loss: 0.46668246388435364, Final Batch Loss: 0.3052157461643219
Epoch 2107, Loss: 0.33565160632133484, Final Batch Loss: 0.17439928650856018
Epoch 2108, Loss: 0.30424104630947113, Final Batch Loss: 0.1424240618944168
Epoch 2109, Loss: 0.33353424072265625, Final Batch Loss: 0.1472897231578827
Epoch 2110, Loss: 0.4722091108560562, Final Batch Loss: 0.26241540908813477
Epoch 2111, Loss: 0.3561304658651352, Final Batch Loss: 0.18629679083824158
Epoch 2112, Loss: 0.35861344635486603, Final Batch Loss: 0.18478447198867798
Epoch 2113, Loss: 0.353032723069191, Final Batch Loss: 0.1752520650625229
Epoch 2114, Loss: 0.3652133196592331, Final Batch Loss: 0.17610524594783783
Epoch 2115, Loss: 0.3153913617134094, Final Batch Loss: 0.1503472626209259
Epoch 2116

Epoch 2228, Loss: 0.4086034595966339, Final Batch Loss: 0.2078360617160797
Epoch 2229, Loss: 0.3537014424800873, Final Batch Loss: 0.14964237809181213
Epoch 2230, Loss: 0.35375744104385376, Final Batch Loss: 0.19255538284778595
Epoch 2231, Loss: 0.3601302057504654, Final Batch Loss: 0.19785065948963165
Epoch 2232, Loss: 0.41722801327705383, Final Batch Loss: 0.2230195850133896
Epoch 2233, Loss: 0.3153100907802582, Final Batch Loss: 0.11222746968269348
Epoch 2234, Loss: 0.35160477459430695, Final Batch Loss: 0.15405398607254028
Epoch 2235, Loss: 0.357235848903656, Final Batch Loss: 0.1574626863002777
Epoch 2236, Loss: 0.3816307783126831, Final Batch Loss: 0.16435889899730682
Epoch 2237, Loss: 0.3579167425632477, Final Batch Loss: 0.17886927723884583
Epoch 2238, Loss: 0.3775162994861603, Final Batch Loss: 0.21880963444709778
Epoch 2239, Loss: 0.28353944420814514, Final Batch Loss: 0.10846477746963501
Epoch 2240, Loss: 0.35522398352622986, Final Batch Loss: 0.19169721007347107
Epoch 2241,

Epoch 2348, Loss: 0.2900123745203018, Final Batch Loss: 0.13088536262512207
Epoch 2349, Loss: 0.3641740530729294, Final Batch Loss: 0.19062380492687225
Epoch 2350, Loss: 0.4443770498037338, Final Batch Loss: 0.22535395622253418
Epoch 2351, Loss: 0.3626067489385605, Final Batch Loss: 0.1881617158651352
Epoch 2352, Loss: 0.3490724563598633, Final Batch Loss: 0.15143384039402008
Epoch 2353, Loss: 0.3638027012348175, Final Batch Loss: 0.23079808056354523
Epoch 2354, Loss: 0.3147096633911133, Final Batch Loss: 0.13779616355895996
Epoch 2355, Loss: 0.3866693526506424, Final Batch Loss: 0.22269997000694275
Epoch 2356, Loss: 0.3462284058332443, Final Batch Loss: 0.16984343528747559
Epoch 2357, Loss: 0.3625708967447281, Final Batch Loss: 0.19773630797863007
Epoch 2358, Loss: 0.3527041971683502, Final Batch Loss: 0.19548752903938293
Epoch 2359, Loss: 0.36284714937210083, Final Batch Loss: 0.14272412657737732
Epoch 2360, Loss: 0.3733402192592621, Final Batch Loss: 0.16556940972805023
Epoch 2361, 

Epoch 2467, Loss: 0.3237292915582657, Final Batch Loss: 0.16801920533180237
Epoch 2468, Loss: 0.38230520486831665, Final Batch Loss: 0.2026698887348175
Epoch 2469, Loss: 0.40084175765514374, Final Batch Loss: 0.21752706170082092
Epoch 2470, Loss: 0.3714348375797272, Final Batch Loss: 0.22510050237178802
Epoch 2471, Loss: 0.3248744457960129, Final Batch Loss: 0.12745770812034607
Epoch 2472, Loss: 0.3792423754930496, Final Batch Loss: 0.20037370920181274
Epoch 2473, Loss: 0.28968483209609985, Final Batch Loss: 0.1377735286951065
Epoch 2474, Loss: 0.3787953704595566, Final Batch Loss: 0.21245881915092468
Epoch 2475, Loss: 0.4220384359359741, Final Batch Loss: 0.24054038524627686
Epoch 2476, Loss: 0.31581658124923706, Final Batch Loss: 0.15407121181488037
Epoch 2477, Loss: 0.35321828722953796, Final Batch Loss: 0.18077120184898376
Epoch 2478, Loss: 0.28226669877767563, Final Batch Loss: 0.10929413884878159
Epoch 2479, Loss: 0.36888158321380615, Final Batch Loss: 0.22317735850811005
Epoch 2

Epoch 2588, Loss: 0.3560514748096466, Final Batch Loss: 0.1626933217048645
Epoch 2589, Loss: 0.35604624450206757, Final Batch Loss: 0.16581915318965912
Epoch 2590, Loss: 0.3056976795196533, Final Batch Loss: 0.1434321403503418
Epoch 2591, Loss: 0.38701915740966797, Final Batch Loss: 0.24048058688640594
Epoch 2592, Loss: 0.35267212986946106, Final Batch Loss: 0.16528013348579407
Epoch 2593, Loss: 0.36052581667900085, Final Batch Loss: 0.21418090164661407
Epoch 2594, Loss: 0.29105304181575775, Final Batch Loss: 0.1377503126859665
Epoch 2595, Loss: 0.3286489099264145, Final Batch Loss: 0.1399846374988556
Epoch 2596, Loss: 0.33306485414505005, Final Batch Loss: 0.17920784652233124
Epoch 2597, Loss: 0.48964712023735046, Final Batch Loss: 0.330121785402298
Epoch 2598, Loss: 0.3079705983400345, Final Batch Loss: 0.12461212277412415
Epoch 2599, Loss: 0.321977898478508, Final Batch Loss: 0.17111635208129883
Epoch 2600, Loss: 0.3352929651737213, Final Batch Loss: 0.14622201025485992
Epoch 2601, 

Epoch 2700, Loss: 0.34012462198734283, Final Batch Loss: 0.2101193517446518
Epoch 2701, Loss: 0.2892989367246628, Final Batch Loss: 0.1520584523677826
Epoch 2702, Loss: 0.35603776574134827, Final Batch Loss: 0.19873246550559998
Epoch 2703, Loss: 0.363326832652092, Final Batch Loss: 0.16148541867733002
Epoch 2704, Loss: 0.3327580839395523, Final Batch Loss: 0.19547811150550842
Epoch 2705, Loss: 0.36767150461673737, Final Batch Loss: 0.18385711312294006
Epoch 2706, Loss: 0.38781675696372986, Final Batch Loss: 0.18731719255447388
Epoch 2707, Loss: 0.29377370327711105, Final Batch Loss: 0.10344109684228897
Epoch 2708, Loss: 0.41921618580818176, Final Batch Loss: 0.25465402007102966
Epoch 2709, Loss: 0.3452892005443573, Final Batch Loss: 0.19502992928028107
Epoch 2710, Loss: 0.35609160363674164, Final Batch Loss: 0.19245977699756622
Epoch 2711, Loss: 0.342224583029747, Final Batch Loss: 0.21429327130317688
Epoch 2712, Loss: 0.2995636612176895, Final Batch Loss: 0.13293634355068207
Epoch 271

Epoch 2820, Loss: 0.36532458662986755, Final Batch Loss: 0.2015364021062851
Epoch 2821, Loss: 0.33578526973724365, Final Batch Loss: 0.1655021756887436
Epoch 2822, Loss: 0.34232114255428314, Final Batch Loss: 0.18674491345882416
Epoch 2823, Loss: 0.31611794978380203, Final Batch Loss: 0.12060872465372086
Epoch 2824, Loss: 0.2949056625366211, Final Batch Loss: 0.1282579004764557
Epoch 2825, Loss: 0.3411039561033249, Final Batch Loss: 0.1897881031036377
Epoch 2826, Loss: 0.3415653705596924, Final Batch Loss: 0.13758625090122223
Epoch 2827, Loss: 0.3402617573738098, Final Batch Loss: 0.19446054100990295
Epoch 2828, Loss: 0.32341189682483673, Final Batch Loss: 0.14625033736228943
Epoch 2829, Loss: 0.30716776847839355, Final Batch Loss: 0.12969695031642914
Epoch 2830, Loss: 0.3316190242767334, Final Batch Loss: 0.16770806908607483
Epoch 2831, Loss: 0.3800530880689621, Final Batch Loss: 0.1367969661951065
Epoch 2832, Loss: 0.2993001118302345, Final Batch Loss: 0.10349560528993607
Epoch 2833,

Epoch 2949, Loss: 0.3494618982076645, Final Batch Loss: 0.2149384319782257
Epoch 2950, Loss: 0.40242888033390045, Final Batch Loss: 0.23038703203201294
Epoch 2951, Loss: 0.34401895105838776, Final Batch Loss: 0.1942083239555359
Epoch 2952, Loss: 0.2918582707643509, Final Batch Loss: 0.14360311627388
Epoch 2953, Loss: 0.35964377224445343, Final Batch Loss: 0.183827206492424
Epoch 2954, Loss: 0.3663969188928604, Final Batch Loss: 0.1664981245994568
Epoch 2955, Loss: 0.3396992161870003, Final Batch Loss: 0.22971844673156738
Epoch 2956, Loss: 0.29732082039117813, Final Batch Loss: 0.11342313140630722
Epoch 2957, Loss: 0.3213071823120117, Final Batch Loss: 0.14901013672351837
Epoch 2958, Loss: 0.29394927620887756, Final Batch Loss: 0.12668552994728088
Epoch 2959, Loss: 0.4325577914714813, Final Batch Loss: 0.26228243112564087
Epoch 2960, Loss: 0.28275204449892044, Final Batch Loss: 0.11909934133291245
Epoch 2961, Loss: 0.34745050966739655, Final Batch Loss: 0.16665391623973846
Epoch 2962, L

Epoch 3062, Loss: 0.30460236966609955, Final Batch Loss: 0.12705561518669128
Epoch 3063, Loss: 0.33108681440353394, Final Batch Loss: 0.17017140984535217
Epoch 3064, Loss: 0.2738946005702019, Final Batch Loss: 0.10383938997983932
Epoch 3065, Loss: 0.2418658509850502, Final Batch Loss: 0.108037568628788
Epoch 3066, Loss: 0.3193445950746536, Final Batch Loss: 0.1720838099718094
Epoch 3067, Loss: 0.2615412771701813, Final Batch Loss: 0.1337110996246338
Epoch 3068, Loss: 0.28092610090970993, Final Batch Loss: 0.15710629522800446
Epoch 3069, Loss: 0.29285409301519394, Final Batch Loss: 0.1186174526810646
Epoch 3070, Loss: 0.26885634660720825, Final Batch Loss: 0.1346832513809204
Epoch 3071, Loss: 0.35777448117733, Final Batch Loss: 0.17800447344779968
Epoch 3072, Loss: 0.31254348158836365, Final Batch Loss: 0.14366522431373596
Epoch 3073, Loss: 0.2753727287054062, Final Batch Loss: 0.13619287312030792
Epoch 3074, Loss: 0.32076670974493027, Final Batch Loss: 0.12424086779356003
Epoch 3075, L

Epoch 3169, Loss: 0.2989775091409683, Final Batch Loss: 0.15745043754577637
Epoch 3170, Loss: 0.3518963158130646, Final Batch Loss: 0.1441928595304489
Epoch 3171, Loss: 0.3059706538915634, Final Batch Loss: 0.13616882264614105
Epoch 3172, Loss: 0.2517736181616783, Final Batch Loss: 0.1101902648806572
Epoch 3173, Loss: 0.2811865210533142, Final Batch Loss: 0.14336206018924713
Epoch 3174, Loss: 0.2626829966902733, Final Batch Loss: 0.12441536039113998
Epoch 3175, Loss: 0.28698983788490295, Final Batch Loss: 0.15329839289188385
Epoch 3176, Loss: 0.3345903009176254, Final Batch Loss: 0.1519850790500641
Epoch 3177, Loss: 0.2695707380771637, Final Batch Loss: 0.07001300156116486
Epoch 3178, Loss: 0.30744974315166473, Final Batch Loss: 0.15971407294273376
Epoch 3179, Loss: 0.2824833542108536, Final Batch Loss: 0.12854303419589996
Epoch 3180, Loss: 0.2725434899330139, Final Batch Loss: 0.1433252990245819
Epoch 3181, Loss: 0.31195099651813507, Final Batch Loss: 0.18276245892047882
Epoch 3182, L

Epoch 3280, Loss: 0.23639419674873352, Final Batch Loss: 0.11895039677619934
Epoch 3281, Loss: 0.24752720445394516, Final Batch Loss: 0.10599713772535324
Epoch 3282, Loss: 0.26931843161582947, Final Batch Loss: 0.12949340045452118
Epoch 3283, Loss: 0.2629581391811371, Final Batch Loss: 0.13637812435626984
Epoch 3284, Loss: 0.32539473474025726, Final Batch Loss: 0.14792391657829285
Epoch 3285, Loss: 0.3021342605352402, Final Batch Loss: 0.1609208732843399
Epoch 3286, Loss: 0.28726379573345184, Final Batch Loss: 0.14966976642608643
Epoch 3287, Loss: 0.27695605158805847, Final Batch Loss: 0.14526891708374023
Epoch 3288, Loss: 0.4191923886537552, Final Batch Loss: 0.16808180510997772
Epoch 3289, Loss: 0.24257543683052063, Final Batch Loss: 0.10899819433689117
Epoch 3290, Loss: 0.2574678808450699, Final Batch Loss: 0.11246481537818909
Epoch 3291, Loss: 0.24097856134176254, Final Batch Loss: 0.10627802461385727
Epoch 3292, Loss: 0.28968629240989685, Final Batch Loss: 0.13754333555698395
Epoc

Epoch 3404, Loss: 0.33588235080242157, Final Batch Loss: 0.15362881124019623
Epoch 3405, Loss: 0.2783961743116379, Final Batch Loss: 0.13642895221710205
Epoch 3406, Loss: 0.33144114911556244, Final Batch Loss: 0.17105865478515625
Epoch 3407, Loss: 0.2704475000500679, Final Batch Loss: 0.07373148947954178
Epoch 3408, Loss: 0.2991870194673538, Final Batch Loss: 0.11270219087600708
Epoch 3409, Loss: 0.33045344054698944, Final Batch Loss: 0.12494975328445435
Epoch 3410, Loss: 0.2758510559797287, Final Batch Loss: 0.09364917874336243
Epoch 3411, Loss: 0.4091433137655258, Final Batch Loss: 0.24788866937160492
Epoch 3412, Loss: 0.41130800545215607, Final Batch Loss: 0.2866382598876953
Epoch 3413, Loss: 0.29188790917396545, Final Batch Loss: 0.1629943996667862
Epoch 3414, Loss: 0.2972313016653061, Final Batch Loss: 0.15557436645030975
Epoch 3415, Loss: 0.2597084417939186, Final Batch Loss: 0.13854655623435974
Epoch 3416, Loss: 0.3504639118909836, Final Batch Loss: 0.16440369188785553
Epoch 341

Epoch 3519, Loss: 0.22601012140512466, Final Batch Loss: 0.09812558442354202
Epoch 3520, Loss: 0.34177081286907196, Final Batch Loss: 0.16246625781059265
Epoch 3521, Loss: 0.3167015612125397, Final Batch Loss: 0.18837618827819824
Epoch 3522, Loss: 0.3508540689945221, Final Batch Loss: 0.21274413168430328
Epoch 3523, Loss: 0.3483567237854004, Final Batch Loss: 0.2008417546749115
Epoch 3524, Loss: 0.29480697959661484, Final Batch Loss: 0.1815166473388672
Epoch 3525, Loss: 0.2740190178155899, Final Batch Loss: 0.14009740948677063
Epoch 3526, Loss: 0.28275322914123535, Final Batch Loss: 0.1272476762533188
Epoch 3527, Loss: 0.26507518440485, Final Batch Loss: 0.11282656341791153
Epoch 3528, Loss: 0.2922833263874054, Final Batch Loss: 0.12275360524654388
Epoch 3529, Loss: 0.26556210964918137, Final Batch Loss: 0.07815913110971451
Epoch 3530, Loss: 0.33986063301563263, Final Batch Loss: 0.1913158893585205
Epoch 3531, Loss: 0.27449965476989746, Final Batch Loss: 0.12360022962093353
Epoch 3532,

Epoch 3638, Loss: 0.27292198687791824, Final Batch Loss: 0.11122751981019974
Epoch 3639, Loss: 0.40659117698669434, Final Batch Loss: 0.19427786767482758
Epoch 3640, Loss: 0.25426004081964493, Final Batch Loss: 0.09572724252939224
Epoch 3641, Loss: 0.32117612659931183, Final Batch Loss: 0.19019906222820282
Epoch 3642, Loss: 0.2744799703359604, Final Batch Loss: 0.13218693435192108
Epoch 3643, Loss: 0.27658550441265106, Final Batch Loss: 0.13860291242599487
Epoch 3644, Loss: 0.31313830614089966, Final Batch Loss: 0.18514588475227356
Epoch 3645, Loss: 0.3003596365451813, Final Batch Loss: 0.1336362212896347
Epoch 3646, Loss: 0.315782368183136, Final Batch Loss: 0.14778031408786774
Epoch 3647, Loss: 0.3244432061910629, Final Batch Loss: 0.15675599873065948
Epoch 3648, Loss: 0.2711125984787941, Final Batch Loss: 0.09755551069974899
Epoch 3649, Loss: 0.293037548661232, Final Batch Loss: 0.1386643946170807
Epoch 3650, Loss: 0.30900582671165466, Final Batch Loss: 0.1574997454881668
Epoch 3651

Epoch 3759, Loss: 0.2926939129829407, Final Batch Loss: 0.14038494229316711
Epoch 3760, Loss: 0.2919882535934448, Final Batch Loss: 0.1640917956829071
Epoch 3761, Loss: 0.3354402482509613, Final Batch Loss: 0.13429929316043854
Epoch 3762, Loss: 0.24015557020902634, Final Batch Loss: 0.11468551307916641
Epoch 3763, Loss: 0.514886662364006, Final Batch Loss: 0.15418581664562225
Epoch 3764, Loss: 0.2845870405435562, Final Batch Loss: 0.14976172149181366
Epoch 3765, Loss: 0.26183465123176575, Final Batch Loss: 0.1341547667980194
Epoch 3766, Loss: 0.3259129077196121, Final Batch Loss: 0.18598991632461548
Epoch 3767, Loss: 0.3414393812417984, Final Batch Loss: 0.16746030747890472
Epoch 3768, Loss: 0.2711828798055649, Final Batch Loss: 0.1600688099861145
Epoch 3769, Loss: 0.2560610771179199, Final Batch Loss: 0.12681639194488525
Epoch 3770, Loss: 0.2618595287203789, Final Batch Loss: 0.15672750771045685
Epoch 3771, Loss: 0.285216748714447, Final Batch Loss: 0.1416236162185669
Epoch 3772, Loss

Epoch 3881, Loss: 0.2892241105437279, Final Batch Loss: 0.1738114356994629
Epoch 3882, Loss: 0.2629963383078575, Final Batch Loss: 0.14136813580989838
Epoch 3883, Loss: 0.2325213998556137, Final Batch Loss: 0.06760068237781525
Epoch 3884, Loss: 0.32124652713537216, Final Batch Loss: 0.19779199361801147
Epoch 3885, Loss: 0.24612286686897278, Final Batch Loss: 0.10147896409034729
Epoch 3886, Loss: 0.2882952615618706, Final Batch Loss: 0.168317973613739
Epoch 3887, Loss: 0.2778187170624733, Final Batch Loss: 0.15665099024772644
Epoch 3888, Loss: 0.25398845225572586, Final Batch Loss: 0.11494144052267075
Epoch 3889, Loss: 0.25952066481113434, Final Batch Loss: 0.11005997657775879
Epoch 3890, Loss: 0.24861357361078262, Final Batch Loss: 0.10984032601118088
Epoch 3891, Loss: 0.21796155720949173, Final Batch Loss: 0.08808184415102005
Epoch 3892, Loss: 0.2602737694978714, Final Batch Loss: 0.12327645719051361
Epoch 3893, Loss: 0.26928602159023285, Final Batch Loss: 0.13892953097820282
Epoch 38

Epoch 4003, Loss: 0.3246123716235161, Final Batch Loss: 0.10602625459432602
Epoch 4004, Loss: 0.25219210237264633, Final Batch Loss: 0.13125573098659515
Epoch 4005, Loss: 0.24505987763404846, Final Batch Loss: 0.11481219530105591
Epoch 4006, Loss: 0.24875490367412567, Final Batch Loss: 0.12064360082149506
Epoch 4007, Loss: 0.2672095373272896, Final Batch Loss: 0.11140774935483932
Epoch 4008, Loss: 0.2568240761756897, Final Batch Loss: 0.12325869500637054
Epoch 4009, Loss: 0.2767893150448799, Final Batch Loss: 0.15931840240955353
Epoch 4010, Loss: 0.2932899594306946, Final Batch Loss: 0.15487664937973022
Epoch 4011, Loss: 0.28632546961307526, Final Batch Loss: 0.15313847362995148
Epoch 4012, Loss: 0.30220718681812286, Final Batch Loss: 0.1473945528268814
Epoch 4013, Loss: 0.2659965753555298, Final Batch Loss: 0.12271332740783691
Epoch 4014, Loss: 0.24861131608486176, Final Batch Loss: 0.09692263603210449
Epoch 4015, Loss: 0.2651066854596138, Final Batch Loss: 0.15190008282661438
Epoch 4

Epoch 4117, Loss: 0.2643236964941025, Final Batch Loss: 0.13783682882785797
Epoch 4118, Loss: 0.37839318066835403, Final Batch Loss: 0.26167774200439453
Epoch 4119, Loss: 0.3215280622243881, Final Batch Loss: 0.1888193041086197
Epoch 4120, Loss: 0.28938569873571396, Final Batch Loss: 0.20048728585243225
Epoch 4121, Loss: 0.3335295617580414, Final Batch Loss: 0.20092791318893433
Epoch 4122, Loss: 0.2573619782924652, Final Batch Loss: 0.13272938132286072
Epoch 4123, Loss: 0.22971975803375244, Final Batch Loss: 0.10268248617649078
Epoch 4124, Loss: 0.2864692807197571, Final Batch Loss: 0.1418815702199936
Epoch 4125, Loss: 0.3349582701921463, Final Batch Loss: 0.2066691517829895
Epoch 4126, Loss: 0.24260365962982178, Final Batch Loss: 0.1254930943250656
Epoch 4127, Loss: 0.29695234447717667, Final Batch Loss: 0.1737227439880371
Epoch 4128, Loss: 0.263355515897274, Final Batch Loss: 0.11324604600667953
Epoch 4129, Loss: 0.2598326578736305, Final Batch Loss: 0.14058788120746613
Epoch 4130, L

Epoch 4235, Loss: 0.27685748040676117, Final Batch Loss: 0.14208662509918213
Epoch 4236, Loss: 0.26520510762929916, Final Batch Loss: 0.1207159087061882
Epoch 4237, Loss: 0.2336692065000534, Final Batch Loss: 0.09253156185150146
Epoch 4238, Loss: 0.2743002250790596, Final Batch Loss: 0.14937424659729004
Epoch 4239, Loss: 0.25772247463464737, Final Batch Loss: 0.1244044378399849
Epoch 4240, Loss: 0.3075007349252701, Final Batch Loss: 0.20112945139408112
Epoch 4241, Loss: 0.28835541009902954, Final Batch Loss: 0.12259908020496368
Epoch 4242, Loss: 0.2879832834005356, Final Batch Loss: 0.17104341089725494
Epoch 4243, Loss: 0.25873883068561554, Final Batch Loss: 0.11301180720329285
Epoch 4244, Loss: 0.2548864707350731, Final Batch Loss: 0.14047199487686157
Epoch 4245, Loss: 0.23899175226688385, Final Batch Loss: 0.07945896685123444
Epoch 4246, Loss: 0.24216057360172272, Final Batch Loss: 0.10865409672260284
Epoch 4247, Loss: 0.2439957708120346, Final Batch Loss: 0.10863250494003296
Epoch 4

Epoch 4357, Loss: 0.25203095376491547, Final Batch Loss: 0.14530745148658752
Epoch 4358, Loss: 0.2334425449371338, Final Batch Loss: 0.08980394899845123
Epoch 4359, Loss: 0.2615804076194763, Final Batch Loss: 0.09384669363498688
Epoch 4360, Loss: 0.24601735174655914, Final Batch Loss: 0.13155613839626312
Epoch 4361, Loss: 0.24663399159908295, Final Batch Loss: 0.11473570764064789
Epoch 4362, Loss: 0.32546618580818176, Final Batch Loss: 0.1949843317270279
Epoch 4363, Loss: 0.3201211839914322, Final Batch Loss: 0.18940947949886322
Epoch 4364, Loss: 0.28502456843852997, Final Batch Loss: 0.15413327515125275
Epoch 4365, Loss: 0.21910879015922546, Final Batch Loss: 0.08540351688861847
Epoch 4366, Loss: 0.22253663837909698, Final Batch Loss: 0.09910240769386292
Epoch 4367, Loss: 0.26446104794740677, Final Batch Loss: 0.10584453493356705
Epoch 4368, Loss: 0.2502288520336151, Final Batch Loss: 0.11505492031574249
Epoch 4369, Loss: 0.2958534061908722, Final Batch Loss: 0.1408379077911377
Epoch 

Epoch 4465, Loss: 0.3036854416131973, Final Batch Loss: 0.14729498326778412
Epoch 4466, Loss: 0.31619662046432495, Final Batch Loss: 0.20617344975471497
Epoch 4467, Loss: 0.2650189697742462, Final Batch Loss: 0.13976790010929108
Epoch 4468, Loss: 0.2687665820121765, Final Batch Loss: 0.1657356321811676
Epoch 4469, Loss: 0.2519225627183914, Final Batch Loss: 0.09347225725650787
Epoch 4470, Loss: 0.265966571867466, Final Batch Loss: 0.15185140073299408
Epoch 4471, Loss: 0.3160702586174011, Final Batch Loss: 0.1668546348810196
Epoch 4472, Loss: 0.30579744279384613, Final Batch Loss: 0.184715136885643
Epoch 4473, Loss: 0.343270018696785, Final Batch Loss: 0.15449070930480957
Epoch 4474, Loss: 0.3865080028772354, Final Batch Loss: 0.2804645001888275
Epoch 4475, Loss: 0.26053017377853394, Final Batch Loss: 0.13303826749324799
Epoch 4476, Loss: 0.252087764441967, Final Batch Loss: 0.13699571788311005
Epoch 4477, Loss: 0.24934885650873184, Final Batch Loss: 0.09838464111089706
Epoch 4478, Loss

Epoch 4580, Loss: 0.2488253116607666, Final Batch Loss: 0.13110849261283875
Epoch 4581, Loss: 0.3056981563568115, Final Batch Loss: 0.15353621542453766
Epoch 4582, Loss: 0.27515583485364914, Final Batch Loss: 0.1585475355386734
Epoch 4583, Loss: 0.30796270072460175, Final Batch Loss: 0.150270476937294
Epoch 4584, Loss: 0.26827461272478104, Final Batch Loss: 0.09284292906522751
Epoch 4585, Loss: 0.30955033004283905, Final Batch Loss: 0.19780753552913666
Epoch 4586, Loss: 0.286111518740654, Final Batch Loss: 0.16488958895206451
Epoch 4587, Loss: 0.25190701335668564, Final Batch Loss: 0.11712674051523209
Epoch 4588, Loss: 0.332268163561821, Final Batch Loss: 0.20647896826267242
Epoch 4589, Loss: 0.2372891530394554, Final Batch Loss: 0.11375948786735535
Epoch 4590, Loss: 0.28082364797592163, Final Batch Loss: 0.15474675595760345
Epoch 4591, Loss: 0.2467406913638115, Final Batch Loss: 0.11529097706079483
Epoch 4592, Loss: 0.1888696774840355, Final Batch Loss: 0.06256792694330215
Epoch 4593,

Epoch 4706, Loss: 0.2569599449634552, Final Batch Loss: 0.14824533462524414
Epoch 4707, Loss: 0.44254225492477417, Final Batch Loss: 0.296384334564209
Epoch 4708, Loss: 0.2935982793569565, Final Batch Loss: 0.17150817811489105
Epoch 4709, Loss: 0.25239717215299606, Final Batch Loss: 0.13895338773727417
Epoch 4710, Loss: 0.25146201252937317, Final Batch Loss: 0.13678297400474548
Epoch 4711, Loss: 0.2834591791033745, Final Batch Loss: 0.16213278472423553
Epoch 4712, Loss: 0.4144556373357773, Final Batch Loss: 0.2576914429664612
Epoch 4713, Loss: 0.28008227050304413, Final Batch Loss: 0.1112731546163559
Epoch 4714, Loss: 0.2972254827618599, Final Batch Loss: 0.186102956533432
Epoch 4715, Loss: 0.22724303603172302, Final Batch Loss: 0.08082562685012817
Epoch 4716, Loss: 0.2486845999956131, Final Batch Loss: 0.120203897356987
Epoch 4717, Loss: 0.22296156734228134, Final Batch Loss: 0.12303782254457474
Epoch 4718, Loss: 0.25905589014291763, Final Batch Loss: 0.13883382081985474
Epoch 4719, L

Epoch 4821, Loss: 0.21839639544487, Final Batch Loss: 0.09876582026481628
Epoch 4822, Loss: 0.21609608829021454, Final Batch Loss: 0.08790947496891022
Epoch 4823, Loss: 0.2836606800556183, Final Batch Loss: 0.15678194165229797
Epoch 4824, Loss: 0.23359280824661255, Final Batch Loss: 0.11408348381519318
Epoch 4825, Loss: 0.22158069908618927, Final Batch Loss: 0.09210249781608582
Epoch 4826, Loss: 0.24170396476984024, Final Batch Loss: 0.11422818154096603
Epoch 4827, Loss: 0.2566480189561844, Final Batch Loss: 0.14469562470912933
Epoch 4828, Loss: 0.24576938897371292, Final Batch Loss: 0.1450120061635971
Epoch 4829, Loss: 0.21868564188480377, Final Batch Loss: 0.09510572999715805
Epoch 4830, Loss: 0.22230274975299835, Final Batch Loss: 0.1179710328578949
Epoch 4831, Loss: 0.3003305569291115, Final Batch Loss: 0.10900267213582993
Epoch 4832, Loss: 0.4360816329717636, Final Batch Loss: 0.29498839378356934
Epoch 4833, Loss: 0.29116111993789673, Final Batch Loss: 0.13975882530212402
Epoch 48

Epoch 4944, Loss: 0.2510925158858299, Final Batch Loss: 0.10000302642583847
Epoch 4945, Loss: 0.2279646322131157, Final Batch Loss: 0.11211151629686356
Epoch 4946, Loss: 0.3250076621770859, Final Batch Loss: 0.1890028417110443
Epoch 4947, Loss: 0.292865589261055, Final Batch Loss: 0.14968234300613403
Epoch 4948, Loss: 0.24143611639738083, Final Batch Loss: 0.1362287998199463
Epoch 4949, Loss: 0.21271295100450516, Final Batch Loss: 0.09651457518339157
Epoch 4950, Loss: 0.4058024659752846, Final Batch Loss: 0.2847570776939392
Epoch 4951, Loss: 0.24725830554962158, Final Batch Loss: 0.11799374222755432
Epoch 4952, Loss: 0.28911449015140533, Final Batch Loss: 0.16255240142345428
Epoch 4953, Loss: 0.24988631904125214, Final Batch Loss: 0.14566205441951752
Epoch 4954, Loss: 0.2854986637830734, Final Batch Loss: 0.15534867346286774
Epoch 4955, Loss: 0.31068871915340424, Final Batch Loss: 0.1865766942501068
Epoch 4956, Loss: 0.27199646830558777, Final Batch Loss: 0.1523510217666626
Epoch 4957,

In [8]:
softmax = nn.Softmax(dim = 1)
model.eval()
for batch in test_loader:
    features, labels = batch
    _, preds = torch.max(softmax(model(features.float())), dim = 1)
    print(metrics.confusion_matrix((labels).cpu(), preds.cpu()))
    print(metrics.classification_report((labels).cpu(), preds.cpu(), digits = 5))

[[ 8  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0]
 [ 0  2  0  0  3  0  0  0  0]
 [ 0  0  1  0  0  7  0  0  5]
 [ 0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  6]]
              precision    recall  f1-score   support

           0    1.00000   1.00000   1.00000         8
           1    0.87500   1.00000   0.93333        14
           2    0.88889   1.00000   0.94118         8
           3    1.00000   1.00000   1.00000        11
           4    1.00000   0.60000   0.75000         5
           5    1.00000   0.53846   0.70000        13
           6    1.00000   1.00000   1.00000        15
           7    1.00000   1.00000   1.00000         9
           8    0.54545   1.00000   0.70588         6

    accuracy                        0.91011        89
   macro avg    0.92326   0.90427   0.89227        89
weighted avg    0.93971   0.91011   0.90653        89



In [19]:
n_samples = 20

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A0 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_1 = gen(latent_vectors).detach().numpy()

y_1 = np.zeros(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A1 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_2 = gen(latent_vectors).detach().numpy()

y_2 = np.ones(n_samples)

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U0A2 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_3 = gen(latent_vectors).detach().numpy()

y_3 = np.ones(n_samples) + 1

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A0 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_4 = gen(latent_vectors).detach().numpy()

y_4 = np.ones(n_samples) + 2

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A1 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_5 = gen(latent_vectors).detach().numpy()

y_5 = np.ones(n_samples) + 3

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U1A2 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_6 = gen(latent_vectors).detach().numpy()

y_6 = np.ones(n_samples) + 4

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A0 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_7 = gen(latent_vectors).detach().numpy()

y_7 = np.ones(n_samples) + 5

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A1 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_8 = gen(latent_vectors).detach().numpy()

y_8 = np.ones(n_samples) + 6

gen = Generator(z_dim = 100)
gen.eval()
load_model(gen, "U2A2 Solo GAN Group 2_gen.param")
latent_vectors = get_noise(n_samples, 100)
fake_features_9 = gen(latent_vectors).detach().numpy()

y_9 = np.ones(n_samples) + 7

fake_features = np.concatenate((fake_features_1, fake_features_2, fake_features_3, fake_features_4, fake_features_5, fake_features_6,
                         fake_features_7, fake_features_8, fake_features_9))
fake_labels = np.concatenate((y_1, y_2, y_3, y_4, y_5, y_6, y_7, y_8, y_9))

fake_features = torch.Tensor(fake_features)

In [20]:
_, preds = torch.max(softmax(model(fake_features.float())), dim = 1)
print(metrics.confusion_matrix((fake_labels), preds.cpu()))
print(metrics.classification_report((fake_labels), preds.cpu(), digits = 5))

[[20  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  2  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  1  2  0]
 [ 2  1  0  0 17  0  0  0  0]
 [ 0  0  4  0  0 10  0  0  6]
 [ 0  0  0  2  0  0 18  0  0]
 [ 0  0  0  0  0  0  0 20  0]
 [ 0  0  1  0  0  1  0  0 18]]
              precision    recall  f1-score   support

         0.0    0.90909   1.00000   0.95238        20
         1.0    0.94737   0.90000   0.92308        20
         2.0    0.80000   1.00000   0.88889        20
         3.0    0.89474   0.85000   0.87179        20
         4.0    0.89474   0.85000   0.87179        20
         5.0    0.90909   0.50000   0.64516        20
         6.0    0.94737   0.90000   0.92308        20
         7.0    0.90909   1.00000   0.95238        20
         8.0    0.75000   0.90000   0.81818        20

    accuracy                        0.87778       180
   macro avg    0.88461   0.87778   0.87186       180
weighted avg    0.88461   0.87778   0.87186       180

